### ISSUE TITLE
[Break XPU] C10_UNUSED change and newly add Inductor UTs break XPU CI.

### ISSUE THREAD

**Issue by guangyey** [pytorch/pytorch#138577]
1. code change in https://github.com/pytorch/pytorch/pull/138364 raise XPU CI break
> /var/lib/jenkins/workspace/third_party/torch-xpu-ops/src/ATen/native/xpu/UpSample.h:231:8: error: 'maybe_unused' attribute cannot be applied to types
2. The newly added UTs break XPU CI
    - cuda-bias code is introduced by https://github.com/pytorch/pytorch/pull/138472;
    - cuda-specific UT is introduced by https://github.com/pytorch/pytorch/pull/138089;
    - expected failure UTs were fixed by https://github.com/pytorch/pytorch/pull/134170

cc @gujinghui @EikanWang @fengyuan14
