### PR TITLE
fix AOTInductor fails to compile dynamic-shape CUDA gather pattern with ValueError: The argument '((0)) + 48' is not comparable

### PR DESCRIPTION
**Pull request by FFXIVYYDS**
# GitHub comment draft for follow-up PR on issue #179900

Below is a ready-to-paste GitHub comment for your PR conversation.

---

Thanks for taking a look.

This PR is a follow-up to issue #179900:  
https://github.com/pytorch/pytorch/issues/179900

That issue was closed after it was reported that the original repro worked on `main`. I re-checked the situation on our side and the conclusion is:

- the original issue in #179900 is **not fully resolved on current `main`**
- `main` no longer fails at the **first** `ValueError: The argument '((0)) + 48' is not comparable` site from the original minimal repro
- however, after that first failure point is avoided, the same underlying symbolic comparability problem still appears at **later compilation stages**
- for our real AOTI model, this means the end-to-end compile is still broken unless we patch additional call sites

## What I found

Initially I also thought the fix might have come from:
- PR #175975

But after checking commit history more carefully, that is not the real reason the original failure path disappeared.

The key change is actually from:
- PR #174521
- commit: `037c0f4053b5136cb22f88b3cb4e18f0ab588cfd`

Patch:  
https://github.com/pytorch/pytorch/commit/037c0f4053b5136cb22f88b3cb4e18f0ab588cfd.patch

The important part is not mainly the `stride_hints()` change from:

```python
result.append(self.size_hint_or_throw(s))
```

to:

```python
result.append(self.optimization_hint(s, fallback=0))
```

The crucial part is that this commit added:

```python
if isinstance(expr, sympy.Expr):
    expr = expr.expand(identity=True)
```

That expansion is what avoids the original comparability failure in the first path.

## Why this PR is still needed

After understanding that, I tried applying the same idea to the later failing sites in the compilation pipeline.

With only the earlier fix in place, I was still able to reproduce new failures from the same model/test, still ending in:

```text
torch._inductor.exc.InductorError: ValueError: The argument '((0)) + 48' is not comparable.
```

In our case, after the first path is fixed, the next failures show up in:

1. `torch/_inductor/sizevars.py`
2. `torch/_inductor/codegen/simd.py`

More specifically, I found that applying the same `expand(identity=True)` handling at these two places fixes the remaining compile failure for this case:

### 1) `torch/_inductor/sizevars.py`

```python
@@ -616,6 +618,8 @@ class SizeVarAllocator:
         """
         strides = []
         index = self.simplify(index)
+        if isinstance(index, Expr):
+            index = index.expand(identity=True)
         # remove any offset
         index = index - sympy_subs(
             index, {v: sympy.S.Zero for v in support_vars if v != 0}
```

### 2) `torch/_inductor/codegen/simd.py`

```python
@@ -933,6 +933,8 @@ class SIMDKernel(Kernel[CSEVariableType], Generic[CSEVariableType]):
         {xindex: 512, rindex: 1024}
         """
         index_to_tile_indexes = {k: v.expr for k, v in self.range_tree_nodes.items()}
+        if isinstance(index, sympy.Expr):
+            index = index.expand(identity=True)
         index_in_tile_vars = sympy_subs(index, index_to_tile_indexes)  # type: ignore[arg-type]
         strides = {}
         for range_tree in self.range_trees:
```

With both of those changes applied, the model finally compiles successfully on my side.

## Result on my side

After patching those two call sites, I get:

```text
python3 repro_inductor_non_comparable_min.py --device cuda
[INFO] device=cuda api=aoti_compile_and_package
[OK] compile success: /tmp/non_comparable_min.pt2
```

## Test coverage

This PR includes a test based on the #179900 scenario.

I can reproduce the remaining failures with:

```bash
python3 test/inductor/test_aot_inductor.py -k test_issue_179900 -v
```

Without the two new `expand(identity=True)` additions, this test still hits the later-stage non-comparable failures on my side.

With the patch in this PR, the same case compiles successfully.

## Summary

So the current situation appears to be:

- issue #179900 exposed a real symbolic comparability problem
- one earlier path was effectively fixed by the `expand(identity=True)` handling introduced in PR #174521
- but that did **not** eliminate the problem globally
- the same class of failure still exists in later compilation/codegen paths
- this PR extends the same fix pattern to the remaining sites that still fail for this case

This is why I am sending this follow-up PR: from my testing, the issue is not fully gone on `main`; the failure just moved deeper into the pipeline.

Could you please take a look and confirm whether extending `expand(identity=True)` in these two additional places is the right upstream direction?

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @kadeng @muchulee8 @amjames @chauhang @aakhundov @coconutruben @jataylo @laithsakka @jansel @eellison @shunting314 @peterbell10

### CODE REVIEW

**Comment by aorenste** [comment]
I can repro the issue with this test. I worry that this is whack-a-mole rather than fixing the underlying problem at the source. @laithsakka could you take a look?

**Comment by jansel** [comment]
@claude review these changes

**Review by jansel — DISMISSED** [review]
I'd like to see a more root-cause fix here, though these changes fix a bug and look safe to me.

**Comment by FFXIVYYDS** [comment]
I took a closer look at the failing merge-gate CI logs today.

From the logs I checked, the failures do not look related to this PR.

One group of failures is from:

```text
test/inductor/test_extension_backend.py::ExtensionBackendTests::test_open_device_registration
```

The failure is:

```text
RuntimeError: The runtime module of 'extension_device' has already been registered
```

and in the earlier rerun stack, it also fails with:

```text
AttributeError: module 'extension_device' has no attribute 'is_available'
```

from:

```text
torch.accelerator.is_available() -> mod.is_available()
```

This looks like an `extension_device` / `torch.accelerator` test issue, plus global device-module registration state left over across reruns.

Another failure I checked is from:

```text
test/inductor/test_combo_kernels.py::ComboKernelTestsMaxAutotune::test_combo_autotune_grouping
```

The failure is:

```text
Expected 2 groups, got 4
```

from combo-kernel autotune grouping logs, and the same run also prints:

```text
Not enough SMs to use max_autotune_gemm mode
```

This looks like a combo-kernel autotune grouping / CI environment expectation issue.

I do not see these failures going through the SymPy comparability paths changed in this PR, nor any failure like:

```text
ValueError: The argument '((0)) + 48' is not comparable
```

The new regression test added in this PR is CUDA-only:

```python
if self.device != "cuda":
    raise unittest.SkipTest("requires CUDA")
```

so it should be skipped in the failing CPU core jobs. The code changes in this PR are limited to normalizing unevaluated SymPy identity expressions in `sizevars.py` and `codegen/simd.py`, plus the CUDA AOTInductor regression test for #179900.

Given that this PR already has approval and the merge attempt failed on what appear to be unrelated CI/test failures, I am not going to push another empty commit just to retrigger CI, since that would create a new HEAD and may reset the current merge-gate context.

Could a committer please take another look and retry the failed jobs or re-run the merge if these failures are considered unrelated?

**Comment by FFXIVYYDS** [comment]
@jansel

I also noticed that some recently merged PRs hit a similar situation where the normal merge attempt failed because of unrelated merge-gate / trunk CI failures, and they were eventually merged by a committer using:

```text
@pytorchbot merge -i
```

From the logs I checked on this PR, the failing jobs look similar in nature. The failures appear to be in unrelated test paths, for example:

```text
test/inductor/test_extension_backend.py::ExtensionBackendTests::test_open_device_registration
```

with errors like:

```text
RuntimeError: The runtime module of 'extension_device' has already been registered
```

and:

```text
AttributeError: module 'extension_device' has no attribute 'is_available'
```

I also saw a combo-kernel autotune grouping failure:

```text
test/inductor/test_combo_kernels.py::ComboKernelTestsMaxAutotune::test_combo_autotune_grouping
```

with:

```text
Expected 2 groups, got 4
```

and the log also printed:

```text
Not enough SMs to use max_autotune_gemm mode
```

These do not look related to the SymPy comparability issue fixed by this PR.

For this PR specifically, the relevant Inductor / AOTInductor checks have passed, and the regression test added here exercises the original failure path from #179900. The new test is CUDA-only, while several of the blocking failures are from CPU core jobs, so they should not be caused by the new test.

The actual code change in this PR is also small and follows the existing `expand(identity=True)` pattern already used in Inductor. It only normalizes unevaluated SymPy identity expressions in the specific sizevar / SIMD codegen paths that still hit the `ValueError: The argument '((0)) + 48' is not comparable` failure.

Given that the PR has already been reviewed and approved, and the current merge blockers appear to be unrelated CI / merge-gate failures, would it be reasonable to retry the merge with `@pytorchbot merge -i` if you agree these failures are unrelated?

**Comment by jansel** [comment]
You might want to start developing off of the branch `viable/strict` rather than `main`, that is the latest commit with a green CI.  This command will also rebase to that branch:

@pytorchbot rebase

**Comment by FFXIVYYDS** [comment]
@jansel

OK, I understand your point now. Thank you for the explanation.

My previous branch was based on an older `main`, and it looks like CI / merge-gate status on that baseline was not clean yet. So instead of continuing from that baseline, rebasing onto a known-good CI baseline such as `viable/strict` should be the right way to make the merge-gate checks meaningful again.

I checked locally and confirmed that the PR branch has been successfully rebased:

```text
cbb6985 Trigger CI
ee4eb82 Trigger CI
2af3095 Fix size hint fallback handling in inductor
dfda4b2e [dynamo] Add data descriptor VTs: MemberDescriptor, GetSetDescriptor, Property, TupleGetter (#182742)
```

So at this point I do not see an obvious remaining blocker from my side.

The actual code change is small, has already been reviewed, and applies the existing `expand(identity=True)` normalization pattern to the relevant sizevar / SIMD codegen paths covered by the #179900 regression test.

Could you please help continue the merge process for this safe fix? We would like to use the latest release-line code and migrate our downstream code to a newer PyTorch version, and this fix helps unblock that migration.

**Comment by jansel** [comment]
Hrm, something doesn't look right with CI still
@pytorchbot rebase

**Review by jansel — DISMISSED** [review]

**Comment by ezyang** [comment]
```
  This PR is causing a ~3-4% geomean speedup regression on H100 inference benchmarks across torchbench, confirmed via binary bisect of the benchmark runs.

  Regression numbers (torchbench, H100, inference, bfloat16):

  ┌─────────────────────┬────────┬───────┬───────┐
  │      Compiler       │ Before │ After │ Delta │
  ├─────────────────────┼────────┼───────┼───────┤
  │ cudagraphs          │ 2.74x  │ 2.65x │ -3.3% │
  ├─────────────────────┼────────┼───────┼───────┤
  │ cudagraphs_freezing │ 2.78x  │ 2.70x │ -2.9% │
  ├─────────────────────┼────────┼───────┼───────┤
  │ aot_inductor        │ 3.28x  │ 3.20x │ -2.4% │
  └─────────────────────┴────────┴───────┴───────┘

  huggingface and timm_models show smaller but consistent drops as well.

  Bisect details: We ran 5 rounds of H100 benchmark bisection across the 65-commit window where the regression appeared in the nightly dashboard, narrowing it
   down to this commit. The parent commit (69295e568f8) benchmarks clean; this commit shows the regression.

  Root cause hypothesis: The index.expand(identity=True) calls added in simd.py:grids_and_strides() and sizevars.py:stride_vars() change how sympy simplifies
  stride expressions during Triton kernel codegen. This produces different tiling decisions for generated kernels, resulting in worse performance. These are
  hot paths that affect every compiled kernel, which explains the broad regression across all compiler configs.

  The fix itself is correct for the dynamic-shape gather compilation failure it targets, but the expand(identity=True) is too broad — it affects all index
  expressions, not just the problematic ((0)) + 48 pattern. Could the expansion be scoped more narrowly, e.g., only applied when the comparison actually
  fails, or only in the AOTInductor dynamic-shape path?
```

cc @jansel

**Comment by FFXIVYYDS** [comment]
Holy crap.😢
