### PR TITLE
Disable dynamo tracing torchrec.distributed

### PR DESCRIPTION
**Pull request by yanboliang**
Summary: Context at T138318923

Test Plan: mannual test

Reviewed By: yf225

Differential Revision: D41631076

cc @mlazos @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by yf225 — APPROVED** [review]

**Comment by yanboliang** [comment]
> I git bisected for the command python benchmarks/dynamo/torchbench.py --only dlrm --inductor --amp --accuracy and found this PR introduces the error
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'

It should be fixed by https://github.com/pytorch/pytorch/pull/90338 already.
