### ISSUE TITLE
Functional Missing Many Functions after Update to 0.40

### ISSUE THREAD

**Issue by kevinj22** [pytorch/pytorch#7376]
Hello,

I updated pytorch from 0.30 to 0.40 today and when running code I receive the following error:

AttributeError: module 'torch.functional' has no attribute 'pad'

I installed via conda following the instructions from: https://pytorch.org/

I also tried uninstalling, installing pytorch 0.50 from source, and attempting to run the code again. I received the same error.

Looking at the functional.py file in my /anaconda3/lib/python3.6/site-packages/torch I see that I am missing many functions, not just pad, in functional.py. 

What should I do to make these functions available again?

I've attached a text file of the functional.py file I currently have.

System:

Ubuntu 16.04
Cuda 9.1
CUDNN 7.1
Python 3.6

[functional.txt](https://github.com/pytorch/pytorch/files/1984826/functional.txt)

**Comment by zou3519** [comment]
Do you mean `torch.nn.functional`?

**Comment by kevinj22** [comment]
Yes

**Comment by kevinj22** [comment]
I was using the wrong functional.

What I was doing: from torch import functional

What I should be doing: from torch.nn import functional

Thanks!
