### PR TITLE
[ROCm] add some support for the occupancy API on ROCm

### PR DESCRIPTION
**Pull request by iotamudelta**
Unfortunately, the HIP function takes uint32_t* instead of int*, so we still need to ifdef for the time being.

### CODE REVIEW

**Review by bddppq — APPROVED** [review]

**Comment by xw285cornell** [comment]
@iotamudelta does this patch work with ROCm 2.7? I'm getting an error

aten/src/ATen/hip/nvrtc_stub/ATenNVRTC.h:88:19: error: reference to overloaded function could not be resolved; did you mean to call it?
  AT_FORALL_NVRTC(CREATE_MEMBER)
  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
aten/src/ATen/hip/nvrtc_stub/ATenNVRTC.h/aten/src/ATen/hip/nvrtc_stub/ATenNVRTC.h:74:3: note: expanded from macro 'AT_FORALL_NVRTC'
  _(hipOccupancyMaxActiveBlocksPerMultiprocessor) \
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aten/src/ATen/hip/nvrtc_stub/ATenNVRTC.h/aten/src/ATen/hip/nvrtc_stub/ATenNVRTC.h:87:38: note: expanded from macro 'CREATE_MEMBER'
#define CREATE_MEMBER(name) decltype(&name) name;
                                     ^~~~~
hip/hcc_detail/hip_runtime_api.h:3127:19: note: possible target for call
inline hipError_t hipOccupancyMaxActiveBlocksPerMultiprocessor(
                  ^
hip/hcc_detail/hip_runtime_api.h:2770:12: note: possible target for call
hipError_t hipOccupancyMaxActiveBlocksPerMultiprocessor(
           ^
1 error generated.

**Comment by iotamudelta** [comment]
@xw285cornell Given that the CI logs have rotated, I cannot say with absolute certainty which ROCm release we tested on but do believe it to be either ROCm 2.7 or 2.8. Does your `hip_runtime_api.h` contain the right function signature?

**Comment by xw285cornell** [comment]
@iotamudelta the diff I have in question is https://github.com/ROCm-Developer-Tools/HIP/commit/4b18b321f722d07db164c6f4040a41ee93feef16 and https://github.com/ROCm-Developer-Tools/HIP/commit/5c8a7521f41ab650e36ebd25e0ea5449e83d0e1e. Do you know if the former is in 2.7 or 2.8? I think the problem is that decltype doesn't work for templated function (at least not in this way)
```
template <class T>	
inline hipError_t hipOccupancyMaxActiveBlocksPerMultiprocessor
```

**Comment by iotamudelta** [comment]
The current definition is:
```
hipError_t hipOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(
   uint32_t* numBlocks, hipFunction_t f, uint32_t blockSize, size_t dynSharedMemPerBlk, unsigned int flags);
```
and
```
template <typename F>
inline
hipError_t hipOccupancyMaxActiveBlocksPerMultiprocessor(uint32_t* numBlocks, F kernel,
    uint32_t blockSize, size_t dynSharedMemPerBlk) {

    using namespace hip_impl;

    hip_impl::hip_init();
    auto f = get_program_state().kernel_descriptor(
        reinterpret_cast<std::uintptr_t>(kernel), target_agent(nullptr));

    return hipOccupancyMaxActiveBlocksPerMultiprocessor(numBlocks, f, blockSize, dynSharedMemPerBlk);
}
```
looks like the former is in ROCm 2.8 from GH but one would need to check w/ HIP team to make sure.
