### ISSUE TITLE
`import torch` fails on Python-3.11 runtime

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#85506]
### 🐛 Describe the bug

```python
Python 3.11.0b1 (main, Jul 28 2022, 09:24:40) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from functorch.dim import dims
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/pytorch/functorch/__init__.py", line 6, in <module>
    import torch
    ^^^^^^^^^^^^
  File "/root/pytorch/torch/__init__.py", line 917, in <module>
    os.environ.get('PYTORCH_DISABLE_LIBRARY', "0") == "0"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pytorch/torch/_decomp/decompositions_for_jvp.py", line 287, in <module>
    _register_jit_decomposition_for_jvp(torch.ops.aten.nll_loss_backward.default)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pytorch/torch/_decomp/decompositions_for_jvp.py", line 83, in _register_jit_decomposition_for_jvp
    graph = torch.jit.script(decomp_fn).graph
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pytorch/torch/jit/_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pytorch/torch/jit/annotations.py", line 386, in try_ann_to_type
    scripted_class = torch.jit._script._recursive_compile_class(ann, loc)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pytorch/torch/jit/_script.py", line 1465, in _recursive_compile_class
    rcb = _jit_internal.createResolutionCallbackForClassMethods(obj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pytorch/torch/_jit_internal.py", line 454, in createResolutionCallbackForClassMethods
    captures.update(get_closure(fn))
                    ^^^^^^^^^^^^^^^
  File "/root/pytorch/torch/_jit_internal.py", line 206, in get_closure
    captures.update(fn.__globals__)
                    ^^^^^^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute '__globals__'
>>> 
```

This is probably caused by https://github.com/pytorch/pytorch/pull/84976 but py-3.11 builds are broken since Sep 12th so it was caught on time

### Versions

nightly

**Comment by t-vi** [comment]
So Python 3.11 does funny things in the Enum metaclass, which ends up assigning `object.__new__` to the Enum subclasses `_new_member_` attribute. A quick fix might be to just filter `(not issubclass(cls, enum.Enum) or name != '_new_member_')` in the enumeration of the class dict here:
https://github.com/pytorch/pytorch/blob/787028cadb7fe83986111ffb7ddb058a68b763c0/torch/_jit_internal.py#L446-L450

**Comment by malfet** [comment]
> ```python
> PYTORCH_DISABLE_LIBRARY
> ```

I've fixed that in https://github.com/pytorch/pytorch/pull/91805 so hopefully everything should work now (but we really need the CI to prevent those from regressing in the future)
