### ISSUE TITLE
[jit] the torch script and c++ api using   

### ISSUE THREAD

**Issue by szupzp** [pytorch/pytorch#15523]
hi, 
I use torch.jit.trace() to create a scriptModel and save it. I test successfully in python script but not work in c++.
the model's forward() is:

    def forward(self, input , env, h, c):
            output, (h_out, c_out) = self.blstm1(input, (h, c))
            output = self.fc1(output)
            output = self.output_fc(output)
            SUB_pred = output + env
            return SUB_pred,output,h_out, c_out

and the jit code is:

     wb_input = torch.ones(1,1,56)
     wb_input_env= torch.ones(1,1,14)
     h= torch.ones(1,1,256)
     c= torch.ones(1,1,256)
     traced_script_module = torch.jit.trace(model, (wb_input,wb_input_env, h, c))
     traced_script_module.save('1.7m_chinese.pt')

the c++ code is:

    int main(int argc, const char* argv[]) {
    	if (argc != 3) {
        std::cerr << "usage: example-app <path-to-exported-script-module>\n";
        //return -1;
      }
      // Deserialize the ScriptModule from a file using torch::jit::load().
      std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(argv[1]);
      assert(module != nullptr);
      std::cout << "load model successfully \n";
      // Create a vector of inputs.
      std::vector<torch::jit::IValue> inputs;
      at::Tensor input_tensor = torch::zeros({ 1, 1, 56 });
      at::Tensor inputenv_tensor = torch::zeros({ 1, 1, 14 });
      at::Tensor h_tensor = torch::zeros({ 1, 1, 256 });
      at::Tensor c_tensor = torch::zeros({ 1, 1, 256 });
      inputs.push_back(input_tensor);
      inputs.push_back(inputenv_tensor);
      inputs.push_back(h_tensor);
      inputs.push_back(c_tensor);
      std::cout << "input tensor successfully \n";
      // Execute the model and turn its output into a tensor.
      at::Tensor output = module->forward(inputs).toTensor();
      std::cout << output.slice(/*dim=*/3, /*start=*/0, /*end=*/20) << '\n';
      while (1);
    }

the c++ project is compile by cmake:

[ 50%] Building CXX object CMakeFiles/example.dir/example.cpp.o
[100%] Linking CXX executable example
[100%] Built target example

but get a error when i run it:

    usage: example-app <path-to-exported-script-module>
    load model successfully
    input tensor successfully
    terminate called after throwing an instance of 'c10::Error'
      what():  isTensor() ASSERT FAILED at 
    /media/datas/zhanpengpan/PycharmProjects/c_project/libtorch/include/ATen/core/ivalue.h:182, please 
    report a bug to PyTorch. (toTensor at 
    /media/datas/zhanpengpan/PycharmProjects/c_project/libtorch/include/ATen/core/ivalue.h:182)
    frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fbdf6739fe1 in 
    /home/zhanpengpan/zhanpengpan/PycharmProjects/c_project/libtorch/lib/libc10.so)
    frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fbdf6739dfa in 
    /home/zhanpengpan/zhanpengpan/PycharmProjects/c_project/libtorch/lib/libc10.so)
    frame #2: c10::IValue::toTensor() && + 0xa8 (0x429516 in ./example)
    frame #3: main + 0x3f0 (0x42752f in ./example)
    frame #4: __libc_start_main + 0xf0 (0x7fbdf5de5830 in /lib/x86_64-linux-gnu/libc.so.6)
    frame #5: _start + 0x29 (0x426979 in ./example)
    Aborted (core dumped)

is something wrong while i used the c++ api?  what can i do?

**Comment by suo** [comment]
The return of forward looks like it should be a tuple, not a tensor.

**Comment by szupzp** [comment]
> The return of forward looks like it should be a tuple, not a tensor.

Yes!! but what is the tuple in c++? the vector of tensor?

**Comment by szupzp** [comment]
> The return of forward looks like it should be a tuple, not a tensor.

Yes!! there are 4 output tensor of my model, so how can i use tuple in c++, i try to use:
    std::tuple<torch::Tensor,torch::Tensor,torch::Tensor,torch::Tensor> output = module->forward(inputs).toTensor();
but i can not compile!

**Comment by zchuang11** [comment]
The error is : traced_script_module.save('mysave.pt')
RuntimeError: Couldn't export Python operator ConstantPadNd
 when I using the jit save to script, can you help me to solve?

**Comment by zchuang11** [comment]
> > The return of forward looks like it should be a tuple, not a tensor.
> 
> Yes!! there are 4 output tensor of my model, so how can i use tuple in c++, i try to use:
> `std::tuple<torch::Tensor,torch::Tensor,torch::Tensor,torch::Tensor> output = module- >forward(inputs).toTensor();`
> but it can not compile!

The error is : traced_script_module.save('mysave.pt')
RuntimeError: Couldn't export Python operator ConstantPadNd
when I using the jit save to script, can you help me to solve? Thank you

**Comment by suo** [comment]
Okay, I'm going to close out this issue as @szupzp's problem has been resolved. @zchuang11, if you have a bug to report, please file a new issue with enough detail to reproduce the problem. Thanks!

**Comment by BAILOOL** [comment]
@szupzp indeed concatenation works. Otherwise, you could do the following to handle multiple outputs:
```
...
auto outputs = module->forward(inputs).toTuple();
torch::Tensor out1 = outputs->elements()[0].toTensor();
torch::Tensor out2 = outputs->elements()[1].toTensor();
...
```

**Comment by xin-xinhanggao** [comment]
Hi @szupzp!  Could you please tell me how to cat the tensor in pytorch C++ API?

**Comment by szupzp** [comment]
hi, do the concatenation in your forward function  of Python and split the tensor in c++. 发自我的iPhone------------------ Original ------------------From: HanggaoXin  <notifications@github.com>Date: Sun,Apr 28,2019 4:35 PMTo: pytorch/pytorch <pytorch@noreply.github.com>Cc: zhanpengpan <szupzp@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [pytorch/pytorch] [jit] the torch script and c++ api using(#15523)Hi @szupzp!  Could you please tell me how to cat the tensor in pytorch C++ API?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pytorch/pytorch","title":"pytorch/pytorch","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/pytorch/pytorch"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xin-xinhanggao in #15523: Hi @szupzp!  Could you please tell me how to cat the tensor in pytorch C++ API?"}],"action":{"name":"View Issue","url":"https://github.com/pytorch/pytorch/issues/15523#issuecomment-487357935"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pytorch/pytorch/issues/15523#issuecomment-487357935",
"url": "https://github.com/pytorch/pytorch/issues/15523#issuecomment-487357935",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jinfagang** [comment]
cat is not the solution, if output tensor not same size in all axis, can not concate. And toTuple() methods I just got some scalar value but not a tuple of tensors.

**Comment by sukuya** [comment]
I am trying to perform forward on two inputs. First is a tensor and second a tuple of two tensors. 
'  std::vector<torch::jit::IValue> input;
  std::tuple<torch::Tensor, torch::Tensor> hidden {torch::ones({2, 10, 200}), torch::ones({2, 10, 200})};
  torch::Tensor x = torch::ones({10,10});
  input.push_back(x);
  input.push_back(torch::ones({2, 10, 200}));
  input.push_back(torch::ones({2, 10, 200}));
'
This gives me follwoing error:
'
terminate called after throwing an instance of 'c10::Error'
  what():  Unknown class name for unpickler: build_tensorlist (getClass at /pytorch/torch/csrc/jit/pickler.cpp:21)
'

**Comment by sicarioakki** [comment]
RuntimeError: Only tensors or tuples of tensors can be output from traced functions (getNestedOutputTrace at /pytorch/torch/csrc/jit/tracer.cpp:200)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f5b22e31441 in /usr/local/lib/python3.5/dist-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f5b22e30d7a in /usr/local/lib/python3.5/dist-packages/torch/lib/libc10.so)
frame #2: torch::jit::tracer::getNestedOutputTrace(std::shared_ptr<torch::jit::tracer::TracingState> const&, c10::IValue const&) + 0x20d (0x7f5b2211673d in /usr/local/lib/python3.5/dist-packages/torch/lib/libtorch.so.1)
frame #3: torch::jit::tracer::exit(std::vector<c10::IValue, std::allocator<c10::IValue> > const&) + 0x2f (0x7f5b2211680f in /usr/local/lib/python3.5/dist-packages/torch/lib/libtorch.so.1)
frame #4: <unknown function> + 0x447d43 (0x7f5b7049bd43 in /usr/local/lib/python3.5/dist-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x459fc2 (0x7f5b704adfc2 in /usr/local/lib/python3.5/dist-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x130d0c (0x7f5b70184d0c in /usr/local/lib/python3.5/dist-packages/torch/lib/libtorch_python.so)
frame #7: PyCFunction_Call + 0x77 (0x4ea137 in /usr/bin/python3)
frame #8: PyEval_EvalFrameEx + 0x59f6 (0x53c176 in /usr/bin/python3)
frame #9: /usr/bin/python3() [0x53fc97]
frame #10: PyEval_EvalFrameEx + 0x50bf (0x53b83f in /usr/bin/python3)
frame #11: /usr/bin/python3() [0x53fc97]
frame #12: PyEval_EvalCode + 0x1f (0x5409bf in /usr/bin/python3)
frame #13: /usr/bin/python3() [0x54a435]
frame #14: PyCFunction_Call + 0x4f (0x4ea10f in /usr/bin/python3)
frame #15: PyEval_EvalFrameEx + 0x614 (0x536d94 in /usr/bin/python3)
frame #16: _PyGen_Send + 0x133 (0x4eddc3 in /usr/bin/python3)
frame #17: PyEval_EvalFrameEx + 0x5d45 (0x53c4c5 in /usr/bin/python3)
frame #18: _PyGen_Send + 0x133 (0x4eddc3 in /usr/bin/python3)
frame #19: PyEval_EvalFrameEx + 0x5d45 (0x53c4c5 in /usr/bin/python3)
frame #20: _PyGen_Send + 0x133 (0x4eddc3 in /usr/bin/python3)
frame #21: PyEval_EvalFrameEx + 0x4d06 (0x53b486 in /usr/bin/python3)
frame #22: PyEval_EvalFrameEx + 0x4b14 (0x53b294 in /usr/bin/python3)
frame #23: PyEval_EvalFrameEx + 0x4b14 (0x53b294 in /usr/bin/python3)
frame #24: PyEval_EvalCodeEx + 0x13b (0x540b0b in /usr/bin/python3)
frame #25: /usr/bin/python3() [0x4ec3f7]
frame #26: PyObject_Call + 0x47 (0x5c20e7 in /usr/bin/python3)
frame #27: PyEval_EvalFrameEx + 0x252b (0x538cab in /usr/bin/python3)
frame #28: /usr/bin/python3() [0x5401ef]
frame #29: PyEval_EvalFrameEx + 0x5513 (0x53bc93 in /usr/bin/python3)
frame #30: /usr/bin/python3() [0x54307f]
frame #31: PyCFunction_Call + 0x4f (0x4ea10f in /usr/bin/python3)
frame #32: PyEval_EvalFrameEx + 0x614 (0x536d94 in /usr/bin/python3)
frame #33: /usr/bin/python3() [0x5401ef]
frame #34: PyEval_EvalFrameEx + 0x5513 (0x53bc93 in /usr/bin/python3)
frame #35: /usr/bin/python3() [0x54307f]
frame #36: PyCFunction_Call + 0x4f (0x4ea10f in /usr/bin/python3)
frame #37: PyEval_EvalFrameEx + 0x614 (0x536d94 in /usr/bin/python3)
frame #38: /usr/bin/python3() [0x5401ef]
frame #39: PyEval_EvalFrameEx + 0x5513 (0x53bc93 in /usr/bin/python3)
frame #40: /usr/bin/python3() [0x54307f]
frame #41: PyCFunction_Call + 0x4f (0x4ea10f in /usr/bin/python3)
frame #42: PyEval_EvalFrameEx + 0x614 (0x536d94 in /usr/bin/python3)
frame #43: PyEval_EvalCodeEx + 0x87a (0x54124a in /usr/bin/python3)
frame #44: /usr/bin/python3() [0x4ec2e3]
frame #45: PyObject_Call + 0x47 (0x5c20e7 in /usr/bin/python3)
frame #46: PyEval_EvalFrameEx + 0x252b (0x538cab in /usr/bin/python3)
frame #47: _PyGen_Send + 0x99 (0x4edd29 in /usr/bin/python3)
frame #48: PyEval_EvalFrameEx + 0x4d06 (0x53b486 in /usr/bin/python3)
frame #49: PyEval_EvalFrameEx + 0x4b14 (0x53b294 in /usr/bin/python3)
frame #50: PyEval_EvalCodeEx + 0x87a (0x54124a in /usr/bin/python3)
frame #51: /usr/bin/python3() [0x4ec3f7]
frame #52: PyObject_Call + 0x47 (0x5c20e7 in /usr/bin/python3)
frame #53: PyEval_EvalFrameEx + 0x252b (0x538cab in /usr/bin/python3)
frame #54: PyEval_EvalCodeEx + 0x87a (0x54124a in /usr/bin/python3)
frame #55: /usr/bin/python3() [0x4ec2e3]
frame #56: PyObject_Call + 0x47 (0x5c20e7 in /usr/bin/python3)
frame #57: /usr/bin/python3() [0x61f73f]
frame #58: PyObject_Call + 0x47 (0x5c20e7 in /usr/bin/python3)
frame #59: PyEval_EvalFrameEx + 0x4ed6 (0x53b656 in /usr/bin/python3)
frame #60: PyEval_EvalCodeEx + 0x13b (0x540b0b in /usr/bin/python3)
frame #61: /usr/bin/python3() [0x4ec2e3]
frame #62: PyObject_Call + 0x47 (0x5c20e7 in /usr/bin/python3)
frame #63: PyEval_EvalFrameEx + 0x252b (0x538cab in /usr/bin/python3)

I am facing this issue while trying to convert PyTorch to Torch script via Tracing..
Can anyone help me with this? @suo @szupzp @jinfagang

**Comment by sukuya** [comment]
> RuntimeError: Only tensors or tuples of tensors can be output from traced functions (getNestedOutputTrace at /pytorch/torch/csrc/jit/tracer.cpp:200)

Can you share the function. Return type seems to be the issue.

**Comment by qinb** [comment]
> @szupzp indeed concatenation works. Otherwise, you could do the following to handle multiple outputs:
> 
> ```
> ...
> auto outputs = module->forward(inputs).toTuple();
> torch::Tensor out1 = outputs->elements()[0].toTensor();
> torch::Tensor out2 = outputs->elements()[1].toTensor();
> ...
> ```

I use this method to get the value of out2 with libtorch-1.1.0, but still the same errors.
```
terminate called after throwing an instance of 'c10::Error'
  what():  isTensor() ASSERT FAILED at /search/odin/boqin/mmdetection_ocr_split/cpp/roi_aligin/libtorch/include/ATen/core/ivalue.h:209, please report a bug to PyTorch. (toTensor at /search/odin/boqin/mmdetection_ocr_split/cpp/roi_aligin/libtorch/include/ATen/core/ivalue.h:209)
```
can you help me? thanks

**Comment by shuiqingliu** [comment]
> @szupzp indeed concatenation works. Otherwise, you could do the following to handle multiple outputs:
> 
> ```
> ...
> auto outputs = module->forward(inputs).toTuple();
> torch::Tensor out1 = outputs->elements()[0].toTensor();
> torch::Tensor out2 = outputs->elements()[1].toTensor();
> ...
> ```

you save my life！

**Comment by ToBigboss** [comment]
> @szupzp indeed concatenation works. Otherwise, you could do the following to handle multiple outputs:
> 
> ```
> ...
> auto outputs = module->forward(inputs).toTuple();
> torch::Tensor out1 = outputs->elements()[0].toTensor();
> torch::Tensor out2 = outputs->elements()[1].toTensor();
> ...
> ```

I  want to get output by node_name， how to do？

**Comment by zyandtom** [comment]
how about multiple inputs? currently I built a dict for these inputs, and struct like this:
"
map<string, vector<vector<torch::Tensor>>> smalldata;
"
and got error:
"
/home/yang.zeng/LaneGCN-master/example-app/example-app.cpp: In function ‘int main(int, const char**)’:
/home/yang.zeng/LaneGCN-master/example-app/example-app.cpp:226:49: error: no matching function for call to ‘torch::jit::Module::forward(std::map<std::basic_string<char>, std::vector<std::vector<at::Tensor> > >&)’
     at::Tensor output = module.forward(smalldata).toTensor();
                                                 ^
In file included from /home/yang.zeng/libtorch/include/torch/csrc/jit/serialization/import.h:5:0,
                 from /home/yang.zeng/libtorch/include/torch/script.h:8,
                 from /home/yang.zeng/LaneGCN-master/example-app/example-app.cpp:1:
/home/yang.zeng/libtorch/include/torch/csrc/jit/api/module.h:113:10: note: candidate: c10::IValue torch::jit::Module::forward(std::vector<c10::IValue>)
   IValue forward(std::vector<IValue> inputs) {
          ^~~~~~~
/home/yang.zeng/libtorch/include/torch/csrc/jit/api/module.h:113:10: note:   no known conversion for argument 1 from ‘std::map<std::basic_string<char>, std::vector<std::vector<at::Tensor> > >’ to ‘std::vector<c10::IValue>’
CMakeFiles/example-app.dir/build.make:62: recipe for target 'CMakeFiles/example-app.dir/example-app.cpp.o' failed
make[2]: *** [CMakeFiles/example-app.dir/example-app.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/example-app.dir/all' failed
make[1]: *** [CMakeFiles/example-app.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
"
How can I input this dictionary?

**Comment by Andyshen555** [comment]
> @szupzp indeed concatenation works. Otherwise, you could do the following to handle multiple outputs:
> 
> ```
> ...
> auto outputs = module->forward(inputs).toTuple();
> torch::Tensor out1 = outputs->elements()[0].toTensor();
> torch::Tensor out2 = outputs->elements()[1].toTensor();
> ...
> ```

This method doesn't work on libtorch 1.9.0 anymore and it says **error: base operand of ‘->’ has non-pointer type ‘at::Tensor’**. When the line is changed to **torch::Tensor out1 = outputs.elements()[0].toTensor();**, it returns **error: ‘class at::Tensor’ has no member named ‘elements’; did you mean ‘element_size’?**.

Could you please tell me what to do to get multiple outputs here?

Thank you.

**Comment by qijiez** [comment]
> Reference in new issue

Do you have any solution?

**Comment by qijiez** [comment]
> @howard0su about multiple inputs? currently I built a dict for these inputs, and struct like this: `map<string, vector<vector<torch::Tensor>>> smalldata;` and got error:
> 
> ```
> (torch) yang.zeng@feature-All-Series:~/LaneGCN-master/example-app/build$ make
> Scanning dependencies of target example-app
> [ 50%] Building CXX object CMakeFiles/example-app.dir/example-app.cpp.o
> /home/yang.zeng/LaneGCN-master/example-app/example-app.cpp: In function ‘int main(int, const char**)’:
> /home/yang.zeng/LaneGCN-master/example-app/example-app.cpp:226:49: error: no matching function for call to ‘torch::jit::Module::forward(std::map<std::basic_string<char>, std::vector<std::vector<at::Tensor> > >&)’
>      at::Tensor output = module.forward(smalldata).toTensor();
>                                                  ^
> In file included from /home/yang.zeng/libtorch/include/torch/csrc/jit/serialization/import.h:5:0,
>                  from /home/yang.zeng/libtorch/include/torch/script.h:8,
>                  from /home/yang.zeng/LaneGCN-master/example-app/example-app.cpp:1:
> /home/yang.zeng/libtorch/include/torch/csrc/jit/api/module.h:113:10: note: candidate: c10::IValue torch::jit::Module::forward(std::vector<c10::IValue>)
>    IValue forward(std::vector<IValue> inputs) {
>           ^~~~~~~
> /home/yang.zeng/libtorch/include/torch/csrc/jit/api/module.h:113:10: note:   no known conversion for argument 1 from ‘std::map<std::basic_string<char>, std::vector<std::vector<at::Tensor> > >’ to ‘std::vector<c10::IValue>’
> CMakeFiles/example-app.dir/build.make:62: recipe for target 'CMakeFiles/example-app.dir/example-app.cpp.o' failed
> make[2]: *** [CMakeFiles/example-app.dir/example-app.cpp.o] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/example-app.dir/all' failed
> make[1]: *** [CMakeFiles/example-app.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> ```
> 
> How can I input this dictionary?

Have you solved your problem?

**Comment by PaulaZhang1996** [comment]
> @qijiez 偶遇大佬！已经解决了感谢！

hello how did you solved your problem? I meet the same problem.

**Comment by Ryan-Faulkner** [comment]
> PaulaZhang1996

Late response but responding mainly for others who find this thread like I did.

Forward functions in libtorch/c++ seem to be impossible to define as taking a single list, vector, dict, array, etc.

The solution I found was to explicitly define in my original python code each tensor input. So instead of passing a single list of 20 tensors, I just wrote a very long argument list, explicitly passing twenty tensors.

e.g. for three tensors, `forward(self, listOfInputs)` becoming defined as `forward(self, x, y, z)`

Libtorch was then able to recognise forward() as a function which takes multiple tensors, and so accepted the list of inputs.

Went slightly crazy when so many other comments explained how to pass in a list of tensors (make a `std::vector<torch::jit::IValue>`) but didn't specify that this was for a forward function with multiple arguments, as opposed to a forward function which takes a single list of inputs. A subtle but crucial difference. Haven't tested on the output end but I suspect forward() functions which `return listOfTensors` as opposed to `return x, y, z` might similarly encounter issues.
