### ISSUE TITLE
module 'torch.backends.cudnn.rnn' has no attribute 'init_rnn_descriptor'

### ISSUE THREAD

**Issue by LaiPiXiong** [pytorch/pytorch#7878]
## My code can works right on the 0.2.0 version. After i update pytorch to 0.4.0, I first change all Variable to tensor, and use "to(device) and no_grad()" instead of '.cuda()' 'volatile=True' respectively. 
Then, when i run this code, it shows errors as follows:

Traceback (most recent call last):
  File "/home/mohong/workspace/July5/train.py", line 209, in <module>
    train(opt)
Terminating BlobFetcher
  File "/home/mohong/workspace/July5/train.py", line 68, in train
    model = model.to(device)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 393, in to
    return self._apply(lambda t: t.to(device))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/home/mohong/workspace/July5/models/rnn.py", line 123, in _apply
    self.flatten_parameters()
  File "/home/mohong/workspace/July5/models/rnn.py", line 102, in flatten_parameters
    fn.rnn_desc = rnn.init_rnn_descriptor(fn, handle)
AttributeError: module 'torch.backends.cudnn.rnn' has no attribute 'init_rnn_descriptor'

**Comment by LaiPiXiong** [comment]
That's my fault, I rewrite a rnn model, which is not match the 0.4.0 version
