### ISSUE TITLE
torch.compile: InternalTorchDynamoError ('method' object has no attribute '__dict__') when tracing inspect.getfullargspec on a bound method

### ISSUE THREAD

**Issue by bhimrazy** [pytorch/pytorch#190171]
## 🐛 Describe the bug

Calling `inspect.getfullargspec()` on a bound method inside a compiled region raises an `InternalTorchDynamoError` on PyTorch 2.12 and 2.13. The same code works on 2.11 and earlier, where Dynamo graph-breaks on `inspect` and runs it eagerly.

The trigger needs the bound method to have been wrapped by Dynamo and then unwrapped again via `__wrapped__` before it's passed to `getfullargspec` — i.e. `obj.meth = compiled.dynamo_ctx(obj.meth)`, then `meth.__wrapped__`. This isn't contrived; it's what PyTorch Lightning does when a compiled model logs a metric (see the last section).

Minimal, self-contained reproducer (no third-party deps):

```python
import inspect
import torch


def takes_param(fn, name):
    if hasattr(fn, "__wrapped__"):
        fn = fn.__wrapped__          # dynamo ctx -> original bound method
    return name in inspect.getfullargspec(fn).args


class Model(torch.nn.Module):
    def step(self, x):
        takes_param(self.step, "dataloader_iter")   # introspect a bound method mid-trace
        return x * 2

    def forward(self, x):
        return self.step(x)


model = Model()
compiled = torch.compile(model)
model.step = compiled.dynamo_ctx(model.step)   # rebind step as a dynamo-wrapped method

compiled(torch.randn(4))
```

This is a tracing-stage failure, so it's independent of the backend — it reproduces with the default backend and never reaches a compiled graph.

I traced it into `torch/_dynamo/variables/dicts.py`. When Dynamo emulates the `obj.__signature__` lookup that `inspect._signature_from_callable` performs, it reaches `SideEffectsProxyDict.get_example_value_dict`, which does `object.__getattribute__(value, "__dict__")`. `method` objects have no `__dict__`, so this raises a raw `AttributeError` that escapes as `InternalTorchDynamoError` instead of either graph-breaking or being surfaced as an in-graph `AttributeError` that the `try/except` in `_signature_from_callable` would catch.

Possibly related but distinct: #147201 — same function, but that was an `Unsupported: 'skip function getfullargspec'` graph-break on a plain function and is closed as non-reproducible. This is a hard `InternalTorchDynamoError` on a **bound method**, new in 2.12.

## Error logs

```
  File ".../torch/_dynamo/variables/dicts.py", line 1430, in get_example_value_dict
    return object.__getattribute__(value, "__dict__")
torch._dynamo.exc.InternalTorchDynamoError: AttributeError: 'method' object has no attribute '__dict__'

from user code:
   File "repro.py", line 15, in forward
     return self.step(x)
   File "repro.py", line 11, in step
     takes_param(self.step, "dataloader_iter")
   File "repro.py", line 7, in takes_param
     return name in inspect.getfullargspec(fn).args
   File ".../inspect.py", line 1391, in getfullargspec
     sig = _signature_from_callable(func, ...)
   File ".../inspect.py", line 2547, in _signature_from_callable
     sig = obj.__signature__
```

## Versions

Observed across versions:

| torch  | result                                        |
| ------ | --------------------------------------------- |
| 2.11.0 | works (graph-breaks on `inspect`, runs eager) |
| 2.12.0 | `InternalTorchDynamoError`                     |
| 2.13.0 | `InternalTorchDynamoError`                     |

I reproduced the error locally on 2.13.0; the 2.12 failure was observed in CI, and 2.11 and earlier are unaffected (the same code path has been green there).

Environment where I reproduced it (from `collect_env.py`):

```
PyTorch version: 2.13.0
Is CUDA available: False
Python version: 3.12.12
OS: macOS-26.3-arm64-arm-64bit
```

## Where this shows up in practice

PyTorch Lightning hits this whenever a `torch.compile`d model calls `self.log()` during training. It rebinds the step methods to Dynamo-wrapped versions in [`compile.py`](https://github.com/Lightning-AI/pytorch-lightning/blob/master/src/lightning/pytorch/utilities/compile.py) and then introspects the step signature inside `self.log()` via [`is_param_in_hook_signature`](https://github.com/Lightning-AI/pytorch-lightning/blob/master/src/lightning/pytorch/utilities/signature_utils.py) — the `__wrapped__` + `getfullargspec` sequence above. Downstream tracking issue: https://github.com/Lightning-AI/pytorch-lightning/issues/21836.

---

> _Disclosure per the repo's [AI policy](https://github.com/pytorch/pytorch/blob/main/AI_POLICY.md): I used Claude Code to help investigate and draft this report. I reproduced the failure locally on 2.13.0, saw the 2.12 failure in CI, and reviewed the root-cause pointer into `dicts.py` myself._

cc @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @kadeng @amjames @jataylo @azahed98
