### ISSUE TITLE
ATen doesn't compile with g++ 4.8.2

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#3571]
The errors we obtain are the following:
```
~/sandbox/pytorch/torch/lib/build/aten/src/ATen/ATen/CPULongType.cpp: In member function ‘virtual at::Tensor& at::CPULongType::m_fill_(at::Tensor&, const at::Tensor&) const’:
~/sandbox/pytorch/torch/lib/build/aten/src/ATen/ATen/CPULongType.cpp:186:18: error: expected ‘)’ before ‘PRId64’
         "with %" PRId64 " dimension(s)", value.dim());
```

A fix that worked for us is to add
```c
#define __STDC_FORMAT_MACROS
#include <inttypes.h>
```
in [ATen/templates/Type.h](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/templates/Type.h#L15), but I'm not sure this is the best solution to this problem.

**Comment by soumith** [comment]
this is the best solution, it's what we should do in c++ settings. Can you send a PR please.

**Comment by andreh7** [comment]
A similar fix was applied in #3190 .

Alternatively, adding the `#define` in `aten/src/ATen/templates/TypeDerived.cpp` seems to fix it also (and would keep the define away from code which includes the derived header files).

**Comment by fmassa** [comment]
I think I prefer @andreh7 solution, but I'm not very familiar with ATen. If there are no objections I'll add the `define` there
