### PR TITLE
[Pipelining] Make PipelineStage support meta initialization

### LINKED ISSUE #136225: [pipelining] create two stage instances out of same stage module
### 🚀 The feature, motivation and pitch

Was trying to build two `PipelineStage` runtimes out of one copy of stage module. The two runtimes differ in the input they expect (e.g. one for prefilling, the other for decoding).

Hit the following error:
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 945, in _apply
[rank0]:     torch.utils.swap_tensors(param, param_applied)
[rank0]:   File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/utils/__init__.py", line 91, in swap_tensors
[rank0]:     check_use_count(t1, "t1")
[rank0]:   File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/utils/__init__.py", line 89, in check_use_count
[rank0]:     raise RuntimeError(error_str)
[rank0]: RuntimeError: Expected use_count of t1 to be 1 or 2 with an AccumulateGrad node but got 4 make sure you are not holding references to the tensor in other places.

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/kw2501/local/torchchat/dist_run.py", line 531, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/kw2501/local/torchchat/dist_run.py", line 444, in main
[rank0]:     decode_stage = PipelineStage(
[rank0]:   File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/distributed/pipelining/stage.py", line 1160, in __init__
[rank0]:     self.submod.to(self.device)
[rank0]:   File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1340, in to
[rank0]:     return self._apply(convert)
[rank0]:   File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
[rank0]:     module._apply(fn)
[rank0]:   File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
[rank0]:     module._apply(fn)
[rank0]:   File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
[rank0]:     module._apply(fn)
[rank0]:   [Previous line repeated 1 more time]
[rank0]:   File "/home/kw2501/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 949, in _apply
[rank0]:     raise RuntimeError(
[rank0]: RuntimeError: _apply(): Couldn't swap Linear.weight
```

The related line of code in pipelining is:
https://github.com/pytorch/pytorch/blob/48d18fbd4cf785e1f69a6555d97a39023a5d199e/torch/distributed/pipelining/stage.py#L1261

Shall we not do this move? My understanding is that it is a convenience feature; but it seems not a big ask if the user were to do it.

### Alternatives

An alternative would be for PipelilneStage to support dynamic input sizes. In this case (prefill vs decode), it is the sequence length that varies.

### Additional context

cc: @H-Huang @wconstab 

cc @XilunWu @H-Huang @awgu @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136243

Avoid allocating memory or dry-running the submodule during stage init.

Save user-provided input/output metadata during stage init, to allow
lazily initializing the buffers before the first step call.

Later, we plan to build on top of this to add lazy shape inference
(#130856) so that no input/output shapes are required at stage init.

For now, we require input/output tensors for stage init, but these
should be on meta device and stage should not allocate any real memory.

Note: this needs more thorough testing and review, but it worked on the
torchtitan 3d test.

TODO:
- delete 'device' arg from PipelineStage ctor? (move it to inferred from
  args tensors passed to first step call? separate PR.
- delete 'output_args' from PipelineStage ctor? we don't actually need
  it, but we use it to do shape validation, which is why I didn't remove
  it in this PR.  Proposal: leave it until we add lazy shape inference?

Fixes #136225, #136226

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @d4l3k @c-p-i-o

### CODE REVIEW

File: torch/distributed/pipelining/stage.py [hunk 1]
```diff
@@ -1258,23 +1258,13 @@ def __init__(
...
-            self.outputs = _create_empty_tensors(self.outputs, device)
-        else:
-            self.outputs = _create_empty_tensors(output_args, device)
-
-        self._configure_outputs_meta(tuple(self.outputs))
+        self.inputs: List[torch.Tensor] = None
+        self.inputs_meta = (
+            (input_args,) if isinstance(input_args, torch.Tensor) else input_args
+        )
+        self._configure_outputs_meta(
```
Comment (H-Huang) [inline torch/distributed/pipelining/stage.py:1265]: This will make `output_args` required (right now it is optional), otherwise initialization will fail right? To have a better transition, can we still run `self.submod()` with the input args and leave the output_args to be false. This will fail if the model is not on the same device as the input, but that is okay and we can say we expect them to be both on meta device.

**Review by H-Huang — APPROVED** [review]
Thanks for the quick fix!

File: torch/distributed/pipelining/stage.py (hunk 1 above)
Comment (wconstab) [reply torch/distributed/pipelining/stage.py:1265]: you're right that this makes output_args required.  I like your suggestion.  If you're willing to let it be an error if users pass real inputs, I would propose to assert the module and inputs are on the same device, and then compute 'outputs_meta' based on inputs.

I was weighing whether to make it a requirement to pass input/module on meta device, but I suppose that is too restrictive.  I do want to ensure that outputs_meta is stored on meta to avoid wasting memory.  So maybe if the user passes cuda model/inputs I will convert the output to meta.  Wdyt?

**Review by kwen2501 — APPROVED** [review]
Lgtm.
We have modified single-stage schedule at this point but not multi-stage ones?

**Comment by wconstab** [comment]
Oh, I should include multi stage schedule in this PR, I'll fix it before landing

**Comment by kwen2501** [comment]
Confirm fixes https://github.com/pytorch/pytorch/issues/136225

**Comment by kwen2501** [comment]
Confirm fixes https://github.com/pytorch/pytorch/issues/136226

File: torch/distributed/pipelining/stage.py (hunk 1 above)
Comment (wconstab) [reply torch/distributed/pipelining/stage.py:1287]: ok, i added output-shape inference back in, but i made it refuse to do inference on non-meta device, so some user code might still have to switch their inputs to meta.  is this ok, or should i make it work for cuda?

File: torch/distributed/pipelining/schedules.py [hunk 2]
```diff
@@ -1186,6 +1180,12 @@ def step(self, *args, target=None, losses: Optional[List] = None, **kwargs):
         target: target for the loss function.
         losses: a list to store the losses for each microbatch.
         """
+        if not self._stages_initialized:
```
Comment (wconstab) [inline torch/distributed/pipelining/schedules.py:1183]: hm, should I move this logic inside _step_microbatches? it seems some of our tests are calling _step_microbatches.  Do we allow this or do we require calling step()?

if we don't require calling step(), then should we also move this code inside _step_microbatches? 

```        # Clean per iteration
        self._stage.clear_runtime_states()
```

File: torch/distributed/pipelining/stage.py [hunk 3]
```diff
@@ -1257,25 +1268,25 @@ def __init__(
         group: Optional[dist.ProcessGroup] = None,
         dw_builder: Optional[Callable[[], Callable[..., None]]] = None,
     ):
+        assert submodule.device == torch.device(
```
Comment (wconstab) [inline torch/distributed/pipelining/stage.py:1271]: this assertion breaks tests. i guess itll break some existing usages.  Is it a good thing to do to prevent bad practices in the future, or should i relax this and make it work if model+inputs are on cuda?

Comment (kwen2501) [reply torch/distributed/pipelining/stage.py:1271]: I think we should relax this. "meta" device is still a high-end thing for most users.
And, is `nn.Module.device` a real thing?

Comment (wconstab) [reply torch/distributed/pipelining/stage.py:1271]: hmm, its not always possible to assert this- maybe there is another way to reliably check the device of the module?

` AttributeError: 'FSDPSequential' object has no attribute 'device'`

File: torch/distributed/pipelining/stage.py [hunk 4]
```diff
@@ -1257,25 +1268,25 @@ def __init__(
...
-
-        self.inputs = _create_empty_tensors(input_args, device)
-
+        self.inputs: Optional[List[torch.Tensor]] = None
+        inputs_devices = set(
+            tree_map_only(torch.Tensor, lambda x: x.device, input_args)
+        )
+        assert (
+            len(inputs_devices) == 1 and inputs_devices.pop() == submodule.device
+        ), "Inputs were not all on the meta device, refusing to perform shape inference"
```
Comment (kwen2501) [inline torch/distributed/pipelining/stage.py:1281]: Same, shall we relax "meta" requirement? is `submodule.device` a thing?

File: torch/distributed/pipelining/stage.py (hunk 1 above)
Comment (H-Huang) [reply torch/distributed/pipelining/stage.py:1287]: It probably might be easier to just let it work for cuda if the users already have it on cuda. Then you wouldn't have to fix all the tests as you mentioned above. I think the main fix of the PR can just be removing the `.to(device)` in init which you did, and with that removal now it is up to the users to make sure that `model(input_args)` works if they pass it in.

Comment (kwen2501) [reply torch/distributed/pipelining/stage.py:1287]: Hmm, can I say that I prefer the previous version better? i.e. removal.
(See also my comments about on relaxing device constraint, which requires removal of dryrun.)

File: torch/distributed/pipelining/stage.py [hunk 5]
```diff
@@ -1434,9 +1457,13 @@ def _validate_stage_shapes(pipeline_stages: List[PipelineStage]):
...
         ]
-        expected_outputs = stage.outputs
-        stage_output = _create_metadata_tensor(expected_outputs, device=stage.device)
-        dist.all_gather(tensor_list, stage_output)
+        outputs_meta = stage.get_outputs_meta()
+        # TODO, (1) are we deleting output validation when we move to shape inference?
+        # (2) if not, we should support multiple outputs
+        assert (
+            len(outputs_meta) == 1
+        ), f"validation logic assumes single output, got {len(outputs_meta)} outputs "
```
Comment (kwen2501) [inline torch/distributed/pipelining/stage.py:1465]: Oh then should we disable validation logic (which an add-on protection) till it supports the multi-output case? Multi-output is pretty common. This assert may break a few tracer cases.

File: torch/distributed/pipelining/stage.py (hunk 1 above)
Comment (H-Huang) [reply torch/distributed/pipelining/stage.py:1287]: Hmm, I'm in the other boat, I think keeping the dry run makes more sense (as a temporary measure) until we get the lazy init working, otherwise we have to update all the tests to pass in both input_args and output_args and also requires users to do so as well.

File: torch/distributed/pipelining/schedules.py (hunk 2 above)
Comment (kwen2501) [reply torch/distributed/pipelining/schedules.py:1183]: Yeah. That would be a good place.
We may have to ask CUDA Graph to only come capture after the first step(...) though.
But that may not be a big deal? And the current change moved the prepare from init to step anyway.

File: torch/distributed/pipelining/stage.py (hunk 1 above)
Comment (kwen2501) [reply torch/distributed/pipelining/stage.py:1287]: Yeah, that's hard. Maybe at least add `with torch.no_grad()`? 
I am actually not sure what side effect running a module has. Saving grad context, marking requires_grad?

File: torch/distributed/pipelining/stage.py (hunk 3 above)
Comment (wconstab) [reply torch/distributed/pipelining/stage.py:1271]: yea, maybe i should just drop the checks and perform the shape inference blindly, but then do a .to(meta) on the outputs.  that should make things on par for what howard mentioned, and then we can delete it once we add lazy inference

Comment (weifengpy) [reply torch/distributed/pipelining/stage.py:1271]: `FSDPSequential` is a superset of 'nn.Sequential'. It means vanilla `nn.Sequential` does not have `device`. I guess what we really want to check whether `model.parameters()` are on meta? that should cover all cases

```
>>> import torch
>>> model = torch.nn.Sequential(torch.nn.Linear(2,2))
>>> model.device
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/weif/pytorch/torch/nn/modules/module.py", line 1931, in __getattr__
    raise AttributeError(
AttributeError: 'Sequential' object has no attribute 'device'
```

File: torch/distributed/pipelining/stage.py (hunk 1 above)
Comment (kwen2501) [reply torch/distributed/pipelining/stage.py:1287]: Also, in `forward_maybe_with_...` we have special logic for DDP/FSDP modules, would this dryrun's escape be an issue? (Or are we just lucky?)

Comment (wconstab) [reply torch/distributed/pipelining/stage.py:1289]: i'm going to leave this for later. its not any worse with this PR and we plan to remove it when adding lazy shape inference.  sound ok?

File: torch/distributed/pipelining/schedules.py (hunk 2 above)
Comment (wconstab) [reply torch/distributed/pipelining/schedules.py]: annoying: Stage class doesn't know "n_microbatches", which may have been intentional? 

I am thinking about whether it is bad to let the schedule 'register' the number of microbatches during Schedule.__init__ and then stage can use this value later when it performs initialization inside forward_one_chunk / backward_one_chunk?

File: torch/distributed/pipelining/stage.py (hunk 5 above)
Comment (wconstab) [reply torch/distributed/pipelining/stage.py:1462]: if this is a new regression, i can remove the assert, but i thought the assert would just make another error more explicit.  The old code assumes 'output' is a single value and tries to validate against it.  Lets see if CI fails and if not, make another PR to fix validation?

File: torch/distributed/pipelining/stage.py (hunk 1 above)
Comment (kwen2501) [reply torch/distributed/pipelining/stage.py:1286]: Yep, sounds good.

File: torch/distributed/pipelining/stage.py (hunk 5 above)
Comment (kwen2501) [reply torch/distributed/pipelining/stage.py:1462]: I see. Yep, if it is not a new assert, then let's see what CI says. :)

**Review by kwen2501 — APPROVED** [review]
