### PR TITLE
[user errors] compulsory case names, allow multiple

### PR DESCRIPTION
**Pull request by avikchaudhuri**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #110878

We want to get to a point where most UserErrors link to exportdb examples. This PR makes passing case names non-optional to make this intent clearer and encourage developers who raise UserErrors to make or point to examples that make fixing such errors more obvious for users.

In addition, sometimes there are multiple examples that are relevant to an error. Thus this PR also enables passing multiple case names.

Retry of #110733 which was reverted due to a landrace.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @gmagogsfm @zhxchen17 @tugsbayasgalan

### CODE REVIEW

**Review by gmagogsfm — APPROVED** [review]

**Review by tugsbayasgalan — APPROVED** [review]

**Comment by kit1980** [comment]
@pytorchbot revert -m "export/test_export.py::TestExport::test_multiple_definitions_same_name_dim - TypeError: UserError.__init__() missing 1 required positional argument: 'case_names' -c landrace
"

**Comment by kit1980** [comment]
@avikchaudhuri Looks like a landrace with your own PR https://github.com/pytorch/pytorch/pull/110638

**Comment by kit1980** [comment]
I'm unlinking Unpublished diff D50087148 to revert this.

**Comment by avikchaudhuri** [comment]
@kit1980 Just want to confirm whether everything is in sync.

1. Initial attempt at this PR was #110733.
2. PR in (1) got reverted by #110783. Yet PR (1) got imported / landed internally as D50090877. This might be because the revert was manual?
3. The current PR was a retry of the original. Now this is reverted. So net effect is that GH doesn't have this change (neither from the retry or the original). So hopefully nothing is broken on GH.
4. However, fbcode still shows the change because of (2). And it also has the change #110638, which you linked as the causing the land race, and which landed internally as D49965944. So I'm afraid the test is currently broken on fbcode.

This doesn't seem OK, does it?

**Comment by kit1980** [comment]
@avikchaudhuri https://github.com/pytorch/pytorch/pull/110783 will be imported and landed to fbcode, so everything will be fine.

We're a bit behind on fbcode sync since Friday.
