### ISSUE TITLE
xpu: build fails with intel::reqd_sub_group_size deprecated attribute error

### ISSUE THREAD

**Issue by dvrogozh** [pytorch/pytorch#186661]
On:
* https://github.com/pytorch/pytorch/commit/b722e151b04fcc935ce69411f4dc1d5768d89275

With:
* Ubuntu 24.04
* https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-13.html (oneAPI 2026.0)
* GCC 13.3.0

Building PyTorch with XPU backend fails with the attribute deprecated warning being forced to error:
```
$ python3 -m venv build
$ . build/bin/activate
$ TORCH_XPU_ARCH_LIST=pvc python3 setup.py develop 2>&1 | tee log.txt
...
  /home/dvrogozh/git/pytorch/pytorch2/third_party/torch-xpu-ops/src/ATen/native/xpu/sycl/Indexing.cpp:977:5: warning: attribute 'intel::re
qd_sub_group_size' is deprecated [-Wdeprecated-attributes]
    977 |   [[intel::reqd_sub_group_size(SIMD)]] void operator()(
        |     ^
  /home/dvrogozh/git/pytorch/pytorch2/third_party/torch-xpu-ops/src/ATen/native/xpu/sycl/Indexing.cpp:977:5: note: did you mean to use 'sy
cl::reqd_sub_group_size' instead?
    977 |   [[intel::reqd_sub_group_size(SIMD)]] void operator()(
        |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        |     sycl::reqd_sub_group_size
  1 warning generated.
  /home/dvrogozh/git/pytorch/pytorch2/third_party/torch-xpu-ops/src/ATen/native/xpu/sycl/Indexing.cpp:977:5: warning: attribute 'intel::reqd_sub_group_size' is deprecated [-Wdeprecated-attributes]
    977 |   [[intel::reqd_sub_group_size(SIMD)]] void operator()(
        |     ^
  /home/dvrogozh/git/pytorch/pytorch2/third_party/torch-xpu-ops/src/ATen/native/xpu/sycl/Indexing.cpp:977:5: note: did you mean to use 'sycl::reqd_sub_group_size' instead?
    977 |   [[intel::reqd_sub_group_size(SIMD)]] void operator()(
        |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        |     sycl::reqd_sub_group_size
  1 warning generated.
  /home/dvrogozh/git/pytorch/pytorch2/third_party/torch-xpu-ops/src/ATen/native/xpu/sycl/Indexing.cpp:978:30: error: ‘intel::reqd_sub_group_size’ scoped attribute directive ignored [-Werror=attributes]
    978 |       sycl::nd_item<1> item) const {
        |                              ^~~~~
  cc1plus: all warnings being treated as errors
```

CC: @guangyey @EikanWang

cc @malfet @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by guangyey** [comment]
I will take a look.

**Comment by guangyey** [comment]
Hi @dvrogozh we already fix this issue in https://github.com/intel/torch-xpu-ops/pull/3892 and will update the xpu commit pin soon.

**Comment by dvrogozh** [comment]
The issue was introduced by https://github.com/intel/torch-xpu-ops/pull/2294. @guangyey , @chuanqi129 , why our ci tests overlooked the issue for this PR? build for the PR should have failed. Do we relax warning treatment as errors in ci builds?

**Comment by chuanqi129** [comment]
Hi @dvrogozh the CI also used GCC13.2, but need to double check why this issue can not be detected, refer https://github.com/pytorch/pytorch/actions/runs/27157982095/job/80165740352#step:8:3435

**Comment by dvrogozh** [comment]
@chuanqi129 , CI had the same warnings, but they were not treated as errors for some reason:
```
2026-06-08T18:41:39.4229545Z /__w/pytorch/pytorch/third_party/torch-xpu-ops/src/ATen/native/xpu/sycl/Indexing.cpp:977:5: warning: attribute 'intel::reqd_sub_group_size' is deprecated [-Wdeprecated-attributes]
2026-06-08T18:41:39.4230334Z   977 |   [[intel::reqd_sub_group_size(SIMD)]] void operator()(
2026-06-08T18:41:39.4230641Z       |     ^
2026-06-08T18:41:39.4231185Z /__w/pytorch/pytorch/third_party/torch-xpu-ops/src/ATen/native/xpu/sycl/Indexing.cpp:977:5: note: did you mean to use 'sycl::reqd_sub_group_size' instead?
2026-06-08T18:41:39.4231929Z   977 |   [[intel::reqd_sub_group_size(SIMD)]] void operator()(
2026-06-08T18:41:39.4232283Z       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2026-06-08T18:41:39.4232620Z       |     sycl::reqd_sub_group_size
2026-06-08T18:41:39.4232915Z 1 warning generated.
2026-06-08T18:41:39.4233607Z /__w/pytorch/pytorch/third_party/torch-xpu-ops/src/ATen/native/xpu/sycl/Indexing.cpp:977:5: warning: attribute 'intel::reqd_sub_group_size' is deprecated [-Wdeprecated-attributes]
2026-06-08T18:41:39.4234334Z   977 |   [[intel::reqd_sub_group_size(SIMD)]] void operator()(
2026-06-08T18:41:39.4234666Z       |     ^
2026-06-08T18:41:39.4235669Z /__w/pytorch/pytorch/third_party/torch-xpu-ops/src/ATen/native/xpu/sycl/Indexing.cpp:977:5: note: did you mean to use 'sycl::reqd_sub_group_size' instead?
2026-06-08T18:41:39.4236482Z   977 |   [[intel::reqd_sub_group_size(SIMD)]] void operator()(
2026-06-08T18:41:39.4236824Z       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2026-06-08T18:41:39.4237129Z       |     sycl::reqd_sub_group_size
2026-06-08T18:41:39.4237421Z 1 warning generated.
2026-06-08T18:41:39.4238551Z /__w/pytorch/pytorch/third_party/torch-xpu-ops/src/ATen/native/xpu/sycl/Indexing.cpp:978:30: warning: ‘intel::reqd_sub_group_size’ scoped attribute directive ignored [-Wattributes]
2026-06-08T18:41:39.4239226Z   978 |       sycl::nd_item<1> item) const {
2026-06-08T18:41:39.4239543Z       |                              ^~~~~
```
