### ISSUE TITLE
../c10/util/Flags.h:78:10: fatal error: 'gflags/gflags.h' file not found

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#16281]
building PyTorch on OS X on master

```
/usr/local/opt/ccache/libexec/g++  -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -DUSE_GCC_ATOMICS=1 -D_FILE_OFFSET_BITS=64 -D_THD_CORE=1 -I../aten/src -I. -I../ -isystem /Users/ezyang/Dev/pytorch-tmp-env/include -isystem ../third_party/ideep/include -isystem ../third_party/ideep/mkl-dnn/include -I../third_party/protobuf/src -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../cmake/../third_party/googletest/googletest/include -I../cmake/../third_party/benchmark/include -isystem ../third_party -isystem ../cmake/../third_party/eigen -isystem /Users/ezyang/Dev/pytorch-tmp-env/include/python3.6m -isystem /Users/ezyang/Dev/pytorch-tmp-env/lib/python3.6/site-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -I../third_party/onnx -Ithird_party/onnx -I../torch/lib/THD/.. -Iaten/src -Icaffe2/aten/src -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_FBGEMM -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -faligned-new -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -std=c++11 -O3  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -fPIC   -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD -std=gnu++11 -MD -MT caffe2/torch/lib/THD/CMakeFiles/THD.dir/base/DataChannelRequest.cpp.o -MF caffe2/torch/lib/THD/CMakeFiles/THD.dir/base/DataChannelRequest.cpp.o.d -o caffe2/torch/lib/THD/CMakeFiles/THD.dir/base/DataChannelRequest.cpp.o -c ../torch/lib/THD/base/DataChannelRequest.cpp
In file included from ../torch/lib/THD/base/DataChannelRequest.cpp:1:
In file included from ../torch/lib/THD/../THD/base/DataChannelRequest.hpp:3:
In file included from ../torch/lib/THD/../THD/base/DataChannel.hpp:4:
In file included from ../torch/lib/THD/../THD/base/ChannelUtils.hpp:3:
In file included from ../aten/src/ATen/ATen.h:5:
In file included from ../aten/src/ATen/Context.h:4:
In file included from ../aten/src/ATen/Type.h:2:
In file included from ../aten/src/ATen/core/Type.h:594:
In file included from ../aten/src/ATen/core/Tensor.h:10:
In file included from ../c10/core/TensorImpl.h:16:
../c10/util/Flags.h:78:10: fatal error: 'gflags/gflags.h' file not found
#include <gflags/gflags.h>
```

Error bisected to 8964a2e6e6f035590260ac5d4ab21f6e3d8a5204

Here is the contents of my brew installed gflags cmake information: [gflags-cmake.zip](https://github.com/pytorch/pytorch/files/2789481/gflags-cmake.zip)

**Comment by ezyang** [comment]
cmake log on fc5b79cd1c6020c20640128e43bac43fd636121e: 
[cmake.log](https://github.com/pytorch/pytorch/files/2789512/cmake.log)

**Comment by angelos-c** [comment]
Hey, have you managed to solve this?

**Comment by ezyang** [comment]
No, I don't think @pjh5 has solved this yet

**Comment by shmakovigor** [comment]
Facing exactly the same issue on macOS. Any solutions? @ezyang @angelos-c

**Comment by pjh5** [comment]
This should have been fixed by https://github.com/pytorch/pytorch/pull/16789
