### PR TITLE
torch.histc added a finite range check to resolve segfaults if tensor has inf. also added checks for nan values, min>max

### PR DESCRIPTION
**Pull request by anjali411**
https://github.com/pytorch/pytorch/issues/27464

### CODE REVIEW

File: aten/src/TH/generic/THTensorMoreMath.cpp [hunk 1]
```diff
@@ -1284,6 +1284,8 @@ void THTensor_(histc)(THTensor *hist, THTensor *tensor, int64_t nbins, scalar_t
     maxval = maxval + 1;
   }
 
+  TORCH_CHECK(!(std::isinf(minval) || std::isinf(maxval)), "range of [", minval, ", ", maxval, "] is not finite");
+
```
Comment (nairbv) [inline aten/src/TH/generic/THTensorMoreMath.cpp]: looks good, let's also add the example from the issue to a unit test too

**Review by vadimkantorov — COMMENTED** [review]
Will it be fine for NaN?

**Comment by anjali411** [comment]
@vadimkantorov good point! I added a check for that and it will throw an error for tensors with nan values in case a finite range is not specified

File: test/test_torch.py [hunk 2]
```diff
@@ -10355,6 +10355,31 @@ def test_histc(self, device):
         self.assertEqual(
             torch.tensor([1], dtype=torch.float, device=device),
             actual)
+        # tensors with inf; min, max not provided -- should throw a RuntimeError
+        self.assertEqual(
+            torch.histc(torch.tensor([float("inf")], dtype=torch.float, device=device)),
+            "range of [inf, inf] is not finite")
```
Comment (nairbv) [inline test/test_torch.py]: I think since this is raising an error not returning a string value, this check isn't going to work. you probably want assertRaisesRegex.

File: test/test_torch.py [hunk 3]
```diff
@@ -10355,6 +10355,31 @@ def test_histc(self, device):
...
+        self.assertEqual(
+            torch.histc(torch.tensor([1., 2., float("inf")], dtype=torch.float, device=device)),
+            "range of [1, inf] is not finite")
+        # tensors with inf; min, max provided
+        self.assertEqual(
+            torch.histc(torch.tensor([float("inf")], dtype=torch.float, device=device),
+            bins=1, min=0, max=3),
```
Comment (nairbv) [inline test/test_torch.py]: flake8 is complaining about the indent on this line

**Review by yf225 — APPROVED** [review]
Changes look awesome! CI failure is likely unrelated, after rebasing and passing CI we should be good to go.

File: aten/src/ATen/native/cuda/SummaryOps.cu [hunk 4]
```diff
@@ -323,6 +323,9 @@ Tensor _histc_cuda_template(
     maxvalue = maxvalue + 1;
   }
 
+  TORCH_CHECK(!(std::isinf(minvalue) || std::isinf(maxvalue) || std::isnan(minvalue) || std::isnan(maxvalue)), "range of [", minvalue, ", ", maxvalue, "] is not finite");
+  TORCH_CHECK(minvalue < maxvalue, "max must be larger than min");
```
Comment (yf225) [inline aten/src/ATen/native/cuda/SummaryOps.cu]: Windows CI gives error:
```
15:26:54 C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_math.h(409): error: more than one instance of overloaded function "fpclassify" matches the argument list:
15:26:54 SummaryOps.cu
15:26:54             function "fpclassify(float)"
15:26:54             function "fpclassify(double)"
15:26:54             function "fpclassify(long double)"
15:26:54             argument types are: (uint8_t)
15:26:54           detected during:
15:26:54             instantiation of "__nv_bool isinf(_Ty) [with _Ty=uint8_t]" 
15:26:54 C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/aten/src/ATen/native/cuda/SummaryOps.cu(326): here
15:26:54             instantiation of "at::Tensor at::<unnamed>::_histc_cuda_template(const at::Tensor &, int64_t, input_t, input_t) [with input_t=uint8_t]" 
15:26:54 C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/aten/src/ATen/native/cuda/SummaryOps.cu(357): here
```
To fix this issue, in this file I think we should write `THCNumerics<input_t>::isinf(val)` instead of `std::isinf(val)`, and `THCNumerics<input_t>::isnan(val)` instead of `std::isnan(val)` (this is taken from https://github.com/pytorch/pytorch/blob/243298668caca7ee7de454ebc4d99c487ec9b272/aten/src/ATen/native/cuda/MultinomialKernel.cu#L244-L245
). This only applies to CUDA code though, and we don't need to change the CPU code.

File: aten/src/ATen/native/cuda/SummaryOps.cu [hunk 5]
```diff
@@ -323,6 +323,9 @@ Tensor _histc_cuda_template(
     maxvalue = maxvalue + 1;
   }
 
+  TORCH_CHECK(!(THCNumerics<input_t>::isinf(minvalue) || THCNumerics<input_t>::isinf(maxvalue) || THCNumerics<input_t>::isnan(minvalue) || THCNumerics<input_t>::isnan(maxvalue)), "range of [", minvalue, ", ", maxvalue, "] is not finite");
+  TORCH_CHECK(minvalue < maxvalue, "max must be larger than min");
+
```
Comment (yf225) [inline aten/src/ATen/native/cuda/SummaryOps.cu]: rocm build is failing with:
```
18:29:27 [ 87%] Linking CXX executable ../bin/generate_proposals_op_gpu_test
18:29:29 ../lib/libtorch.so: undefined reference to `isinf(float)'
18:29:29 ../lib/libtorch.so: undefined reference to `isnan(float)'
18:29:29 ../lib/libtorch.so: undefined reference to `isnan(double)'
18:29:29 ../lib/libtorch.so: undefined reference to `isinf(double)'
18:29:29 clang: [0;1;31merror: [0mlinker command failed with exit code 1 (use -v to see invocation)[0m
```
To fix this, I think we need to `#include <THC/THCNumerics.cuh>` at the top of this file after `#include <ATen/cuda/CUDAApplyUtils.cuh>`, taking inspiration from the `aten/src/ATen/native/cuda/MultinomialKernel.cu` file.

Comment (anjali411) [reply aten/src/ATen/native/cuda/SummaryOps.cu]: oh okay 👌 thanks!!

File: aten/src/TH/generic/THTensorMoreMath.cpp [hunk 6]
```diff
@@ -1284,6 +1284,9 @@ void THTensor_(histc)(THTensor *hist, THTensor *tensor, int64_t nbins, scalar_t
     maxval = maxval + 1;
   }
 
+  TORCH_CHECK(!(std::isinf(minval) || std::isinf(maxval) || std::isnan(minval) || std::isnan(maxval)), "range of [", minval, ", ", maxval, "] is not finite");
```
Comment (bddppq) [inline aten/src/TH/generic/THTensorMoreMath.cpp]: `std::isnan` -> `th_isnan`

**Comment by yf225** [comment]
Current CI errors seem unrelated and we are ready to merge this PR :D

**Comment by nairbv** [comment]
@anjali411 this previously segfaulted right? so not BC-breaking?
