### ISSUE TITLE
AttributeError: module 'torch._C._te' has no attribute 'Reduce'

### ISSUE THREAD

**Issue by HangJie720** [pytorch/pytorch#59440]
when I run the pytorch/examples/fx/nnc_compile.py with official pytorch1.8, error is occurred,
Traceback (most recent call last):
 File "nnc_compile.py", line 447, in <module>
 cg = nnc_compile(mod, inps)
 File "nnc_compile.py", line 385, in nnc_compile
 result = lower_function(node, node.target, lookup_env(node.args), node.args)
 File "nnc_compile.py", line 326, in lower_function
 return lowering_functions[op](node.name, node.shape, inp_shapes, nnc_args)
 File "nnc_compile.py", line 306, in bmm_lower
 return te.Reduce(name, get_dim_args([B, N, P]), te.Sum(), mm, get_dim_args([M]))
AttributeError: module 'torch._C._te' has no attribute 'Reduce'

cc @gmagogsfm

**Comment by tugsbayasgalan** [comment]
This seems more related to NNC? @asuhan

**Comment by asuhan** [comment]
@ZolotukhinM Looks like an issue with the Python bindings, right?

**Comment by ZolotukhinM** [comment]
Yes, looks so, I'll take a look!

**Comment by HangJie720** [comment]
@ZolotukhinM https://github.com/pytorch/examples/blob/master/fx/nnc_compile.py

**Comment by ZolotukhinM** [comment]
Got it, thanks!

This API is not official, so it changes quickly and what possibly happened with that example is that it was written with API that's available on master branch, but was different at the 1.8 branch cut. However, you could still make it work on 1.8 if you make small edits in `nnc_compile.py`. If you replace
https://github.com/pytorch/examples/blob/cbb760d5e50a03df667cdc32a61f75ac28e11cbf/fx/nnc_compile.py#L306
with
```python
    return te.SumReduce(name, get_dim_args([B, N, P]), mm, get_dim_args([M]))
```
and
https://github.com/pytorch/examples/blob/cbb760d5e50a03df667cdc32a61f75ac28e11cbf/fx/nnc_compile.py#L318
with
```python
    return te.SumReduce(name, get_dim_args([N, P]), mm, get_dim_args([M]))
```
the example should work.

I'm going to close the issue, but please feel free to reopen it if you have other issues with the example!

**Comment by HangJie720** [comment]
@ZolotukhinM 
I try to modify it, and run with error as follows,
Traceback (most recent call last):
  File "nnc_compile.py", line 449, in <module>
    cg = nnc_compile(mod, inps)
  File "nnc_compile.py", line 402, in nnc_compile
    cg = te.construct_codegen('llvm', stmt, [te.BufferArg(x) for x in [env[i.name] for i in module_attrs] + inputs + outs])
RuntimeError: PyTorch not compiled with LLVM support!

**Comment by ZolotukhinM** [comment]
Right, this needs LLVM-enabled pytorch build. I don't think it's included into official release builds yet, but we're working on adding it.

If you build pytorch from sources, you could add `USE_LLVM=/path/to/llvm/install/` option to enable LLVM (note that this path should point to a folder with `bin` and `lib` folders, not to the `clang` executable). If you don't have LLVM, I could provide instructions on how to build it from sources too.

**Comment by HangJie720** [comment]
Thank you very much, I try to set USE_LLVM and compile from sources, running is ok.
$ python nnc_compile.py
NNC time:  0.006966352462768555
PyTorch time 0.020020246505737305
Static Runtime time 0.009425640106201172
Sums: tensor(-3.2382) tensor(-3.2382)

**Comment by ZolotukhinM** [comment]
Excellent, glad to hear that! :)
