### ISSUE TITLE
compile with cuda + openmpi : pml_ucx.c:226 Error: UCP worker does not support MPI_THREAD_MULTIPLE

### ISSUE THREAD

**Issue by mjc14** [pytorch/pytorch#10158]
my potorch  installed from source, and i  compile  with cuda-8.0 + openmpi-3.1.1  successfully ,but  when i use it ,some error happened. i need help.
[compile method](https://discuss.pytorch.org/t/segfault-using-cuda-with-openmpi/11140)
**test  #code:**
import torch
import torch.distributed as dist

dist.init_process_group(backend='mpi')

t = torch.zeros(5,5).fill_(dist.get_rank()).cuda()

dist.all_reduce(t) 

error:
pml_ucx.c:226 Error: UCP worker does not support MPI_THREAD_MULTIPLE

**Comment by ailzhang** [comment]
@mjc14 Could you also try mpi3.0.0? I cannot repro it on 3.0.0 version.
I'm installing 3.1.1, will confirm if I can repro it or not.

**Comment by ailzhang** [comment]
Hi @mjc14 , I actually did all my experiments with cuda9.0, and it works fine with openmpi 2.1 and 3.0.

**Comment by ailzhang** [comment]
@mjc14 Let us know if you still see the issue consistently, better to give us a way to repro on our end. Thanks

**Comment by mjc14** [comment]
@ailzhang could you give me your configs of experiments? or a guide line of compilation ? may be my some configs lead to the error.

**Comment by ailzhang** [comment]
Hi @mjc14 , here is my experiment script. I will get back to you with the openmpi compile guideline shortly. 

```
import torch.distributed as dist
import torch

def debug_fun():
    torch.cuda.set_device(dist.get_rank())
    torch.manual_seed(dist.get_rank())
    device = "cuda:{}".format(dist.get_rank())
    # device = "cpu"
    param = torch.FloatTensor(1,1).to(device)

    param.uniform_()
    print("Rank {}, before sync: {} at {}".format(dist.get_rank(),param.cpu().data.numpy(), param.device))
    print(param.data)
    torch.cuda.synchronize()
    dist.all_reduce(param.data)
    print("Rank {}, after sync : {} at {}".format(dist.get_rank(),param.cpu().data.numpy(), param.device))


if __name__ == '__main__':
    dist.init_process_group("mpi")
    debug_fun()
```

**Comment by ailzhang** [comment]
Hi @mjc14 , for openmpi compilation, we just did `/configure --prefix=<PATH_TO_OPENMPI> --with-cuda=<PATH_TO_CUDA>`

**Comment by ailzhang** [comment]
Closing, please reopen if you still need help.
