### PR TITLE
Set `BLAS_LIBRARIES` to `${MKL_LIBRARIES}` for MKL case

### LINKED ISSUE #72653: C++ linking to Pytorch on Linux (CPU) fails with libtorch 1.10.1 - cannot find MKL
### 🐛 Describe the bug

**test.cpp:**
```
#include "torch/script.h"

int main() {
    return 0;
}
```

**Building:** (libtorch 1.10.1 Linux, CPU, C++, cxx11 ABI)
```
g++-8 -o test-binary test.cpp -Ilibtorch/include -D_GLIBCXX_USE_CXX11_ABI=1 -Llibtorch/lib -lfbgemm -lasmjit -lnnapi_backend -lcaffe2_observers -lcaffe2_detectron_ops -lbackend_with_compiler -ltorch -ltorch_global_deps -ltorch_cpu -ltorch_python -ltorchbind_test -lXNNPACK -lmkldnn -ljitbackend_test -lcaffe2_module_test_dynamic -lshm -lc10
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_zd_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_d_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_dsbrdbn'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_zlaeh2'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_d_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_s_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_zd_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_trans_mkl_zimatcopy_square_t_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_sc_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_claeh2'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_slaeh2'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_d_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_dlaed2'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_c_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_zhbrdbn'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_dz_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_c_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_s_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_s_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_cs_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_trans_mkl_comatcopy2_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_dlaeh2'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_z_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_sc_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_cs_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_z_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_dlaed3'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_z_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_slaed3'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_trans_mkl_cimatcopy_square_t_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_z_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_c_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_ssbrdbn'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_trans_mkl_zomatcopy2_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_dz_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_s_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_d_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_c_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_chbrdbn'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_slaed2'
```

No problem with libtorch 1.8.2. But does not work with 1.10.1.

### Versions

g++-8 --version
```
g++-8 (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

cc @ezyang @gchanan @zou3519 @seemethere @malfet @jbschlosser

### PR DESCRIPTION
**Pull request by atalman**
This reverts [suggestion](https://github.com/pytorch/pytorch/pull/49647#discussion_r677737470) proposed to https://github.com/pytorch/pytorch/pull/49647

Which is somehow sufficient to workaround symptoms of https://github.com/pytorch/pytorch/issue/72653 

I.e. before this change, `BLAS_LIBRARIES` were set to `caffe2::mkl`
which is an interface library with link property set as follows:
https://github.com/pytorch/pytorch/blob/59dd84cab6ede977173cd48d64abf1bcf6b2fabb/cmake/public/mkl.cmake#L10-L12

And as per CMake doc:
https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_LINK_LIBRARIES.html

Section INTERFACE_LINK_LIBRARIES:
Note that it is not advisable to populate the INTERFACE_LINK_LIBRARIES of a target with absolute paths to dependencies. That would hard-code into installed packages the library file paths for dependencies as found on the machine the package was made on.

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
Can you provide a more detailed description why it fixes the problem?

**Review by malfet — APPROVED** [review]
Edited description. Looks good to me as a workaround (considering 1.11 urgency), but needs a follow up
