### ISSUE TITLE
14k github models TorchDynamo + TorchInductor bugs umbrella task

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#92670]
We are welcome contributions, please check [14k github models test and debug env setup](https://github.com/pytorch/pytorch/issues/93667#issue-1565238954) for how to reproduce these issues.
### TorchDynamo ([pass rate tracker](https://github.com/pytorch/pytorch/issues/93667))
* [x] pytest ./generated/test_BlinkDL_RWKV_LM.py -k test_005 [Subclasses torch.jit.ScriptModule - unusual usage, not a priority]
* [x] pytest ./generated/test_INVOKERer_DeepRFT.py -k test_010 https://github.com/pytorch/pytorch/pull/91840 (@davidberard98)
* [x] pytest ./generated/test_assassint2017_abdominal_multi_organ_segmentation.py -k test_000 https://github.com/pytorch/pytorch/pull/93043 (@davidberard98)
* [x] pytest ./generated/test_facebookresearch_ClassyVision.py -k test_008
* [x] pytest ./generated/test_facebookresearch_denoiser.py -k test_005 [fails eager]
* [x] pytest ./generated/test_facebookresearch_pytext.py -k test_001 (shape_as_tensor handling)
* [x] pytest ./generated/test_fangwei123456_spikingjelly.py -k test_016 @davidberard98  https://github.com/pytorch/pytorch/pull/94658
* [ ] pytest ./generated/test_github_pengge_PyTorch_progressive_growing_of_gans.py -k test_002 [numpy.ndarray] (https://github.com/pytorch/pytorch/issues/93684 ?)
* [x] pytest ./generated/test_guanfuchen_semseg.py -k test_034 [segfault in triton]
* [x] pytest ./generated/test_ludwig_ai_ludwig.py -k test_018 (@yanboliang)
* [x] pytest ./generated/test_nianticlabs_simplerecon.py -k test_001 [segfault in triton]
* [ ] pytest ./generated/test_pytorch_translate.py -k test_006 (InternalTorchDynamoError: 'int' object has no attribute 'view')
* [x] pytest ./generated/test_easezyc_deep_transfer_learning.py -k test_004 (cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @davidberard98, this is regression caused by #91840) https://github.com/pytorch/pytorch/pull/94332
* [x] pytest ./generated/test_ELEKTRONN_elektronn3.py -k test_018 (#92922) @yanboliang 
* [x] pytest ./generated/test_HaSai666_rec_pangu.py -k test_017 (#92926) @yanboliang 
* [x] pytest ./generated/test_Shmuma_ptan.py -k test_002 (#93177) @yanboliang 
* [x] pytest ./generated/test_awslabs_sockeye.py -k test_009 (#94145) @yanboliang
* [x] pytest ./generated/test_lorenmt_mtan.py -k test_005 (invalid combination of arguments) (#97508) @lantiankaikai
* [x] pytest ./generated/test_ustcml_RecStudio.py -k test_036 (invalid combination of arguments) (#97508) @lantiankaikai
* [x] pytest ./generated/test_PeterouZh_CIPS_3D.py -k test_003 (#97810) @lantiankaikai
* [x] pytest ./generated/test_IDEA_CCNL_Fengshenbang_LM.py -k test_008 (https://github.com/pytorch/pytorch/pull/101141) @yanboliang 
* [ ] pytest ./generated/test_VainF_pytorch_msssim.py -k test_000 @lyoka
* [ ] pytest ./generated/test_sony_sqvae.py -k test_007 (Tensor-likes are not close!) @chaekit 

### TorchInductor ([pass rate tracker](https://github.com/pytorch/pytorch/issues/93667))
* [x] pytest ./generated/test_baal_org_baal.py -k test_011 https://github.com/pytorch/pytorch/pull/96634 @ngimel
* [x] pytest ./generated/test_ZhaoJ9014_face_evoLVe.py -k test_000 (@yanboliang)
* [x] pytest ./generated/test_ACheun9_Pytorch_implementation_of_Mobile_Former.py -k test_002 [addmm(inp, mat1, mat2) with scalar inp] @davidberard98
* [x] pytest ./generated/test_BloodAxe_pytorch_toolbelt.py -k test_070 (https://github.com/pytorch/pytorch/pull/101051) @yanboliang
* [x] pytest ./generated/test_adriansahlman_stylegan2_pytorch.py -k test_000 (#98448) @chaekit  
* [ ] pytest ./generated/test_HomebrewNLP_revlib.py -k test_004 (KeyError: 'val') 
* [x] pytest ./generated/test_ProGamerGov_neural_dream.py -k test_000 (LoweringException: AssertionError: target: aten.avg_pool2d.default) @yanboliang (https://github.com/pytorch/pytorch/pull/96727)
* [x] pytest ./generated/test_NKI_AI_direct.py -k test_009 (Unhandled FakeTensor Device Propagation for aten.copy.default, found two different devices cpu, cuda:0) (https://github.com/pytorch/pytorch/pull/102677) @davidberard98 
* [ ] pytest ./generated/test_XuyangBai_PointDSC.py -k test_004 (RuntimeError: as_strided_scatter: sizes [4], strides [85], storage offset 256  and itemsize 4 requiring a storage size of 2048 are out of bounds for storage of size 1024) (#98483) @lantiankaikai
* [ ] pytest ./generated/test_agrimgupta92_sgan.py -k test_000 (RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu)
* [x] pytest ./generated/test_hkchengrex_XMem.py -k test_013 (LoweringException: AssertionError: target: aten.index_put.default) @yanboliang (https://github.com/pytorch/pytorch/pull/97105)
* [ ] pytest ./generated/test_laddie132_Match_LSTM.py -k test_009 (RuntimeError: masked_fill only supports boolean masks, but got dtype Byte)
* [x] pytest ./generated/test_nlp_uoregon_trankit.py -k test_021 (LoweringException: AssertionError: target: aten.cat.default) (#98517) @yanboliang 
* [x] pytest ./generated/test_open_mmlab_mmclassification.py -k test_006 (LoweringException: RuntimeError: Tensor must have a last dimension with stride 1. target: aten.view_as_complex.default)
* [ ] pytest ./generated/test_HKUST_KnowComp_MnemonicReader.py -k test_003 (NotImplementedError: could not find kernel for aten._cudnn_rnn_flatten_weight.default at dispatch key DispatchKey.Meta)
* [x] pytest ./generated/test_DKuan_MADDPG_torch.py -k test_002 (RuntimeError: backwards not supported on prim)
* [x] https://github.com/pytorch/pytorch/pull/99671 (@yanboliang)
* [ ] pytest ./generated/test_adapter_hub_adapter_transformers.py -k test_115 (https://github.com/pytorch/pytorch/pull/100115) @bdhirsh (fixed once the PR is in)
* [x] pytest ./generated/test_yizhou_wang_RODNet.py -k test_000 (https://github.com/pytorch/pytorch/pull/102664) @williamwen42 
* [x] pytest ./generated/test_shinianzhihou_ChangeDetection.py -k test_027 (AssertionError: Unexpected fake buffer _tensor_constant0 Enable TORCH_FAKE_TENSOR_DEBUG=1 to get creation stack traces on fake tensors.) (repro reported to https://github.com/pytorch/pytorch/issues/102989) @williamwen42 
* [x] pytest ./generated/test_clovaai_lffont.py -k test_008 (triton codegen error) (https://github.com/pytorch/pytorch/issues/103481, fixed by https://github.com/pytorch/pytorch/pull/103527) @williamwen42 
* [ ] pytest ./generated/test_adriansahlman_stylegan2_pytorch.py -k test_000 (TypeError: unsupported operand type(s) for *: 'NoneType' and 'Tensor')
* [x] pytest ./generated/test_alibaba_EasyCV.py -k test_054 (Please check that Nodes in the graph are topologically ordered) (https://github.com/pytorch/pytorch/pull/103794) @yanboliang 
* [ ] pytest ./generated/test_adriansahlman_stylegan2_pytorch.py -k test_000

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by anijain2305** [comment]
@yanboliang Seems like almost all are fixed. Maybe look at the remaining ones and close the taks if not needed.
