### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'ones_like'

### ISSUE THREAD

**Issue by chivee** [pytorch/pytorch#3102]
Enviroment:
Python 3.5.4 :: Anaconda custom (64-bit)
pytorch                   0.2.1           py35h24644ff_0.2.1cu80    peterjc123  

couldn't find ones_like API.

**Comment by fmassa** [comment]
The `ones_like` function has been recently introduced in https://github.com/pytorch/pytorch/pull/2489 , and I believe your installation is not recent enough to have it.

**Comment by chivee** [comment]
@fmassa , thanks, I'll using `ones` instead.
