### ISSUE TITLE
'torch.cuda.LongTensor' object has no attribute 'neg'

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#2354]
This code used to work on the previous version of pytorch, but does not work on the 0.2:

```python
import torch
x = torch.LongTensor(10).random_(10)
x = torch.autograd.Variable(x)
y = 1 - x
```

It raises the following error:
`AttributeError: 'torch.cuda.LongTensor' object has no attribute 'neg'`

It works if `x` is a tensor and not a variable.

**Comment by gchanan** [comment]
looks like the same as https://github.com/pytorch/pytorch/issues/1894, let's track it there.

**Comment by gchanan** [comment]
reopening this because as noted by @glample this is still an issue after https://github.com/pytorch/pytorch/pull/2357.

**Comment by apaszke** [comment]
This has been fixed.
