### PR TITLE
Filter out more expected errors from sccache log

### PR DESCRIPTION
**Pull request by samestep**
This PR extends `.jenkins/pytorch/print_sccache_log.py` to filter out a distracting "error" message that @walterddr came across while debugging failures in #55176:

```
=================== sccache compilation log ===================
ERROR 2021-04-05T15:44:18Z: sccache::server: Compilation failed: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "/var/lib/jenkins/.cache/torch_extensions/test_compilation_error_formatting/main.cpp: In function ‘int main()’:\n/var/lib/jenkins/.cache/torch_extensions/test_compilation_error_formatting/main.cpp:2:23: error: expected ‘;’ before ‘}’ token\n int main() { return 0 }\n                       ^\n" }
```

**Test plan:**

TODO (reviewers: is there an easy way to test this?)

### CODE REVIEW

**Review by driazati — APPROVED** [review]
Seems like any time sccache appears in the logs it's basically useless to devs (especially when Dr. CI picks it up), should we skip outputting its logs altogether (or somehow shove them somewhere where you have to go looking for them to get it)?

File: .jenkins/pytorch/print_sccache_log.py [hunk 1]
```diff
@@ -6,7 +6,12 @@
     lines = f.readlines()
 
 for line in lines:
-    # Ignore errors from CPU instruction set or symbol existing testing
-    keywords = ['src.c', 'CheckSymbolExists.c']
+    # Ignore errors from CPU instruction set, symbol existing testing,
+    # or compilation error formatting
+    keywords = [
```
Comment (walterddr) [inline .jenkins/pytorch/print_sccache_log.py:11]: nit:
```suggestion
    ignored_keywords = [
```

**Review by walterddr — APPROVED** [review]
looks good. 

RE: Test plan: since we only added one string to the list, it should be fine

**Comment by walterddr** [comment]
> Seems like any time sccache appears in the logs it's basically useless to devs (especially when Dr. CI picks it up), should we skip outputting its logs altogether (or somehow shove them somewhere where you have to go looking for them to get it)?

It is useful to debug whether there's any issue regarding build time regression. no necessarily for a failure though

File: .jenkins/pytorch/print_sccache_log.py [hunk 2]
```diff
@@ -6,7 +6,12 @@
...
+        'src.c',
+        'CheckSymbolExists.c',
+        'test_compilation_error_formatting',
+    ]
     if all([keyword not in line for keyword in keywords]):
```
Comment (samestep) [inline .jenkins/pytorch/print_sccache_log.py:16]:
```suggestion
    if all([keyword not in line for keyword in ignored_keywords]):
```

Comment (walterddr) [reply .jenkins/pytorch/print_sccache_log.py]: why are you suggesting in your own PR? :-P

Comment (samestep) [reply .jenkins/pytorch/print_sccache_log.py]: > why are you suggesting in your own PR? :-P

@walterddr because your suggestion was insufficient to rename the variable, so I added a second suggestion to rename it in its usage so that I could use GitHub's "commit batch" feature to make the commit without having to go to the trouble of switching branches locally
