### PR TITLE
Remove javasphinx extension

### PR DESCRIPTION
**Pull request by jlin27**
See PR [31581](https://github.com/pytorch/pytorch/pull/31581) for more details.

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 3a869240:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=3a869240903303635fdbdb454a168646e59895a7).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4169926) pytorch_ios_11_2_1_x86_64_build (1/1)
**Step:** "Run Simulator Tests" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=81962281) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=81962281))
<details>
<summary>
<code>ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/Users/distiller/anaconda/lib/python3.7/site-packages/PIL/__init__.py)</code>
</summary>

```
  File "/Users/distiller/anaconda/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 9, in <module> 
    from .fakedata import FakeData 
  File "/Users/distiller/anaconda/lib/python3.7/site-packages/torchvision/datasets/fakedata.py", line 3, in <module> 
    from .. import transforms 
  File "/Users/distiller/anaconda/lib/python3.7/site-packages/torchvision/transforms/__init__.py", line 1, in <module> 
    from .transforms import * 
  File "/Users/distiller/anaconda/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 17, in <module> 
    from . import functional as F 
  File "/Users/distiller/anaconda/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 5, in <module> 
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION 
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/Users/distiller/anaconda/lib/python3.7/site-packages/PIL/__init__.py) 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by zou3519** [comment]
I think we need to revert this; it broke pytorch_linux_xenial_cuda9_cudnn7_py3_build on the v1.4.0 branch. I am looking into what the best way to do a revert here is.

**Comment by zou3519** [comment]
Reverted at https://github.com/pytorch/pytorch/pull/32059
