### ISSUE TITLE
Win build failure: CUDA 10.2/cuDNN 7.6.5 and CUDA 10.1/cuDNN 7.6.4

### ISSUE THREAD

**Issue by mstfbl** [pytorch/pytorch#53563]
## 🐛 Bug

Building on CUDA 10.2/cuDNN 7.6.5 and CUDA 10.1/cuDNN 7.6.4 results in the following build failure.

This is the specific failure I'm getting:
```
FAILED: bin/caffe2_nvrtc.dll lib/caffe2_nvrtc.lib 
2021-03-08T22:14:46.6529249Z cmd.exe /C "cd . && C:\Miniconda\envs\windows_2019_py_38\Library\bin\cmake.exe -E vs_link_dll --intdir=caffe2\CMakeFiles\caffe2_nvrtc.dir --rc="C:\PROGRA~2\Windows Kits\10\bin\10.0.18362.0\x64\rc.exe" --mt="C:\PROGRA~2\Windows Kits\10\bin\10.0.18362.0\x64\mt.exe" --manifests  -- "C:\PROGRA~2\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\link.exe" /nologo caffe2\CMakeFiles\caffe2_nvrtc.dir\__\aten\src\ATen\cuda\nvrtc_stub\ATenNVRTC.cpp.obj  /out:bin\caffe2_nvrtc.dll /implib:lib\caffe2_nvrtc.lib /pdb:bin\caffe2_nvrtc.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /INCREMENTAL:NO /debug  "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\cuda.lib"  "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\nvrtc.lib"  -DELAYLOAD:nvcuda.dll  delayimp.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
2021-03-08T22:14:46.6548551Z LINK: command "C:\PROGRA~2\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\link.exe /nologo caffe2\CMakeFiles\caffe2_nvrtc.dir\__\aten\src\ATen\cuda\nvrtc_stub\ATenNVRTC.cpp.obj /out:bin\caffe2_nvrtc.dll /implib:lib\caffe2_nvrtc.lib /pdb:bin\caffe2_nvrtc.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /INCREMENTAL:NO /debug C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\cuda.lib C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\nvrtc.lib -DELAYLOAD:nvcuda.dll delayimp.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:bin\caffe2_nvrtc.dll.manifest" failed (exit code 1120) with the following output:
2021-03-08T22:14:46.6710945Z    Creating library lib\caffe2_nvrtc.lib and object lib\caffe2_nvrtc.exp
2021-03-08T22:14:46.6742833Z ATenNVRTC.cpp.obj : error LNK2019: unresolved external symbol nvrtcGetCUBINSize referenced in function load_nvrtc
2021-03-08T22:14:46.6745221Z ATenNVRTC.cpp.obj : error LNK2019: unresolved external symbol nvrtcGetCUBIN referenced in function load_nvrtc
```

## To Reproduce

1. Build on CUDA 10.2/cuDNN 7.6.5 or CUDA 10.1/cuDNN 7.6.4

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): Latest
 - OS (e.g., Linux): Windows Server 2019
 - How you installed PyTorch (`conda`, `pip`, source): From source `python setup.py install`
 - Build command you used (if compiling from source): `python setup.py install`
 - Python version: Py 3.8/3.7
 - CUDA/cuDNN version: CUDA 10.2/cuDNN 7.6.5 and CUDA 10.1/cuDNN 7.6.4
 - Any other relevant information:

## Additional context

Attached is full build output.
[full_output.txt](https://github.com/pytorch/pytorch/files/6104718/full_output.txt)
@seemethere 

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by skyline75489** [comment]
A little search leads me to this line 

https://github.com/pytorch/pytorch/blob/0d04e51233d66d7b15bba2b2cc257cf57e34f90c/aten/src/ATen/cuda/nvrtc_stub/ATenNVRTC.h#L57-L62

Clearly this is for CUDA > 11.1. For some reason, in your environment, the detection of CUDA_VERSION is wrong. I found the following line in your log:

```text
Found CUB: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/include  
```

Does this mean you have multiple CUDA installed in the environment? This *could* be the reason of the failure.

**Comment by mstfbl** [comment]
Hi @skyline75489 , that is correct, I have CUDA 11.2, 10.2 and 10.1 installed, and am working on getting builds working for these CUDA versions, given the correct environment variables. Thank you for pointing out the "Found CUB" line, I suppose I am not yet setting an env var correctly. I wonder which env var is leading to CUDA 11.2 leaking into this CUDA 10.1 build.

**Comment by mstfbl** [comment]
Update: I have implemented a workaround for this error [here](https://github.com/pytorch/pytorch/blob/dd2a6cf36818ec7573a285e8f61a01a002f0ec02/.azure_pipelines/job_templates/prepare-build-template.yml#L52-L61). I have CUDA/cuDNN 11.2/8.1.0, 10.2/7.6.5 and 10.1/7.6.4 installed locally. When not building with CUDA 11.2/cuDNN 8.1.0, I remove 11.2's CUB located at `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include\cub`. When building with CUDA 1.2/cuDNN 8.1.0, I make sure that 11.2's CUB does exist at `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include\cub`.

**Comment by kit1980** [comment]
Closing as these versions are obsolete now.
