### PR TITLE
test irange in util

### PR DESCRIPTION
**Pull request by frank-dong-ms-zz**
Test below failure from PR #53951: 

C:/Users/circleci/project/aten/src\ATen/Utils.h(55): error: no instance of overloaded function "c10::irange" matches the argument list
            argument types are: (size_t)

### CODE REVIEW

**Comment by frank-dong-ms** [comment]
Close this one, finished testing.
