### PR TITLE
[inductor][FlexGEMM] Fix reduction plan test and runtime routing

### PR DESCRIPTION
**Pull request by warrendeng**
## Summary
We observed two `test_flex_gemm` failures while updating the Triton pin in https://github.com/pytorch/pytorch/pull/191697.

The first failure was caused by the test passing `"max"` as `reduction_node` instead of `reduction_type`. Use the explicit `reduction_type="max"` keyword. The B200 test job stops after the first consistent failure, so this prevented the remaining tests in the file from running.

Once fixed, the B200 suite reached an existing stable logsumexp test and failed with `AttributeError: 'tuple' object has no attribute 'shape'`. Stable logsumexp returns `(main, reduced_aux)`, but its `reduction_plan` is `None` because it is not a single reduction. Lowering therefore failed to tell QuACK about `reduced_aux`, and QuACK treated the tuple as a tensor.

Use `outputs.local_reduce` to route the reduced output instead.

## Test Plan

- `lintrunner --take PYFMT test/inductor/test_flex_gemm.py torch/_inductor/kernel/flex_gemm/lowering.py`
- `python -m py_compile test/inductor/test_flex_gemm.py torch/_inductor/kernel/flex_gemm/lowering.py`
- B200: all four chained grouped-expression tests
- B200: full `test/inductor/test_flex_gemm.py` (321 tests passed)

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @kadeng @muchulee8 @amjames @chauhang @aakhundov @coconutruben @jataylo

### CODE REVIEW

**Review by atalman — APPROVED** [review]

**Review by drisspg — APPROVED** [review]
Thanks for fixing

**Review by mlazos — APPROVED** [review]

**Comment by warrendeng** [comment]
changes landed in https://github.com/pytorch/pytorch/pull/190158, closing
