### ISSUE TITLE
Compilation failure, pytorch 1.2, CUDA 10.1, OS X

### ISSUE THREAD

**Issue by elbamos** [pytorch/pytorch#26945]
## 🐛 Bug

I get compilation failures, starting with ONNX. The errors appear to relate to protobuf headers.

The errors began when I upgraded XCode to 10.1, which seems to be required for CUDA 10.1. 
 
The errors did not occur with XCode 10.0 and CUDA 10. (However the resulting executable was unable to successfully perform any CUDA operations.)

## To Reproduce

Follow the build instructions per the github page, followed by `MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py build`

The first errors are:

```
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:17:2: error: This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:18:2: error: incompatible with your Protocol Buffer headers.  Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:19:2: error: regenerate this file with a newer version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:310:68: error: non-virtual member function marked 'final' hides virtual member function
      bool deterministic, ::google::protobuf::uint8* target) const final;
                                                                   ^
/usr/local/include/google/protobuf/message_lite.h:486:18: note: hidden overloaded virtual function 'google::protobuf::MessageLite::InternalSerializeWithCachedSizesToArray' declared here: different number of parameters (1 vs 2)
  virtual uint8* InternalSerializeWithCachedSizesToArray(uint8* target) const;
                 ^
In file included from ../third_party/onnx/onnx/common/ir_pb_converter.cc:4:
In file included from ../third_party/onnx/onnx/common/ir_pb_converter.h:6:
In file included from ../third_party/onnx/onnx/common/ir.h:23:
In file included from ../third_party/onnx/onnx/common/tensor.h:10:
In file included from ../third_party/onnx/onnx/onnx_pb.h:50:
In file included from third_party/onnx/onnx/onnx-ml.pb.h:2:
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:694:68: error: non-virtual member function marked 'final' hides virtual member function
      bool deterministic, ::google::protobuf::uint8* target) const final;
```

## Environment

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.1.168
GPU models and configuration: Could not collect
Nvidia driver version: 1.1.0
cuDNN version: Probably one of the following:
/usr/local/cuda/lib/libcudnn.7.dylib
/usr/local/cuda/lib/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy==1.16.4
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      233
[conda] mkl-include               2019.4                      233
[conda] mkl-service               2.3.0            py37hfbe908c_0
[conda] mkl_fft                   1.0.14           py37h5e564d8_0
[conda] mkl_random                1.1.0            py37ha771720_0

clang -v
Apple LLVM version 10.0.0 (clang-1000.11.45.5)

## Additional context

cc @malfet @seemethere @ngimel

**Comment by soumith** [comment]
sounds more like you're a `git clean xfd` away from getting back to normal compilation

**Comment by elbamos** [comment]
Yup you were right

**Comment by elbamos** [comment]
Sorry, I spoke to soon. 

I get the same problem with 1.2.0 release and master, after `git clean -xfd`. I've tried XCode from 9.4 to 10.1, and CUDA from 10.0 to 10.1 update 1.

Here's a more fulsome error report:

```
[422/3314] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/__/__/caffe2/onnx/torch_ops/defs.cc.o
FAILED: third_party/onnx/CMakeFiles/onnx.dir/__/__/caffe2/onnx/torch_ops/defs.cc.o
/Volumes/home500/Applications/Xcode9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -I../cmake/../third_party/benchmark/include -Icaffe2/contrib/aten -I../third_party/onnx -Ithird_party/onnx -isystem ../cmake/../third_party/googletest/googlemock/include -isystem ../cmake/../third_party/googletest/googletest/include -isystem ../third_party/protobuf/src -isystem /Volumes/home500/anaconda/envs/pytorchmaster/include -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../third_party -isystem ../cmake/../third_party/eigen -isystem /Volumes/home500/anaconda/envs/pytorchmaster/include/python3.6m -isystem /Volumes/home500/anaconda/envs/pytorchmaster/lib/python3.6/site-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -isystem /opt/rocm/hip/include -isystem /include -isystem ../cmake/../third_party/cub -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -Xpreprocessor -fopenmp -I/usr/local/include -Wnon-virtual-dtor -O3 -DNDEBUG -isysroot /Volumes/home500/Applications/Xcode9.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.9 -fPIC   -std=gnu++11 -MD -MT third_party/onnx/CMakeFiles/onnx.dir/__/__/caffe2/onnx/torch_ops/defs.cc.o -MF third_party/onnx/CMakeFiles/onnx.dir/__/__/caffe2/onnx/torch_ops/defs.cc.o.d -o third_party/onnx/CMakeFiles/onnx.dir/__/__/caffe2/onnx/torch_ops/defs.cc.o -c ../caffe2/onnx/torch_ops/defs.cc
In file included from ../caffe2/onnx/torch_ops/defs.cc:4:
In file included from ../caffe2/onnx/torch_ops/./schema.h:4:
In file included from ../third_party/onnx/onnx/defs/schema.h:21:
In file included from ../third_party/onnx/onnx/defs/data_type_utils.h:11:
In file included from ../third_party/onnx/onnx/onnx_pb.h:50:
In file included from third_party/onnx/onnx/onnx-ml.pb.h:2:
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:17:2: error: This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:18:2: error: incompatible with your Protocol Buffer headers.  Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:19:2: error: regenerate this file with a newer version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:310:68: error: non-virtual member function marked 'final' hides virtual member function
      bool deterministic, ::google::protobuf::uint8* target) const final;
                                                                   ^
```

That is from a clean pull, and `git clean -xfd` doesn't help. 

I tried to identify the problematic commit. I was able to trace it to sometime between bd88fd0 (July 15), which works, and 1c57445 (July 22), which produces the error.

**Comment by elbamos** [comment]
I traced it - its definitely caused by a2b3403, PR23012.  When I revert that one-line commit, the build completes properly.

**Comment by garymm** [comment]
@elbamos is this still an issue?

**Comment by elbamos** [comment]
I this this issue has sunset. The last macs that supported Nvidia gpus are, I believe, no longer supported by apple, and Nvidia isn’t supporting more recent versions of OS X. I think I was one of the last people to try pytorch with cuda on OS X, and even I’ve given up and moved onto Linux.
