### PR TITLE
Remove unbalanced `pragma diagnostic pop`

### PR DESCRIPTION
**Pull request by malfet**
Detected by internal CI, we should have it in OSS as well:
```
aten/src/ATen/native/cpu/Loops.h:398:24: error: pragma diagnostic pop could not pop, no matching push [-Werror,-Wunknown-pragmas]
#pragma GCC diagnostic pop
```
Regression introduced by https://github.com/pytorch/pytorch/pull/82883

### CODE REVIEW

**Review by albanD — APPROVED** [review]
lint needs fixing. SGTM otherwise.

**Review by seemethere — APPROVED** [review]
