### ISSUE TITLE
[setup] Incosistent CUDA detection between THPP and other libs

### ISSUE THREAD

**Issue by CDLuminate** [pytorch/pytorch#638]
I failed to compile pytorch in CPU-only mode with d4c9a3782bfe786b00851b05cc550aa32915deb9 .

```
python3 setup.py build
...

[ 57%] Building CXX object CMakeFiles/THPP.dir/storages/THCStorage.cpp.o
In file included from /home/lumin/git/pytorch/torch/lib/THPP/storages/THCStorage.cpp:1:0:
/home/lumin/git/pytorch/torch/lib/THPP/storages/THCStorage.hpp:3:21: fatal error: THC/THC.h: No such file or directory
 #include <THC/THC.h>
                     ^
compilation terminated.
```

**Comment by apaszke** [comment]
Do you have CUDA installed? Can you paste what CMake printed when configuring THPP?

**Comment by CDLuminate** [comment]
This is the complete log

```
make[1]: Leaving directory '/home/lumin/git/pytorch/torch/lib/build/THNN'
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- TH_LIBRARIES: /home/lumin/git/pytorch/torch/lib/tmp_install/lib/libTH.so.1
-- Found CUDA: /usr (found suitable version "8.0", minimum required is "5.5") 
-- THC_LIBRARIES: /home/lumin/git/pytorch/torch/lib/tmp_install/lib/libTHC.so.1
-- Excluding /home/lumin/git/pytorch/torch/lib/THPP/storages/generic/THCStorage.cpp from the build
-- Excluding /home/lumin/git/pytorch/torch/lib/THPP/storages/generic/THStorage.cpp from the build
-- Excluding /home/lumin/git/pytorch/torch/lib/THPP/tensors/generic/THCTensor.cpp from the build
-- Excluding /home/lumin/git/pytorch/torch/lib/THPP/tensors/generic/THTensor.cpp from the build
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    THCUNN_SO_VERSION
    THC_SO_VERSION
    THNN_SO_VERSION
    THS_LIBRARIES
    TH_INCLUDE_PATH
    TH_LIB_PATH
    TH_SO_VERSION


-- Build files have been written to: /home/lumin/git/pytorch/torch/lib/build/THPP
make[1]: Entering directory '/home/lumin/git/pytorch/torch/lib/build/THPP'
make[2]: Entering directory '/home/lumin/git/pytorch/torch/lib/build/THPP'
make[3]: Entering directory '/home/lumin/git/pytorch/torch/lib/build/THPP'
Scanning dependencies of target THPP
make[3]: Leaving directory '/home/lumin/git/pytorch/torch/lib/build/THPP'
make[3]: Entering directory '/home/lumin/git/pytorch/torch/lib/build/THPP'
[ 14%] Building CXX object CMakeFiles/THPP.dir/storages/THCStorage.cpp.o
[ 28%] Building CXX object CMakeFiles/THPP.dir/storages/THStorage.cpp.o
[ 42%] Building CXX object CMakeFiles/THPP.dir/Traits.cpp.o
[ 57%] Building CXX object CMakeFiles/THPP.dir/TraitsCuda.cpp.o
In file included from /home/lumin/git/pytorch/torch/lib/THPP/storages/THCStorage.cpp:1:0:
/home/lumin/git/pytorch/torch/lib/THPP/storages/THCStorage.hpp:3:21: fatal error: THC/THC.h: No such file or directory
 #include <THC/THC.h>
                     ^
compilation terminated.
CMakeFiles/THPP.dir/build.make:110: recipe for target 'CMakeFiles/THPP.dir/storages/THCStorage.cpp.o' failed
make[3]: *** [CMakeFiles/THPP.dir/storages/THCStorage.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /home/lumin/git/pytorch/torch/lib/THPP/TraitsCuda.cpp:1:0:
/home/lumin/git/pytorch/torch/lib/THPP/TraitsCuda.hpp:4:25: fatal error: THC/THCHalf.h: No such file or directory
 #include <THC/THCHalf.h>
                         ^
compilation terminated.
CMakeFiles/THPP.dir/build.make:86: recipe for target 'CMakeFiles/THPP.dir/TraitsCuda.cpp.o' failed
make[3]: *** [CMakeFiles/THPP.dir/TraitsCuda.cpp.o] Error 1
make[3]: Leaving directory '/home/lumin/git/pytorch/torch/lib/build/THPP'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/THPP.dir/all' failed
make[2]: *** [CMakeFiles/THPP.dir/all] Error 2
make[2]: Leaving directory '/home/lumin/git/pytorch/torch/lib/build/THPP'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/lumin/git/pytorch/torch/lib/build/THPP'
dh_auto_build: python setup.py build --force returned exit code 1
```

**Comment by CDLuminate** [comment]
My cuda instance is from Debian archive `nvidia-cuda-toolkit 8.0.44-3`, compiling on Debian Sid.

**Comment by apaszke** [comment]
Was THC built before THPP? Does `torch/lib/tmp_install/include/THC` exist?

**Comment by CDLuminate** [comment]
1. TH 2. THS 3. THNN 4. THPP (failure)

**Comment by apaszke** [comment]
Ok, why are you saying it's a CPU-only build? Did you pass `NO_CUDA=1` to setup.py?

**Comment by CDLuminate** [comment]
I didn't look into the compiling detail. From torch/lib/build_all.sh I found:

```
 67 mkdir -p tmp_install                                                            
 68 build TH                                                                        
 69 build THS                                                                       
 70 build THNN                                                                      
 71                                                                                 
 72 if [[ "$1" == "--with-cuda" ]]; then                                            
 73     build THC                                                                   
 74     build THCS                                                                  
 75     build THCUNN                                                                
 76     if [[ $(uname) != 'Darwin' ]]; then                                         
 77         if [[ `ldconfig -p | grep libnccl` == '' ]]; then                       
 78           build_nccl                                                            
 79         fi                                                                      
 80     fi                                                                          
 81 fi                                                                              
 82                                                                                 
 83 build THPP                                                                      
 84 CPP_FLAGS=" -std=c++11 "                                                        
 85 build libshm                 
```

THC is not compiled (`$ python3 setup.py build`), so I think the script is compiling in CPU-only mode.
I didn't pass the `NO_CUDA=1` argument, I'm trying it now.

**Comment by apaszke** [comment]
No, no. It's not going to help. I think it's just that `setup.py` doesn't detect CUDA on your machine, but THPP does 😕 Can you try giving it `CUDA_HOME=<where CUDA is installed>` instead?

**Comment by CDLuminate** [comment]
I have installed CUDA package but my laptop ships no NVIDIA card. Well how can I disable all the CUDA stuff?

And indeed the CUDA detection part is buggy ...

**Comment by apaszke** [comment]
It doesn't look for a GPU, it only checks if it's installed somewhere. We'll have to figure out a way of forcing CUDA detection in THPP to be off when `--with-cuda` isn't specified.

Why is it buggy? You probably have it in a non standard directory. Where is it installed? Did you just copy the libs and includes to /usr?

**Comment by CDLuminate** [comment]
Debian's CUDA package installs all the stuff in `/usr/` instead of `/usr/local/` or somewhere else.

**Comment by apaszke** [comment]
I see. I'll add that to the search path.

**Comment by CDLuminate** [comment]
I hacked THPP's CMake file, and passed the build. The result shows the root of problem is the incosistent CUDA detection between THPP and other libs.

**Comment by apaszke** [comment]
Yes I'm aware of that. I'll fix it later today

**Comment by apaszke** [comment]
Thanks for help!

**Comment by apaszke** [comment]
Fixed in #661.
