### PR TITLE
[ROCm] Bump fbgemm to 1.7.0

### PR DESCRIPTION
**Pull request by zjliu-amd**
Bump fbgemm to 1.7.0 to remove dependency on rocm-smi, needed by https://github.com/pytorch/pytorch/pull/190014

This PR also adds fbgemm as an additional package to build in `inductor-periodic` workflow for test purpose, as fbgemm currently is not consumed anywhere in the CI by ROCm jobs.

It also adds a workaround to build without sccache caching to address an FBGEMM build issue on ROCm when using sccache; and only for gfx950, purely to optimize fbgemm build time in CI.

Bumping `third_party/fbgemm` to 1.7.0 pulls in [FBGEMM #5635](https://github.com/pytorch/FBGEMM/pull/5635) (commit `faef9bf61`), which removed the `&& defined(FBGEMM_FBCODE)` guard around the AVX512-BF16 dequant kernel in `src/QuantUtilsAvx512.cc` (https://github.com/pytorch/FBGEMM/blob/bf6dce360a4fe133bc779e2fd036277678509f95/src/QuantUtilsAvx512.cc#L394). That kernel is now compiled unconditionally on x86, so the `fbgemm_avx512` target requires `-mavx512bf16` to build.

FBGEMM #5635 added the flag to its *own* build (`BUILD.bazel`, `cmake/modules/FindAVX.cmake:111`), but that doesn't reach us: PyTorch builds FBGEMM via `add_subdirectory`, and PyTorch's own `find_package(AVX)` (`CMakeLists.txt:913`) runs first and caches `CXX_AVX512_FLAGS` without bf16. FBGEMM's `FindAVX` then short-circuits on `IF(NOT CXX_AVX512_FOUND)`, so its flag never applies. The `fbgemm_avx512` object compiles without `-mavx512bf16` and the CPU build fails at `QuantUtilsAvx512.cc.o`. This adds the flag to the cached AVX512 flags that the FBGEMM target inherits.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @jataylo @hongxiayang @naromero77amd @pragupta @jerrymannil @xinyazhang

### CODE REVIEW

File: .ci/pytorch/common_utils.sh [hunk 1]
```diff
@@ -216,7 +216,20 @@ function install_fbgemm() {
...
+    # (has_cpu_support=False, has_gpu_support=False). Under CI's S3-backed sccache
+    # (classic/preprocessor-off mode, whose key ignores both the input path and -o)
+    # these collapse to one cached object that is copied to the other outputs, so every
+    # copy carries the same __hip_cuid symbol and the HIP link fails with
+    # "multiple definition of __hip_cuid_...". Force every compile in this build to
+    # recache so each identical source is compiled independently; clang folds -o into
+    # the CUID hash, giving each object a distinct __hip_cuid. Inline (not exported) and
+    # scoped to the ROCm build so it does not affect the PyTorch build (already built).
+    if [[ "${build_variant}" == "rocm" ]]; then
+      SCCACHE_RECACHE=1 python setup.py bdist_wheel --build-target=default --build-variant="${build_variant}"
```
Comment (jithunnair-amd) [inline .ci/pytorch/common_utils.sh]: @q10 Can you please take a look at this change to see if this is acceptable?

Comment (jithunnair-amd) [reply .ci/pytorch/common_utils.sh]: I also created PRs https://github.com/pytorch/FBGEMM/pull/6043 and https://github.com/pytorch/FBGEMM/pull/6044 to address this issue from the FBGEMM side, so we don't need this workaround. But even if we go with one of those two fixes, we will still need this workaround to proceed currently, until the next fbgemm submodule bump picks them up.

**Review by jithunnair-amd — APPROVED** [review]
LGTM. The sccache workaround is needed until we fix this from the FBGEMM side, for which I have created PRs https://github.com/pytorch/FBGEMM/pull/6043 and https://github.com/pytorch/FBGEMM/pull/6044.

File: .ci/pytorch/common_utils.sh (hunk 1 above)
Comment (q10) [reply .ci/pytorch/common_utils.sh]: LGTM

**Review by q10 — APPROVED** [review]

**Review by atalman — APPROVED** [review]
lgtm
