### PR TITLE
[dynamo] Split TupleIteratorVariable off ListIteratorVariable to match CPython

### PR DESCRIPTION
**Pull request by indrajeetapache**
## Summary

In CPython, `tuple_iterator` is not a subclass of `list_iterator`:

```
>>> issubclass(type(iter(())), type(iter([])))
False
```

`dir()` on both is the same (`__iter__`, `__next__`, `__length_hint__`), so there is no extra method table to model. Dynamo still had `TupleIteratorVariable(ListIteratorVariable)`, which made every `isinstance(x, ListIteratorVariable)` check match tuple iterators too.

#193261 has landed and already introduced `BaseListIteratorVariable` for the deque split. This PR rebases on that and reparents `TupleIteratorVariable` onto the same base so list and tuple iterators are siblings.

Review feedback from #193727 (`@guilhermeleobas`) is incorporated:

- Do **not** export `BaseListIteratorVariable` (no CPython counterpart). It stays internal to `lists.py`.
- Be explicit at call sites: `ListIteratorVariable` and `TupleIteratorVariable`, not the shared base.
- `GET_YIELD_FROM_ITER` checks `ListIteratorVariable`, `TupleIteratorVariable`, and `DequeIteratorVariable`. Deque has to stay listed after #193261, because deque iterators are no longer a `ListIteratorVariable` subclass.

Also in this PR:

- `python_type()` / `as_python_constant()` on `TupleIteratorVariable` return a real `tuple_iterator`.
- `TupleIteratorVariable` is added to the unpack fast path.
- Regression tests cover the hierarchy, `yield from`, and `type(iter((1, 2, 3)))`.

Part of #192874

## Test plan

```
python test/dynamo/test_iterators.py TestIterators.test_tuple_iterator_not_a_list_iterator
python test/dynamo/test_iterators.py TestIterators.test_yield_from_tuple_iterator
python test/dynamo/test_iterators.py TestIterators.test_tuple_iterator_python_type
python test/dynamo/test_iterators.py
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @kadeng @chauhang @amjames @jataylo @azahed98 @guilhermeleobas @williamwen42 @jansel @Skylion007 @albanD

### CODE REVIEW

**Comment by indrajeetapache** [comment]
@codex Review

**Comment by jansel** [comment]
@claude review these changes

**Comment by indrajeetapache** [comment]
@codex Review

**Comment by indrajeetapache** [comment]
Addressed the `python_type() / as_python_constant()` mismatch for `TupleIteratorVariable`, and added a traced `type(iter((1, 2, 3)))` test. Left the other review notes as-is.

**Comment by indrajeetapache** [comment]
I noticed the independently opened overlapping PR #193727.
This PR also includes the follow-up fix for TupleIteratorVariable.as_python_constant() to return a tuple iterator consistently with python_type(), along with a traced regression test for type(iter((1, 2, 3))).

Happy to rebase, adjust the scope, or close this in favor of #193727 if maintainers prefer that direction.

**Comment by indrajeetapache** [comment]
@guilhermeleobas @williamwen42 @jansel @Skylion007 @albanD

Rebased this PR onto main now that #193261 has landed, and incorporated the review notes from #193727.

**What I changed in this update**

1. Rebased on #193261. `BaseListIteratorVariable` is already on main from the deque split, so this PR is now just the tuple re-parent plus call-site/test updates.
2. Do not export `BaseListIteratorVariable`. It has no CPython counterpart, so it stays an internal type in `lists.py`.
3. Be explicit at call sites instead of `isinstance(..., BaseListIteratorVariable)`:
   - `side_effects.py` matches `ListIteratorVariable` and `TupleIteratorVariable`
   - `GET_YIELD_FROM_ITER` matches `ListIteratorVariable`, `TupleIteratorVariable`, and `DequeIteratorVariable` (deque has to stay listed after #193261)
4. `TupleIteratorVariable.python_type()` / `as_python_constant()` now return a real `tuple_iterator`, with a traced `type(iter((1, 2, 3)))` regression test.

Happy to take another look whenever you have cycles.

**Comment by guilhermeleobas** [comment]
@indrajeetapache can you address the test failures?

**Comment by indrajeetapache** [comment]
> @indrajeetapache can you address the test failures?

@guilhermeleobas  Thanks for the ping — the CI failures are addressed in 93427d2.

Root cause: the 117 failures were all the same import-time error, not separate test bugs. In side_effects.py I had introduced a module-level tuple:

```
_LIST_OR_TUPLE_ITERATOR = (
    variables.ListIteratorVariable,
    variables.TupleIteratorVariable,
)
```
That runs while `torch._dynamo.variables` is still initializing (`builder.py imports side_effects before ListIteratorVariable is exported`), which caused:

AttributeError: partially initialized module 'torch._dynamo.variables' has no attribute 'ListIteratorVariable'

Fix: keep explicit `ListIteratorVariable / TupleIteratorVariable` checks (per your #193727 feedback — no exported BaseListIteratorVariable), but evaluate them lazily inside the matcher/body, same pattern as other side-effect handlers.

Everything else from the earlier update is unchanged:

`TupleIteratorVariable` reparented onto `BaseListIteratorVariable`
explicit call sites in `side_effects.py, GET_YIELD_FROM_ITER`, and `_unpack_fast_types`
`python_type() / as_python_constant() + regression tests`
looks clean on my side now.

File: torch/_dynamo/symbolic_convert.py [hunk 1]
```diff
@@ -6557,8 +6550,8 @@ def YIELD_VALUE(self, inst: Instruction) -> None:
 
     def GET_YIELD_FROM_ITER(self, inst: Instruction) -> None:
         tos = self.stack[-1]
-        # tuple iterators subclass ListIteratorVariable; deque is a sibling
-        if not isinstance(tos, (ListIteratorVariable, DequeIteratorVariable)):
+        iter_vts = (ListIteratorVariable, TupleIteratorVariable, DequeIteratorVariable)
+        if not isinstance(tos, iter_vts):
```
Comment (guilhermeleobas) [inline torch/_dynamo/symbolic_convert.py:6554]: Not for this PR but I think this can be replaced by `not isinstance(tos, IteratorVariable)`.
https://github.com/python/cpython/blob/e76aa128fea8691525b482a211bef6b1c514019d/Python/bytecodes.c#L2556-L2581

**Review by guilhermeleobas — APPROVED** [review]
