### PR TITLE
Use std::min for #166021

### PR DESCRIPTION
**Pull request by clee2000**
Summary:
Attempting to forward fix failures from D85405167 (PR 
https://github.com/pytorch/pytorch/pull/166021)

This is devmates suggestion and seems to work, but idk if it's a good idea or not.  Devmate says it's getting resolved to at::min which is host only, and it doesn't happen in OSS is likely because `AT_PER_OPERATOR_HEADERS` is defined in OSS but not internally.

```
In file included from .../ATen/native/hip/Normalization.hip:11:
.../ATen/native/hip/Normalization.cuh:302:37: error: no matching function for call to 'min'
  302 |         v_[u] = input[batch][plane][min(x+u*blockDim.x, input.size(2)-1)];
      |                                     ^~~
```

Differential Revision: D85463674

### CODE REVIEW

**Review by Camyll — APPROVED** [review]

**Review by Camyll — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by Skylion007** [comment]
Not sure about ROCM, but for Nvidia I don't think ti matters with CCCL. @ngimel would know though.

**Review by eqy — APPROVED** [review]
