### PR TITLE
[Inductor][Refactor] 1/N Introduce heuristics/ module with triton_template/

### PR DESCRIPTION
**Pull request by etaf**
Stack from [ghstack](https://github.com/ezyang/ghstack/tree/0.15.0) (oldest at bottom):
* #183278
* #183277
* #183276
* __->__ #183275

## Motivation

Per the RFC (https://github.com/pytorch/pytorch/issues/178153), we are unifying triton heuristics under a single `heuristics/` module with two sub-modules: `template/` (compile-time config) and `triton_codegen/` (runtime config).

## Solution

Introduce `torch/_inductor/heuristics/` as the unified entry point:

* `heuristics/__init__.py` + `heuristics/base.py`: device dispatch extracted
  from `InductorChoices.get_config_heuristics()`; `choices.py` now delegates to
  `get_config_heuristic_for_device()`.
* `heuristics/template/`: move of the former top-level
  `template_heuristics/` package into the new hierarchy.  All internal imports,
  test imports, and `select_algorithm.py` are updated to the new paths.

No behavioral change.

## Test plan

Existing CI covers the affected code paths.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @kadeng @muchulee8 @amjames @chauhang @aakhundov @coconutruben @jataylo

Differential Revision: [D110187735](https://our.internmc.facebook.com/intern/diff/D110187735)

### CODE REVIEW

**Comment by etaf** [comment]
@claude review PR

File: torch/_inductor/heuristics/template/cutedsl.py [hunk 1]
```diff
@@ -26,7 +26,7 @@ def get_exhaustive_groupgemm_configs() -> list[CuTeGemmConfig]:
     """
     Returns the exhaustive configuration set for the Blackwell CuTeDSL Grouped GEMM kernel.
     For information regarding valid config sets, see:
-    https://github.com/NVIDIA/cutlass/blob/main/examples/python/CuTeDSL/blackwell/grouped_gemm.py
+    https://github.com/NVIDIA/cutlass/blob/main/examples/python/CuTeDSL/cute/blackwell/kernel/grouped_gemm/grouped_gemm.py
```
Comment (etaf) [inline torch/_inductor/heuristics/template/cutedsl.py:29]: The origin URL is 404 now, update it to avoid lint error.

**Comment by etaf** [comment]
@claude updated, please review again.

**Review by jansel — APPROVED** [review]

**Review by jansel — CHANGES_REQUESTED** [review]
fix merge conflicts

**Comment by etaf** [comment]
> fix merge conflicts

Thanks for the reminder, I've resolved the merge conflict.

**Comment by etaf** [comment]
Hi  @jansel:
 This PR touches a large number of files, so it conflicts with the latest main branch very easily. Would it be possible to get your approval first? I’ll land it immediately once CI finishes. Otherwise, after some time it will likely conflict again. Also, rebasing onto the latest main instead of viable/strict often introduces unrelated CI failures.

**Review by jansel — APPROVED** [review]

**Comment by georgehong** [comment]
@pytorchbot revert -m "This commit is breaking internal PR sync jobs due to the scale of files that are simultaneously changed and due to land order. It should be sufficient to rebase and reland this PR" -c ghfirst

Hi @etaf, wanted to give a heads-up that we needed to revert this stack in order to fix our PR sync jobs, but it should be okay to rebase and reland. Please let me know if there's any other info I can provide - thanks.

**Comment by izaitsevfb** [comment]
@pytorchbot revert -m "breaking internal tests" -c ghfirst

Internal diff: https://www.internalfb.com/diff/D105887562 (internal-only)

this stack breaks too many things, I believe we should revert it.


> The template_heuristics → heuristics/template rename missed several downstream import sites that weren't visible from this PR's CI, including a Meta-internal extension module that's transitively imported by heuristics/template/__init__.py. The cascade fails import for any caller that pulls in the new package — DTensor / FSDP / executorch builds all break. We also found two stale references in test/inductor/test_origami.py that the rename missed on the OSS side (separately fixed in #184662).
>  For the reland: please (a) add a thin backward-compat shim at the old torch/_inductor/template_heuristics/ path that re-exports from the new location for one release, like #183276 already does for triton_template/registry.py; (b) make heuristics/template/__init__.py lazy / not eagerly import leaf modules, so a bad leaf can't break the whole package; (c) coordinate with a Meta-internal reviewer (e.g. @jansel or anyone with codev access) to grep our tree for stale references before merge. Thanks!


see also:
• [pytorch/pytorch#184660](https://github.com/pytorch/pytorch/issues/184660) — DISABLED test_origami_fallback_when_disabled (TestOrigami). Labels: module: rocm, module: regression, module: inductor. Stack trace: AttributeError: module 'torch._inductor' has no attribute 'template_heuristics'. Cites commit 5236c71 as the cause.
• [pytorch/pytorch#184658](https://github.com/pytorch/pytorch/issues/184658) — DISABLED test_origami_module_gate_when_env_var_unset (TestOrigami). Same labels. Stack trace: ModuleNotFoundError: No module named 'torch._inductor.template_heuristics'. Failing on inductor-rocm-mi355 from 5236c71 onwards ([HUD link in the issue body](https://hud.pytorch.org/hud/pytorch/pytorch/bf6b7fb48c55069847a0887eb84b0781e0c9a838/2?per_page=50&name_filter=inductor-rocm-mi355&useRegexFilter=true&mergeEphemeralLF=true)).

**Comment by etaf** [comment]
Rebase to latest main always have unrelated "New CI failure".

**Comment by etaf** [comment]
> @pytorchbot revert -m "breaking internal tests" -c ghfirst
> 
> Internal diff: https://www.internalfb.com/diff/D105887562 (internal-only)
> 
> this stack breaks too many things, I believe we should revert it.
> 
> > The template_heuristics → heuristics/template rename missed several downstream import sites that weren't visible from this PR's CI, including a Meta-internal extension module that's transitively imported by heuristics/template/**init**.py. The cascade fails import for any caller that pulls in the new package — DTensor / FSDP / executorch builds all break. We also found two stale references in test/inductor/test_origami.py that the rename missed on the OSS side (separately fixed in #184662).
> > For the reland: please (a) add a thin backward-compat shim at the old torch/_inductor/template_heuristics/ path that re-exports from the new location for one release, like #183276 already does for triton_template/registry.py; (b) make heuristics/template/**init**.py lazy / not eagerly import leaf modules, so a bad leaf can't break the whole package; (c) coordinate with a Meta-internal reviewer (e.g. @jansel or anyone with codev access) to grep our tree for stale references before merge. Thanks!
> 
> see also: • [pytorch/pytorch#184660](https://github.com/pytorch/pytorch/issues/184660) — DISABLED test_origami_fallback_when_disabled (TestOrigami). Labels: module: rocm, module: regression, module: inductor. Stack trace: AttributeError: module 'torch._inductor' has no attribute 'template_heuristics'. Cites commit [5236c71](https://github.com/pytorch/pytorch/commit/5236c717d49986daaa72249528f8f1aa5062bedb) as the cause. • [pytorch/pytorch#184658](https://github.com/pytorch/pytorch/issues/184658) — DISABLED test_origami_module_gate_when_env_var_unset (TestOrigami). Same labels. Stack trace: ModuleNotFoundError: No module named 'torch._inductor.template_heuristics'. Failing on inductor-rocm-mi355 from [5236c71](https://github.com/pytorch/pytorch/commit/5236c717d49986daaa72249528f8f1aa5062bedb) onwards ([HUD link in the issue body](https://hud.pytorch.org/hud/pytorch/pytorch/bf6b7fb48c55069847a0887eb84b0781e0c9a838/2?per_page=50&name_filter=inductor-rocm-mi355&useRegexFilter=true&mergeEphemeralLF=true)).

Hi, @jansel I've added a thin backward-compat shim at the old `torch/_inductor/template_heuristics/` ， can I reland now?

**Comment by etaf** [comment]
Hi @jansel 

> @pytorchbot revert -m "breaking internal tests" -c ghfirst
> 
> Internal diff: https://www.internalfb.com/diff/D105887562 (internal-only)
> 
> this stack breaks too many things, I believe we should revert it.
> 
> > The template_heuristics → heuristics/template rename missed several downstream import sites that weren't visible from this PR's CI, including a Meta-internal extension module that's transitively imported by heuristics/template/**init**.py. The cascade fails import for any caller that pulls in the new package — DTensor / FSDP / executorch builds all break. We also found two stale references in test/inductor/test_origami.py that the rename missed on the OSS side (separately fixed in #184662).
> > For the reland: please (a) add a thin backward-compat shim at the old torch/_inductor/template_heuristics/ path that re-exports from the new location for one release, like #183276 already does for triton_template/registry.py; (b) make heuristics/template/**init**.py lazy / not eagerly import leaf modules, so a bad leaf can't break the whole package; (c) coordinate with a Meta-internal reviewer (e.g. @jansel or anyone with codev access) to grep our tree for stale references before merge. Thanks!
> 
> see also: • [pytorch/pytorch#184660](https://github.com/pytorch/pytorch/issues/184660) — DISABLED test_origami_fallback_when_disabled (TestOrigami). Labels: module: rocm, module: regression, module: inductor. Stack trace: AttributeError: module 'torch._inductor' has no attribute 'template_heuristics'. Cites commit [5236c71](https://github.com/pytorch/pytorch/commit/5236c717d49986daaa72249528f8f1aa5062bedb) as the cause. • [pytorch/pytorch#184658](https://github.com/pytorch/pytorch/issues/184658) — DISABLED test_origami_module_gate_when_env_var_unset (TestOrigami). Same labels. Stack trace: ModuleNotFoundError: No module named 'torch._inductor.template_heuristics'. Failing on inductor-rocm-mi355 from [5236c71](https://github.com/pytorch/pytorch/commit/5236c717d49986daaa72249528f8f1aa5062bedb) onwards ([HUD link in the issue body](https://hud.pytorch.org/hud/pytorch/pytorch/bf6b7fb48c55069847a0887eb84b0781e0c9a838/2?per_page=50&name_filter=inductor-rocm-mi355&useRegexFilter=true&mergeEphemeralLF=true)).

Hi, @jansel , would you like to do me a favor to land this? I've added the backward-compat shim.

**Comment by jansel** [comment]
@claude explain those CI failures, are they related?

**Review by jansel — CHANGES_REQUESTED** [review]
fix test failures

**Comment by jansel** [comment]
@claude explain those CI failures, are they related?

**Comment by etaf** [comment]
Hi, @jansel  does it ready to land?

**Comment by jansel** [comment]
@claude verify this is just moving stuff around and not changing any semantics.

**Review by jansel — APPROVED** [review]

**Comment by jansel** [comment]
@claude explain those CI failures, are they related?

**Review by jansel — CHANGES_REQUESTED** [review]
fix test failures

**Comment by etaf** [comment]
Hi, @jansel, I've added the label `inductor-rocm-mi355` and the failed case pass now.

**Review by jansel — APPROVED** [review]

**Comment by etaf** [comment]
Double checked those CI failures are not PR related.
@pytorchbot merge -i

**Comment by etaf** [comment]
> @pytorchmergebot revert -c ghfirst -m "Sorry, this is failing internally. Once reverted, reimport of the PR is required, and we would need to add internal only changes to land it"

Hi @atalman，Does that mean I should wait until the “internal-only changes” are completed by someone before trying to reland this?

**Comment by etaf** [comment]
Hi, @atalman anyone can hep with this "reimport of the PR is required, and we would need to add internal only changes to land it"

**Comment by atalman** [comment]
@atalman has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D110187735).

**Comment by atalman** [comment]
@atalman has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D110187735).
