### ISSUE TITLE
[feature request] Bucketization

### ISSUE THREAD

**Issue by superbobry** [pytorch/pytorch#7284]
## Issue description

Both the 0.4.0 version and the `master` version are missing a bucketization operation, i.e. an operation which given a 1-D tensor of values, and another 1-D tensor of bucket boundaries, return a new tensor where each value is substituted for the index of the corresponding bucket.

The operation seems to be [available](https://github.com/pytorch/pytorch/blob/master/caffe2/operators/one_hot_ops.cc#L90) in Caffe2, but I'm not sure if the code can be reused in PyTorch.

Alternatively, PyTorch could provide a variant of [`searchsorted`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.searchsorted.html) so that the users can easily write O(log n) bucketization.

## Code example

A trivial implementation might be something like:

```python
def bucketize(tensor, bucket_boundaries):
    result = torch.zeros_like(tensor, dtype=torch.int32)
    for boundary in bucket_boundaries:
        result += (tensor > boundary).int()
    return result
```

```python
>>> bucketize(torch.tensor([-3, 1, 2, 4]), bucket_boundaries=torch.tensor([2]))
tensor([ 0,  0,  0,  1], dtype=torch.int32)
```

N.B. the handling of bucket endpoints could be implemented differently.

## System Info

```
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.3
GCC version: Could not collect
CMake version: version 3.8.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy (1.14.2)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.1)
[conda] torch                     0.4.0                     <pip>
[conda] torchvision               0.2.1                     <pip>
```

cc @ezyang @gchanan @zou3519

**Comment by SsnL** [comment]
Is this for discretization?

**Comment by superbobry** [comment]
Yes, discretization would be another name, I was using TensorFlow terminology. The NumPy function is called [`digitize`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.digitize.html).

**Comment by guolinke** [comment]
vote for this.
tf has this op called `bucketize` .

**Comment by aliutkus** [comment]
Since I needed this kind of thing, I programmed a `searchsorted` implementation for pytorch:
https://github.com/aliutkus/pytorch_searchsorted

maybe it's useful

**Comment by pshvechikov** [comment]
+1 
This is absolutely indispensable for Systematic Resampling -- probably the most widespread method for resampling in sequential models.

**Comment by tingiskhan** [comment]
Same as @pshvechikov, would be awesome if this was implemented

**Comment by jjasonhe** [comment]
+1 for this!

**Comment by aliutkus** [comment]
I updated my searchsorted implementation to work with pytorch v1.0
[https://github.com/aliutkus/torchsearchsorted](https://github.com/aliutkus/torchsearchsorted)

**Comment by tingiskhan** [comment]
@aliutkus Awesome! Will try and test your library in the coming week

**Comment by conormdurkan** [comment]
@aliutkus Great work, thanks! Is it possible for this solution to be integrated into PyTorch?

**Comment by ezyang** [comment]
I'll commit to reviewing a PR that adds this functionality to PyTorch. However, I would like to know what to do about the identical functionality in one_hot_ops

**Comment by aliutkus** [comment]
I would be glad if it gets integrated. I don't know how to proceed and got no time for the heavy unit testing it probably takes though

cheers

**Comment by chenzhekl** [comment]
I need `searchsorted` as well for implementing "Cubic-Spline Flows". TensorFlow already has a method for that https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/searchsorted

**Comment by sachinruk** [comment]
Wondering if this has been implemented now with pytorch 1.3? The library mentioned above is causing me compilations issues (on my non-GPU mac).

**Comment by aliutkus** [comment]
@sachinruk, talking of my torchsearchsorted ? which error ?

**Comment by sachinruk** [comment]
@aliutkus Not sure why I can't open an issue in that repo but yes, I get the following error when I do `python setup.py install`:
```
 /Users/sachin/miniconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/cuda.h:5:10: fatal error:
      'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 warning and 1 error generated.
error: command 'gcc' failed with exit status 1
```

**Comment by aliutkus** [comment]
@sachinruk sorry I didnt activate issues, it's done now

**Comment by kurtamohler** [comment]
I can start working on this.

**Comment by ezyang** [comment]
@kurtamohler Best to hold off for a bit, IIRC @gchanan wanted to use this as an onboarding task for one of our engineers. Maybe you could help review their diff :)

**Comment by glaringlee** [comment]
This feature has been added in PR
https://github.com/pytorch/pytorch/pull/34577

Close this issue.
