### ISSUE TITLE
Libtorch Linker Error in Debug Mode Since 1.11.0

### ISSUE THREAD

**Issue by jonahclarsen** [pytorch/pytorch#76957]
### 🐛 Describe the bug

I have used the latest version of the VS extension to create a Libtorch project, including the `/INCLUDE:?warp_size@cuda@at@@YAHXZ 
/INCLUDE:?_torch_cuda_cu_linker_symbol_op_cuda@native@at@@YA?AVTensor@2@AEBV32@@Z` linker commands. The project runs fine in Release mode (linking/including the Release Libtorch), but gives the following errors when running in Debug mode (linking/including the debug Libtorch):
> Error	LNK1120	11 unresolved externals	TorchProject1	C:\Users\jonah\source\repos\TorchProject1\x64\Debug\TorchProject1.exe	1	
Error	LNK2001	unresolved external symbol "class at::Tensor __cdecl at::native::_torch_cuda_cu_linker_symbol_op_cuda(class at::Tensor const &)" (?_torch_cuda_cu_linker_symbol_op_cuda@native@at@@YA?AVTensor@2@AEBV32@@Z)	TorchProject1	C:\Users\jonah\source\repos\TorchProject1\LINK	1	
Error	LNK2001	unresolved external symbol "int __cdecl at::cuda::warp_size(void)" (?warp_size@cuda@at@@YAHXZ)	TorchProject1	C:\Users\jonah\source\repos\TorchProject1\LINK	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl c10::WeakOrStrongTypePtr::WeakOrStrongTypePtr(struct c10::WeakTypePtr)" (__imp_??0WeakOrStrongTypePtr@c10@@QEAA@UWeakTypePtr@1@@Z) referenced in function "public: void __cdecl c10::ivalue::Object::unsafe_make_weak_compilation_ref(void)" (?unsafe_make_weak_compilation_ref@Object@ivalue@c10@@QEAAXXZ)	TorchProject1	C:\Users\jonah\source\repos\TorchProject1\example-app.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl c10::WeakOrStrongTypePtr::WeakOrStrongTypePtr(struct c10::StrongTypePtr)" (__imp_??0WeakOrStrongTypePtr@c10@@QEAA@UStrongTypePtr@1@@Z) referenced in function "public: __cdecl c10::ivalue::Object::Object(struct c10::StrongTypePtr,unsigned __int64)" (??0Object@ivalue@c10@@QEAA@UStrongTypePtr@2@_K@Z)	TorchProject1	C:\Users\jonah\source\repos\TorchProject1\example-app.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: struct c10::WeakTypePtr __cdecl c10::WeakOrStrongTypePtr::asWeakTypePtr(void)const " (__imp_?asWeakTypePtr@WeakOrStrongTypePtr@c10@@QEBA?AUWeakTypePtr@2@XZ) referenced in function "public: void __cdecl c10::ivalue::Object::unsafe_make_weak_compilation_ref(void)" (?unsafe_make_weak_compilation_ref@Object@ivalue@c10@@QEAAXXZ)	TorchProject1	C:\Users\jonah\source\repos\TorchProject1\example-app.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: bool __cdecl c10::WeakOrStrongTypePtr::holds_strong_ref(void)const " (__imp_?holds_strong_ref@WeakOrStrongTypePtr@c10@@QEBA_NXZ) referenced in function "public: class std::shared_ptr<struct torch::jit::CompilationUnit> __cdecl c10::ivalue::Object::compilation_unit(void)" (?compilation_unit@Object@ivalue@c10@@QEAA?AV?$shared_ptr@UCompilationUnit@jit@torch@@@std@@XZ)	TorchProject1	C:\Users\jonah\source\repos\TorchProject1\example-app.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl c10::WeakOrStrongTypePtr::~WeakOrStrongTypePtr(void)" (__imp_??1WeakOrStrongTypePtr@c10@@QEAA@XZ) referenced in function "int `public: __cdecl c10::ivalue::Object::Object(struct ivalue::Object::dtor$1 const &)'::`1'::dtor$1" (?dtor$1@?0???0Object@ivalue@c10@@QEAA@AEBU012@@Z@4HA)	TorchProject1	C:\Users\jonah\source\repos\TorchProject1\example-app.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl c10::WeakOrStrongTypePtr::WeakOrStrongTypePtr(struct c10::WeakOrStrongTypePtr const &)" (__imp_??0WeakOrStrongTypePtr@c10@@QEAA@AEBU01@@Z) referenced in function "public: __cdecl c10::ivalue::Object::Object(struct c10::ivalue::Object const &)" (??0Object@ivalue@c10@@QEAA@AEBU012@@Z)	TorchProject1	C:\Users\jonah\source\repos\TorchProject1\example-app.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl c10::WeakOrStrongTypePtr::WeakOrStrongTypePtr(struct c10::WeakOrStrongTypePtr &&)" (__imp_??0WeakOrStrongTypePtr@c10@@QEAA@$$QEAU01@@Z) referenced in function "public: static class c10::intrusive_ptr<struct c10::ivalue::Object,struct c10::detail::intrusive_target_default_null_type<struct c10::ivalue::Object> > __cdecl c10::intrusive_ptr<struct c10::ivalue::Object,struct c10::detail::intrusive_target_default_null_type<struct c10::ivalue::Object> >::make<struct c10::WeakOrStrongTypePtr,unsigned __int64 &>(struct c10::WeakOrStrongTypePtr &&,unsigned __int64 &)" (??$make@UWeakOrStrongTypePtr@c10@@AEA_K@?$intrusive_ptr@UObject@ivalue@c10@@U?$intrusive_target_default_null_type@UObject@ivalue@c10@@@detail@3@@c10@@SA?AV01@$$QEAUWeakOrStrongTypePtr@1@AEA_K@Z)	TorchProject1	C:\Users\jonah\source\repos\TorchProject1\example-app.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: struct c10::WeakOrStrongTypePtr & __cdecl c10::WeakOrStrongTypePtr::operator=(struct c10::WeakOrStrongTypePtr const &)" (__imp_??4WeakOrStrongTypePtr@c10@@QEAAAEAU01@AEBU01@@Z) referenced in function "public: struct c10::ivalue::Object & __cdecl c10::ivalue::Object::operator=(struct c10::ivalue::Object const &)" (??4Object@ivalue@c10@@QEAAAEAU012@AEBU012@@Z)	TorchProject1	C:\Users\jonah\source\repos\TorchProject1\example-app.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: struct c10::WeakOrStrongTypePtr & __cdecl c10::WeakOrStrongTypePtr::operator=(struct c10::WeakOrStrongTypePtr &&)" (__imp_??4WeakOrStrongTypePtr@c10@@QEAAAEAU01@$$QEAU01@@Z) referenced in function "public: struct c10::ivalue::Object & __cdecl c10::ivalue::Object::operator=(struct c10::ivalue::Object &&)" (??4Object@ivalue@c10@@QEAAAEAU012@$$QEAU012@@Z)	TorchProject1	C:\Users\jonah\source\repos\TorchProject1\example-app.obj	1	

I have made sure to change the post-build event to copy the correct binaries.

This project works fine with libtorch-1.10.1+cu113 debug version (with the `-INCLUDE:?searchsorted_cuda@native@at@@YA?AVTensor@2@AEBV32@0_N1@Z` linker command instead). This seems to be a problem with 1.11.0, possibly just with that new linker command.

### Versions

- Visual Studio 2019
- Windows 10
- Libtorch 1.11.0 (From pytorch.org; tried with Debug and Release versions as described)
- Cuda 11.3

**Comment by jonahclarsen** [comment]
My apologies, I think I had messed up my files and had incorrectly labeled an older libtorch as 1.11.0.
