### PR TITLE
Fix static `py::object` dangling pointer with `py::gil_safe_call_once_and_store`

### PR DESCRIPTION
**Pull request by XuehaiPan**
Fix static `py::object`s with `py::gil_safe_call_once_and_store`.

The following code will leak a `py::object` which will call its destructor when shutdown the program. The destructor will call `Py_DECREF(obj.m_ptr)` which may raise a segmentation fault.

```c++
void func() {
    static py::object obj = py::module_::import("foo").attr("bar");

    ...
}
```

The correct code is to use raw pointers rather than the instance.

```c++
void func() {
    static py::object* obj_ptr = new py::object{py::module_::import("foo").attr("bar")};
    py::object obj = *obj_ptr;

    ...
}
```

This PR uses the `py::gil_safe_call_once_and_store` function from `pybind11`, which can run arbitrary initialization code only once under the Python GIL thread safely.

```c++
void func() {
    PYBIND11_CONSTINIT static py::gil_safe_call_once_and_store<py::object> storage;
    py::object obj = storage
                         .call_once_and_store_result(
                             []() -> py::object {
                                 return py::module_::import("foo").attr("bar");
                             }
                         )
                         .get_stored();

    ...
}
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by williamwen42** [comment]
Yep, I encountered this issue while working on dynamo 3.13 enablement. Is this behavior documented anywhere in pybind? It would be great if pybind could support code like
```c++
static py::object obj = py::module_::import("foo").attr("bar");
```

**Comment by zou3519** [comment]
internal needs a third-party/pybind update (https://github.com/pytorch/pytorch/pull/130064 got reverted for a similar reason)

**Comment by izaitsevfb** [comment]
@pytorchbot revert -m "internal needs pybind update" -c ghfirst

Apologies for reverting this, but it appears that meta uses pybind 2.10.4 that is not fully compatible with this change:
```
In file included from fbcode/caffe2/caffe2/python/pybind_state.cc:44:
fbcode/caffe2/torch/csrc/jit/python/module_python.h:13:3: error: unknown type name 'PYBIND11_CONSTINIT'
  PYBIND11_CONSTINIT static py::gil_safe_call_once_and_store<py::object>
  ^
fbcode/caffe2/torch/csrc/jit/python/module_python.h:13:33: error: definition or redeclaration of 'gil_safe_call_once_and_store' not allowed inside a function
  PYBIND11_CONSTINIT static py::gil_safe_call_once_and_store<py::object>
                            ~~~~^
fbcode/caffe2/torch/csrc/jit/python/module_python.h:13:33: error: no member named 'gil_safe_call_once_and_store' in namespace 'pybind11'
  PYBIND11_CONSTINIT static py::gil_safe_call_once_and_store<py::object>
                            ~~~~^
fbcode/caffe2/torch/csrc/jit/python/module_python.h:13:61: error: expected ';' at end of declaration
  PYBIND11_CONSTINIT static py::gil_safe_call_once_and_store<py::object>
                                                            ^
                                                            ;
fbcode/caffe2/torch/csrc/jit/python/module_python.h:16:7: error: use of undeclared identifier 'storage'
      storage
      ^
fbcode/caffe2/torch/csrc/jit/python/module_python.h:28:3: error: unknown type name 'PYBIND11_CONSTINIT'
  PYBIND11_CONSTINIT static py::gil_safe_call_once_and_store<
  ^
fbcode/caffe2/torch/csrc/jit/python/module_python.h:28:33: error: definition or redeclaration of 'gil_safe_call_once_and_store' not allowed inside a function
  PYBIND11_CONSTINIT static py::gil_safe_call_once_and_store<
                            ~~~~^
fbcode/caffe2/torch/csrc/jit/python/module_python.h:28:61: error: expected ';' at end of declaration
  PYBIND11_CONSTINIT static py::gil_safe_call_once_and_store<
                                                            ^
                                                            ;
fbcode/caffe2/torch/csrc/jit/python/module_python.h:32:7: error: use of undeclared identifier 'storage'
      storage
      ^
9 errors generated.
```

@malfet is working on updating pybind internally, but it's not a fast process. I decided to revert this change for now. We'll reland this PR once pybind is updated.

**Review by malfet — APPROVED** [review]

**Comment by albanD** [comment]
Sorry for the delay on this one. The internal pybind upgrade necessary to merge this has been a slog :/

**Comment by albanD** [comment]
FYI https://github.com/pytorch/pytorch/pull/136370 is a rework of this PR to avoid the internal pybind issue
