### ISSUE TITLE
PyTorch-nightly can not me imported using python-3.7.0

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#74087]
### 🐛 Describe the bug

Steps to reproduce:
```
conda create -n py3.7-torch-nightly python==3.7.0 pytorch cpuonly -c pytorch-nightly
conda activate py3.7-torch-nightly
python -c "import torch"
```
which would fail with:
```
% python -c "import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/nshulga/git/pytorch/pytorch/torch/__init__.py", line 751, in <module>
    from .functional import *  # noqa: F403
  File "/Users/nshulga/git/pytorch/pytorch/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/nshulga/git/pytorch/pytorch/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/nshulga/git/pytorch/pytorch/torch/nn/modules/__init__.py", line 1, in <module>
    from .module import Module
  File "/Users/nshulga/git/pytorch/pytorch/torch/nn/modules/module.py", line 205, in <module>
    class Module:
  File "/Users/nshulga/git/pytorch/pytorch/torch/nn/modules/module.py", line 1318, in Module
    def state_dict(self, *, prefix: str = ..., keep_vars: bool = ...) -> typing.OrderedDict[str, Tensor]:
AttributeError: module 'typing' has no attribute 'OrderedDict'
```

Same works fine if  Python-3.7.2 or newer is used

Introduced by https://github.com/pytorch/pytorch/pull/72211

### Versions

nightly

cc @ezyang @gchanan @zou3519

**Comment by malfet** [comment]
[Edit] False alarm, this change was not picked in release branch, only into nightly

**Comment by rajuptvs** [comment]
Hey, I was having a similar issue with 
torch version=  '1.13.0+cu116' and
python version = '3.7.0'
 
was able to circumvent the issue by changing the import libraries as below 

Before :
from typing import Any, Callable, List, Optional, OrderedDict, Sequence, Tuple

After:
from typing import Any, Callable, List, Optional, Sequence, Tuple
from collections import OrderedDict
