### ISSUE TITLE
AttributeError: module 'torch.autograd.graph' has no attribute 'GradientEdge' 

### ISSUE THREAD

**Issue by pengr** [pytorch/pytorch#121402]
### 🐛 Describe the bug

In my conda 24.3.1 base environment (with python 3.11.7, cuda 12.3), use the command under the official link to install torch: 
###CUDA 12.1 
pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 - -index-url https://download.pytorch.org/whl/cu121 
When importing torch, an error will be raised: 
AttributeError: module 'torch.autograd.graph' has no attribute 'GradientEdge'.
The simplest solution I found was to remove the term "--index": pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 
Please fix this issues as soon as possible, it make user crazzy.

### Versions

Conda 24.3.1 base environment, Python 3.11.7, cuda 12.3, torch 2.1.2

cc @seemethere @malfet @osalpekar @atalman @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by albanD** [comment]
This is most likely pulling in a partial package somewhere.

Can you share the stack trace of where this error is being raised from please?

**Comment by soulitzer** [comment]
Hi @pengr, GradientEdge requires torch>=2.2. Could you try again after upgrading to a later version?

**Comment by pengr** [comment]
This is my stack trace for this error: Traceback (most recent call last):
  File "/mnt/m6pr/data-manager/inference_qwen2.py", line 5, in <module>
    import torch
  File "/opt/conda/lib/python3.11/site-packages/torch/__init__.py", line 1382, in <module>
    from .functional import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/functional.py", line 7, in <module>
    import torch.nn.functional as F
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 7, in <module>
    from .. import functional as F
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py", line 20, in <module>
    from .._jit_internal import boolean_dispatch, _overload, BroadcastingList1, BroadcastingList2, BroadcastingList3
  File "/opt/conda/lib/python3.11/site-packages/torch/_jit_internal.py", line 41, in <module>
    import torch.distributed.rpc
  File "/opt/conda/lib/python3.11/site-packages/torch/distributed/rpc/__init__.py", line 74, in <module>
    from .server_process_global_profiler import (
  File "/opt/conda/lib/python3.11/site-packages/torch/distributed/rpc/server_process_global_profiler.py", line 6, in <module>
    from torch.autograd.profiler_legacy import profile
  File "/opt/conda/lib/python3.11/site-packages/torch/autograd/__init__.py", line 442, in <module>
    if not torch._C._autograd_init():
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'torch.autograd.graph' has no attribute 'GradientEdge'

**Comment by pengr** [comment]
> Hi @pengr, GradientEdge requires torch>=2.2. Could you try again after upgrading to a later version?

Yes, although this error disappears when I upgrade torch to 2.2. 
But I need to install vllm package >=0.3.0, which limits the torch version to 0.2.1.
So I chose to remove - index-url https://download.pytorch.org/whl/cu121, in which case the torch 2.1.2 version met my needs.
