### PR TITLE
Back out D118342273: "[ROCm][BE] Remove outdated version conditions (#193927)" (#195788)

### PR DESCRIPTION
**Pull request by huydhn**
Summary:

D118342273 (diff-train import of pytorch/pytorch#193927) drops every `ROCM_VERSION >= 60300/60400/60500/70000` guard in caffe2, on the premise that "ROCm minimum supported version is now 7.0". That premise holds for OSS PyTorch but not for fbcode, which still pins ROCm 6.2.1 and 6.4.0 -- see the live `select()` arms and their `TODO(T256598044)` in `fbcode/caffe2/fb/fbcode/defs_hip.bzl`.

**Trunk break in `c10/cuda/CUDAEvent.h`.** With the guard gone, `record()` and `block()` reference the external-event flags unconditionally. The HIP headers added the two pairs in different releases:

- ROCm 6.2.1: neither pair exists
- ROCm 6.4.0: `hipEventRecordDefault`/`hipEventRecordExternal` exist, `hipEventWaitDefault`/`hipEventWaitExternal` do NOT
- ROCm 6.4.2 and later: all four exist

So on 6.4.0 the record pair resolves and only the wait pair fails:

```
c10/hip/HIPEvent.h:173:13: error: use of undeclared identifier 'hipEventWaitExternal'
c10/hip/HIPEvent.h:174:13: error: use of undeclared identifier 'hipEventWaitDefault'
```

That takes out `fbcode//caffe2:ATen-hip` and everything downstream of it. It was reported against `fbcode//sigrid/predictor/utils:event_pool` (Sigrid predictor AMD), one of the targets the 6.4.0 pin exists for.

**`ATen/cuda/tunable/GemmHipblaslt.h` is the same hazard one step behind.** The diff also removes the `ROCM_VERSION >= 70000` guard around `HIP_R_4F_E2M1`, which only exists in ROCm 7.0's `hipblaslt.h` and previously fell back to `static_cast<hipDataType>(33)`. Those are the guards D111505147 added in July for exactly this reason.

Backing out the whole commit rather than patching the two files, since the remaining hunks carry the same latent hazard. This should re-land once fbcode's 6.2.1 and 6.4.0 ROCm pins are retired (T256598044).

 ---

bypass-github-export-checks

This is an internal-only backout of a landed diff-train import, taken as the immediate stop-gap for a live trunk break, so there is no PR to link. Per the GitHub-first hotfix path, the upstream side still needs handling: pytorch/pytorch#193927 must be reverted or fixed on GitHub (restoring the guards for ROCm < 7.0), otherwise the next diff train re-imports it and re-breaks the 6.2.1/6.4.0 builds.

Test Plan:
Repro at the culprit commit (`6160cf8408fd`, which contains D118342273), ROCm 6.4.0:

```
buck2 build --flagfile fbcode//mode/opt-amd-gpu \
  -m ovr_config//third-party/rocm/constraints:6.4.0 \
  fbcode//sigrid/predictor/utils:event_pool
```

EXIT=3, `use of undeclared identifier 'hipEventWaitExternal'` / `'hipEventWaitDefault'` at `c10/hip/HIPEvent.h:173`/`174` -- byte-identical to the reported failure.

With this backout applied, all three ROCm versions fbcode still builds are green:

```
# 6.4.0 -- previously failing
buck2 build --flagfile fbcode//mode/opt-amd-gpu -m ovr_config//third-party/rocm/constraints:6.4.0 \
  fbcode//sigrid/predictor/utils:event_pool fbcode//caffe2:ATen-hip    -> EXIT=0

# 7.0 (default) -- no regression on the path the original diff targeted
buck2 build --flagfile fbcode//mode/opt-amd-gpu \
  fbcode//sigrid/predictor/utils:event_pool fbcode//caffe2:ATen-hip    -> EXIT=0

# 6.2.1
buck2 build --flagfile fbcode//mode/opt-amd-gpu -m ovr_config//third-party/rocm/constraints:6.2.1 \
  fbcode//sigrid/predictor/utils:event_pool                            -> EXIT=0
```

`arc f`: no changes. `arc lint --rev .^`: no lint issues.

Differential Revision: D118535204

### CODE REVIEW

**Comment by huydhn** [comment]
I think I'll revert https://github.com/pytorch/pytorch/pull/193927 instead, it's cleaner

**Comment by jeanschmidt** [comment]
@huydhn as you did revert, let me close this one then
