### PR TITLE
Fix Windows configure failure with MSVC 14.51 (VS Build Tools 18.6+)

### LINKED ISSUE #3718: [LNL] [PTL] Build issue with latest Build Tools
### 🐛 Describe the bug

There is build issue with Build Tools 18.6.0. I don't have this issue with version 18.4.0.

Log: [build_torch.log](https://github.com/user-attachments/files/28056796/build_torch.log)

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro (10.0.26200 64-bit)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 4.3.2
Libc version: N/A

Python version: 3.12.13 | packaged by conda-forge | (main, Mar  5 2026, 16:36:12) [MSC v.1944 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-11-10.0.26200-SP0
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
Is XPU available: N/A
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A
Caching allocator config: N/A

CPU:
Name: Intel(R) Core(TM) Ultra 7 258V
Manufacturer: GenuineIntel
Family: 774
Architecture: 9
ProcessorType: 3
DeviceID: CPU0
CurrentClockSpeed: 2200
MaxClockSpeed: 2200
L2CacheSize: 14336
L2CacheSpeed: None
Revision: None

Versions of relevant libraries:
[pip3] intel-openmp==2025.3.3
[pip3] mkl-include==2025.3.1
[pip3] mkl-static==2025.3.1
[pip3] numpy==2.4.6
[pip3] onemkl-license==2025.3.1
[pip3] optree==0.19.1
[pip3] tbb==2022.3.1
[pip3] tbb-devel==2022.3.1
[pip3] tcmlib==1.4.1
[conda] intel-openmp              2025.3.3                 pypi_0    pypi
[conda] mkl-include               2025.3.1                 pypi_0    pypi
[conda] mkl-static                2025.3.1                 pypi_0    pypi
[conda] numpy                     2.4.6                    pypi_0    pypi
[conda] onemkl-license            2025.3.1                 pypi_0    pypi
[conda] optree                    0.19.1                   pypi_0    pypi
[conda] tbb                       2022.3.1                 pypi_0    pypi
[conda] tbb-devel                 2022.3.1                 pypi_0    pypi
[conda] tcmlib                    1.4.1                    pypi_0    pypi

### PR DESCRIPTION
**Pull request by PatrykWilczewski**
When building PyTorch on Windows with MSVC 14.51 (shipped in VS Build Tools 18.6.0 and later), CMake configuration aborts while processing the bundled sleef submodule:
1. Configure-time ICE (feature probe)
	CMake Error: Generator: build tool execution failed, command
	was: ninja.exe -v cmTC_...
	COMPILER_SUPPORTS_BUILTIN_MATH - Failed
	Configuration incomplete, errors occured!
2. Compile-time ICE (sleef sources)
After the probe passes, MSVC 14.51 then crashes compiling sleef's
PUREC_SCALAR fallback sources (sleefsimdsp.c / sleefsimddp.c):
	sleefsimdsp.c(NNNN) : fatal error C1001: Internal compiler error.
	(compiler file '...\Compiler\Utc\src\p2\main.cpp', line 262)
	ninja: build stopped: subcommand failed. / Access violation

Fix: for MSVC only, wrap add_subdirectory(sleef) with two scoped chages:
- set CMAKE_TRY_COMPILE_CONFIGURATION=Release so sleef's try_compile probes are built optimized (avoids the configure ICE);
- append /fp:strict to CMAKE_C_FLAGS so the sleef sources use the non-crashing FP codegen path.

Both are restored immediately after the subdirectory so no other target is affected. The sleef library itself is already built in Release regardless, so this only changes how the configure-time probes are compiled.

Verified with a full configure + build on MSVC 14.51.26231 (cl 19.51.26252: COMPILER_SUPPORTS_BUILTIN_MATH now  succeeds, configure and generate complete, and the build proceeds to completion.

This patch is workaround for problem reported to Microsoft.
The fix will be included in MSVC 14.52 (release Q4 2026).
Microsoft statement:
"We have fixed this issue and are staging it for release in a subsequent MSVC Build Tools Preview release. [...] The default toolset is updated twice a year, as per https://aka.ms/msvc/lifecycle [...]"

Fixes: https://github.com/intel/torch-xpu-ops/issues/3718

### CODE REVIEW

**Comment by PatrykWilczewski** [comment]
It turned out that after adding the workaround, other problems occurred. It's best to wait for the MSVC release instead of providing the workaround.
