### PR TITLE
properly update _flat_weights in RNN modules

### LINKED ISSUE #32346: Pytorch 1.4.0 weight drop - 'LSTM' object has no attribute 'weight_hh_l0'
Hi,

awd-lstm implementation doesn't work after upgrading to 1.4.0. Here is how weight drop class looks like:

```python
class WeightDrop(torch.nn.Module):
    def __init__(self, module, weights, dropout=0, variational=False):
        super(WeightDrop, self).__init__()
        self.module = module
        self.weights = weights
        self.dropout = dropout
        self.variational = variational
        self._setup()

    def widget_demagnetizer_y2k_edition(*args, **kwargs):        
        return

    def _setup(self):
        # Terrible temporary solution to an issue regarding compacting weights re: CUDNN RNN
        if issubclass(type(self.module), torch.nn.RNNBase):
            self.module.flatten_parameters = self.widget_demagnetizer_y2k_edition

        for name_w in self.weights:
            print('Applying weight drop of {} to {}'.format(self.dropout, name_w))
            w = getattr(self.module, name_w)
            del self.module._parameters[name_w]
            self.module.register_parameter(name_w + '_raw', Parameter(w.data))

    def _setweights(self):
        for name_w in self.weights:
            raw_w = getattr(self.module, name_w + '_raw')
            w = None
            if self.variational:               
                mask = torch.ones(raw_w.size(0), 1)

                if raw_w.is_cuda: mask = mask.cuda()
                mask = torch.nn.functional.dropout(mask, p=self.dropout, training=True)
                w = mask.expand_as(raw_w) * raw_w
            else:
                w = torch.nn.functional.dropout(raw_w, p=self.dropout, training=self.training)
            setattr(self.module, name_w, w)

    def forward(self, *args):
        self._setweights()        
        return self.module.forward(*args)
```

what model's init looks like:

```python
class RNNModel(nn.Module):
    def __init__(self, ninp, nhid, history_size, label_size, nlayers=1, dropout=0.5, dropouth=0.5, dropouti=0.2, dropoute=0.1, wdrop=0.7, tie_weights=False):
        super(RNNModel, self).__init__()
        self.ninp = ninp
        self.nhid = nhid
        self.nlayers = nlayers        

        self.rnns = [torch.nn.LSTM(ninp if l == 0 else nhid, nhid if l != nlayers - 1 else (ninp if tie_weights else nhid), 1, dropout=0) for l in range(nlayers)]
        if wdrop:
            self.rnns = [WeightDrop(rnn, ['weight_hh_l0'], dropout=wdrop) for rnn in self.rnns]

        self.rnns = torch.nn.ModuleList(self.rnns)
        self.decoder = nn.Linear(nhid, label_size)
```

What should I do to update my code? I can't figure it out myself, thanks.

**edit:**
To reproduce, the code below is enough and I discovered it only happens when using .to(device), .cpu() or .cuda()

    encoder = RNNModel(5, 128, 120, 2, 1).cuda()

**Environment**
- PyTorch Version (e.g., 1.0): 1.4.0
- OS (e.g., Linux): Windows 10
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source):
- Python version: 3.7
- CUDA/cuDNN version: 10.1
- GPU models and configuration:
- Any other relevant information:

cc @ezyang @gchanan @zou3519

### PR DESCRIPTION
**Pull request by ngimel**
Should fix #32346 hopefully. Now when _flat_weights list is updated, `None` elements are appended to it if some weights are missing, subsequent `setattr` calls for the missing weights should repair _flat_weights and make it suitable to use in the backend.

### CODE REVIEW

File: test/test_nn.py [hunk 1]
```diff
@@ -5741,13 +5741,23 @@ def test_partial_flat_weights(self):
...
+        # deletes an attribute of original LSTM
+        weight_orig = m.weight_hh_l0
         del m.weight_hh_l0
-
+        self.assertFalse(hasattr(m, "weight_hh_l0"))
         # verifies that moving to CUDA with only some attributes defined
         # does not throw an error
         m.cuda()
+        # recompute the weight and make sure that module can be used
+        setattr(m, "weight_hh_l0", weight_orig.cuda())
```
Comment (mruberry) [inline test/test_nn.py]: m.weight_hh_l0 = weight_orig.cuda()

**Review by mruberry — APPROVED** [review]
Looks better than before!

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 81b2f1cb:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=81b2f1cb31dc2474ef1d560078f9e73c7469c793).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4405268) pytorch_windows_test1 (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=94781626) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=94781626))
<details>
<summary>
<code>RuntimeError: test_nn failed!</code>
</summary>

```
 
---------------------------------------------------------------------- 
Ran 1630 tests in 580.107s 
 
FAILED (errors=13, skipped=68, expected failures=4) 
Traceback (most recent call last): 
  File "run_test.py", line 457, in <module> 
    main() 
  File "run_test.py", line 450, in main 
    raise RuntimeError(message) 
RuntimeError: test_nn failed! 
 
(base) circleci@PACKER-5E29F737 C:\Users\circleci\project\test>if ERRORLEVEL 1 exit /b 1  
+ cleanup
+ retcode=1
+ set +x
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>
