### ISSUE TITLE
Opencv 4 compatibility

### ISSUE THREAD

**Issue by achalshah20** [pytorch/pytorch#11950]
## Issue description

Pytorch is not compatible with opencv 4 macros

## Code example

Getting errors related to opencv macros when compile with opencv 4.
```
In file included from /home/achal/achal/opensource/pytorch/caffe2/image/image_input_op.cc:1:0:
/home/achal/achal/opensource/pytorch/caffe2/image/image_input_op.h: In member function ‘bool caffe2::ImageInputOp<Context>::GetImageAndLabelAndInfoFromDBValue(const string&, cv::Mat*, caffe2::ImageInputOp<Context>::PerImageArg&, int, std::mt19937*)’:
/home/achal/achal/opensource/pytorch/caffe2/image/image_input_op.h:468:22: error: ‘CV_LOAD_IMAGE_COLOR’ was not declared in this scope
             color_ ? CV_LOAD_IMAGE_COLOR : CV_LOAD_IMAGE_GRAYSCALE);
                      ^~~~~~~~~~~~~~~~~~~
/home/achal/achal/opensource/pytorch/caffe2/image/image_input_op.h:468:44: error: ‘CV_LOAD_IMAGE_GRAYSCALE’ was not declared in this scope
             color_ ? CV_LOAD_IMAGE_COLOR : CV_LOAD_IMAGE_GRAYSCALE);
                                            ^~~~~~~~~~~~~~~~~~~~~~~
/home/achal/achal/opensource/pytorch/caffe2/image/image_input_op.h:543:22: error: ‘CV_LOAD_IMAGE_COLOR’ was not declared in this scope
             color_ ? CV_LOAD_IMAGE_COLOR : CV_LOAD_IMAGE_GRAYSCALE);
                      ^~~~~~~~~~~~~~~~~~~
/home/achal/achal/opensource/pytorch/caffe2/image/image_input_op.h:543:44: error: ‘CV_LOAD_IMAGE_GRAYSCALE’ was not declared in this scope
             color_ ? CV_LOAD_IMAGE_COLOR : CV_LOAD_IMAGE_GRAYSCALE);
                                            ^~~~~~~~~~~~~~~~~~~~~~~
/home/achal/achal/opensource/pytorch/caffe2/image/image_input_op.h:684:44: error: ‘CV_BGR2GRAY’ was not declared in this scope
     cv::cvtColor(src, *img, (out_c == 1) ? CV_BGR2GRAY : CV_GRAY2BGR);
                                            ^~~~~~~~~~~
/home/achal/achal/opensource/pytorch/caffe2/image/image_input_op.h:684:58: error: ‘CV_GRAY2BGR’ was not declared in this scope
     cv::cvtColor(src, *img, (out_c == 1) ? CV_BGR2GRAY : CV_GRAY2BGR);
```

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): cmake
- OS: linux
- PyTorch version: 0.4
- Python version: 3.6.6
- CUDA/cuDNN version: 10.0/7.3
- GPU models and configuration: nvidia titan x
- GCC version (if compiling from source): 6 (Doesn't work with 7.3 yet)
- CMake version: 3.11
- Versions of any other relevant libraries: N/A

I have already sent PR a long time back https://github.com/pytorch/pytorch/pull/9966. Can someone merge this if looks good?

**Comment by mratsim** [comment]
Hitting that as well, pending #9966
