### ISSUE TITLE
mkl-dnn build breaks with mkl 2019.3

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#18365]
## 🐛 Bug
When building with mkl 2019.3 installed (this is now the default version on conda) I'm getting the errors related to deprecation of some functions:
```
/workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp: In member function 'void mkldnn::impl::cpu::_ref_rnn_common_t<aprop>::pack_weights(int, int, int, int, int, int, int, float**, int, int*, const float*, float*, bool)':
/workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:891:36: error: 'float* cblas_sgemm_alloc(CBLAS_IDENTIFIER, int, int, int)' is deprecated [-Werror=deprecated-declarations]
                 weights(i, d, p) = cblas_sgemm_alloc(CblasAMatrix, m_p, n, k_p);
                                    ^
In file included from /workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/opt/conda/include/mkl_cblas.h:791:25: note: declared here
 MKL_DEPRECATED_C float* cblas_sgemm_alloc(const  CBLAS_IDENTIFIER identifier,
                         ^
/workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:891:36: error: 'float* cblas_sgemm_alloc(CBLAS_IDENTIFIER, int, int, int)' is deprecated [-Werror=deprecated-declarations]
                 weights(i, d, p) = cblas_sgemm_alloc(CblasAMatrix, m_p, n, k_p);
                                    ^
In file included from /workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/opt/conda/include/mkl_cblas.h:791:25: note: declared here
 MKL_DEPRECATED_C float* cblas_sgemm_alloc(const  CBLAS_IDENTIFIER identifier,
                         ^
/workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp: In member function 'void mkldnn::impl::cpu::_ref_rnn_common_t<aprop>::free_packed_weights(int, int, int, float**)':
/workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:979:17: error: 'void cblas_sgemm_free(float*)' is deprecated [-Werror=deprecated-declarations]
                 cblas_sgemm_free(weights(i, j, k));
                 ^
In file included from /workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/opt/conda/include/mkl_cblas.h:804:23: note: declared here
 MKL_DEPRECATED_C void cblas_sgemm_free(float *dest);
                       ^
/workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:979:17: error: 'void cblas_sgemm_free(float*)' is deprecated [-Werror=deprecated-declarations]
                 cblas_sgemm_free(weights(i, j, k));
                 ^
In file included from /workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /workspace/ALL/pytorch_upstream/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/opt/conda/include/mkl_cblas.h:804:23: note: declared here
 MKL_DEPRECATED_C void cblas_sgemm_free(float *dest);
                       ^
```

## To Reproduce
conda install mkl mkl-include
python setup.py develop

## Expected behavior

Build does not error out

## Environment

Current master, Ubuntu 16.04, python 3.6 inside conda env

**Comment by rahulunair** [comment]
MKL-DNN version breaks on ClearLinux  28320 as well for mkl 2019.3

**Comment by ezyang** [comment]
First thing to check is see if upgrading ideep submodule to latest fixes this. If not, time to file an upstream bug.

**Comment by ezyang** [comment]
Oh, these are deprecations, not actual compile errors.

**Comment by ezyang** [comment]
It looks like a submodule upgrade should fix this.

**Comment by NhanTran96** [comment]
I had the same problem. How do I solve it?

My setup: 
ubuntu 18.04.2
nvidia-driver-410
cuda 10.0
cudnn 7.5.0
mkl=2019.3

**Comment by soumith** [comment]
as an update, @jianhui from Intel said they are working on a hotfix to the MKL-DNN 0.17.3 branch to fix this issue.

**Comment by zhanwenchen** [comment]
In the meantime, I found a solution: download the [mkl_dnn 0.18.1](https://github.com/intel/mkl-dnn/releases) source code and just pasted the folder into third_party/ideep/, replacing the old mkl_dnn folder. It has to be 0.18.1 because 0.17.4 causes the same error.

**Comment by soumith** [comment]
fixed via #18463
