### PR TITLE
[Forward Fix][PGNCCL] Add define guard for NCCL_SPLIT_NOCOLOR

### PR DESCRIPTION
**Pull request by kwen2501**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #137544
* #138384
* #138374
* __->__ #138488
* #137855

Forward fix for build issue introduced by #137855:
```
In file included from fbcode/caffe2/torch/csrc/distributed/c10d/NCCLUtils.cpp:2:
fbcode/caffe2/torch/csrc/distributed/c10d/ProcessGroupNCCL.hpp:508:21: error: use of undeclared identifier 'NCCL_SPLIT_NOCOLOR'
  508 |     int split_color{NCCL_SPLIT_NOCOLOR - 1};
      |                     ^
```

cc @H-Huang @awgu @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Comment by fduwjj** [comment]
maybe next time, you want to import into fbcode and wait for internal CI as well?

**Review by fduwjj — APPROVED** [review]

**Comment by fduwjj** [comment]
We do need this release note tag. Since it is not user facing, it won't get mentioned in the release note.
