### ISSUE TITLE
async keyword on cuda() no longer works

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#5174]
```
    input_var = Variable(input, volatile=(not train)).cuda(async=True)
TypeError: cuda() got an unexpected keyword argument 'async'
```

**Comment by soumith** [comment]
@ezyang I thought https://github.com/pytorch/pytorch/pull/4999 fixes it. Did you rebase?

**Comment by apaszke** [comment]
This is probably the offending PR, since it removed async and added non_blocking. We should keep the previous keyword for backward compatibility in older Python versions

**Comment by ezyang** [comment]
Looks like it's a pretty simple fix. Patch coming.
