### PR TITLE
Move c10/util/TypeCast.h and overflows.h into torch/headeronly

### PR DESCRIPTION
**Pull request by cleonard530**
## Summary
Move `TypeCast.h` and `overflows.h` from `c10/util` into `torch/headeronly/util` under `torch::headeronly`, leaving the old `c10/util` paths as one-line forwarding includes (matching `Half.h` / `BFloat16.h`).

`TypeCast.h`'s `report_overflow` used to be a `C10_API` symbol defined in `TypeCast.cpp` so the `ostringstream`/`throw` path was not inlined into every `checked_convert` instantiation (see #65830 / #66721). Header-only code cannot export that symbol, and inlining it directly could reintroduced the code-size bloat. We therefore add the `C10_NOINLINE` macro with `inline` so the overflow path is still not inlined into every `checked_convert` instantiation.

Removed the now-dead `//c10/util:TypeCast` Bazel target and its two dependents (`c10/build.bzl`, `c10/core/build.bzl`), since `TypeCast.cpp` no longer exists.

This is the second leaf-utilities PR toward moving aten/src/ATen/native/Math.h and its dependency chain into headeronly. (This should be independent of the first PR #194673, and should not have any merge conflicts with it)

Note: As of only a few days ago (when this PR was originally opened) [c10/util/TypeCast.cpp](https://github.com/pytorch/pytorch/pull/194781/files/77e9a5cb8c0b02b2ece4c5753c47431dc2e40999#diff-f214545d71bcddab19fa2ddf585ee75affd601a1000bd0c0eb6dfa9caf97d32c) threw a `std::runtime_error` instead of `TORCH_CHECK`, so the error in `report_overflow` can safely be converted to `STD_TORCH_CHECK`.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @kadeng @chauhang @amjames @jataylo @azahed98 @janeyx99 

checkout commit https://github.com/pytorch/pytorch/pull/194781/changes/1b1317dab693052d2aab00404972b4cfb3d240c2 to see the diff between the old header and the new headeronly headers.

## Test plan
`build/bin/test_aoti_abi_check --gtest_filter='TestCast.*:TestOverflows.*'`

## Test Result 
 
image

### CODE REVIEW

File: torch/headeronly/util/TypeCast.h [hunk 1]
```diff
@@ -0,0 +1,326 @@
...
+  }
+};
+
+template <typename To, typename From>
+C10_HOST_DEVICE To convert(From f) {
+  return static_cast_with_inter_type<To, From>::apply(f);
+}
+
+// Define separately (C10_NOINLINE) to avoid being inlined and prevent
+// code-size bloat.
```
Comment (janeyx99) [inline torch/headeronly/util/TypeCast.h]:
```suggestion
// Define with C10_NOINLINE to prevent code-size bloat.
```

File: torch/headeronly/util/TypeCast.h [hunk 2]
```diff
@@ -0,0 +1,326 @@
...
+[[noreturn]] C10_NOINLINE inline void report_overflow(const char* name) {
+  STD_TORCH_CHECK(
+      false,
+      "value cannot be converted to type ",
+      name,
+      " without overflow"); // rather than domain_error (issue 33562)
```
Comment (janeyx99) [inline torch/headeronly/util/TypeCast.h]:
```suggestion
      " without overflow"); // runtime_error rather than domain_error (#33562)
```
super nit

**Review by janeyx99 — COMMENTED** [review]
Several concerns:

1. we still need old libtorch builds to work, so you will need to maintain c10::report_overflow. but have it delegate to the headeronly impl to reduce duplication
2. Everyone that includes c10/util/TypeCast.h and c10/util/overflows.h should be able to access their transitive includes (like the APIs in c10/util/complex.h not yet migrated). Preserve the includes in the c10
3. I don't think we can delete the public //c10/util:TypeCast target in build.bzl. So add it back.

More concretely (summarized by codex):
  - Keep torch::headeronly::report_overflow as C10_NOINLINE inline.
  - Retain c10::report_overflow as a C10_API declaration.
  - Keep TypeCast.cpp, implementing the exported function by delegating to the header-only
    function.

  - Keep the public //c10/util:TypeCast build target unchanged.
  - Restore the original transitive includes in c10/util/TypeCast.h and c10/util/
    overflows.h.

  - Remove the stale D25440771 test-trigger comment. => in the OG c10 TypeCast.h

File: c10/util/TypeCast.cpp [hunk 3]
```diff
@@ -1,14 +1,11 @@
...
-
 namespace c10 {
 
+// Export c10::report_overflow as C10_API for libtorch ABI. The throw logic
+// lives in torch::headeronly::report_overflow; this wrapper delegates to it.
 [[noreturn]] void report_overflow(const char* name) {
-  std::ostringstream oss;
-  oss << "value cannot be converted to type " << name << " without overflow";
-  // c10::Error rather than domain_error (issue 33562)
-  TORCH_CHECK(false, std::move(oss).str());
```
Comment (janeyx99) [inline c10/util/TypeCast.cpp:11]: can you add a note in the PR description saying that as of only a few days ago this was a throw std::runtime_error so this can safely be STD_TORCH_CHECK.

File: c10/util/TypeCast.h [hunk 4]
```diff
@@ -11,311 +11,45 @@
...
-  C10_HOST_DEVICE static inline src_t apply(src_t src) {
-    return src;
-  }
-};
-
-template <typename src_t>
-struct maybe_real<true, src_t> {
   C10_HOST_DEVICE static inline decltype(auto) apply(src_t src) {
-    return src.real();
+    return torch::headeronly::maybe_real<B, src_t>::apply(src);
```
Comment (janeyx99) [inline c10/util/TypeCast.h:32]: i'm confused by the forwarding here, why can't all of this code be deleted and inherit from torch/headeronly?

**Review by janeyx99 — DISMISSED** [review]
accepting

I realize I was wrong earlier. We shouldn't have to keep around the .cpp because we don't promise abi stability of libtorch.so. We may run into issues internally where they still may expect abi stability, but I'm seeing how much more complicated it makes this PR. 

Can you revert your changes to remove the .cpp and everything related to it, and then try landing it? If it gets reverted from internal we can evaluate then. This is the first time we're moving a .cpp to a .h with C10_NOINLINE so there may be wrinkles unforeseen, but let's land the simplest approach first.

File: c10/util/TypeCast.h (hunk 4 above)
Comment (cleonard530) [reply c10/util/TypeCast.h:32]: That made since to me too, but I am getting the following CI errors
`/__w/pytorch/pytorch/c10/util/TypeCast.h:32:8: error: ‘c10::static_cast_with_inter_type<long unsigned int, long unsigned int>’ declared with greater visibility than its base ‘torch::headeronly::static_cast_with_inter_type<long unsigned int, long unsigned int>’ [-Werror=attributes]`

It looks like `headeronly` is wrapped in a `HIDDEN_NAMESPACE`, while `C10` has public visibility.

**Comment by cleonard530** [comment]
@albanD, this PR migrates `report_overflow` from [‎c10/util/TypeCast.cpp](https://github.com/pytorch/pytorch/pull/194781/changes#diff-f214545d71bcddab19fa2ddf585ee75affd601a1000bd0c0eb6dfa9caf97d32c) to the headeronly file  [‎torch/headeronly/util/TypeCast.h](https://github.com/pytorch/pytorch/pull/194781/changes#diff-0b2e747623222ecc11300c97631f125a81d25151b34d0a14a352da7cf7c7b7d5) with `C10_NOINLINE`. This reverts some of your changes that you made on https://github.com/pytorch/pytorch/pull/194379 since `TORCH_CHECK` depends on libtorch. This includes reverting the `TORCH_CHECK` back to `std::runtime_error`, as well reverting some of  the changes you made in the test files [c10/test/core/Scalar_test.cpp](https://github.com/pytorch/pytorch/pull/194379/changes#diff-327bd1488eba8ae68bf4f93c405cad37727d87193902fbfd8240ba4a6081ad4e), [‎c10/test/util/safe_conv_test.cpp‎](https://github.com/pytorch/pytorch/pull/194781/changes#diff-0d987067a134009348be84a584d38ec2a95707328fa22a4f05e565a37be1ff25), [test/dynamo/test_nb_float.py‎](https://github.com/pytorch/pytorch/pull/194781/changes#diff-688734ed5b9001921a0d936564abd2d1236e4f135a080dc813c4367df6650bdb), and [‎test/dynamo/test_nb_int.py‎](https://github.com/pytorch/pytorch/pull/194781/changes#diff-d400ac2e853995571577a676118ab2b655862f39564de97203da3f54b5a37eb2) 

Please, let me know if this is going to cause any issues.

**Comment by cleonard530** [comment]
Hi @albanD, I am unable to merge this because of these 2 canceled jobs, are you able to rerun these for me?

**Comment by izaitsevfb** [comment]
@pytorchbot revert -m="breaks internal windows builds" -c="ghfirst"

please see the failure context below:


### MSVC `C2872: 'complex<double>': ambiguous symbol` in a downstream Windows build

MSVC 14.39.33519 (VS 17.9), CUDA 12.8, Windows x86_64, optimized. A TU that reaches
`checked_convert` via `c10/core/Scalar.h` fails to compile:
```
torch/headeronly/util/overflows.h(110): error C2872: 'complex<double>': ambiguous symbol
  ...\MSVC\14.39.33519\include\complex(1111): note: could be 'std::complex<double>'
  torch/headeronly/util/complex.h(148): note: or       'c10::complex<double>'
torch/headeronly/util/overflows.h(110): note: the template instantiation context (the oldest one first)
c10/core/Scalar.h(147): note: see reference to function template instantiation
    'To c10::checked_convert<uint8_t,c10::complex<double>>(From,const char *)' being compiled
```
That TU has `using namespace std;` at global scope, after its libtorch includes.
`overflows.h:108-113` is the body of the `is_complex` overload of `overflows()`:
```cpp
  return overflows<
             typename scalar_value_type<To>::type,
             typename From::value_type>(f.real(), strict_unsigned) ||
      overflows<
             typename scalar_value_type<To>::type,
             typename From::value_type>(f.imag(), strict_unsigned);
```
Line 110 contains no `complex` token. `From` is `c10::complex<double>` at the reported
instantiation.
The PR moved these templates from `namespace c10` into `namespace torch::headeronly`, and
every type name in `TypeCast.h` lost its `c10::` qualifier — `c10::complex<c10::Half>`
became `complex<Half>`. So `c10/util/TypeCast.h:175-183` became, at
`torch/headeronly/util/TypeCast.h:163`:
```cpp
struct static_cast_with_inter_type<complex<Half>, complex<double>> {
  C10_HOST_DEVICE static inline complex<Half> apply(complex<double> src) {
```
`complex.h:148` declares `struct alignas(sizeof(T) * 2) complex` inside `namespace c10`.
`complex.h:648-649` does `HIDDEN_NAMESPACE_BEGIN(torch, headeronly)` then
`using c10::complex;`, so inside `torch::headeronly` unqualified `complex` names
`c10::complex`.
`HIDDEN_NAMESPACE_BEGIN` (`torch/headeronly/macros/Macros.h:807-817`) expands differently
per platform. On `__GNUG__ && !_WIN32` it emits
`namespace torch { namespace headeronly __attribute__((visibility("hidden"))) {`;
otherwise — the MSVC/Windows path — `namespace torch::headeronly {`. So the namespace
holding the de-qualified names is opened through a different macro branch on the only
compiler that fails. Does that branch difference matter for name lookup here, or is the
bare `complex` spelling enough on its own to explain the ambiguity under MSVC?


## Next step
A reduced repro would settle it: one TU with `using namespace std;` that includes
`c10/core/Scalar.h` and instantiates
`c10::checked_convert<uint8_t, c10::complex<double>>`, built with MSVC 14.39.
The narrowest thing to try is re-qualifying the `complex` uses in
`torch/headeronly/util/TypeCast.h:112-273`, either as `torch::headeronly::complex<...>` —
matching that file's own convention for other symbols, e.g.
`torch::headeronly::unchecked_cast_to_int` at lines 77 and 106 — or by restoring the
pre-move `c10::` spelling.



Other MSVC C2872 reports against PyTorch headers: #173232, #188952.

**Comment by cleonard530** [comment]
@izaitsevfb, I haven't been able to recreate the build error you found locally, but I added the namespace prefixes everywhere I think the ambiguous symbol error may have come from. Now, the `torch::headeronly` prefix is used everywhere the `c10::` prefix was used before the migration, and for the 3 functions that were defined in both namespaces, `convert`, `checked_convert`, and `unsafe_wrapping_convert`, I went through and made sure the explicit namespace prefix was used for their calls. Please let me know if you are still having issues. 

cc @janeyx99

**Comment by izaitsevfb** [comment]
@cleonard530, I re-ran the failing builds internally, and one issue is fixed, but another one is still outstanding, see the details below:


A Windows CUDA build using nvcc 12.8 with MSVC still fails; it passes without this PR. Its sphericart-torch `autograd.cu` has file-scope `using namespace std;` after the libtorch includes.
```
autograd.cu
tmpxft_00001f54_00000000-10_autograd.compute_120a.cudafe1.cpp
torch/headeronly/util/overflows.h(109): error C2872: 'complex<double>': ambiguous symbol
  ...\MSVC\14.39.33519\include\complex(1111): note: could be 'std::complex<double>'
  torch/headeronly/util/complex.h(148): note: or       'c10::complex<double>'
torch/headeronly/util/overflows.h(109): note: the template instantiation context (the oldest one first) is
c10/core/Scalar.h(147): note: see reference to function template instantiation
    'To c10::checked_convert<unsigned char,c10::complex<double>>(From,const char *)' being compiled
c10/util/TypeCast.h(62): note: see reference to function template instantiation
    'bool torch::headeronly::overflows<unsigned char,c10::complex<double>>(From,bool)' being compiled
```
The split is by compile path: plain MSVC passes; nvcc-driven MSVC fails. `cudafe1.cpp` is nvcc-generated code compiled by MSVC.
Every `complex` in `torch/headeronly/util/TypeCast.h` is qualified. In `overflows.h`, the `is_complex<From>` overload still uses unqualified `is_complex<To>`, `scalar_value_type<To>` and recursive `overflows<...>`. Line 109 starts its two-call return and has no `complex` token.

**Comment by cleonard530** [comment]
Okay @izaitsevfb, with help from codex I was able to reproduce your error and this should hopefully fix it (it did on my end). 

When I first migrated over to the `headeronly` namespace there was an issue where existing downstream explicit specializations in the namespace `c10` became ill-formed, so I re-added these definitions back to the `c10` file. I should have just moved them to the `headeronly` files but declared the methods/structs in the `c10` namespace, then re-export them with using-declarations to the `headeronly` namespace. This is what I updates it to do now, and what is done in a few other files (e.g. `torch/headeronly/util/complex.h`). You can see the updates on the last commit: https://github.com/pytorch/pytorch/pull/194781/changes/1b1317dab693052d2aab00404972b4cfb3d240c2

cc @janeyx99

**Comment by izaitsevfb** [comment]
@cleonard530, thank you, it looks good now, all the previous build errors are gone.

**Review by izaitsevfb — APPROVED** [review]
