### ISSUE TITLE
Mac OS X build with Python 3.6 fails

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#3573]
One representative error:

```
torch/csrc/autograd/functions/init.cpp:220:37: error: address of overloaded function 'getTupleAttr' does not match required type '_object *(_object *, void *)'
  {(char*)"output_padding", (getter)getTupleAttr<ConvBackwardBackward, std::vector<int>, ConvParams,
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
torch/csrc/autograd/functions/init.cpp:82:11: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'Convert'
PyObject* getTupleAttr(PyObject* obj, void* _unused)
```

The cause of the problem is aa911939a328eff55c9b28b39ed3c43507ba8a2a:

```
   {(char*)"output_padding", (getter)getTupleAttr<ConvForward, std::vector<int>, ConvParams,
-                                         &ConvParams::output_padding, long, PyInt_FromLong>, NULL, NULL, NULL},
+                                         &ConvParams::output_padding, int64_t, PyInt_FromLong>, NULL, NULL, NULL},
```

It seems that on clang, changing the type parameter here is sufficient to cause template instantiation to fail.

Maybe the easiest way to fix this is to write a more portable version of PyInt_FromLong (and friends) which always returns `int64_t`.
