### ISSUE TITLE
Unable to compile in Mac High Sierra 10.13.2

### ISSUE THREAD

**Issue by linzhiqiu** [pytorch/pytorch#4680]
I am using Mac OSX High Sierra 10.13.2, and I followed the instruction on the front page to install, but I failed when I run the setup.py using "MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install".( I also tried "MACOSX_DEPLOYMENT_TARGET=10.13 CC=clang CXX=clang++ python setup.py install", but it doesn't seem to resolve the issue).

The errors that I am getting seem to be unknown type issue and they look like this: 
"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/resource.h:196:2: error: 
      unknown type name 'uint8_t'
        uint8_t  ri_uuid[16];"

I have attached the entire log here.
[output.txt](https://github.com/pytorch/pytorch/files/1634615/output.txt)

**Comment by zou3519** [comment]
A quick google search got me [this stackoverflow post](https://stackoverflow.com/questions/46872922/broken-c-std-libraries-on-macos-high-sierra-10-13) that could be relevant. It sounds like your `stdint.h` isn't being found. Do any of the workarounds in that post help?

**Comment by linzhiqiu** [comment]
Thanks! It solves my problem!
