### ISSUE TITLE
AttributeError: module 'torch.jit' has no attribute 'unused'

### ISSUE THREAD

**Issue by haruiz** [pytorch/pytorch#26608]
## 🐛 Bug

Error using the pytorch.hub API:
code:
```
entrypoints = torch.hub.list('pytorch/vision', force_reload=True)
```

```
Downloading: "https://github.com/pytorch/vision/archive/master.zip" to .../.cache\torch\hub\master.zip
Traceback (most recent call last):
  File "..../test.py", line 2, in <module>
    entrypoints = torch.hub.list('pytorch/vision', force_reload=True)
  File "...\.conda\envs\hackaton\lib\site-packages\torch\hub.py", line 285, in list
    hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
  File "..\.conda\envs\hackaton\lib\site-packages\torch\hub.py", line 72, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".../.cache\torch\hub\pytorch_vision_master/hubconf.py", line 4, in <module>
    from torchvision.models.alexnet import alexnet
  File "..../.cache\torch\hub\pytorch_vision_master\torchvision\__init__.py", line 1, in <module>
    from torchvision import models
  File "...../.cache\torch\hub\pytorch_vision_master\torchvision\models\__init__.py", line 6, in <module>
    from .densenet import *
  File "...../.cache\torch\hub\pytorch_vision_master\torchvision\models\densenet.py", line 22, in <module>
    class _DenseLayer(nn.Module):
  File ".../.cache\torch\hub\pytorch_vision_master\torchvision\models\densenet.py", line 52, in _DenseLayer
    @torch.jit.unused  # noqa: T484
AttributeError: module 'torch.jit' has no attribute 'unused'

Process finished with exit code 1
```

cc @ezyang @gchanan @zou3519 @ailzhang @suo

**Comment by suo** [comment]
@eellison, @fmassa: it appears we're using unreleased features (`torch.jit.unused`) in torchvision master.

**Comment by suo** [comment]
@haruiz, a workaround is to install the pytorch nightly.

**Comment by haruiz** [comment]
@suo , that is actually what I did, using the nightly version works, thanks

**Comment by fmassa** [comment]
Torchvision master is not expected to work with PyTorch 1.2 or earlier. I think the collab examples should use a pinned version of torchvision instead

**Comment by haruiz** [comment]
@fmassa , then you guys should update also the documentation, please see the image below:

![2019-09-22_13-18-01](https://user-images.githubusercontent.com/3827551/65392563-d94caa80-dd3b-11e9-854d-33fd9e8075b5.png)

**Comment by ezyang** [comment]
Declassifying from jit, this is a packaging problem

**Comment by fmassa** [comment]
This is not a packaging problem. TorchHub always use the master version of the cloned repo by default. The examples should be updated, the packaging are correct I believe

**Comment by ezyang** [comment]
Reclassifying as hub. But it seems to me that it's not just an examples issue: hub should know what versions models are compatible with?

**Comment by colesbury** [comment]
cc @ailzhang -- I also reported this on https://github.com/pytorch/hub/issues/55

**Comment by ailzhang** [comment]
`entrypoints = torch.hub.list('pytorch/vision', force_reload=True)` loads from vision master which depends on pytorch master. I think `entrypoints = torch.hub.list('pytorch/vision:v0.4.0', force_reload=True)` should work. Hub CI tests against latest pytorch & vision conda releases. 
I agree it's good to annotate the current stable releases for these repos...

**Comment by VitalyFedyunin** [comment]
Should we move such issue into the hub, instead of keeping them duplicated?

**Comment by ailzhang** [comment]
I'll close this one and track in the hub issue. I'm thinking about what's the best way to track stable release in webpage. If you have ideas, please let me know!

**Comment by dxw1997** [comment]
AttributeError: module 'torch.jit' has no attribute '_script_if_tracing'
This is a similar problem , do you know how to solve it? The detailed information
are listed.
      4   raise RuntimeError('Cannot run this cell without GPU runtime.')
      5 
----> 6 gpu_model = torch.hub.load('pytorch/vision', 'resnet50', pretrained=True)
      7 gpu_model.eval()
      8 gpu_model = gpu_model.to('cuda')

10 frames
/root/.cache/torch/hub/pytorch_vision_master/torchvision/ops/boxes.py in <module>()
     40 
     41 
---> 42 @torch.jit._script_if_tracing
     43 def batched_nms(
     44     boxes: Tensor,

**Comment by Strivathsavashwin** [comment]
Hi,

I am running the python script in Spyder using Anaconda command prompt. I am getting the same error module 'torch.jit' has no attribute 'unused'

**Comment by jacatarino** [comment]
I had the same problem and I tried to run _conda update pytorch torchvision_ and it worked for me.
