### ISSUE TITLE
torch.cuda.amp.autocast not working with torchvision.models.detection.maskrcnn

### ISSUE THREAD

**Issue by WaterKnight1998** [pytorch/pytorch#37735]
## 🐛 Bug

I am converting the model into FP16.

Using `torch.cuda.amp.autocast`. But it throws me an error:

```
~/Documents/test/seg/models/archs/mask_rcnn.py in mixed_precision_one_batch(self, i, b)
    186         with autocast():
    187             self.model.train()
--> 188             loss_dict = self.model(images,targets)
    189             if not self.training:
    190                 self.model.eval()

~/anaconda3/envs/seg/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    556             result = self._slow_forward(*input, **kwargs)
    557         else:
--> 558             result = self.forward(*input, **kwargs)
    559         for hook in self._forward_hooks.values():
    560             hook_result = hook(self, input, result)

~/anaconda3/envs/seg/lib/python3.7/site-packages/torchvision/models/detection/generalized_rcnn.py in forward(self, images, targets)
     68         if isinstance(features, torch.Tensor):
     69             features = OrderedDict([('0', features)])
---> 70         proposals, proposal_losses = self.rpn(images, features, targets)
     71         detections, detector_losses = self.roi_heads(features, proposals, images.image_sizes, targets)
     72         detections = self.transform.postprocess(detections, images.image_sizes, original_image_sizes)

~/anaconda3/envs/seg/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    556             result = self._slow_forward(*input, **kwargs)
    557         else:
--> 558             result = self.forward(*input, **kwargs)
    559         for hook in self._forward_hooks.values():
    560             hook_result = hook(self, input, result)

~/anaconda3/envs/seg/lib/python3.7/site-packages/torchvision/models/detection/rpn.py in forward(self, images, features, targets)
    486         proposals = self.box_coder.decode(pred_bbox_deltas.detach(), anchors)
    487         proposals = proposals.view(num_images, -1, 4)
--> 488         boxes, scores = self.filter_proposals(proposals, objectness, images.image_sizes, num_anchors_per_level)
    489 
    490         losses = {}

~/anaconda3/envs/seg/lib/python3.7/site-packages/torchvision/models/detection/rpn.py in filter_proposals(self, proposals, objectness, image_shapes, num_anchors_per_level)
    408             boxes, scores, lvl = boxes[keep], scores[keep], lvl[keep]
    409             # non-maximum suppression, independently done per level
--> 410             keep = box_ops.batched_nms(boxes, scores, lvl, self.nms_thresh)
    411             # keep only topk scoring predictions
    412             keep = keep[:self.post_nms_top_n()]

~/anaconda3/envs/seg/lib/python3.7/site-packages/torchvision/ops/boxes.py in batched_nms(boxes, scores, idxs, iou_threshold)
     73     offsets = idxs.to(boxes) * (max_coordinate + 1)
     74     boxes_for_nms = boxes + offsets[:, None]
---> 75     keep = nms(boxes_for_nms, scores, iou_threshold)
     76     return keep
     77 

~/anaconda3/envs/seg/lib/python3.7/site-packages/torchvision/ops/boxes.py in nms(boxes, scores, iou_threshold)
     33         by NMS, sorted in decreasing order of scores
     34     """
---> 35     return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
     36 
     37 

RuntimeError: Unrecognized tensor type ID: Autocast
```

cc @ngimel

**Comment by ngimel** [comment]
cc @mcarilli

**Comment by mcarilli** [comment]
> RuntimeError: Unrecognized tensor type ID: Autocast

That’s a strange error. If you’re using a Pytorch build new enough to support autocast, AutocastTensorId should be present in the backend. If you’re not, I’d expect a different error, sooner (torch.cuda.amp.autocast should not be available in Python to begin with).

What version of Pytorch are you using?

**Comment by WaterKnight1998** [comment]
@mcarilli This is the version:

```
import torchvision
print(torch.__version__)
print(torchvision.__version__)```
```

1.6.0.dev20200421
0.7.0a0+6e47842
```

**Comment by mcarilli** [comment]
Looking at source of torch.nn.Module, it appears [_slow_forward](https://github.com/pytorch/pytorch/blob/5ec87a3c1a6acfb0eb4704873649ffcd7e65c221/torch/nn/modules/module.py#L533) path is only taken when jit tracing is enabled.  Are you using jit tracing explicitly in your script?

**Comment by WaterKnight1998** [comment]
> 
> 
> Looking at source of torch.nn.Module, it appears [_slow_forward](https://github.com/pytorch/pytorch/blob/5ec87a3c1a6acfb0eb4704873649ffcd7e65c221/torch/nn/modules/module.py#L533) path is only taken when jit tracing is enabled. Are you using jit tracing explicitly in your script?

@mcarilli I don't know if it is inside the model. I think that it saw in source code.

I am using the Mask-RCNN implementation from torchvision. 
Here is the [docs](https://pytorch.org/docs/stable/torchvision/models.html#mask-r-cnn).

And the source code is in [here](https://github.com/pytorch/vision/blob/master/torchvision/models/detection/mask_rcnn.py)

**Comment by WaterKnight1998** [comment]
> 
> 
> > Looking at source of torch.nn.Module, it appears [_slow_forward](https://github.com/pytorch/pytorch/blob/5ec87a3c1a6acfb0eb4704873649ffcd7e65c221/torch/nn/modules/module.py#L533) path is only taken when jit tracing is enabled. Are you using jit tracing explicitly in your script?
> 
> @mcarilli I don't know if it is inside the model. I think that it saw in source code.
> 
> I am using the Mask-RCNN implementation from torchvision.
> Here is the [docs](https://pytorch.org/docs/stable/torchvision/models.html#mask-r-cnn).
> 
> And the source code is in [here](https://github.com/pytorch/vision/blob/master/torchvision/models/detection/mask_rcnn.py)

**Comment by WaterKnight1998** [comment]
@mcarilli have you discovered something?

**Comment by xwang233** [comment]
I tried some repro here https://github.com/xwang233/code-snippet/tree/master/mask-rcnn-37735. I get the same error message in 4/21 nightly build of pytorch and torchvision. 

The error appears to be gone in 6/22 nightly build of pytorch and torchvision, but it yields a different error message. Here is the backtrace
```
$ python repro.py
1.6.0a0+18122fa
0.7.0a0+42aa9b2
/home/xwang/Developer/pytorch/torch/nn/functional.py:3000: UserWarning: The default behavior for interpolate/upsample with float scale_factor will change in 1.6.0 to align with other frameworks/libraries, and use scale_factor directly, instead of relying on the computed output size. If you wish to keep the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor will change "
/home/xwang/Developer/vision/torchvision/ops/boxes.py:102: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  ../torch/csrc/utils/python_arg_parser.cpp:766.)
  keep = keep.nonzero().squeeze(1)
Traceback (most recent call last):
  File "repro.py", line 44, in <module>
    loss_dict = model(d, tds)
  File "/home/xwang/Developer/pytorch/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xwang/Developer/vision/torchvision/models/detection/generalized_rcnn.py", line 99, in forward
    detections, detector_losses = self.roi_heads(features, proposals, images.image_sizes, targets)
  File "/home/xwang/Developer/pytorch/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xwang/Developer/vision/torchvision/models/detection/roi_heads.py", line 752, in forward
    box_features = self.box_roi_pool(features, proposals, image_shapes)
  File "/home/xwang/Developer/pytorch/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xwang/Developer/vision/torchvision/ops/poolers.py", line 222, in forward
    spatial_scale=scale, sampling_ratio=self.sampling_ratio)
  File "/home/xwang/Developer/vision/torchvision/ops/roi_align.py", line 45, in roi_align
    sampling_ratio, aligned)
RuntimeError: Expected tensor for argument #1 'input' to have the same type as tensor for argument #2 'rois'; but type torch.cuda.HalfTensor does not equal torch.cuda.FloatTensor (while checking arguments for ROIAlign_forward_cuda)
```

@mcarilli has more information.

**Comment by mcarilli** [comment]
The new backtrace makes sense:  some C++ function is receiving mismatched arguments.  I'll track down the implementation.  If it's a custom autograd function, we'll need to apply a custom function decorator.  If it's a torch backend function, I'll need to add it to the Amp promote list, or possibly the FP32 list or FP16 list, if the op has a preferred precision.  @fmassa do you know if this op has a preferred precision?

**Comment by mcarilli** [comment]
After discussion with @ezyang we have a tentative plan to fix. Ed is laying the foundation in https://github.com/pytorch/vision/pull/2366, which updates `roi_align` to allow Pytorch's internal dispatcher to select different code paths.  The dispatcher knows about autocast, so I can register a code path that casts inputs if autocast is active, if @fmassa confirms this is a sensible approach.

The fix will be in torchvision, not pytorch, therefore torchvision-specific.  Other external libs that use the new-style C++ registration API may still break with autocast, and it's unclear what a generally autocast-safe registration API might look like.  However, a quick-and-dirty torchvision-specific fix is probably the best we can do for 1.6 and it's not the end of the world:
- I expect few external libs use the new-style registrations yet.
- the work gives us (meaning mostly Ed) a clear example of what external libs need for native-like interaction with the dispatcher.  Hacking on it helps inform registration API improvements.

**Comment by fmassa** [comment]
This approach seems good to me

**Comment by fmassa** [comment]
@mcarilli also note that we might need to change `nms` as well, but it should be easy as there is no gradients assigned to it so it should be simpler to use the new registration mechanism

**Comment by mcarilli** [comment]
@WaterKnight1998 Fix was merged.  Can you try your code again with the latest torchvision?

**Comment by JosueCom** [comment]
I just ran some code with the latest version of pytorch and I am getting the following error still:

```python
     84         if amp_enable:
---> 85             with th.cuda.amp.autocast():
     86                 out1 = model(sub, inp)
     87                 out2 = temp_ly(sub, out1)

AttributeError: module 'torch.cuda.amp' has no attribute 'autocast'
```

**Comment by mcarilli** [comment]
Autocast is not available in 1.5 or 1.5.1.

**Comment by JosueCom** [comment]
> 
> 
> Autocast is not available in 1.5 or 1.5.1.

Thank you. Just found out recently. Had to download the nightly version. But, I believe it was recently brought to the stable version a few days ago

**Comment by gioipv** [comment]
There is still not available in 1.5 or 1.5.1.

**Comment by iegorval** [comment]
I have the same error: `RuntimeError: Unrecognized tensor type ID: Autocast`.

`torch==1.9.0+cu111
torchaudio==0.9.0
torchvision==0.10.0+cu111`

I have tried to use different torch versions, but they did not work with my Cuda 11.1. Is there any other way to fix it, or some version that works with Cuda 11.1, but does not give this error? Thanks.

**Comment by JosueCom** [comment]
> I have the same error: `RuntimeError: Unrecognized tensor type ID: Autocast`.
> 
> `torch==1.9.0+cu111`
> 
> `torchaudio==0.9.0`
> 
> `torchvision==0.10.0+cu111`
> 
> I have tried to use different torch versions, but they did not work with my Cuda 11.1. Is there any other way to fix it, or some version that works with Cuda 11.1, but does not give this error? Thanks.

Do you get any other error with it?

**Comment by jimmYA-1995** [comment]
I also get the same error in my custom cpp extension decorated with autocast. The error happened when I change ngc image version from `pytorch-21.02-py3:latest` to `pytorch-21.06-py3:latest`. In 21.06 version, `CUDA==11.3`, `torch==1.9.0a0+c3d40fd`, `torchvision==0.10.0a0`. 

It works after I clean the old extension caches.
