### PR TITLE
[Caffe2] GCC-7 doesn't like the original syntax.

### LINKED ISSUE #7881: [Caffe2] CUDA 9.2 and gcc 7.3.1
## Issue description

CUDA 9.2 is now listing gcc-7.3.1 in its supported compiler.
Use it for several CUDA projects, including Caffe1, and works well.

A PR is created to adjust the cmake restriction: #7880 

However in Caffe2 we're getting some errors in operator headers like
```
GetSingleArgument is not a member of OperatorBase
```
Seems nvcc has some compile errors inside template function.
The same commit works with gcc-6.3.1.
Any idea?

## System Info

- PyTorch or Caffe2: Caffe2
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): cmake
- OS: CentOS-7
- PyTorch version: master
- CUDA version: 9.2
- GPU models and configuration: 1080Ti
- GCC version (if compiling from source): 7.3.1 from devtoolset-7
- CMake version: 3.11.2

### PR DESCRIPTION
**Pull request by xkszltl**
Replace with "this->template f<T>()".

Fix #7881

### CODE REVIEW

**Comment by xkszltl** [comment]
Also recommend add gcc7-CUDA build.

**Review by ezyang — APPROVED** [review]

**Comment by xkszltl** [comment]
Any concern on merging this?
That me know if there's any update needed.

Thanks
