### ISSUE TITLE
Error when building with USE_DISTRIBUTED=0

### ISSUE THREAD

**Issue by Lezcano** [pytorch/pytorch#77766]
### 🐛 Describe the bug

Doing `import torch` throws:

```
Traceback (most recent call last):
  File "test/test_public_bindings.py", line 4, in <module>
    from torch.testing._internal.common_utils import TestCase, run_tests, IS_WINDOWS
  File "/home/lezcano/git/pytorch/pytorch/torch/__init__.py", line 780, in <module>
    from .functional import *  # noqa: F403
  File "/home/lezcano/git/pytorch/pytorch/torch/functional.py", line 7, in <module>
    import torch.nn.functional as F
  File "/home/lezcano/git/pytorch/pytorch/torch/nn/__init__.py", line 3, in <module>
    from .parallel import DataParallel
  File "/home/lezcano/git/pytorch/pytorch/torch/nn/parallel/__init__.py", line 5, in <module>
    from .distributed import DistributedDataParallel
  File "/home/lezcano/git/pytorch/pytorch/torch/nn/parallel/distributed.py", line 21, in <module>
    from torch.distributed.utils import (
  File "/home/lezcano/git/pytorch/pytorch/torch/distributed/utils.py", line 121, in <module>
    process_group: dist.ProcessGroup,
AttributeError: module 'torch.distributed' has no attribute 'ProcessGroup'
```

The flags I'm using
```
export BUILD_TEST=0
export BUILD_CAFFE2=0
export USE_CUDA=1
export USE_XNNPACK=1
export USE_KINETO=1
export USE_DISTRIBUTED=0
export USE_NCCL=0
export USE_PRECOMPILED_HEADERS=0
export TORCH_CUDA_ARCH_LIST="7.5"
export USE_GOLD_LINKER=1
export CMAKE_BUILD_TYPE=RelWithDebInfo
export DEBUG=0
```

### Versions

master

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501 @malfet @seemethere

**Comment by pritamdamania87** [comment]
@rohan-varma This seems to be broken by https://github.com/pytorch/pytorch/pull/77492 when compiling with `USE_DISTRIBUTED=0`.

**Comment by pritamdamania87** [comment]
Oh looks like this is a duplicate of https://github.com/pytorch/pytorch/issues/77704 and fixed by https://github.com/pytorch/pytorch/pull/77727. 

@Lezcano Can you rebase past https://github.com/pytorch/pytorch/pull/77727 and see if that resolves your issue too?

**Comment by Lezcano** [comment]
Yup, that fixes it, thanks!
