### ISSUE TITLE
Missing TORCH_VERSION_2_12_0 guard to torch_from_blob_v2 implementation

### ISSUE THREAD

**Issue by cluePrints** [pytorch/pytorch#176133]
### 🐛 Describe the bug

Local builds on my Mac fail. Looks to be caused by #175089

Repro
```
git checkout 62a71f1481a
pip install -e . -v --no-build-isolation
```
<details>
<summary>build error: shim_common.cpp:700:34: error: no previous prototype for function 'torch_from_blob_v2'</summary>

```
    /Users/ivansobolev/Downloads/pytorch/torch/csrc/shim_common.cpp:700:34: error: no previous prototype for function 'torch_from_blob_v2' [-Werror,-Wmissing-prototypes]                                                                      
      700 | AOTI_TORCH_EXPORT AOTITorchError torch_from_blob_v2(                                                                                                                                                                               
          |                                  ^                                                                                                                                                                                                 
    /Users/ivansobolev/Downloads/pytorch/torch/csrc/shim_common.cpp:700:19: note: declare 'static' if the function is not intended to be used outside of this translation unit                                                                 
      700 | AOTI_TORCH_EXPORT AOTITorchError torch_from_blob_v2(                                                                                                                                                                               
          |                   ^                                                                                                                                                                                                                
          |                   static                                                                                                                                                                                                           
    1 error generated. 
```

Last lines from the log:
https://gist.github.com/cluePrints/060096442c9be94de40142a30e17b94b


</details>

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 26.3 (arm64)
GCC version: Could not collect
Clang version: 17.0.0 (clang-1700.6.3.2)
CMake version: version 4.2.0
Libc version: N/A

Python version: 3.13.11 | packaged by Anaconda, Inc. | (main, Dec 10 2025, 21:21:08) [Clang 20.1.8 ] (64-bit runtime)
Python platform: macOS-26.3-arm64-arm-64bit-Mach-O
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
Is XPU available: N/A
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A
Caching allocator config: N/A

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] No relevant packages
[conda] No relevant packages

cc @malfet @seemethere @aditvenk
