### PR TITLE
Fix MultiThreadedTestCase for destroy_process_group

### PR DESCRIPTION
**Pull request by H-Huang**
Fixes #175065

Some tests fail with `AttributeError: 'ThreadLocalWorld' object has no attribute 'comms'` during `destroy_process_group()`

## Changes

`ThreadLocalWorld` is used by multi threaded pg (which is used by `MultiThreadedTestCase`) to allow each rank/thread to have its own independent view of the `_World` state. https://github.com/pytorch/pytorch/pull/174202 Updated `_World` to add a `comms` property, so we need to mirror this in the multithreaded pg.

## Follow ups
1. Not sure why this test wasn't captured in the trunk CI, everything was green in the offending PR.
2. We can make this more robust by deleting the `WorldData` class and directly referencing `_World()`. This is a more involved change where we also need to update some parts of distributed_c10d to turn the module-level globals (i.e. `_pg_map`, `_pg_names`, etc.) to become instance attributes on `_World`

Stack from [ghstack](https://github.com/ezyang/ghstack/tree/0.13.0) (oldest at bottom):
* __->__ #175175

### CODE REVIEW

**Review by d4l3k — APPROVED** [review]
LGTM thanks for fixing this!

**Comment by d4l3k** [comment]
Ah, maybe land the other one

**Comment by H-Huang** [comment]
will wait on https://github.com/pytorch/pytorch/pull/175099 to land!
