### PR TITLE
[1/N] Remove inclusion of ATen/core/Array.h

### PR DESCRIPTION
**Pull request by cyyever**
The functionality of Array.h is largely overlapped with std::array and it should be safe to use std::array instead.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Do you remember why Array.h was added in the first place? c++17 backport?

**Comment by cyyever** [comment]
> Do you remember why Array.h was added in the first place? c++17 backport?

I don't know, but I guess it is before C++14 was adopted?

**Comment by cyyever** [comment]
@ezyang CUDA 12.1 ptx keeps crashing after these changes. It seems that we have to delay the merge.

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change, but lots of compilation errors show up after this lands' -c landrace

For example, 

inductor/test_minifier.py::MinifierTests::test_accuracy_vs_strict_accuracy [GH job link](https://github.com/pytorch/pytorch/actions/runs/11884131022/job/33112671696) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/486b9aaa67a02807aea06f33c009b5311caab337)
