### PR TITLE
Back out "fix: make sure `sorter` indices are inbound in `searchsorted` (#94863)"

### PR DESCRIPTION
**Pull request by weiwangmeta**
Summary:
Original commit changeset: 96a2200d1fd8

Original Phabricator Diff: D43342962

Test Plan: Sandcastle and land castle as well as buck2 build mode/opt //frl/et/projects/Masquerade/stable/datasets/masquerade/c6p7:post_processing

Reviewed By: seemethere, bigfootjon

Differential Revision: D43402398

@bypass-github-export-checks

### CODE REVIEW

**Review by bigfootjon — APPROVED** [review]
Mirroring my fbsource review

**Comment by ganler** [comment]
Hi @weiwangmeta @bigfootjon Can you kindly let me know the reason for reverting? Thanks!

**Comment by weiwangmeta** [comment]
> Internal build errors
> 
> ```
> fbcode/caffe2/aten/src/ATen/native/BucketizationUtils.h(139): error: expected an identifier
> fbcode/caffe2/aten/src/ATen/native/BucketizationUtils.h(139): error: identifier "vmin" is undefined
> fbcode/caffe2/aten/src/ATen/native/BucketizationUtils.h(139): error: identifier "vmax" is undefined
> ```

fbcode/caffe2 == pytorch here.
