### ISSUE TITLE
Compilation errors on master, Ubuntu 17.10, CUDA 9, GCC 6.4 / GCC 5.4.1

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#5136]
Probably similar to https://github.com/pytorch/pytorch/issues/3963 and https://github.com/pytorch/pytorch/issues/3807, but this time in `ATen_generated_TensorCompare.cu.o` and with more errors.

The machine is clean, no previous versions of PyTorch are present. Full log in attachment:
[log.txt](https://github.com/pytorch/pytorch/files/1708254/log.txt)

Main error types are:
```
.../pytorch/torch/lib/build/aten/src/ATen/ATen/Functions.h:1635:61:   required from here
/usr/include/c++/6/tuple:489:65: error: mismatched argument pack lengths while expanding ‘std::is_convertible<_UElements&&, _Elements>’
       return __and_<is_convertible<_UElements&&, _Elements>...>::value;

.../pytorch/torch/lib/build/aten/src/ATen/ATen/Functions.h:1635:61:   required from here
/usr/include/c++/6/tuple:495:244: error: wrong number of template arguments (4, should be 2)
       return  __and_<__not_<is_same<tuple<_Elements...>,
```

Something is wrong about using `tuple`

**Comment by vadimkantorov** [comment]
Downgrading to `apt install gcc-5 g++-5 && export CC=gcc-5 && export CXX=g++-5` gets to different errors on `std::to_string`, `std::isnan`, `std::isinf` missing:

<details>
[ 46%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_TensorCompare.cu.o
.../pytorch/aten/src/ATen/Half.h(28): error: namespace "std" has no member "isinf"

.../pytorch/aten/src/ATen/Half.h(31): error: namespace "std" has no member "isnan"

.../pytorch/aten/src/ATen/Half.h(42): error: namespace "std" has no member "to_string"

3 errors detected in the compilation of "/tmp/tmpxft_00001dae_00000000-4_CUDAHalf.cpp4.ii".
CMake Error at ATen_generated_CUDAHalf.cu.o.cmake:267 (message):
  Error generating file
  .../pytorch/torch/lib/build/aten/src/ATen/CMakeFiles/ATen.dir/cuda/./ATen_generated_CUDAHalf.cu.o


src/ATen/CMakeFiles/ATen.dir/build.make:1134: recipe for target 'src/ATen/CMakeFiles/ATen.dir/cuda/ATen_generated_CUDAHalf.cu.o' failed
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/cuda/ATen_generated_CUDAHalf.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
.../pytorch/aten/src/ATen/Half.h(42): error: namespace "std" has no member "to_string"

.../pytorch/aten/src/ATen/Half.h(28): error: namespace "std" has no member "isinf"
          detected during instantiation of "To at::checked_convert<To,From>(From, const char *) [with To=uint8_t, From=double]" 
.../pytorch/aten/src/ATen/Scalar.h(61): here

.../pytorch/aten/src/ATen/Half.h(31): error: namespace "std" has no member "isnan"
          detected during instantiation of "To at::checked_convert<To,From>(From, const char *) [with To=uint8_t, From=double]" 
.../pytorch/aten/src/ATen/Scalar.h(61): here

3 errors detected in the compilation of "/tmp/tmpxft_00001dc2_00000000-6_IndexUtils.cpp1.ii".
CMake Error at ATen_generated_IndexUtils.cu.o.cmake:267 (message):
  Error generating file
  .../pytorch/torch/lib/build/aten/src/ATen/CMakeFiles/ATen.dir/cuda/detail/./ATen_generated_IndexUtils.cu.o


src/ATen/CMakeFiles/ATen.dir/build.make:1127: recipe for target 'src/ATen/CMakeFiles/ATen.dir/cuda/detail/ATen_generated_IndexUtils.cu.o' failed
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/cuda/detail/ATen_generated_IndexUtils.cu.o] Error 1
.../pytorch/aten/src/ATen/Half.h(42): error: namespace "std" has no member "to_string"

.../pytorch/aten/src/ATen/Half.h(28): error: namespace "std" has no member "isinf"
          detected during instantiation of "To at::checked_convert<To,From>(From, const char *) [with To=uint8_t, From=double]" 
.../pytorch/aten/src/ATen/Scalar.h(61): here

.../pytorch/aten/src/ATen/Half.h(31): error: namespace "std" has no member "isnan"
          detected during instantiation of "To at::checked_convert<To,From>(From, const char *) [with To=uint8_t, From=double]" 
.../pytorch/aten/src/ATen/Scalar.h(61): here

.../pytorch/aten/src/ATen/Half.h(42): error: namespace "std" has no member "to_string"

.../pytorch/aten/src/ATen/Half.h(28): error: namespace "std" has no member "isinf"
          detected during instantiation of "To at::checked_convert<To,From>(From, const char *) [with To=uint8_t, From=double]" 
.../pytorch/aten/src/ATen/Scalar.h(61): here

.../pytorch/aten/src/ATen/Half.h(31): error: namespace "std" has no member "isnan"
          detected during instantiation of "To at::checked_convert<To,From>(From, const char *) [with To=uint8_t, From=double]" 
.../pytorch/aten/src/ATen/Scalar.h(61): here

3 errors detected in the compilation of "/tmp/tmpxft_00001e1d_00000000-6_Distributions.cpp1.ii".
CMake Error at ATen_generated_Distributions.cu.o.cmake:267 (message):
  Error generating file
  .../pytorch/torch/lib/build/aten/src/ATen/CMakeFiles/ATen.dir/native/cuda/./ATen_generated_Distributions.cu.o


src/ATen/CMakeFiles/ATen.dir/build.make:1141: recipe for target 'src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_Distributions.cu.o' failed
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_Distributions.cu.o] Error 1
.../pytorch/aten/src/ATen/native/cuda/Embedding.cu(36): warning: function "__any"
/usr/local/cuda/include/device_atomic_functions.h(180): here was declared deprecated ("__any() is deprecated in favor of __any_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")

.../pytorch/aten/src/ATen/Half.h(42): error: namespace "std" has no member "to_string"

.../pytorch/aten/src/ATen/Half.h(28): error: namespace "std" has no member "isinf"
          detected during instantiation of "To at::checked_convert<To,From>(From, const char *) [with To=uint8_t, From=double]" 
.../pytorch/aten/src/ATen/Scalar.h(61): here

.../pytorch/aten/src/ATen/Half.h(31): error: namespace "std" has no member "isnan"
          detected during instantiation of "To at::checked_convert<To,From>(From, const char *) [with To=uint8_t, From=double]" 
.../pytorch/aten/src/ATen/Scalar.h(61): here

3 errors detected in the compilation of "/tmp/tmpxft_00001e29_00000000-6_TensorCompare.cpp1.ii".
CMake Error at ATen_generated_TensorCompare.cu.o.cmake:267 (message):
  Error generating file
  .../pytorch/torch/lib/build/aten/src/ATen/CMakeFiles/ATen.dir/native/cuda/./ATen_generated_TensorCompare.cu.o


src/ATen/CMakeFiles/ATen.dir/build.make:1155: recipe for target 'src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_TensorCompare.cu.o' failed
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_TensorCompare.cu.o] Error 1
3 errors detected in the compilation of "/tmp/tmpxft_00001e3c_00000000-6_Embedding.cpp1.ii".
CMake Error at ATen_generated_Embedding.cu.o.cmake:267 (message):
  Error generating file
  .../pytorch/torch/lib/build/aten/src/ATen/CMakeFiles/ATen.dir/native/cuda/./ATen_generated_Embedding.cu.o


src/ATen/CMakeFiles/ATen.dir/build.make:1148: recipe for target 'src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_Embedding.cu.o' failed
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_Embedding.cu.o] Error 1
CMakeFiles/Makefile2:194: recipe for target 'src/ATen/CMakeFiles/ATen.dir/all' failed
make[1]: *** [src/ATen/CMakeFiles/ATen.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
</details>

**Comment by vadimkantorov** [comment]
As a workaround, to make it compile with g++-5.4.1 I had to add this on top of `aten/src/ATen/Half.h`:
```cpp
#include <sstream>
namespace std {
        using ::isnan;
        using ::isinf;

        template < typename T > std::string to_string( const T& n )
        {
                std::ostringstream stm;
                stm<<n;
                return stm.str();
        }
}

```

**Comment by sdmonov** [comment]
I didn't had much chance to debug the original issue with gcc 6.4 but I debugged gcc 5.4 and the reason of the failure is that there is apparently a bug in Ubuntu 17.10 where _GLIBCXX_USE_C99 is not set in /usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h in package libstdc++-5-dev. This leads to the issue with gcc 5.4. This is the bug in launchpad https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1725848 and it is in status "Won't Fix" as gcc 5 is considered very outdated and not supported any more. The only solution I found for now is to use gcc 4.8 which works for me:

sudo apt-get install gcc-4.8 g++-4.8
export CC=gcc-4.8
export CXX=g++-4.8

I think it would be good if we check in CMake if the gcc-5 is used under Ubuntu 17.10 and show a meaningful error similar to https://github.com/caffe2/caffe2/issues/1633 which is essentially same problem under caffee2. I'll work on this.

**Comment by Abrosimov-a-a** [comment]
Successfully builded on Debian Buster with:
CUDA = 9.0
gcc g++ = 4.8

**Comment by ahmed-shariff** [comment]
I also had to use gcc, g++-4.8 on arch linux to successfully build.

cuda: 9.1
cudnn: 7

**Comment by hsed** [comment]
I can't seem to get it working with gcc/g++-4.8. I'm using Ubunutu 17.10/ CUDA 9 / CuDNN 7.
I'm only using pyenv instead of conda but i don't think that should be much different apart from no magma (which I don't mind).
Compilation stops at about 45% with the following errors:
```
    /tmp/pip-osju86eo-build/aten/src/ATen/Half.h(42): error: namespace "std" has no member "to_string"

    /tmp/pip-osju86eo-build/aten/src/ATen/Half.h(28): error: namespace "std" has no member "isinf"
              detected during instantiation of "To at::checked_convert<To,From>(From, const char *) [with To=uint8_t, From=double]"
    /tmp/pip-osju86eo-build/aten/src/ATen/Scalar.h(61): here

    /tmp/pip-osju86eo-build/aten/src/ATen/Half.h(31): error: namespace "std" has no member "isnan"
              detected during instantiation of "To at::checked_convert<To,From>(From, const char *) [with To=uint8_t, From=double]"
    /tmp/pip-osju86eo-build/aten/src/ATen/Scalar.h(61): here

    3 errors detected in the compilation of "/tmp/tmpxft_0000129a_00000000-10_IndexUtils.compute_70.cpp1.ii".
    CMake Error at ATen_generated_IndexUtils.cu.o.cmake:267 (message):
      Error generating file
      /tmp/pip-osju86eo-build/torch/lib/build/aten/src/ATen/CMakeFiles/ATen.dir/cuda/detail/./ATen_generated_IndexUtils.cu.o


    src/ATen/CMakeFiles/ATen.dir/build.make:1134: recipe for target 'src/ATen/CMakeFiles/ATen.dir/cuda/detail/ATen_generated_IndexUtils.cu.o' failed
    make[2]: *** [src/ATen/CMakeFiles/ATen.dir/cuda/detail/ATen_generated_IndexUtils.cu.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    /tmp/pip-osju86eo-build/aten/src/ATen/Half.h(28): error: namespace "std" has no member "isinf"

    /tmp/pip-osju86eo-build/aten/src/ATen/Half.h(31): error: namespace "std" has no member "isnan"

    /tmp/pip-osju86eo-build/aten/src/ATen/Half.h(42): error: namespace "std" has no member "to_string"
```


Full log: [pytorch_build.txt](https://github.com/pytorch/pytorch/files/1725644/pytorch_build.txt)

I've been trying to compile for Ubuntu 17.10 for quite a while, I'm aware of the gcc5 issue, gcc6 also gave similar errors as above and gcc4.8 also doesn't work for me. Are they any fixes planned for gcc6?

**Comment by sdmonov** [comment]
@hsed can you tell me what is the output of the following commands:

```bash
grep "_GLIBCXX_USE_C99" /usr/include/x86_64-linux-gnu/c++/4.8/bits/c++config.h

apt-cache showpkg libstdc++-4.8-dev
```

Btw I tested with pyenv and it compiles for me with g++-4.8.

**Comment by hsed** [comment]
@sdmonov here is the output:
Am I suppose to add `#define _GLIBCXX_USE_C99` somewhere?

```
$ grep "_GLIBCXX_USE_C99" /usr/include/x86_64-linux-gnu/c++/4.8/bits/c++config.h
/* #undef _GLIBCXX_USE_C99 */
#define _GLIBCXX_USE_C99_COMPLEX 1
#define _GLIBCXX_USE_C99_COMPLEX_TR1 1
#define _GLIBCXX_USE_C99_CTYPE_TR1 1
#define _GLIBCXX_USE_C99_FENV_TR1 1
#define _GLIBCXX_USE_C99_INTTYPES_TR1 1
#define _GLIBCXX_USE_C99_INTTYPES_WCHAR_T_TR1 1
/* #undef _GLIBCXX_USE_C99_MATH */
#define _GLIBCXX_USE_C99_MATH_TR1 1
#define _GLIBCXX_USE_C99_STDINT_TR1 1
```

```
$ apt-cache showpkg libstdc++-4.8-dev
Package: libstdc++-4.8-dev
Versions: 
4.8.5-4ubuntu6 (/var/lib/apt/lists/gb.archive.ubuntu.com_ubuntu_dists_artful_universe_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/gb.archive.ubuntu.com_ubuntu_dists_artful_universe_binary-amd64_Packages
                  MD5: a197f2aec835e5fc6f8f76039d8a7c4e
 Description Language: 
                 File: /var/lib/apt/lists/gb.archive.ubuntu.com_ubuntu_dists_artful_universe_binary-i386_Packages
                  MD5: a197f2aec835e5fc6f8f76039d8a7c4e
 Description Language: en
                 File: /var/lib/apt/lists/gb.archive.ubuntu.com_ubuntu_dists_artful_universe_i18n_Translation-en
                  MD5: a197f2aec835e5fc6f8f76039d8a7c4e


Reverse Depends: 
  g++-4.8,libstdc++-4.8-dev 4.8.5-4ubuntu6
  libstdc++-4.8-dev:i386,libstdc++-4.8-dev 4.8.5-4ubuntu6
  libstdc++-4.8-dev:i386,libstdc++-4.8-dev 4.8.5-4ubuntu6
  libx32stdc++6-4.8-dbg,libstdc++-4.8-dev 4.8.5-4ubuntu6
  libx32stdc++-4.8-dev,libstdc++-4.8-dev 4.8.5-4ubuntu6
  libstdc++6-4.8-dbg,libstdc++-4.8-dev 4.8.5-4ubuntu6
  libstdc++-4.8-pic,libstdc++-4.8-dev 4.8.5-4ubuntu6
  libboost1.63-dev,libstdc++-4.8-dev
  lib32stdc++6-4.8-dbg,libstdc++-4.8-dev 4.8.5-4ubuntu6
  lib32stdc++-4.8-dev,libstdc++-4.8-dev 4.8.5-4ubuntu6
  libboost1.62-dev,libstdc++-4.8-dev
Dependencies: 
4.8.5-4ubuntu6 - gcc-4.8-base (5 4.8.5-4ubuntu6) libgcc-4.8-dev (5 4.8.5-4ubuntu6) libstdc++6 (2 4.8.5-4ubuntu6) libc6-dev (2 2.13-0ubuntu6) libg++2.8-dev (0 (null)) libg++27-dev (0 (null)) libg++272-dev (3 2.7.2.8-1) libstdc++2.10-dev (3 1:2.95.3-2) libstdc++2.8-dev (0 (null)) libstdc++2.9-dev (0 (null)) libstdc++2.9-glibc2.1-dev (0 (null)) libstdc++3.0-dev (0 (null)) libstdc++-4.8-doc (0 (null)) libstdc++-4.8-dev:i386 (35 4.8.5-4ubuntu6) libstdc++-4.8-dev:i386 (38 4.8.5-4ubuntu6) 
Provides: 
4.8.5-4ubuntu6 - libstdc++-dev (= ) 
Reverse Provides: 
```

**Comment by kwierman** [comment]
Just to be clear, @hsed, where those lines added to /usr/include/x86_64-linux-gnu/c++/4.8/bits/c++config.h ?

**Comment by hsed** [comment]
Yes, and I used the same version (4.8) of GCC to compile.

**Comment by kwierman** [comment]
@hsed Thanks. That seemed to fix one problem, and then I ran into issue #3786. One of these days I'll dig my way out of this rabbithole.

**Comment by PiotrCzapla** [comment]
downgrading to `4.8` didn't work for me on Ubuntu 17.10  and cuda9 this issue #3807 says it is possible to compile using `gcc-6`

**Comment by Inoryy** [comment]
Same issue, Ubuntu 17.10, CUDA 9.0. I've tried compiling with gcc versions `6.4.0`, `5.4.1` and `4.8.5`.
For `4.8.5` I've tried the `_GLIBCXX_USE_C99` trick, but then it fails with:
> python/pytorch/aten/src/TH/THAtomic.c:9:23: fatal error: stdatomic.h: No such file or directory

`stdatomic.h` missing seems to be a known bug in `4.8` without any workaround...

**Comment by PiotrCzapla** [comment]
I've managed to compile pytorch on ubuntu 17.10 and cuda 9.0 using Docker (that had image of ubuntu 16.04) and adopted version of this script: https://github.com/pytorch/builder/blob/master/manywheel/build.sh.
to build a proper wheel archive.

If anyone needs  a hand let me know I can post the steps.

**Comment by jameschartouni** [comment]
Hey, PiotrCzapla. Could you please post the steps or a copy of your image? Thanks!

**Comment by SsnL** [comment]
gcc6: This is an NVIDIA NVCC bug, which is fixed in CUDA 9.2.
gcc5: a GCC bug, which was labeled as nofix

#8863 which adds a clear error message for the gcc 6 error.

**Comment by benwu232** [comment]
In Ubuntu 16.04, I successfully compiled pytorch 0.5, with cuda9.2 + dudnn7.2 + gcc-4.9 + g++-4.9 on my laptop with nvidia870m which has compatibility 3.0. Just apt-get install gcc-4.9 and g++-4.9, no patching. I tried gcc5 in system but failed.

**Comment by toby5box** [comment]
> At the moment no standard compiler of Ubuntu 17.10 can compile PyTorch :(

Hey don't feel bad, can't build Caffe either.
