### ISSUE TITLE
Compile with MAGMA 2.10.0 cause #error

### ISSUE THREAD

**Issue by sfence** [pytorch/pytorch#183741]
### 🐛 Describe the bug

Try to compile PyTorch from sources against MAGMA library 2.10.0

PyTorch version tag v2.12.0

### Error logs

```
pytorch/aten/src/ATen/native/cuda/linalg/BatchLinearAlgebra.cpp:58:2: error: #error "MAGMA release minor or micro version >= 10, please correct AT_MAGMA_VERSION"
         58 | #error "MAGMA release minor or micro version >= 10, please correct AT_MAGMA_VERSION"
```

### Versions

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 16.1.1 20260430
Clang version: 22.1.5
CMake version: version 4.3.2
Libc version: glibc-2.43

Python version: 3.13.13 (main, May 14 2026, 09:22:44) [GCC 16.1.1 20260430] (64-bit runtime)
Python platform: Linux-7.0.3-arch1-2-x86_64-with-glibc2.43
Is CUDA available: N/A
CUDA runtime version: 13.2.78
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA RTX 4000 Ada Generation
Nvidia driver version: 595.71.05
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.9.22.0
/usr/lib/libcudnn_adv.so.9.22.0
/usr/lib/libcudnn_cnn.so.9.22.0
/usr/lib/libcudnn_engines_precompiled.so.9.22.0
/usr/lib/libcudnn_engines_runtime_compiled.so.9.22.0
/usr/lib/libcudnn_engines_tensor_ir.so.9.22.0
/usr/lib/libcudnn_ext.so.9.22.0
/usr/lib/libcudnn_graph.so.9.22.0
/usr/lib/libcudnn_heuristic.so.9.22.0
/usr/lib/libcudnn_ops.so.9.22.0
Is XPU available: N/A
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A
Caching allocator config: N/A

CPU:
Architecture:                            x86_64
CPU op-mode(s):                          32-bit, 64-bit
Address sizes:                           46 bits physical, 48 bits virtual
Byte Order:                              Little Endian
CPU(s):                                  24
On-line CPU(s) list:                     0-23
Vendor ID:                               GenuineIntel
Model name:                              Intel(R) Core(TM) Ultra 9 285K
CPU family:                              6
Model:                                   198
Thread(s) per core:                      1
Core(s) per socket:                      24
Socket(s):                               1
Stepping:                                2
Microcode version:                       0x117
CPU(s) scaling MHz:                      63%
CPU max MHz:                             4600.0000
CPU min MHz:                             800.0000
BogoMIPS:                                7372.80
Flags:                                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect user_shstk avx_vnni lam wbnoinvd dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi vnmi umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid bus_lock_detect movdiri movdir64b fsrm md_clear serialize arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                          VT-x
L1d cache:                               768 KiB (20 instances)
L1i cache:                               1.3 MiB (20 instances)
L2 cache:                                40 MiB (12 instances)
L3 cache:                                36 MiB (1 instance)
NUMA node(s):                            1
NUMA node0 CPU(s):                       0-23
Vulnerability Gather data sampling:      Not affected
Vulnerability Ghostwrite:                Not affected
Vulnerability Indirect target selection: Not affected
Vulnerability Itlb multihit:             Not affected
Vulnerability L1tf:                      Not affected
Vulnerability Mds:                       Not affected
Vulnerability Meltdown:                  Not affected
Vulnerability Mmio stale data:           Not affected
Vulnerability Old microcode:             Vulnerable
Vulnerability Reg file data sampling:    Not affected
Vulnerability Retbleed:                  Not affected
Vulnerability Spec rstack overflow:      Not affected
Vulnerability Spec store bypass:         Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:                Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:                Mitigation; Enhanced / Automatic IBRS; IBPB conditional; PBRSB-eIBRS Not affected; BHI BHI_DIS_S
Vulnerability Srbds:                     Not affected
Vulnerability Tsa:                       Not affected
Vulnerability Tsx async abort:           Not affected
Vulnerability Vmscape:                   Mitigation; IBPB before exit to userspace

Versions of relevant libraries:
[pip3] intel-cmplr-lib-ur==2026.0.0
[pip3] intel-openmp==2026.0.0
[pip3] mkl-include==2026.0.0
[pip3] mkl-static==2026.0.0
[pip3] numpy==2.4.4
[pip3] onemkl-license==2026.0.0
[pip3] optree==0.19.1
[pip3] tbb==2023.0.0
[pip3] tbb-devel==2023.0.0
[pip3] tcmlib==1.5.0
[pip3] umf==1.1.0
[conda] Could not collect

cc @malfet @ptrblck @msaroufim @eqy @jerryzh168 @tinglvv @nWEIdia @jianyuh @nikitaved @mruberry @walterddr @xwang233 @Lezcano @chauhang @penguinwu

**Comment by jansel** [comment]
My agent was unable to reproduce this on 8dd44388526b4c638900a96f16ecfd1c0b2b0f8d. Reopen if you see this on the latest PyTorch nightly
