### ISSUE TITLE
tensor.topk doesn't accept out parameter anymore

### ISSUE THREAD

**Issue by edunov** [pytorch/pytorch#5497]
Hi, 

The latest version of pytorch doesn't seem to accept "out" parameter in the tensor.topk:

```
>>> import torch
>>> torch.rand(3, 4).topk(1, out=(torch.FloatTensor(0), torch.LongTensor(0)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: topk() got an unexpected keyword argument 'out'
```

It seems to work with torch.topk though:
```
>>> torch.topk(torch.rand(3, 4), 1, out=(torch.FloatTensor(0), torch.LongTensor(0)))
(
 0.9105
 0.9654
 0.9619
[torch.FloatTensor of size (3,1)]
,
 1
 1
 3
[torch.LongTensor of size (3,1)]
)
```

Pytorch installed from source ('0.3.0b0+af3964a')

Is it expected?

**Comment by zou3519** [comment]
@edunov we don't support the `out` keyword on tensor.* methods, only on torch.* methods.

**Comment by edunov** [comment]
@zou3519  but you used to until recently
e.g it works in version 0.4.0a0+6c587e9 and in 0.3.0b0+af3964a  
or was it an undocumented feature?

**Comment by zou3519** [comment]
It was a bug, the `out` keyword should not have worked on the tensor.* methods.

**Comment by edunov** [comment]
Thank you for your response!
