### ISSUE TITLE
Cuda_runtime.h not found on ROCM build

### ISSUE THREAD

**Issue by victor-felicitas** [pytorch/pytorch#7687]
Hi all,

I've tried to install newest build on Ubuntu 16.04 ROCM 1.8 machine.
I used the command
sudo WITH_ROCM=1 NO_CUDA=1  python setup.py  install
but I always get the same error **cuda_runtime.h not found** even while ROCM build is clearly activated (ROCM=TRUE)
I guess the build should not use CUDA at all if I am on AMD GPU with ROCM, right?

Any help will be appreciated!

Full output is below:

[ 53%] Building CXX object src/ATen/test/CMakeFiles/scalar_tensor_test.dir/scalar_tensor_test.cpp.o
In file included from /home/vityek/pytorch/aten/src/THC/THCReduceApplyUtils.cu:1:
In file included from /home/vityek/pytorch/aten/src/THC/THCReduceApplyUtils.cuh:6:
/home/vityek/pytorch/aten/build/src/THC/THCGeneral.h:13:10: fatal error: 'cuda_runtime.h' file not found
#include "cuda_runtime.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
In file included from /home/vityek/pytorch/aten/src/THC/THCReduceApplyUtils.cu:1:
In file included from /home/vityek/pytorch/aten/src/THC/THCReduceApplyUtils.cuh:6:
/home/vityek/pytorch/aten/build/src/THC/THCGeneral.h:13:10: fatal error: 'cuda_runtime.h' file not found
#include "cuda_runtime.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
Died at /opt/rocm/bin/hipcc line 501.
CMake Error at ATen_cuda_generated_THCReduceApplyUtils.cu.o.cmake:120 (message):
  Error generating
  /home/vityek/pytorch/aten/build/src/ATen/CMakeFiles/ATen_cuda.dir/__/THC/./ATen_cuda_generated_THCReduceApplyUtils.cu.o

src/ATen/CMakeFiles/ATen_cuda.dir/build.make:63: recipe for target 'src/ATen/CMakeFiles/ATen_cuda.dir/__/THC/ATen_cuda_generated_THCReduceApplyUtils.cu.o' failed
make[2]: *** [src/ATen/CMakeFiles/ATen_cuda.dir/__/THC/ATen_cuda_generated_THCReduceApplyUtils.cu.o] Error 1
CMakeFiles/Makefile2:273: recipe for target 'src/ATen/CMakeFiles/ATen_cuda.dir/all' failed
make[1]: *** [src/ATen/CMakeFiles/ATen_cuda.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 53%] Built target tbb_init_test
[ 54%] Built target scalar_test
[ 55%] Built target basic
[ 55%] Built target broadcast_test
[ 55%] Built target dlconvertor_test
[ 56%] Built target undefined_tensor_test
[ 56%] Built target wrapdim_test
[ 56%] Built target native_test
[ 56%] Built target apply_utils_test
[ 56%] Built target atest
[ 56%] Linking CXX executable scalar_tensor_test
[ 56%] Built target scalar_tensor_test
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ezyang** [comment]
CC @Jorghi12

**Comment by odellus** [comment]
there's a preprocessing, hipify step where you need to run `python tools/amd_build/build_pytorch_amd.py` and make sure you have the python files at https://github.com/ROCm-Developer-Tools/pyHIPIFY copied over to `/opt/rocm/bin` not sure if you need to `chmod +x hipify-python.py` for build_pytorch_amd.py to work, but I did it anyway. Now I'm on to the next issue, problems with operator overloading using the `Half` data type.
https://github.com/pytorch/pytorch/issues/9219
