### PR TITLE
Fix build error with MSVC

### LINKED ISSUE #20642: Build error with MSVC (aten\src\ATen\native\quantized\Copy.cpp)
## 🐛 Bug

```
..\aten\src\ATen\native\quantized\Copy.cpp(18): error C2065: 'src_data': undeclared identifier
..\aten\src\ATen\native\quantized\Copy.cpp(18): error C2672: 'at::quantize_val': no matching overloaded function found
..\aten\src\ATen\native\quantized\Copy.cpp(26): error C2780: 'T at::quantize_val(float,int32_t,float)': expects 3 arguments - 2 provided
```

## To Reproduce

```
set CMAKE_GENERATOR="Visual Studio 16 2019" x64

set DISTUTILS_USE_SDK=1

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64

set CMAKE_GENERATOR=Ninja

set REL_WITH_DEB_INFO=1

python setup.py install
```

### PR DESCRIPTION
**Pull request by Jonas1312**
Close #20642 

Possibly broken by #19816

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]
Thanks!
