### ISSUE TITLE
Error in installing C++ Distribution of PyTorch

### ISSUE THREAD

**Issue by mmetwalli96** [pytorch/pytorch#88835]
### 🐛 Describe the bug

I am working on going throw the tutorial in this link [C++ DISTRIBUTIONS OF PYTORCH](https://pytorch.org/cppdocs/installing.html) 
I was able to run the first cmake command  ```cmake ..``` and I created this CMakeLists.txt file
```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(torch-cpp)

set(CMAKE_PREFIX_PATH "D:/OneDrive/Documents/Projects/pytorch-cpp/libtorch")

find_package(Torch REQUIRED)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")

add_executable(torch-cpp main.cpp)
target_link_libraries(torch-cpp "${TORCH_LIBRARIES}")
set_property(TARGET torch-cpp PROPERTY CXX_STANDARD 14)
```
this file generate the visual studio project file successfully
When I build the project to get the executables I ran to this error 
```
MSBuild version 17.4.0+18d5aef85 for .NET Framework
     Creating library D:/OneDrive/Documents/Projects/pytorch-cpp/build/Release/torch-cpp.lib and object D:/OneDrive/Documents/Projects/pytorch-cpp/build/Release/torch-cpp.exp
main.obj : error LNK2001: unresolved external symbol __imp___tls_index_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA [D:\OneDrive\Documents\Projects\pytorch-cpp\build\torch-cpp.vcxproj]
main.obj : error LNK2001: unresolved external symbol __imp___tls_offset_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA [D:\OneDrive\Documents\Projects\pytorch-cpp\build\torch-cpp.vcxproj]
D:\OneDrive\Documents\Projects\pytorch-cpp\build\Release\torch-cpp.exe : fatal error LNK1120: 2 unresolved externals [D:\OneDrive\Documents\Projects\pytorch-cpp\build\torch-cpp.vcxproj]
```

What should I do now? 

### Versions

wget: The term 'wget' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
C:\Users\mmetwalli\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'D:\\OneDrive\\Documents\\Projects\\pytorch-cpp\\collect_env.py': [Errno 2] No such file or directory

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @peterjc123 @mszhanyi @skyline75489 @nbcsm @jbschlosser

**Comment by zavinator** [comment]
This seems related to last Visual Studio version - I have this problem after upgrading VS2022 to 17.4.1
But I can compile same code with 17.3.6 without problem...

**Comment by Blackhex** [comment]
@zavinator The linker regression issue is tracked as [thread\_local causing fatal error LNK1161: invalid export specification on VS 2022 - Visual Studio Feedback](https://developercommunity.visualstudio.com/t/thread_local-causing-fatal-error-LNK1161/10199441)

**Comment by Blackhex** [comment]
@zavinator The linker issue fix was releaed in Visual Studio / Build Tools 17.4.3. Can you please verify it fixes your issue so we can close it?

**Comment by zavinator** [comment]
Confirmed, now it works ok
