### ISSUE TITLE
torch.autograd.profiler.load_nvprof() crash

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#45490]
## 🐛 Bug

torch.autograd.profiler.load_nvprof() crash because 
```
TypeError: __init__() missing 1 required positional argument: 'node_id'
```

## To Reproduce

Get a nvprof trace file, then
```
$ python -c 'import torch; a = torch.autograd.profiler.load_nvprof("a.prof")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xwang/Developer/pytorch/torch/autograd/profiler.py", line 590, in load_nvprof
    return EventList(parse_nvprof_trace(path))
  File "/home/xwang/Developer/pytorch/torch/autograd/profiler.py", line 1031, in parse_nvprof_trace
    evt = FunctionEvent(id=row['marker_id'],
TypeError: __init__() missing 1 required positional argument: 'node_id'
```

## Expected behavior

No crash

## Environment

1.7.0a0+ 208df1a
cuda 11.0

## Additional context

constructor call

https://github.com/pytorch/pytorch/blob/50b91103a90ac87c7836a330d692f5db3949f1ee/torch/autograd/profiler.py#L1041-L1045

constructor definition

https://github.com/pytorch/pytorch/blob/50b91103a90ac87c7836a330d692f5db3949f1ee/torch/autograd/profiler.py#L666-L686

Seems like `node_id` was introduced in https://github.com/pytorch/pytorch/pull/38748. @rohan-varma 

cc @ptrblck @ngimel @gchanan

**Comment by gchanan** [comment]
this isn't a crash.

**Comment by xwang233** [comment]
Potentially fixed in https://github.com/pytorch/pytorch/commit/9679e1affcded109201a4b33900943cf452c2ae0#diff-0610d675edef2e9dfc9922cf3872f2e6R1120-R1121.

**Comment by malfet** [comment]
PR  #45004 fixes the issue, will pick relevant parts of the fix into 1.7
