### PR TITLE
fallback to cpu_kernel for VSX

### LINKED ISSUE #97497: PyTorch Build From Source Error: ppc64le + gcc 7.3.1 + cuda 11.8 + python 3.9
### 🐛 Describe the bug

About 50% of the way through the `setup.py ` script I get a fatal error that kills the build process. I've got everything installed via `conda` as per the Build From Source instructions, and have had no problems building 1.12 on the same system. 

I attached the output of `python setup.py install` since I'm not sure how to parse it. I've tried different versions of cmake, as well as cleaning and reinitializing the submodules. There are a number of other compilers on the system, but since I've had luck with gcc 7.3.1 on PyTorch 1.12 in the past (and this didn't seem to be a gcc error) I haven't messed around with the compiler much. I have gotten the same error with gcc 8.3.1 as well. I have nsight-compute/2022.3.0 loaded but no cuDNN for now. 

[install.log](https://github.com/pytorch/pytorch/files/11058270/install.log)
[env.txt](https://github.com/pytorch/pytorch/files/11058284/env.txt)

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux Server release 7.9 (Maipo) (ppc64le)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Clang version: 12.0.1
CMake version: version 3.25.0
Libc version: glibc-2.17

Python version: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:27)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-4.14.0-115.35.1.3chaos.ch6a.ppc64le-ppc64le-with-glibc2.17
Is CUDA available: N/A
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:          ppc64le
Byte Order:            Little Endian
CPU(s):                176
On-line CPU(s) list:   0-175
Thread(s) per core:    4
Core(s) per socket:    22
Socket(s):             2
NUMA node(s):          6
Model:                 2.1 (pvr 004e 1201)
Model name:            POWER9, altivec supported
CPU max MHz:           3800.0000
CPU min MHz:           2300.0000
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
L3 cache:              10240K
NUMA node0 CPU(s):     0-87
NUMA node8 CPU(s):     88-175
NUMA node252 CPU(s):   
NUMA node253 CPU(s):   
NUMA node254 CPU(s):   
NUMA node255 CPU(s):

Versions of relevant libraries:
[pip3] numpy==1.23.4
[conda] numpy                     1.23.4           py39hea7066a_1    conda-forge

cc @malfet @seemethere

### PR DESCRIPTION
**Pull request by cdeepali**
Attempt to fix https://github.com/pytorch/pytorch/issues/97497

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

File: aten/src/ATen/native/cpu/BinaryOpsKernel.cpp [hunk 1]
```diff
@@ -313,6 +313,14 @@ void bitwise_xor_kernel(TensorIteratorBase& iter) {
 }
 
 void lshift_kernel(TensorIteratorBase& iter) {
+#if defined(__VSX__)  || defined(CPU_CAPABILITY_VSX)
+  AT_DISPATCH_INTEGRAL_TYPES(iter.dtype(), "lshift_cpu", [&]() {
+    cpu_kernel(iter,
+      [](scalar_t a, scalar_t b) -> scalar_t {
+        return static_cast<std::make_unsigned_t<scalar_t>>(a) << b;
+    });
+  });
```
Comment (jgong5) [inline aten/src/ATen/native/cpu/BinaryOpsKernel.cpp:322]: Is there vectorized bit shift support in VSX to add in `vec256/vsx/` so that we don't have to exclude it explicitly here in the common aten kernel?

Comment (cdeepali) [reply aten/src/ATen/native/cpu/BinaryOpsKernel.cpp:322]: @jgong5, I am not sure on it. But this presently fixes the build errors that we are seeing. 
@quickwritereader, any idea if we have bit shift support in VSX?

Comment (quickwritereader) [reply aten/src/ATen/native/cpu/BinaryOpsKernel.cpp:322]: I believe left shift should be this one https://www.ibm.com/docs/en/xl-c-and-cpp-linux/16.1.0?topic=functions-vec-sldw
but still, it's worth defining if it's not defined. similarly this way inside here https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h#L71-L83
but with c as an argument for template type T

Comment (quickwritereader) [reply aten/src/ATen/native/cpu/BinaryOpsKernel.cpp:322]: something like this for 4 byte:
vec_sl( vec , vec_splats(static_cast<unsigned int>(shift_int) ));

Comment (quickwritereader) [reply aten/src/ATen/native/cpu/BinaryOpsKernel.cpp:322]: so it seems its better to write that code for each type or to use macros. I do not know why I wrote it macros heavily instead of template heavily like I did zarch version.

Comment (cdeepali) [reply aten/src/ATen/native/cpu/BinaryOpsKernel.cpp:322]: Thanks @quickwritereader, I will try this.

**Comment by ax3l** [comment]
Confirming that this PR unbreaks Power9 builds with pytorch 2.0.1 for me, building with CUDA 11.7 for V100, GCC 9.3.0, and Python 3.8.10 :sparkles:

Thanks @cdeepali @quickwritereader .

File: aten/src/ATen/native/cpu/BinaryOpsKernel.cpp (hunk 1 above)
Comment (cdeepali) [reply aten/src/ATen/native/cpu/BinaryOpsKernel.cpp:322]: @quickwritereader, I tried using the following in `vsx_helpers.h` along with the respective macro calls in the associated header files. 

```
#define DEFINE_MEMBER_OP2(op, op_type, func)                                  \
  Vectorized<op_type> C10_ALWAYS_INLINE operator<<(unsigned int shift) const {
     auto shift_vec = vec_splats( shift );
    return {vec_sl(_vec0, shift_vec), vec_sl(_vec1,shift_vec )};
   }


```
but I get errors of the kind:

```
<mydir>work/aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h:177:35: error: 'shift' was not declared in this scope
<mydir>work/aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h:177:41: error: invalid parameter combination for AltiVec intrinsic '__builtin_vec_splats'
<mydir>work/aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h:178:5: error: expected unqualified-id before 'return'
<mydir>work/aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h:179:4: error: expected declaration before '}' token
<mydir>work/aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h:159:13: error: invalid parameter combination for AltiVec intrinsic '__builtin_vec_sl'
<mydir>work/aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h:159:39: error: invalid parameter combination for AltiVec intrinsic '__builtin_vec_sl'
<mydir>work/aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h:159:59: error: no matching function for call to 'at::vec::DEFAULT::Vectorized<short int>::Vectorized(<brace-enclosed initializer list>)'
<mydir>work/aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h:159:13: error: invalid parameter combination for AltiVec intrinsic '__builtin_vec_sl'
<mydir>work/aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h:159:39: error: invalid parameter combination for AltiVec intrinsic '__builtin_vec_sl'
<mydir>work/aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h:159:59: error: no matching function for call to 'at::vec::DEFAULT::Vectorized<int>::Vectorized(<brace-enclosed initializer list>)'
<mydir>work/aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h:159:13: error: invalid parameter combination for AltiVec intrinsic '__builtin_vec_sl'
<mydir>work/aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h:159:39: error: invalid parameter combination for AltiVec intrinsic '__builtin_vec_sl'
<mydir>work/aten/src/ATen/cpu/vec/vec256/vsx/vsx_helpers.h:159:59: error: no matching function for call to 'at::vec::DEFAULT::Vectorized<long int>::Vectorized(<brace-enclosed initializer list>)'
```
Do you think I am missing something obvious?

Comment (quickwritereader) [reply aten/src/ATen/native/cpu/BinaryOpsKernel.cpp:322]: I see.
I think type should match. See if (op_type shift) works

Comment (quickwritereader) [reply aten/src/ATen/native/cpu/BinaryOpsKernel.cpp:322]: And also imho better rename it as DEFINE_SHIFT_LEFT,  as it is used specially for that operation

Comment (cdeepali) [reply aten/src/ATen/native/cpu/BinaryOpsKernel.cpp:322]: yes, I just pasted trial code, yet to update the name of the macro. I will update it in final code.

**Review by quickwritereader — APPROVED** [review]
lgtm

**Comment by cdeepali** [comment]
Thanks @quickwritereader.

**Comment by cdeepali** [comment]
@malfet, Pls review.

**Comment by malfet** [comment]
@cdeepali you need to sign PyTorch CLA, otherwise this change can not be merge

**Comment by cdeepali** [comment]
> @cdeepali you need to sign PyTorch CLA, otherwise this change can not be merge.
> 
> Also, if automatic rebase will fail, please make sure to rebase to get a good signal.

@malfet, I finally got the CLA signed.

**Comment by cdeepali** [comment]
> > @cdeepali you need to sign PyTorch CLA, otherwise this change can not be merge.
> > Also, if automatic rebase will fail, please make sure to rebase to get a good signal.
> 
> @malfet, I finally got the CLA signed.

**Comment by cdeepali** [comment]
@malfet, Do you think that this PR  can be merged?

**Review by ezyang — APPROVED** [review]

**Comment by Flamefire** [comment]
I noticed that this introduces bugs/issues when the rhs is out-of bounds, e.g. negative or greater than the bit size of the lhs, see #109777
