### ISSUE TITLE
CUDA 8 build error on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#16711]
From the nightly build log:
```
[1595/2461] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/operators/caffe2_gpu_generated_copy_op.cu.obj
FAILED: caffe2/CMakeFiles/caffe2_gpu.dir/operators/caffe2_gpu_generated_copy_op.cu.obj 
cmd.exe /C "cd /D %SRC_DIR%\build\caffe2\CMakeFiles\caffe2_gpu.dir\operators && %BUILD_PREFIX%\Library\bin\cmake.exe -E make_directory C:/w/1/s/tmp_conda_3.6_104959/conda/conda-bld/pytorch-nightly_1549191570965/work/build/caffe2/CMakeFiles/caffe2_gpu.dir/operators/. && %BUILD_PREFIX%\Library\bin\cmake.exe -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=C:/w/1/s/tmp_conda_3.6_104959/conda/conda-bld/pytorch-nightly_1549191570965/work/build/caffe2/CMakeFiles/caffe2_gpu.dir/operators/./caffe2_gpu_generated_copy_op.cu.obj -D generated_cubin_file:STRING=C:/w/1/s/tmp_conda_3.6_104959/conda/conda-bld/pytorch-nightly_1549191570965/work/build/caffe2/CMakeFiles/caffe2_gpu.dir/operators/./caffe2_gpu_generated_copy_op.cu.obj.cubin.txt -P C:/w/1/s/tmp_conda_3.6_104959/conda/conda-bld/pytorch-nightly_1549191570965/work/build/caffe2/CMakeFiles/caffe2_gpu.dir/operators/caffe2_gpu_generated_copy_op.cu.obj.Release.cmake"

C:/w/1/s/tmp_conda_3.6_104959/conda/conda-bld/pytorch-nightly_1549191570965/work/third_party/protobuf/src\google/protobuf/arena.h(338): error: static assertion failed with "CreateArray requires a trivially destructible type"
          detected during:
            instantiation of "T *google::protobuf::Arena::CreateArray<T>(google::protobuf::Arena *, size_t) [with T=char]" 
C:/w/1/s/tmp_conda_3.6_104959/conda/conda-bld/pytorch-nightly_1549191570965/work/third_party/protobuf/src\google/protobuf/repeated_field.h(1367): here
            instantiation of "void google::protobuf::RepeatedField<Element>::Reserve(int) [with Element=google::protobuf::uint32]" 
C:/w/1/s/tmp_conda_3.6_104959/conda/conda-bld/pytorch-nightly_1549191570965/work/third_party/protobuf/src\google/protobuf/repeated_field.h(1187): here
            instantiation of "void google::protobuf::RepeatedField<Element>::Add(const Element &) [with Element=google::protobuf::uint32]" 
C:/w/1/s/tmp_conda_3.6_104959/conda/conda-bld/pytorch-nightly_1549191570965/work/third_party/protobuf/src\google/protobuf/wire_format_lite_inl.h(254): here
            instantiation of "__nv_bool google::protobuf::internal::WireFormatLite::ReadRepeatedFixedSizePrimitive<CType,DeclaredType>(int, google::protobuf::uint32, google::protobuf::io::CodedInputStream *, google::protobuf::RepeatedField<CType> *) [with CType=google::protobuf::uint32, DeclaredType=google::protobuf::internal::WireFormatLite::TYPE_FIXED32]" 
C:/w/1/s/tmp_conda_3.6_104959/conda/conda-bld/pytorch-nightly_1549191570965/work/third_party/protobuf/src\google/protobuf/wire_format_lite_inl.h(307): here
```

cc @peterjc123

**Comment by peterjc123** [comment]
See `extra_compile_flags` of https://docs.python.org/3/distutils/apiref.html#distutils.core.Extension. And document for Cpp Extension: https://pytorch.org/docs/stable/cpp_extension.html#torch.utils.cpp_extension.CppExtension.

**Comment by jsagar87** [comment]
I am facing similar issue while building caffe2 for windows,

` "C:\Devtools\pytorchcaffe1\pytorch\build\ALL_BUILD.vcxproj" (default target) (1) ->
       "C:\Devtools\pytorchcaffe1\pytorch\build\caffe2\caffe2_gpu.vcxproj" (default target) (9) ->
       (CustomBuild target) ->
         C:/Devtools/pytorchcaffe1/pytorch/third_party/protobuf/src\google/protobuf/arena.h(338): error : static assertion failed with "CreateArray requires a trivially destructible type" [C:\Devtoo
       ls\pytorchcaffe1\pytorch\build\caffe2\caffe2_gpu.vcxproj]

    52470 Warning(s)
    1 Error(s)`


Let me know if you find any solution.

**Comment by peterjc123** [comment]
cc @orionr

**Comment by orionr** [comment]
cc @pjh5 and @kostmo

**Comment by peterjc123** [comment]
Tested the following cases:
test.cpp
```cpp
#include <type_traits>

template <typename T>
static T* CreateArray() {
	static_assert(std::is_pod<T>::value,
		"CreateArray requires a trivially constructible type");
	static_assert(std::is_trivially_destructible<T>::value,
		"CreateArray requires a trivially destructible type");
	return static_cast<T*>(::operator new[](5 * sizeof(T)));
}

int main()
{
	CreateArray<char>();
    return 0;
}
```
`test.cpp` is able to compile using nvcc (cuda 8.0) and msvc 2015.
test.cu
```cuda
__device__ void test() {
	CreateArray<char>();
}
```
During the build of `test.cu`, it throws an error `error: static assertion failed with "CreateArray requires a trivially destructible type"`. So it looks like a bug/missing feature in CUDA 8.

**Comment by peterjc123** [comment]
The possible solutions I could think of are:
1. Downgrade protobuf when building for CUDA 8
2. Disable these assert with some code modifications

**Comment by klust** [comment]
It looks like a protobuf problem, I get the same error message at the same place just compiling protobuf with the Intel 2019 compilers.

**Comment by cristianPanaite** [comment]
Hello @peterjc123,

I tried to replicate your issue on the latest versions, but I could not. 

Installing the nightly version of PyTorch from [here](https://pytorch.org/get-started/locally) doesn't generate any error. 

If you think the issue still persists, please open a new issue with details on how to reproduce it on the latest version.
