### ISSUE TITLE
THDTensor build Fails with some gcc versions

### ISSUE THREAD

**Issue by davidmascharka** [pytorch/pytorch#3183]
[This line](https://github.com/pytorch/pytorch/blob/cb011410b8a39f7f4891b967bd3d2d40c31167e0/torch/lib/THD/master_worker/master/generic/THDTensor.cpp#L19) in THDTensor is problematic for some gcc versions. The `inttypes.h` include isn't enough for older compilers. It looks like you also need to `#define __STDC_FORMAT_MACROS` to build properly.

Here's a minimal example:

```c++
#define __STDC_FORMAT_MACROS

#include <inttypes.h>
#include <stdio.h>

int main() {
    printf("%" PRId64 "\n", 10);
    return 0;
}
```

commenting out the `#define` causes the following error with gcc 4.8.5:

```
test.cpp: In function ‘int main()’:
test.cpp:7:16: error: expected ‘)’ before ‘PRId64’
     printf("%" PRId64 "\n", 10);
```

but does work with gcc 5.4.0. I haven't tested with any other compilers.

**Comment by apaszke** [comment]
Can you please send a PR?

**Comment by jdsalmonson** [comment]
I have the same issue both with gcc 4.93 and 6.1.0.  My work around was to replace line 20 of torch/lib/THD/master_worker/master/generic/THDTensor.cpp :
   `n += snprintf(str+n, L-n, "%" PRId64, tensor->size[i]);`
with
    `n += snprintf(str+n, L-n, "%lld" , tensor->size[i]);`
 which appears to at least compile (with 6.1.0).

**Comment by ink1** [comment]
That was my temporary fix as well.
CentOS 7 here with gcc 4.8.5

**Comment by ezyang** [comment]
Fixed in #3190
