### PR TITLE
Add maximize support to LBFGS

### LINKED ISSUE #86339: Add `maximize` support to LBFGS optimizer
As per title.
This is lower priority than the other optimizers in https://github.com/pytorch/pytorch/issues/68052 and so is not being worked on right now.

### PR DESCRIPTION
**Pull request by tanishmeh**
Fixes #86339

### Context

LBFGS is the last unchecked box on #68052 ("Add the `maximize` flag to all optimizers"),
which is otherwise closed. It is currently the only stable optimizer whose constructor
does not accept `maximize`:

```
ASGD Adadelta Adafactor Adagrad Adam AdamW Adamax NAdam RAdam RMSprop Rprop SGD SparseAdam  -> yes
LBFGS                                                                                        -> no
```

Without it, users maximizing an objective have to negate their closure and then
re-negate the value it returns.

### Implementation

Maximizing `f` is minimizing `-f`, so the objective value and gradient are negated at
the three points where they enter the algorithm: the initial evaluation in `step()`,
the re-evaluation on the no-line-search path, and `_directional_evaluate()`, which is
what the strong-Wolfe line search calls. Everything downstream — the convergence
checks, the two-loop recursion, the Wolfe conditions — is expressed in terms of those
two quantities, so nothing else changes.

`orig_loss` is deliberately left alone: `step()` returns the closure's own value so
callers see their real objective rather than the negated one used internally, matching
every other optimizer.

Two notes on the choices here:

- Wrapping the closure to return `-loss` does not work on its own. The closure's
  `backward()` populates `p.grad` with the gradient of `f`, not `-f`, so the gathered
  gradient would still need separate negation, and `orig_loss` would come back negated.
- LBFGS had no `__setstate__`, so one is added to default `maximize` to `False`.
  Without it, loading a checkpoint written before this change leaves the param group
  without the key and `step()` raises `KeyError` on `group["maximize"]`.

### Testing

`maximize` is added to the LBFGS entries in the optimizer info database, both alone and
combined with `strong_wolfe`, so the existing generic optimizer tests cover it. Before
this change those inputs fail with
`TypeError: LBFGS.__init__() got an unexpected keyword argument 'maximize'`
(75 failed, 3 passed); after, the suite is green (78 passed, 16 skipped):

```
python test/test_optim.py -k LBFGS
```

The state_dict and older-state-dict tests, which exercise the new `__setstate__`:

```
python test/test_optim.py -k "LBFGS and (older_state_dict or state_dict or deepcopy)"
```

Verified by hand that on `f(x) = -(x-3)^2 + 5`, `maximize=True` converges to the maximum
at `x=3` for both `line_search_fn=None` and `'strong_wolfe'`; that `maximize=False` still
minimizes; and that `step()` returns the true objective value rather than the negated one.

The strongest check was equivalence: on a small MLP regression the parameter trajectory
from `maximize=True` on `-L` is **bitwise identical** to `maximize=False` on `L` over six
steps, for both line-search settings. Loading a `state_dict` with the `maximize` key
removed, simulating an older checkpoint, also steps correctly.

Prepared with the assistance of an AI coding assistant.

### CODE REVIEW

**Comment by janeyx99** [comment]
thanks for the PR, sorry there was actually another PR that fixed this already! https://github.com/pytorch/pytorch/pull/187309
