### PR TITLE
Revert "Add std::variant backport as c10::variant (#26836)"

### PR DESCRIPTION
**Pull request by yf225**
This reverts commit 0cd188035a27fc38ce1e8eee205f6d47cd7650e6.

As reported by @jerryzh168 and @pritamdamania87, mpark::variant doesn’t compile with gcc 7.3.1 on fb devserver and throws error similar to https://github.com/mpark/variant/issues/43. (However, it doesn’t fail with gcc 7.3.1 in OSS CI, based on https://circleci.com/api/v1.1/project/github/pytorch/pytorch/2995606/output/107/0?file=true)
A plausible workaround is to upgrade devserver to devtoolset-8, but that would in turn causes CUDA build to complain: 
```
/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 7 are not supported!
 #error -- unsupported GNU version! gcc versions later than 7 are not supported!
```
(Thanks @pritamdamania87 for the report!)

The solution for now is to revert the mpark::variant addition, and I will find alternatives that will work with gcc 7.3.1 on fb devserver.

### CODE REVIEW

**Review by pritamdamania87 — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
I'm surprised you didn't ninja unland the original diff

**Comment by yf225** [comment]
@ezyang I fixed the clang 3.8 build error and then re-landed the original PR. But it seems that there is another problem with it (noted in this PR). :(
