### ISSUE TITLE
Compile error maybe associated with nccl

### ISSUE THREAD

**Issue by CoinCheung** [pytorch/pytorch#14363]
I am compiling from source, and I am working on ubuntu1604 with python3.5. I simply clone the whole repository and run the `setup.py` script: 
```
git clone --recursive https://github.com/pytorch/pytorch.git
python setup.py install
```
It compiles smoothly in the beginning, but at around [80%], there appears a link error

>Makefile:140: recipe for target 'all' failed
setup.py::build_deps::run()
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn --use-qnnpack caffe2'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/init_test] Error 1
make[1]: *** [caffe2/CMakeFiles/init_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/timer_test] Error 1
make[1]: *** [caffe2/CMakeFiles/timer_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/common_test] Error 1
make[1]: *** [caffe2/CMakeFiles/common_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/smart_tensor_printer_test] Error 1
make[1]: *** [caffe2/CMakeFiles/smart_tensor_printer_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/event_test] Error 1
make[1]: *** [caffe2/CMakeFiles/event_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/cast_test] Error 1
make[1]: *** [caffe2/CMakeFiles/cast_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/verify_api_visibility] Error 1
make[1]: *** [caffe2/CMakeFiles/verify_api_visibility.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/context_test] Error 1
make[1]: *** [caffe2/CMakeFiles/context_test.dir/all] Error 2
CMakeFiles/inline_container_test.dir/serialize/inline_container_test.cc.o: In function `at::(anonymous namespace)::PyTorchFileWriterAndReader_SaveAndLoad_Test::TestBody()':
inline_container_test.cc:(.text+0x1a8): warning: the use of `tmpnam' is /dangerous,data /betterzhangzy use `/mkstempbuild'/
pytorch//databuild//zhangzylib//buildlibcaffe2_gpu.so/:pytorch/ buildundefined/ lib/referencelibcaffe2_gpu.so :to  undefined` ncclGroupEndreference' 
to/ data`/ncclGroupEnd'zhangzy
//databuild//zhangzypytorch//buildbuild//pytorch/libbuild//libcaffe2_gpu.solib/:libcaffe2_gpu.so :undefined  undefinedreference reference  toto  `ncclGroupStart'
`ncclGroupStart'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make[2]: *** [bin/inline_container_test] Error 1
make[1]: *** [caffe2/CMakeFiles/inline_container_test.dir/all] Error 2
make[2]: *** [bin/cudnn_test] Error 1
make[1]: *** [caffe2/CMakeFiles/cudnn_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/dlconvertor_test] Error 1
make[1]: *** [caffe2/CMakeFiles/dlconvertor_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/conv_op_cache_cudnn_test] Error 1
make[1]: *** [caffe2/CMakeFiles/conv_op_cache_cudnn_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/tbb_init_test] Error 1
make[1]: *** [caffe2/CMakeFiles/tbb_init_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/device_test] Error 1
make[1]: *** [caffe2/CMakeFiles/device_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/event_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/event_gpu_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/TopoSortTest] Error 1
make[1]: *** [caffe2/CMakeFiles/TopoSortTest.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/weakref_test] Error 1
make[1]: *** [caffe2/CMakeFiles/weakref_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/stats_test] Error 1
make[1]: *** [caffe2/CMakeFiles/stats_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/undefined_tensor_test] Error 1
make[1]: *** [caffe2/CMakeFiles/undefined_tensor_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/test_parallel] Error 1
make[1]: *** [caffe2/CMakeFiles/test_parallel.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/net_async_tracing_test] Error 1
make[1]: *** [caffe2/CMakeFiles/net_async_tracing_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/half_test] Error 1
make[1]: *** [caffe2/CMakeFiles/half_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/wrapdim_test] Error 1
make[1]: *** [caffe2/CMakeFiles/wrapdim_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/workspace_test] Error 1
make[1]: *** [caffe2/CMakeFiles/workspace_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/batch_matmul_op_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/batch_matmul_op_gpu_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/operator_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/operator_gpu_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/reshape_op_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/reshape_op_gpu_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/utility_ops_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/utility_ops_gpu_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/int8_roi_align_op_test] Error 1
make[1]: *** [caffe2/CMakeFiles/int8_roi_align_op_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/TarjansImplTest] Error 1
make[1]: *** [caffe2/CMakeFiles/TarjansImplTest.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/net_simple_refcount_test] Error 1
make[1]: *** [caffe2/CMakeFiles/net_simple_refcount_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/mpi_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/mpi_gpu_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/module_test] Error 1
make[1]: *** [caffe2/CMakeFiles/module_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/parallel_net_test] Error 1
make[1]: *** [caffe2/CMakeFiles/parallel_net_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/operator_fallback_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/operator_fallback_gpu_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/mpi_test] Error 1
make[1]: *** [caffe2/CMakeFiles/mpi_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/observer_test] Error 1
make[1]: *** [caffe2/CMakeFiles/observer_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/graph_test] Error 1
make[1]: *** [caffe2/CMakeFiles/graph_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/string_ops_test] Error 1
make[1]: *** [caffe2/CMakeFiles/string_ops_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/transform_test] Error 1
make[1]: *** [caffe2/CMakeFiles/transform_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/roi_align_op_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/roi_align_op_gpu_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/pattern_net_transform_test] Error 1
make[1]: *** [caffe2/CMakeFiles/pattern_net_transform_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/math_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/math_gpu_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/operator_test] Error 1
make[1]: *** [caffe2/CMakeFiles/operator_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/blob_gpu_test] Error 1
make[1]: *** [caffe2/CMakeFiles/blob_gpu_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/cuda_half_test] Error 1
make[1]: *** [caffe2/CMakeFiles/cuda_half_test.dir/all] Error 2
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupEnd'
/data/zhangzy/build/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `ncclGroupStart'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/cuda_packedtensoraccessor_test] Error 1
make[1]: *** [caffe2/CMakeFiles/cuda_packedtensoraccessor_test.dir/all] Error 2
make: *** [all] Error 2
>
I am not able to continue. What is the cause of this please ?

**Comment by soulslicer** [comment]
I'm having this issue with the master branch as well right now. Did you manage to fix it?

**Comment by colesbury** [comment]
Closing as the related PR is merged. Please re-open if this is still an issue

**Comment by soulslicer** [comment]
For some reason, if you compile the latest NCCL from source and install it. Pytorch will attempt to compile and link against it and fail. I had to uninstall NCCL from /usr/local for it to work so that Pytorch would compile and link its own NCCL. Just putting it out there in case anyone has this issue
