### PR TITLE
[Abandoned] Bool cpu follow up

### PR DESCRIPTION
**Pull request by izdeby**
This is a follow up PR that resolves some additional feedback on one the of previous Bool Tensor PRs.

@gchanan, here is a list of almost all the comments from the original [PR](https://github.com/pytorch/pytorch/pull/17376) with respective fixes and replies:

**[utils/python_scalars.h] why is this converting from uint8_t and not bool? (comment?)**
When i was adding this, i was testing by creating a tensor and then calling its .tolist(). it worked for bool and uint8_t equally good so i left uint8_t as thought it makes more sense as we are calling PyBool_FromLong.  Changing it to bool.

**[ATen/Dispatch.h]better name?.** 
fixed.

**[test/test_torch.py] what about other factories, such as full? (and more).** 
There is a test that goes through the factory methods - test_tensor_factories_empty. i added some bool cases above it and added a comment that once CUDA will be done, i will unite them and it will iterate not just between CUDA and CPU but also all types.   Adding all bool cases now. Will unite in CUDA PR.

**[generic/THTensorMath.h]** any changes in this file actually needed?
Bad merge. Fixed.

**[TH/THTensor.h] this generates code for random, clampedRandom, and cappedRandom -- do we have tests for all of these with bool?** 
Added

****[c10/core/ScalarType.h]** I'm not very confident about the lack of Bool here -- can you look at the call sites and see what makes sense to do here?**
Added bool to the macro and created a similar one without for a single case which fails the build with errors: 

_./torch/csrc/jit/symbolic_variable.h:79:20: error: ambiguous overload for ‘operator*’ (operand types are ‘const torch::jit::SymbolicVariable’ and ‘torch::jit::Value*’)
     return (*this) * insertConstant(rhs);_

### CODE REVIEW

**Comment by izdeby** [comment]
@gchanan,

**[test/common_utils.py]this doesn't respect prec, but it should be easy to fix -- if prec > 1, then you can just immediately return True. Also, can you put in a TODO that says we can improve this if we support "==" or "-"?**
im not sure what is precision in a given context. what should it be checking? 

**[generic/THTensorRandom.cpp] do we still need geometric in this file? Your change makes it be generated for bool, but it doesn't seem relevant.**
Should i move it to THTensorMath?

File: aten/src/TH/generic/THTensorRandom.h [hunk 1]
```diff
@@ -6,10 +6,10 @@ TH_API void THTensor_(random)(THTensor *self, THGenerator *_generator);
 TH_API void THTensor_(clampedRandom)(THTensor *self, THGenerator *_generator, int64_t min, int64_t max);
 TH_API void THTensor_(cappedRandom)(THTensor *self, THGenerator *_generator, int64_t max);
 TH_API void THTensor_(geometric)(THTensor *self, THGenerator *_generator, double p);
+TH_API void THTensor_(uniform)(THTensor *self, THGenerator *_generator, double a, double b);
```
Comment (gchanan) [inline aten/src/TH/generic/THTensorRandom.h]: what is the motivation for this change?  It's a bit strange that we have a integer type function taking doubles.

File: c10/core/Scalar.h [hunk 2]
```diff
@@ -31,7 +31,7 @@ class C10_API Scalar {
   // We can't set v in the initializer list using the
   // syntax v{ .member = ... } because it doesn't work on MSVC
 
-  AT_FORALL_SCALAR_TYPES(DEFINE_IMPLICIT_CTOR)
+  AT_FORALL_SCALAR_TYPES_WITHOUT_BOOL(DEFINE_IMPLICIT_CTOR)
```
Comment (gchanan) [inline c10/core/Scalar.h]: If we have Bool tensors it seems to make sense that we have a constructor here that takes a bool.  Does adding one cause problems?

File: c10/core/ScalarType.h [hunk 3]
```diff
@@ -53,6 +53,17 @@ _(at::Half,Half,d) \
 _(float,Float,d)   \
 _(double,Double,d)
 
+#define AT_FORALL_SCALAR_TYPES(_) \
```
Comment (gchanan) [inline c10/core/ScalarType.h]: I think we should try to keep some fidelity with Dispatch.h  In dispatch.h ALL doesn't include BOOL, you have to use AND_BOOL.  Can we match those here?

File: test/test_torch.py [hunk 4]
```diff
@@ -2901,18 +2901,53 @@ def test_tensor_factory_cuda_type(self):
         self.assertTrue(x.is_cuda)
         torch.set_default_tensor_type(saved_type)
 
+    def test_tensor_randoms_bool(self):
+        expectedShape = (1, 2)
+
+        test = torch.rand(expectedShape, dtype=torch.bool)
+        self.assertEqual(expectedShape, test.shape)
```
Comment (gchanan) [inline test/test_torch.py]: I would expect dtype checks with all of these.

File: test/test_torch.py [hunk 5]
```diff
@@ -2901,18 +2901,53 @@ def test_tensor_factory_cuda_type(self):
...
+
+        test2 = torch.rand_like(test, dtype=torch.bool)
+        self.assertEqual(test, test2)
+
+        test = torch.rand(expectedShape, dtype=torch.bool)
+        self.assertEqual(expectedShape, test.shape)
+
+        # capped & clamped random
+        test = torch.tensor([[0, 0]], dtype=torch.bool)
+        test.random_(0, 2)
```
Comment (gchanan) [inline test/test_torch.py]: this isn't going to effect the test -- in place functions don't typically change the shape of a tensor.

File: test/test_torch.py [hunk 6]
```diff
@@ -2901,18 +2901,53 @@ def test_tensor_factory_cuda_type(self):
...
+        self.assertEqual(expectedShape, test.shape)
+
+        test.random_(2)
```
Comment (gchanan) [inline test/test_torch.py]: same here.

File: test/test_torch.py [hunk 7]
```diff
@@ -2901,18 +2901,53 @@ def test_tensor_factory_cuda_type(self):
...
     # will be done, these test cases will be moved down to test_tensor_factories_empty test
-    def test_tensor_factories_empty_bool(self):
+    def test_tensor_factories_bool(self):
         expectedShape = (1, 2)
         test = torch.empty(expectedShape, dtype=torch.bool)
         self.assertEqual(expectedShape, test.shape)
-        self.assertEqual(expectedShape, torch.empty_like(test).shape)
+
+        test2 = torch.empty_like(test, dtype=torch.bool)
+        self.assertEqual(test, test2)
```
Comment (gchanan) [inline test/test_torch.py]: same issue as above, there is no guarantee this gives you the same tensor.

File: aten/src/TH/generic/THTensorRandom.h (hunk 1 above)
Comment (izdeby) [reply aten/src/TH/generic/THTensorRandom.h]: Uniform is being used by random so i had to move it out from **#if defined(TH_REAL_IS_FLOAT) || defined(TH_REAL_IS_DOUBLE)** but now im thinking that i should put it into a **#if defined(TH_REAL_IS_FLOAT) || defined(TH_REAL_IS_DOUBLE) || defined(TH_REAL_IS_BOOL)** because it will be generated for all other types now.

Comment (gchanan) [reply aten/src/TH/generic/THTensorRandom.h]: can you link me the line where it is being used?

File: c10/core/Scalar.h (hunk 2 above)
Comment (izdeby) [reply c10/core/Scalar.h]: if i add bool here, im getting this kind of errors: 
jit/symbolic_variable.h:79:20: error: ambiguous overload for ‘operator*’ (operand types are ‘const torch::jit::SymbolicVariable’ and ‘torch::jit::Value*’)

_jit/symbolic_variable.h:126:20: error: ambiguous overload for ‘operator+’ (operand types are ‘const torch::jit::SymbolicVariable’ and ‘torch::jit::Value*’)

Im not sure if im supposed to be touching this. should i?

File: test/test_torch.py (hunk 5 above)
Comment (izdeby) [reply test/test_torch.py]: Yes, i mostly wanted to check if those calls wont fail. Im adding check for a dtype but not sure which test case/assert would do a better job here.

File: aten/src/TH/generic/THTensorRandom.h (hunk 1 above)
Comment (izdeby) [reply aten/src/TH/generic/THTensorRandom.h]: ~/local/pytorch/aten/src/ATen/native/TensorFactories.cpp, rand(IntArrayRef size, Generator* generator, const TensorOptions& options)

line 277

**Comment by izdeby** [comment]
Created a stacked [version](https://github.com/pytorch/pytorch/pull/18165) for parallel work. sorry for the inconveniences
