### ISSUE TITLE
[PyTorch CI] XPU windows build failed due to https://github.com/pytorch/pytorch/pull/185421

### ISSUE THREAD

**Issue by guangyey** [pytorch/pytorch#185753]
### Operating System

Windows

### Error Log

```bash
C:\actions-runner\_work\pytorch\pytorch\third_party\torch-xpu-ops\src\ATen\native\xpu\sycl\ResizeKernel.cpp(77,60): error: invalid operands to binary expression ('IntArrayRef' (aka 'ArrayRef<long long>') and 'at::OptionalIntArrayRef' (aka 'OptionalArrayRef<long long>'))
   77 |   if (self->sizes() == size && (!stride || self->strides() == stride)) {
```

### CI Job URL

https://github.com/pytorch/pytorch/actions/runs/26702110210/job/78696778243

### Reason not caught
Due to https://github.com/pytorch/pytorch/pull/185421
We didn't catch it earlier because the Windows CI was canceled (unstable CI) last week, so the relevant tests were not exercised.

### How to fix
1. fix the build error in torch-xpu-ops
2. update the commit pin

cc @malfet @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex @nkhasbag-nv @pytorch/pytorch-dev-infra @gujinghui @EikanWang @fengyuan14
