### ISSUE TITLE
AllenaiLongformerBase failing w/ dynamic shapes: "'Pointwise' object has no attribute 'get_stride'"

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#112913]
### 🐛 Describe the bug

`AllenaiLongformerBase` has started failing (bisected to #112119)

```
python benchmarks/dynamo/huggingface.py --performance --cold-start-latency --training --amp --backend inductor --dynamic-shapes --dynamic-batch-only --device cuda --only AllenaiLongformerBase --output bisect.csv
```

Log:

```
LoweringException: AttributeError: 'Pointwise' object has no attribute 'get_stride'
  target: aten.sym_stride.int
  args[0]: TensorBox(StorageBox(
    Pointwise(
      'cuda',
      torch.float16,
      def inner_fn(index):
          i0, i1, i2 = index
          tmp0 = ops.load(buf2, i2 + 768 * i1 + 3072 * i0)
          tmp1 = ops.load(primals_2, i2)
          tmp2 = ops.to_dtype(tmp1, torch.float16, src_dtype=torch.float32)
          tmp3 = tmp0 + tmp2
          tmp4 = ops.constant(8.0, torch.float16)
          tmp5 = tmp3 / tmp4
          return tmp5
      ,
      ranges=[1024, 4, 768],
      origin_node=div,
      origins={convert_element_type, div, add}
    )
  ))
  args[1]: 0
```

Full log:

<details>

```

loading model: 0it [00:00, ?it/s]
loading model: 0it [00:08, ?it/s]
cuda train AllenaiLongformerBase              
ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "/home/dberard/local/pytorch/benchmarks/dynamo/common.py", line 2601, in warmup
    fn(model, example_inputs)
  File "/home/dberard/local/pytorch/torch/_dynamo/eval_frame.py", line 410, in _fn
    return fn(*args, **kwargs)
  File "/home/dberard/local/pytorch/benchmarks/dynamo/huggingface.py", line 560, in forward_and_backward_pass
    cloned_inputs = clone_inputs(inputs)
  File "/home/dberard/local/pytorch/benchmarks/dynamo/huggingface.py", line 561, in resume_in_forward_and_backward_pass
    self.optimizer_zero_grad(mod)
  File "/home/dberard/local/pytorch/benchmarks/dynamo/huggingface.py", line 563, in resume_in_forward_and_backward_pass
    pred = mod(**cloned_inputs)
  File "/home/dberard/local/pytorch/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dberard/local/pytorch/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dberard/local/miniconda3/envs/pytorch/lib/python3.10/site-packages/transformers/models/longformer/modeling_longformer.py", line 1844, in forward
    outputs = self.longformer(
  File "/home/dberard/local/pytorch/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dberard/local/pytorch/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dberard/local/miniconda3/envs/pytorch/lib/python3.10/site-packages/transformers/models/longformer/modeling_longformer.py", line 1747, in forward
    encoder_outputs = self.encoder(
  File "/home/dberard/local/pytorch/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dberard/local/pytorch/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dberard/local/miniconda3/envs/pytorch/lib/python3.10/site-packages/transformers/models/longformer/modeling_longformer.py", line 1291, in forward
    is_global_attn = is_index_global_attn.flatten().any().item()
  File "/home/dberard/local/pytorch/torch/_dynamo/eval_frame.py", line 558, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/dberard/local/pytorch/torch/_dynamo/convert_frame.py", line 687, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/home/dberard/local/pytorch/torch/_dynamo/convert_frame.py", line 148, in _fn
    return fn(*args, **kwargs)
  File "/home/dberard/local/pytorch/torch/_dynamo/convert_frame.py", line 406, in _convert_frame_assert
    return _compile(
  File "/home/dberard/local/pytorch/torch/_dynamo/convert_frame.py", line 614, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/dberard/local/pytorch/torch/_dynamo/utils.py", line 221, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/dberard/local/pytorch/torch/_dynamo/convert_frame.py", line 531, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/dberard/local/pytorch/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/home/dberard/local/pytorch/torch/_dynamo/convert_frame.py", line 501, in transform
    tracer.run()
  File "/home/dberard/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2118, in run
    super().run()
  File "/home/dberard/local/pytorch/torch/_dynamo/symbolic_convert.py", line 752, in run
    and self.step()
  File "/home/dberard/local/pytorch/torch/_dynamo/symbolic_convert.py", line 715, in step
    getattr(self, inst.opname)(inst)
  File "/home/dberard/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2229, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/dberard/local/pytorch/torch/_dynamo/output_graph.py", line 896, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/dberard/local/miniconda3/envs/pytorch/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/dberard/local/pytorch/torch/_dynamo/output_graph.py", line 998, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/dberard/local/pytorch/torch/_dynamo/utils.py", line 221, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/dberard/local/pytorch/torch/_dynamo/output_graph.py", line 1069, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/dberard/local/pytorch/torch/_dynamo/output_graph.py", line 1050, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/dberard/local/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/dberard/local/pytorch/torch/_dynamo/backends/inductor.py", line 9, in inductor
    return compile_fx(*args, **kwargs)
  File "/home/dberard/local/pytorch/torch/_inductor/compile_fx.py", line 1225, in compile_fx
    return aot_autograd(
  File "/home/dberard/local/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/dberard/local/pytorch/torch/_functorch/aot_autograd.py", line 4798, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/dberard/local/pytorch/torch/_dynamo/utils.py", line 221, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/dberard/local/pytorch/torch/_functorch/aot_autograd.py", line 4336, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/dberard/local/pytorch/torch/_functorch/aot_autograd.py", line 2685, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/dberard/local/pytorch/torch/_functorch/aot_autograd.py", line 2872, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/dberard/local/pytorch/torch/_functorch/aot_autograd.py", line 3703, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(
  File "/home/dberard/local/pytorch/torch/_dynamo/utils.py", line 221, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/dberard/local/pytorch/torch/_inductor/compile_fx.py", line 1158, in fw_compiler_base
    return inner_compile(
  File "/home/dberard/local/pytorch/torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/dberard/local/pytorch/torch/_inductor/debug.py", line 303, in inner
    return fn(*args, **kwargs)
  File "/home/dberard/local/miniconda3/envs/pytorch/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/dberard/local/pytorch/torch/_inductor/compile_fx.py", line 390, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/home/dberard/local/pytorch/torch/_inductor/compile_fx.py", line 599, in fx_codegen_and_compile
    graph.run(*example_inputs)
  File "/home/dberard/local/pytorch/torch/_dynamo/utils.py", line 221, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/dberard/local/pytorch/torch/_inductor/graph.py", line 431, in run
    return super().run(*args)
  File "/home/dberard/local/pytorch/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/home/dberard/local/pytorch/torch/_inductor/graph.py", line 733, in run_node
    result = super().run_node(n)
  File "/home/dberard/local/pytorch/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/dberard/local/pytorch/torch/_inductor/graph.py", line 603, in call_function
    raise LoweringException(e, target, args, kwargs).with_traceback(
  File "/home/dberard/local/pytorch/torch/_inductor/graph.py", line 600, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/home/dberard/local/pytorch/torch/_inductor/lowering.py", line 288, in wrapped
    out = decomp_fn(*args, **kwargs)
  File "/home/dberard/local/pytorch/torch/_inductor/lowering.py", line 5036, in sym_stride
    return a.get_stride()[dim]
  File "/home/dberard/local/pytorch/torch/_inductor/ir.py", line 5909, in __getattr__
    fn = getattr(self.data, name)
  File "/home/dberard/local/pytorch/torch/_inductor/ir.py", line 5909, in __getattr__
    fn = getattr(self.data, name)
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: AttributeError: 'Pointwise' object has no attribute 'get_stride'
  target: aten.sym_stride.int
  args[0]: TensorBox(StorageBox(
    Pointwise(
      'cuda',
      torch.float16,
      def inner_fn(index):
          i0, i1, i2 = index
          tmp0 = ops.load(buf2, i2 + 768 * i1 + 3072 * i0)
          tmp1 = ops.load(primals_2, i2)
          tmp2 = ops.to_dtype(tmp1, torch.float16, src_dtype=torch.float32)
          tmp3 = tmp0 + tmp2
          tmp4 = ops.constant(8.0, torch.float16)
          tmp5 = tmp3 / tmp4
          return tmp5
      ,
      ranges=[1024, 4, 768],
      origin_node=div,
      origins={convert_element_type, div, add}
    )
  ))
  args[1]: 0

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

```

</details>

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### Versions

`db66f15785e` = hash for the nightly dashboard run on nov 02

**Comment by ezyang** [comment]
I will get to this probably this week
