### PR TITLE
Update torch-xpu-ops commit pin

### LINKED ISSUE #185367: DISABLED test_comprehensive_native_group_norm_xpu_float16 (__main__.TestInductorOpInfoXPU)
Platforms: xpu

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22test%2Finductor%2Ftest_torchinductor_opinfo.py%3A%3ATestInductorOpInfoXPU%3A%3Atest_comprehensive_native_group_norm_xpu_float16%22%5D)).

cc @mruberry @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @kadeng @muchulee8 @amjames @aakhundov @coconutruben @jataylo @gujinghui @fengyuan14

### LINKED ISSUE #185753: [PyTorch CI] XPU windows build failed due to https://github.com/pytorch/pytorch/pull/185421
### Operating System

Windows

### Error Log

```bash
C:\actions-runner\_work\pytorch\pytorch\third_party\torch-xpu-ops\src\ATen\native\xpu\sycl\ResizeKernel.cpp(77,60): error: invalid operands to binary expression ('IntArrayRef' (aka 'ArrayRef<long long>') and 'at::OptionalIntArrayRef' (aka 'OptionalArrayRef<long long>'))
   77 |   if (self->sizes() == size && (!stride || self->strides() == stride)) {
```

### CI Job URL

https://github.com/pytorch/pytorch/actions/runs/26702110210/job/78696778243

### Reason not caught
Due to https://github.com/pytorch/pytorch/pull/185421
We didn't catch it earlier because the Windows CI was canceled (unstable CI) last week, so the relevant tests were not exercised.

### How to fix
1. fix the build error in torch-xpu-ops
2. update the commit pin

cc @malfet @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex @nkhasbag-nv @pytorch/pytorch-dev-infra @gujinghui @EikanWang @fengyuan14

### PR DESCRIPTION
**Pull request by CuiYifeng**
Update the torch-xpu-ops commit to [intel/torch-xpu-ops@f1f4ce](https://github.com/intel/torch-xpu-ops/commit/f1f4ce749cf80c2e524c7a02294baf5e329ac57d), includes:

- Fix Windows build error in ResizeKernel.cpp caused by hidden-friend operator== ADL resolution
- Fix group_norm accuracy by using acc_type for accumulation
- Fix LSTM fused cell bias handling by checking each bias pointer independently to avoid skipping valid bias2
- Implement fused adagrad operator for XPU
- Rewrite nonzero kernel to use bounded scratch memory with a two-pass chunked algorithm

# Additional Context
fix https://github.com/pytorch/pytorch/issues/185753
fix https://github.com/pytorch/pytorch/issues/185367

### CODE REVIEW

**Comment by guangyey** [comment]
Added fix message to description.

**Review by guangyey — APPROVED** [review]

**Review by EikanWang — APPROVED** [review]

**Comment by guangyey** [comment]
We should land this PR soon; the CI/CD has been broken for about 3 days.

**Comment by guangyey** [comment]
@chuanqi129 manywheel ci test failed.

**Comment by chuanqi129** [comment]
> @chuanqi129 manywheel ci test failed.

The py315 & 315t failure caused by the PR https://github.com/pytorch/pytorch/pull/185094 to enable triton-xpu build, we can ignore those 2 failure on this PR. I will draft another to fix it if need

**Comment by guangyey** [comment]
Thanks, let's land this PR as CI/CD should be fixed ASAP.
@pytorchbot merge -i
