### PR TITLE
Fix InternalTorchDynamoError on attribute access of a compiled method

### LINKED ISSUE #190171: torch.compile: InternalTorchDynamoError ('method' object has no attribute '__dict__') when tracing inspect.getfullargspec on a bound method
## 🐛 Describe the bug

Calling `inspect.getfullargspec()` on a bound method inside a compiled region raises an `InternalTorchDynamoError` on PyTorch 2.12 and 2.13. The same code works on 2.11 and earlier, where Dynamo graph-breaks on `inspect` and runs it eagerly.

The trigger needs the bound method to have been wrapped by Dynamo and then unwrapped again via `__wrapped__` before it's passed to `getfullargspec` — i.e. `obj.meth = compiled.dynamo_ctx(obj.meth)`, then `meth.__wrapped__`. This isn't contrived; it's what PyTorch Lightning does when a compiled model logs a metric (see the last section).

Minimal, self-contained reproducer (no third-party deps):

```python
import inspect
import torch


def takes_param(fn, name):
    if hasattr(fn, "__wrapped__"):
        fn = fn.__wrapped__          # dynamo ctx -> original bound method
    return name in inspect.getfullargspec(fn).args


class Model(torch.nn.Module):
    def step(self, x):
        takes_param(self.step, "dataloader_iter")   # introspect a bound method mid-trace
        return x * 2

    def forward(self, x):
        return self.step(x)


model = Model()
compiled = torch.compile(model)
model.step = compiled.dynamo_ctx(model.step)   # rebind step as a dynamo-wrapped method

compiled(torch.randn(4))
```

This is a tracing-stage failure, so it's independent of the backend — it reproduces with the default backend and never reaches a compiled graph.

I traced it into `torch/_dynamo/variables/dicts.py`. When Dynamo emulates the `obj.__signature__` lookup that `inspect._signature_from_callable` performs, it reaches `SideEffectsProxyDict.get_example_value_dict`, which does `object.__getattribute__(value, "__dict__")`. `method` objects have no `__dict__`, so this raises a raw `AttributeError` that escapes as `InternalTorchDynamoError` instead of either graph-breaking or being surfaced as an in-graph `AttributeError` that the `try/except` in `_signature_from_callable` would catch.

Possibly related but distinct: #147201 — same function, but that was an `Unsupported: 'skip function getfullargspec'` graph-break on a plain function and is closed as non-reproducible. This is a hard `InternalTorchDynamoError` on a **bound method**, new in 2.12.

## Error logs

```
  File ".../torch/_dynamo/variables/dicts.py", line 1430, in get_example_value_dict
    return object.__getattribute__(value, "__dict__")
torch._dynamo.exc.InternalTorchDynamoError: AttributeError: 'method' object has no attribute '__dict__'

from user code:
   File "repro.py", line 15, in forward
     return self.step(x)
   File "repro.py", line 11, in step
     takes_param(self.step, "dataloader_iter")
   File "repro.py", line 7, in takes_param
     return name in inspect.getfullargspec(fn).args
   File ".../inspect.py", line 1391, in getfullargspec
     sig = _signature_from_callable(func, ...)
   File ".../inspect.py", line 2547, in _signature_from_callable
     sig = obj.__signature__
```

## Versions

Observed across versions:

| torch  | result                                        |
| ------ | --------------------------------------------- |
| 2.11.0 | works (graph-breaks on `inspect`, runs eager) |
| 2.12.0 | `InternalTorchDynamoError`                     |
| 2.13.0 | `InternalTorchDynamoError`                     |

I reproduced the error locally on 2.13.0; the 2.12 failure was observed in CI, and 2.11 and earlier are unaffected (the same code path has been green there).

Environment where I reproduced it (from `collect_env.py`):

```
PyTorch version: 2.13.0
Is CUDA available: False
Python version: 3.12.12
OS: macOS-26.3-arm64-arm-64bit
```

## Where this shows up in practice

PyTorch Lightning hits this whenever a `torch.compile`d model calls `self.log()` during training. It rebinds the step methods to Dynamo-wrapped versions in [`compile.py`](https://github.com/Lightning-AI/pytorch-lightning/blob/master/src/lightning/pytorch/utilities/compile.py) and then introspects the step signature inside `self.log()` via [`is_param_in_hook_signature`](https://github.com/Lightning-AI/pytorch-lightning/blob/master/src/lightning/pytorch/utilities/signature_utils.py) — the `__wrapped__` + `getfullargspec` sequence above. Downstream tracking issue: https://github.com/Lightning-AI/pytorch-lightning/issues/21836.

---

> _Disclosure per the repo's [AI policy](https://github.com/pytorch/pytorch/blob/main/AI_POLICY.md): I used Claude Code to help investigate and draft this report. I reproduced the failure locally on 2.13.0, saw the 2.12 failure in CI, and reviewed the root-cause pointer into `dicts.py` myself._

cc @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @kadeng @amjames @jataylo @azahed98

### PR DESCRIPTION
**Pull request by JaimeLucero**
Fixes #190171

## The bug

`torch.compile(obj.meth)` stores the bound method in the wrapper's `_torchdynamo_inline` attribute. When traced code reads any attribute off that wrapper, Dynamo materializes the backing object's instance dict at `dicts.py:1431`:

```python
return object.__getattribute__(value, "__dict__")
```

and that raises `AttributeError: 'method' object has no attribute '__dict__'`, which escapes as `InternalTorchDynamoError` because the graceful `unimplemented()` beside it only guards the `NO_SUCH_SUBOBJ` branch.

## Root cause

`object.__getattribute__` deliberately bypasses the type's `tp_getattro`. That bypass is **correct for user-defined classes** — a custom `__getattribute__` must not be able to lie to Dynamo about the instance dict — and it was generalized to every type.

But a `method` owns no `__dict__` slot at all:

```python
>>> '__dict__' in type(c.meth).__dict__
False
>>> c.meth.__dict__ is c.meth.__func__.__dict__
True
```

`m.__dict__` resolves only because `method`'s `tp_getattro` forwards the lookup to `__func__`, and it returns *the very same dict object* the function owns. This is by design: a method is rebuilt on every attribute access (`c.meth is c.meth` is `False`), so storage of its own would evaporate; CPython gives it none and forwards instead.

So bypassing the forwarding skips the only route to a dict that genuinely exists. CPython's `AttributeError` is the correct answer to the wrong question — Dynamo asked "what storage is inside this method object?" (truthfully: none) and concluded "therefore it has no `__dict__`".

## The fix

Two shapes, because two different kinds of caller reach this pattern.

**`variables/dicts.py` — `get_example_value_dict` (the read path).** Here the unit is a `VariableTracker`, not a raw object. For `WrapperUserFunctionVariable`, `get_real_python_backed_value` returns the *inline target* (the method), but `vt.source` denotes the *wrapper*, and `get_value___dict__` gives every key a source underneath it. Reading the target's dict would pair values from one object with sources naming another, and Dynamo would build guards for a relationship that never held. So it reads the wrapper's own `__dict__` — the object `vt.source` designates:

```python
if isinstance(vt, variables.WrapperUserFunctionVariable):
    return object.__getattribute__(vt.wrapper_obj, "__dict__")
```

The wrapper is a plain function and owns a real dict, so no `method` reaches `object.__getattribute__` on this path at all.

**`utils.py` — `object_setattr_ignore_descriptor` / `object_delattr_ignore_descriptor` (the side-effect replay paths).** These take *real runtime objects*, not tracked values, so there is no source to stay consistent with. They follow `__func__` directly, which matches eager — writing through `method.__dict__` writes to the function's dict:

```python
if isinstance(obj, types.MethodType):
    obj = obj.__func__
```

Both helpers already special-case `threading.local` for the same underlying reason: `object.__getattribute__` cannot see its dict either.

### Alternative considered

Unwrapping inside `WrapperUserFunctionVariable.get_real_python_backed_value` so it returns `__func__` rather than the method. Rejected: that accessor has many callers which perform identity and `issubclass` checks and legitimately need the real method object. The repair belongs at the `__dict__`-materialization sites.

## Scope is wider than the issue reports

Measured on 2.13.0 and on nightly `2.14.0.dev20260715`:

| case | before |
| --- | --- |
| `nn.Module` bound method (reported) | crash |
| plain-class bound method | crash — not `nn.Module`-specific |
| **classmethod** | crash — not mentioned in the issue |
| staticmethod / free function / lambda / `functools.partial` | ok |

Anything producing a `method` object is affected, so classmethods are included (`C.cls_meth` is a `method` bound to the class). staticmethods and plain functions are safe because they *are* functions and own a `__dict__`.

It is also **not** specific to `dynamo_ctx` or to `inspect.getfullargspec`. Plain `torch.compile(obj.meth)` reproduces it with no `dynamo_ctx` involved, and every attribute name reaches the same path — even `__name__`, which is explicitly handled at `functions.py:468` but only *after* `getattro_impl` materializes `__dict__` at line 465. `getfullargspec` is simply how pytorch-lightning happens to arrive there.

## Regression

Introduced by #177658, which made `SideEffectsProxyDict` materialize `__dict__` eagerly at construction. Confirmed against released wheels on Python 3.12.12 with the reporter's reproducer:

| torch | result |
| --- | --- |
| 2.11.0 | ok |
| 2.12.0 | `InternalTorchDynamoError` |
| 2.13.0 | `InternalTorchDynamoError` |
| 2.14.0.dev20260715 | `InternalTorchDynamoError` |

That PR added the same accessor to `UserMethodVariable` returning the underlying function (safe), but the `WrapperUserFunctionVariable` one can return a method. Fixing the replay paths additionally makes that PR's own `test_method_dunder_dict_setitem` reproducer pass, so its `unittest.expectedFailure` is removed.

## Tests

`test/dynamo/test_repros.py`:

- `test_getattr_on_compiled_method` — parametrized over `nn.Module` method, plain-class method, classmethod, plus staticmethod and free function as controls
- `test_getfullargspec_on_dynamo_ctx_method` — the pytorch-lightning shape end-to-end
- `test_method_dunder_dict_setitem` — `expectedFailure` removed

The tests were checked to actually discriminate rather than merely pass: with the fix all seven cases pass; without it the five method-based cases fail and both controls still pass. They assert eager/compiled agreement rather than absence of a raise, since crash-free-but-wrong-answer is the failure mode worth locking down.

## Note for reviewers

Local verification applied this patch to a 2.13.0 wheel, as a source build was not available on the machine used. The touched functions and the `side_effects.py` codegen gate are byte-identical between that wheel and this branch's base, and the nested-graph-breaks configuration was reproduced locally via `config.patch`.

Worth knowing: an earlier revision of this PR read the *inline target's* `__dict__` instead of the wrapper's. It passed the default config and every local test, but produced a guard over values and sources that described different objects — and only `test_nested_graph_breaks_wrapped.py` (which auto-derives `ReproTests` under `nested_graph_breaks` + `debug_force_nested_calls`) surfaced it, as `Guard failed on the same frame it was created`. That is why the read path keys off `vt.source` rather than unwrapping the method.

`lintrunner` reports no new findings for the touched files (identical error count with and without the change; the remainder are pre-existing PYREFLY resolution errors from the unbuilt tree).

## Related

- Downstream tracking: https://github.com/Lightning-AI/pytorch-lightning/issues/21836
- Separate, not addressed here: `hasattr(wrapper, "__wrapped__")` returns `True` in eager but `False` under Dynamo, because `BaseUserFunctionVariable.call_obj_hasattr` introspects `get_function()` (the inlined target) rather than the wrapper. It is harmless for the reported case — the divergences cancel, so this fix alone makes the lightning predicate agree with eager — and arguably intentional, since `WrapperUserFunctionVariable` exists to make wrappers transparent for inlining. Flagging it for owners rather than changing it here.

---

This change was authored with the assistance of an AI coding agent, per the repository's AI policy.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @kadeng @chauhang @amjames @jataylo @azahed98

### CODE REVIEW

**Comment by JaimeLucero** [comment]
@guilhermeleobas @Lucaskabela this fixes a regression from #177658. `method` owns no `__dict__` slot -- it forwards attribute lookups to `__func__` -- so the eager materialization in `SideEffectsProxyDict` hits `object.__getattribute__(method, "__dict__")` and raises. It also makes the `test_method_dunder_dict_setitem` reproducer from that PR pass, so I removed the `expectedFailure`.

Could someone approve the workflows? I do not have access to trigger CI.

**Comment by JaimeLucero** [comment]
Pushed `2e577df` — this fixes the CI failure from the previous commit, so the red run above is stale.

**What failed:** `test_nested_graph_breaks_wrapped.py::NestedGraphBreaksReproTests::test_getfullargspec_on_dynamo_ctx_method_nested_graph_breaks`, on all 6 jobs, with:

```
AssertionError: Guard failed on the same frame it was created. This is a bug.
Guard fail reason: fn.__self__.step._torchdynamo_inline.__closure__[0].cell_contents
                     is fn.__self__.step.__dict__['__wrapped__']
```

**Why:** my first revision read the *inline target's* `__dict__` in `get_example_value_dict`. But for `WrapperUserFunctionVariable`, `vt.source` denotes the **wrapper**, and `get_value___dict__` gives every key a source underneath it — so values came from the target's function dict (empty) while the sources named the wrapper's (8 keys). Dynamo then built a guard over a relationship that never held, hence it failing on the frame that created it.

**Fix:** read the `__dict__` of the object `vt.source` actually denotes:

```python
if isinstance(vt, variables.WrapperUserFunctionVariable):
    return object.__getattribute__(vt.wrapper_obj, "__dict__")
```

That also subsumes the original crash — the wrapper is a plain function and owns a real `__dict__`, so no `method` reaches `object.__getattribute__` on that path. The `__func__` hop remains only in the two `utils.py` replay helpers, which take real runtime objects and have no source to stay consistent with.

Reproduced the nested-graph-breaks config locally via `config.patch` and confirmed it now passes under both default and nested settings.

@guilhermeleobas @Lucaskabela the workflows need approval again for the new commit — the previous approval expired with the old SHA. I do not have access to trigger CI.

**Comment by jansel** [comment]
@claude review these changes

**Comment by JaimeLucero** [comment]
CI is green on `2e577df` — 209 passing, 0 failing (the two non-green entries are `lintrunner-clang-partial`, skipped since nothing under clang's scope changed, and the Dr.CI bot's neutral status).

@jansel thanks for running the review. Addressing its one actionable point, since I think it resolves in favor of the current shape:

The review is right that the `dicts.py` branch fires for all three `WrapperUserFunctionVariable` kinds, not only `_torchdynamo_inline`. That is intentional, and it is the same argument the PR makes for the compiled-method case. `get_value___dict__` sources every key as `DictGetItemSource(AttrSource(vt.source, "__dict__"), key)`, and `vt.source` denotes the **wrapper** for all three. Reading `get_real_python_backed_value().__dict__` pairs values from the inline target with sources naming the wrapper regardless of which wrapper kind it is — the compiled-method case is just the one where the target additionally has no `__dict__` to read, so it crashes loudly instead of quietly building a guard over a relationship that never held.

On whether the other two wrappers reliably return a dict from `object.__getattribute__` — they do. Measured on 2.13.0:

```
lru_cache wrapper:          8 keys  ['__annotations__', '__doc__', '__module__', '__name__', '__qualname__', ...]
script_if_tracing wrapper:  3 keys  ['__original_fn', '__script_if_tracing_wrapper', '__wrapped__']
```

Both are `update_wrapper`'d and own real instance dicts, so neither reaches the `method` failure mode. Reading `__name__` and `__qualname__` off each inside a `fullgraph=True` region agrees with eager both with and without this patch — the broadening changes which object is read, but for these two kinds the previous read happened to be source-inconsistent-but-harmless rather than wrong, and it stays correct now for a better reason.

Happy to add the suggested lru_cache regression test to lock that down — say the word and I'll push it, though I'd otherwise prefer to keep this SHA green and send it as a follow-up rather than re-trigger the full run plus workflow approval.

Would you be willing to approve and merge if this looks right? I don't have write access, so I can't drive `@pytorchbot merge` myself.

File: torch/_dynamo/variables/dicts.py [hunk 1]
```diff
@@ -1423,6 +1423,13 @@ def get_example_value_dict(vt: VariableTracker) -> dict[str, object]:
         elif isinstance(vt, variables.LocalGeneratorFunctionVariable):
             return SideEffectsProxyDict.get_example_value_dict(vt.vt)
         else:
+            if isinstance(vt, variables.WrapperUserFunctionVariable):
+                # get_real_python_backed_value returns the inline target, which
+                # may be a method and owns no __dict__ of its own. vt.source
+                # denotes the wrapper, and the keys below are given sources under
+                # it, so read the wrapper's __dict__ to keep values and sources
+                # describing the same object.
+                return object.__getattribute__(vt.wrapper_obj, "__dict__")
```
Comment (guilhermeleobas) [inline torch/_dynamo/variables/dicts.py]: I think we need to actually fix the object returned by `get_real_python_backed_value()` instead of adding a special case here.

**Review by guilhermeleobas — COMMENTED** [review]
The `get_real_python_backed_value()` was originally written to fix the `a is b` case and we extended to use in other places. Given this, I think the python backed value returned in some variable trackers is wrong:

```python
import functools

import torch
from torch.jit import _script_if_tracing


def check(kind):
    def g(x):
        return x + 1

    if kind == "compile":
        wrapped = torch.compile(g, backend="eager")
    elif kind == "lru_cache":
        wrapped = functools.lru_cache(g)
    elif kind == "script_if_tracing":
        wrapped = _script_if_tracing(g)
    else:
        raise ValueError(kind)

    def fn(x):
        return x + 1, (wrapped is g), (g is wrapped)

    x = torch.zeros(1)
    eager = fn(x)
    compiled = torch.compile(fn, backend="eager", fullgraph=True)(x)

    agree = eager[1:] == compiled[1:]
    print(f"{kind:20s} eager(wrapped is g)={eager[1]!s:5}  "
        f"compiled={compiled[1]!s:5}  agree={agree}")
    return agree


if __name__ == "__main__":
    results = [check(k) for k in ("compile", "lru_cache", "script_if_tracing")]
    if all(results):
        print("\nALL AGREE -- bug fixed")
    else:
        print("\nDIVERGENCE -- get_real_python_backed_value returns the target, not the wrapper")
```

With this in mind, perhaps we should actually fix `get_real_python_backed_value` instead of adding special cases everywhere.

**Comment by JaimeLucero** [comment]
Good call, I went with that.

  `get_real_python_backed_value` now returns `self.wrapper_obj`. That's what `source` points at anyway, so the special case in `dicts.py` is gone. The generic path handles it: wrappers are either plain functions or `_lru_cache_wrapper`, both of which have a real `__dict__`.

  Your repro agrees with eager on all three kinds now.

  It also explains the CI failure on my previous revision, which was an `is` guard:

  ```
  fn.__self__.step._torchdynamo_inline.__closure__[0].cell_contents
    is fn.__self__.step.__dict__['__wrapped__']
  ```

  Reproduces before the change, clean after, both default config and `nested_graph_breaks`.

  I also dropped the two `utils.py` hunks and put the `expectedFailure` back on `test_method_dunder_dict_setitem`. Couldn't convince myself those hunks were reachable: both call sites sit behind `isinstance(var, UserDefinedObjectVariable)`
and `UserMethodVariable` isn't one. Whether that path can replay at all is probably its own bug.

  Same issue exists in `UserMethodVariable.get_real_python_backed_value`, which
  returns `self.fn` while the source is the bound method, so `obj.meth is obj.meth` folds to True. Wants a different fix though, since bound methods get rebuilt on every access. I'll do it separately.

  Rebased on main. No local build on my end, so CI is the first real run of these. Can someone approve the workflows?

**Review by guilhermeleobas — APPROVED** [review]

**Comment by guilhermeleobas** [comment]
Thanks @JaimeLucero. Once CI passes, ping me and I can merge it

**Comment by JaimeLucero** [comment]
@guilhermeleobas the CI passed, PR is ready to merge now. Thank you
