### PR TITLE
IR serialization / deserialization via protobuf

### PR DESCRIPTION
**Pull request by lantiga**
Addresses #5757

This PR
- adds a `export_raw_ir` flag to `export` functions to avoid the ONNX pass altogether and output IR nodes in ONNX protobufs;
- adds `ir_import.cpp` that exposes an `ImportIRGraph` function; the function loads the serialized IR (+ eventual initializers) back into a graph using `nanopb`
- deserializes graphs as attributes recursively
- manages blocks (e.g. if conditions, while loops)
- exposes `ImportIRGraph` to Python through `pybind11`
- adds "graph -> proto -> graph" roundtrip tests in `test_jit.py`

### CODE REVIEW

File: tools/cpp_build/build_common.sh [hunk 1]
```diff
@@ -31,14 +32,15 @@ BUILD_TYPE=${BUILD_TYPE:-Debug}
...
   # https://stackoverflow.com/questions/1715580/how-to-discover-number-of-logical-cores-on-mac-os-x
   JOBS="$(sysctl -n hw.ncpu)"
 fi
 set -e
-if [[ $? -ne 0 ]]; then
-  JOBS=4
-fi
+#if [[ $? -ne 0 ]]; then
+#  JOBS=4
+#fi
```
Comment (apaszke) [inline tools/cpp_build/build_common.sh]: Why did this change?

File: tools/cpp_build/src/import.cpp [hunk 2]
```diff
@@ -0,0 +1,462 @@
...
+  return true;
+}
+
+}
+
+void ImportGraph(std::string& serialized_graph,
+                 std::shared_ptr<Graph>& graph,
+                 std::vector<at::Tensor>& initializers) {
+
+  pb_istream_t istream = pb_istream_from_buffer(reinterpret_cast<pb_byte_t *>(&serialized_graph[0]), serialized_graph.size());
```
Comment (apaszke) [inline tools/cpp_build/src/import.cpp]: Why can't we use `serialized_graph.data()`?

File: tools/cpp_build/src/import.cpp [hunk 3]
```diff
@@ -0,0 +1,462 @@
...
+			break;
+    default:
+      throw std::runtime_error("Unsupported data type");
+  }
+
+  tensor.resize_(dims);
+
+  JIT_ASSERT(tensor.storage()->size() * tensor.storage()->elementSize() == raw_data.size());
+
+  std::memcpy(tensor.data_ptr(), &raw_data[0], raw_data.size());
```
Comment (apaszke) [inline tools/cpp_build/src/import.cpp]: Couldn't we use `raw_data.data()` here?

File: tools/cpp_build/src/import.cpp [hunk 4]
```diff
@@ -0,0 +1,462 @@
...
+  std::vector<AttributeValue*> attrs;
+  proto.attribute.funcs.decode = &decode_attribute;
+  proto.attribute.arg = &attrs;
+
+  if (!pb_decode(stream, onnx_NodeProto_fields, &proto)) {
+    return false;
+  }
+
+	assert(op_type != "CppOp");
+	assert(op_type != "PythonOp");
```
Comment (apaszke) [inline tools/cpp_build/src/import.cpp]: `asserts` are usually compiled away, use `TORCH_ASSERT`

**Review by apaszke — COMMENTED** [review]
I skimmed over the code and it looks ok to me. cc @ezyang who wrote some neat C++ wrappers for nanopb, and to review ONNX + build code

File: tools/cpp_build/build_common.sh (hunk 1 above)
Comment (lantiga) [reply tools/cpp_build/build_common.sh]: I fixed this #6420, I'm removing this change.

File: tools/cpp_build/src/import.cpp (hunk 2 above)
Comment (lantiga) [reply tools/cpp_build/src/import.cpp]: Done

File: tools/cpp_build/src/import.cpp (hunk 3 above)
Comment (lantiga) [reply tools/cpp_build/src/import.cpp]: Done

File: tools/cpp_build/src/import.cpp (hunk 4 above)
Comment (lantiga) [reply tools/cpp_build/src/import.cpp]: Done

**Comment by ezyang** [comment]
@apaszke Do you know what's going on with the dispatcher? I'd have to dig into the code to find out, and it looks like you may have missed that part of the PR description.

**Comment by apaszke** [comment]
I read that part but I don't really know. Should we even have `_convolution` in our traces? I don't really know what this function is supposed to do. Is this a generic interface for all `convNd`?

**Comment by ezyang** [comment]
Yes, that's right.

**Comment by apaszke** [comment]
It's true that there's no `_convolution-2-...`, but there is a `_convolution-3-...` op. I just traced ResNet18 and it's also using `aten::_convolution`, but one of the inputs (bias) is always coming from the `Undefined` nodes. It's possible that the exporter is removing them somehow

**Comment by lantiga** [comment]
I added the printout of the same trace before exporting from Python (https://gist.github.com/lantiga/81251e7338adb93fa9dc55c2013cf22b).

**Comment by lantiga** [comment]
@apaszke a-ha!

**Comment by lantiga** [comment]
Ok, so it is my fault. My code doesn't deal with `Undefined` yet. It doesn't deserializes them, so the dispatch doesn't see them and the dispatch fails.
Thanks a lot @apaszke and @ezyang!

**Comment by lantiga** [comment]
Ok , `resnet18` now runs correctly from `libtorch`.

**Review by apaszke — COMMENTED** [review]
I thought a bit about having a more automatic interface for reading the graph and [this is what I came up with](https://godbolt.org/g/xYKbJm). It's more declarative, and will take care of all the pointer casts and callback initializations. Let me know what you think!

**Comment by lantiga** [comment]
This is great @apaszke! I’ll refactor the code to use this approach over the weekend.
Thanks a lot for looking into this.

**Review by ezyang — DISMISSED** [review]
Changes planned c.f. @apaszke's comment

**Comment by lantiga** [comment]
@ezyang I'm halfway through the changes. I'll find some time in the next couple of days, sorry if it's taking a while.

**Comment by lantiga** [comment]
Refactoring completed. If this looks good, I'll go ahead and complete handling of blocks/subgraphs, move `import.cpp` and `import.h` under `torch/csrc/jit` and write proper tests.

**Comment by lantiga** [comment]
@ezyang CI looks jammed, should I close the PR and resubmit a new one?

**Comment by lantiga** [comment]
@ezyang, just FYI: ATen fails to build on `pr/pytorch-linux-trusty-py3.6-gcc5.4`
```
In file included from generic/THTensorMath.c:1:0,
14:23:40                  from /var/lib/jenkins/workspace/aten/src/TH/THGenerateIntTypes.h:10,
14:23:40                  from /var/lib/jenkins/workspace/aten/src/TH/THGenerateAllTypes.h:11,
14:23:40                  from /var/lib/jenkins/workspace/aten/src/TH/THTensor.cpp:31:
14:23:40 /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.c:3868:86: error: macro "TH_TENSOR_APPLY_REDUCTION_OMP" requires 5 arguments, but only 4 given
14:23:40      TH_TENSOR_APPLY_REDUCTION_OMP(real, tensor, &&:prod, prod = prod && *tensor_data;);
```

**Comment by apaszke** [comment]
Master was broken for a moment, but it’s already fixed. A rebase will fix it for you

**Comment by lantiga** [comment]
Thanks! Since we're at it: tests should hopefully pass now (they do on my CUDA 9.0 instance).
If this is true, the PR is complete on my end.

Since we're at it, writing tests have unearthed a possible JIT bug. Running GraphExecutor on a trace after a fuse pass leads to a segfault (it's unrelated to this PR).
```
torch._C._jit_pass_fuse(trace.graph())
graph = trace.graph()
ge = torch._C.GraphExecutor(graph, False)
out = ge(*inputs)
```
Does this ring a bell?

**Comment by lantiga** [comment]
Failure seems unrelated

**Comment by lantiga** [comment]
Ok, tests pass 🎉! Ready for review.

(The possible JIT bug above is still applicable, but it's outside of the scope of this PR)

File: tools/cpp_build/build_common.sh [hunk 5]
```diff
@@ -34,11 +35,8 @@ set +e
...
   JOBS="$(grep -c '^processor' /proc/cpuinfo)"
-else # if [[ "$(uname)" -eq "Darwin"]]
+else # if [[ "$(uname)" == "Darwin"]]
   # https://stackoverflow.com/questions/1715580/how-to-discover-number-of-logical-cores-on-mac-os-x
   JOBS="$(sysctl -n hw.ncpu)"
 fi
 set -e
-if [[ $? -ne 0 ]]; then
-  JOBS=4
-fi
```
Comment (ezyang) [inline tools/cpp_build/build_common.sh]: What's going on here?

**Comment by ezyang** [comment]
@anderspapitto Does this intersect with your `NO_PYTHON` changes coming down the pipe?

File: torch/csrc/jit/export.cpp [hunk 6]
```diff
@@ -38,11 +33,13 @@ struct ExportContext {
 
 void encodeGraph(onnx::GraphProto * p_g, const std::shared_ptr<Graph> & g,
                  const std::vector<at::Tensor> & initializers,
-                 ExportContext *ctx, RawDataExportMap* raw_data_export_map=nullptr);
+                 ExportContext *ctx, RawDataExportMap* raw_data_export_map=nullptr,
+                 bool export_raw_ir = false);
```
Comment (ezyang) [inline torch/csrc/jit/export.cpp]: What does `export_raw_ir` mean?

Comment (ezyang) [reply torch/csrc/jit/export.cpp]: Perhaps this parameter should go in ExportContext? It seems to be threaded around everywhere.

**Review by ezyang — APPROVED** [review]
Super legit. Thank you.

One long term code org note: the original exporter was written with the idea that it was only for ONNX, and so it took a number of short cuts (which you have if-conditional'ed out with `export_raw_ir`.) This now means anyone who works on this code has to have both use cases in their head if they want to make changes. This is probably OK, but an even more sustainable situation would be to tweak the ONNX passes to do a little bit more processing, so that when we see, e.g., "onnx::Undefined", we can unconditionally replace it with "" (and not have to have a boolean in this case.)

File: torch/csrc/jit/export.cpp (hunk 6 above)
Comment (apaszke) [reply torch/csrc/jit/export.cpp]: +1 for this

File: torch/csrc/jit/ir_import.cpp [hunk 7]
```diff
@@ -0,0 +1,559 @@
...
+  }
+
+  virtual void decode(pb_istream_t *stream) = 0;
+
+  static bool decode(pb_istream_t *stream, const pb_field_t *, void **_self) {
+    ReaderBase* self = *reinterpret_cast<ReaderBase* const *>(_self);
+    try {
+      self->decode(stream);
+    }
+    catch (const std::runtime_error& error) {
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: Why do we handle this in here? This causes some `Reader`s to silently ignore errors (e.g. you don't check the return value in `Reader<std::vector<T>>`). It would be better to handle the exceptions in the caller if that's what's needed.

File: torch/csrc/jit/ir_import.cpp [hunk 8]
```diff
@@ -0,0 +1,559 @@
...
+
+template<typename T>
+struct Reader : ReaderBase {};
+
+template<typename T>
+struct Reader<std::vector<T>> : Reader<T> {
+  Reader(pb_callback_t& cb) : Reader<T>(cb) {}
+  virtual void decode(pb_istream_t *stream) override {
+    Reader<T>::decode(stream);
+    values.push_back(std::move(Reader<T>::value));
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: Isn't this going to decode at most a single element? Don't we need a loop here?

File: torch/csrc/jit/ir_import.cpp [hunk 9]
```diff
@@ -0,0 +1,559 @@
...
+  }
+  std::vector<T> values;
+};
+
+template<>
+struct Reader<std::string> : ReaderBase {
+  Reader(pb_callback_t& cb) : ReaderBase(cb) {}
+  virtual void decode(pb_istream_t *stream) override {
+    std::vector<uint8_t> res(stream->bytes_left);
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: Isn't it the case that `bytes_left` might be quite a lot? Can we somehow lazily enlarge the vector on demand?

File: torch/csrc/jit/ir_import.cpp [hunk 10]
```diff
@@ -0,0 +1,559 @@
...
+  }
+  std::string value;
+};
+
+template<>
+struct Reader<double> : ReaderBase {
+  Reader(pb_callback_t& cb) : ReaderBase(cb) {}
+  virtual void decode(pb_istream_t *stream) override {
+    double val;
+    if (!pb_decode_fixed32(stream, &val)) {
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: Can't you just pass in `&value`? The temporary `val` is unnecessary

File: torch/csrc/jit/ir_import.cpp [hunk 11]
```diff
@@ -0,0 +1,559 @@
...
+  }
+  double value;
+};
+
+template<>
+struct Reader<int64_t> : ReaderBase {
+  Reader(pb_callback_t& cb) : ReaderBase(cb) {}
+  virtual void decode(pb_istream_t *stream) override {
+    uint64_t val;
+    if (!pb_decode_varint(stream, &val)) {
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: Same here

File: torch/csrc/jit/ir_import.cpp [hunk 12]
```diff
@@ -0,0 +1,559 @@
...
+  return tensors;
+}
+
+Graph_ readSubgraph(const std::string& serialized_subgraph) {
+  pb_istream_t istream = pb_istream_from_buffer(reinterpret_cast<const pb_byte_t *>(serialized_subgraph.data()), serialized_subgraph.size());
+
+  return Reader<Graph_>::read(&istream);
+}
+
+std::vector<Graph_> readSubgraphs(const std::vector<std::string>& serialized_subgraphs) {
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: `fmap` again?

File: torch/csrc/jit/ir_import.cpp [hunk 13]
```diff
@@ -0,0 +1,559 @@
...
+
+  return subgraphs;
+}
+
+std::shared_ptr<Graph> buildGraph(const Graph_& graph_);
+
+std::vector<std::shared_ptr<Graph>> buildGraphs(const std::vector<Graph_>& graphs_);
+
+void buildBlocks(const std::vector<Graph_>& graphs_, Node* node,
+                 std::unordered_map<std::string, Value*>& value_map);
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: nit: if we were to put `buildBlock` beneath those 3 functions, then we'd only need to forward declare it.

File: torch/csrc/jit/ir_import.cpp [hunk 14]
```diff
@@ -0,0 +1,559 @@
...
+void buildBlock(const Graph_& graph_, Block* block,
+                std::unordered_map<std::string, Value*>& value_map) {
+
+  for (auto input : graph_.inputs) {
+    value_map[input.name] = block->addInput();
+  }
+
+  for (auto node_ : graph_.nodes) {
+    TORCH_ASSERT(node_.op_type != "CppOp");
+    TORCH_ASSERT(node_.op_type != "PythonOp");
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: Aren't we saving qualified names? Will this ever be true?

File: torch/csrc/jit/ir_import.cpp [hunk 15]
```diff
@@ -0,0 +1,559 @@
...
+
+    auto node = block->owningGraph()->create(Symbol::fromQualString(node_.op_type),
+                                             node_.outputs.size());
+
+    for (auto attr : node_.attrs) {
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: Use `for (auto & attr : ...)` to avoid a copy

File: torch/csrc/jit/ir_import.cpp [hunk 16]
```diff
@@ -0,0 +1,559 @@
...
+
+Graph_ readSubgraph(const std::string& serialized_subgraph) {
+  pb_istream_t istream = pb_istream_from_buffer(reinterpret_cast<const pb_byte_t *>(serialized_subgraph.data()), serialized_subgraph.size());
+
+  return Reader<Graph_>::read(&istream);
+}
+
+std::vector<Graph_> readSubgraphs(const std::vector<std::string>& serialized_subgraphs) {
+  std::vector<Graph_> subgraphs;
+  for (auto serialized_subgraph : serialized_subgraphs) {
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: use `auto &` to avoid a copy

File: torch/csrc/jit/ir_import.cpp [hunk 17]
```diff
@@ -0,0 +1,559 @@
...
+                 std::unordered_map<std::string, Value*>& value_map);
+
+void buildBlock(const Graph_& graph_, Block* block,
+                std::unordered_map<std::string, Value*>& value_map) {
+
+  for (auto input : graph_.inputs) {
+    value_map[input.name] = block->addInput();
+  }
+
+  for (auto node_ : graph_.nodes) {
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: Use `auto &` to avoid a copy

File: torch/csrc/jit/ir_import.cpp [hunk 18]
```diff
@@ -0,0 +1,559 @@
...
+    TORCH_ASSERT(node_.op_type != "CppOp");
+    TORCH_ASSERT(node_.op_type != "PythonOp");
+
+    auto node = block->owningGraph()->create(Symbol::fromQualString(node_.op_type),
+                                             node_.outputs.size());
+
+    for (auto attr : node_.attrs) {
+      Symbol name = Symbol::attr(attr.name);
+
+      if (attr.type && onnx_AttributeProto_AttributeType_GRAPHS &&
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: Why are you checking `attr.type`? Isn't that an enum? Also, you could just put an `if (attr.name == "_blocks")` as part of the `GRAPHS` case below to simplify the code.

File: torch/csrc/jit/ir_import.cpp [hunk 19]
```diff
@@ -0,0 +1,559 @@
...
+        case onnx_AttributeProto_AttributeType_TENSORS:
+          node->ts_(name, buildTensors(attr.ts));
+          break;
+        case onnx_AttributeProto_AttributeType_GRAPHS:
+          node->gs_(name, buildGraphs(readSubgraphs(attr.gs)));
+          break;
+      }
+    }
+
+    for (auto input : node_.inputs) {
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: Please use `auto &`

File: torch/csrc/jit/ir_import.cpp [hunk 20]
```diff
@@ -0,0 +1,559 @@
...
+    }
+
+    for (size_t i=0; i<node_.outputs.size(); i++) {
+      value_map[node_.outputs[i]] = node->outputs()[i];
+    }
+
+    block->appendNode(node);
+  }
+
+  for (auto output : graph_.outputs) {
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: `auto &`

File: torch/csrc/jit/ir_import.cpp [hunk 21]
```diff
@@ -0,0 +1,559 @@
...
+    if (value_map.find(output.name) != value_map.end()) {
+      Value* v = value_map.at(output.name);
+      block->registerOutput(v);
+    }
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: Why do we silently ignore outputs that are not in `value_map`? That looks like an error to me

File: torch/csrc/jit/ir_import.cpp [hunk 22]
```diff
@@ -0,0 +1,559 @@
...
+std::shared_ptr<Graph> buildGraph(const Graph_& graph_) {
+  auto graph = std::make_shared<Graph>();
+  std::unordered_map<std::string, Value*> value_map;
+
+  buildBlock(graph_, graph->block(), value_map);
+
+  return graph;
+}
+
+std::vector<std::shared_ptr<Graph>> buildGraphs(const std::vector<Graph_>& graphs_) {
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: `fmap`?

File: torch/csrc/jit/ir_import.cpp [hunk 23]
```diff
@@ -0,0 +1,559 @@
...
+    initializers.push_back(buildTensor(tensor_));
+  }
+
+  return graph;
+}
+
+}
+
+std::shared_ptr<Graph> ImportIRGraph(const std::string& serialized_graph,
+                                     std::vector<at::Tensor>& initializers) {
```
Comment (apaszke) [inline torch/csrc/jit/ir_import.cpp]: Do we use initializers for anything? Are they an output argument?

File: torch/csrc/jit/python_ir.cpp [hunk 24]
```diff
@@ -328,6 +330,9 @@ void initPythonIRBindings(PyObject * module_) {
   m.def("_jit_get_graph", [](tracer::TracingState* s) {
     return s->graph;
   });
+  m.def("import_ir_graph", [](const std::string& serialized_graph, std::vector<at::Tensor> & initializers) {
```
Comment (apaszke) [inline torch/csrc/jit/python_ir.cpp]: If `initializers` are an output argument, then I think that changes to it don't carry over to Python.

File: torch/onnx/utils.py [hunk 25]
```diff
@@ -154,7 +160,7 @@ def _model_to_graph(model, args, f, verbose=False, training=False,
         graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
         params = list(_unique_state_dict(model).values())
 
-    graph = _optimize_graph(graph, aten)
+    graph = _optimize_graph(graph, aten, onnx_pass=not export_raw_ir)
```
Comment (apaszke) [inline torch/onnx/utils.py]: Can we call the argument `export_raw_ir` everywhere? Adding a different name is confusing

**Review by apaszke — COMMENTED** [review]
Looks nice! I have a few comments that can simplify the code, and I noticed it does a bunch of unnecessary copies in the for loops, so let's fix it before merging.

**Review by apaszke — CHANGES_REQUESTED** [review]
(See review above) The initializers arg is also very confusing for me

**Comment by ezyang** [comment]
@lantiga, could you post a sample textual protobuf of a simple exported model in this form?

File: tools/cpp_build/build_common.sh (hunk 5 above)
Comment (lantiga) [reply tools/cpp_build/build_common.sh]: Whoops, my bad, this is a leftover

File: torch/csrc/jit/export.cpp (hunk 6 above)
Comment (lantiga) [reply torch/csrc/jit/export.cpp]: Good point, I'll move it to ExportContext and document it.

File: tools/cpp_build/src/import_test.cpp [hunk 26]
```diff
@@ -0,0 +1,45 @@
...
+
+  std::vector<at::Tensor> inputs = { v(input_t) };
+
+  for (auto t : initializers) {
+    inputs.push_back(v(t));
+  }
+
+  auto outputs = executor.run(torch::jit::variable_tensor_list(std::move(inputs)));
+
+  std::cout<<"OUTPUT "<<outputs[0]<<std::endl;
```
[the remark this answers is not in the document]
Comment (lantiga) [reply tools/cpp_build/src/import_test.cpp]: The file was there previously but I had already removed it, not sure why it still showed up.

File: torch/csrc/jit/ir_import.cpp [hunk 27]
```diff
@@ -0,0 +1,488 @@
...
+          node->i_(name, attr.i);
+          break;
+        case onnx_AttributeProto_AttributeType_STRING:
+          node->s_(name, std::move(attr.s));
+          break;
+        case onnx_AttributeProto_AttributeType_TENSOR:
+          node->t_(name, buildTensor(attr.t));
+          break;
+        case onnx_AttributeProto_AttributeType_GRAPH:
+          // TODO
```
[the remark this answers is not in the document]
Comment (lantiga) [reply torch/csrc/jit/ir_import.cpp]: Same as above, this was taken care of in the PR, this seems like outdated code

File: tools/cpp_build/src/import_test.cpp (hunk 26 above)
[the remark this answers is not in the document]
Comment (apaszke) [reply tools/cpp_build/src/import_test.cpp]: Don't worry about those. I started a review a week ago when those files were here, but I haven't finished it until today, and so my comments were still there.

File: torch/csrc/jit/ir_import.cpp (hunk 8 above)
Comment (lantiga) [reply torch/csrc/jit/ir_import.cpp]: So `decode` is going to be called repeatedly from the callback (registered in the parent class constructor) each time an element is encountered. So all we do is relay the decoding through the parent class `decode` and push the result, every time this `decode` is called.

File: torch/csrc/jit/python_ir.cpp (hunk 24 above)
Comment (lantiga) [reply torch/csrc/jit/python_ir.cpp]: I thought I checked, but admittedly I was doing my tests in `libtorch` first.
In any case, I changed this function to return a `tuple`.

File: tools/cpp_build/build_nanopb.sh [hunk 28]
```diff
@@ -0,0 +1,25 @@
...
+pushd $NANOPB_BUILDPATH
+
+cmake -DCMAKE_BUILD_TYPE:STRING=Release \
+      -DCMAKE_INSTALL_PREFIX:STRING=$INSTALL_PREFIX \
+      -DCMAKE_INSTALL_MESSAGE=NEVER \
+      -Dnanopb_BUILD_GENERATOR:BOOL=OFF \
+      -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON \
+      -G "$GENERATE" \
+      $PYTORCHPATH/third_party/nanopb
+$MAKE -j "$JOBS"
```
[the remark this answers is not in the document]
Comment (lantiga) [reply tools/cpp_build/build_nanopb.sh]: You mean using the `ExternalProject` mechanism in CMake?

File: torch/csrc/jit/ir_import.cpp (hunk 21 above)
Comment (lantiga) [reply torch/csrc/jit/ir_import.cpp]: Shouldn't all values at this point be in `value_map`? The inputs to the graph and the outputs from every node have been stored in `value_map` earlier, so they have to be there.
Maybe an `assert` would be more appropriate.

**Comment by lantiga** [comment]
Thanks for the awesome reviews. I'm almost done with this round of fixes.

@ezyang here's the export for this model
```
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,2)

    def forward(self, x):
        y = F.tanh(self.linear(x))
        return y
```
Graph
```
graph(%0 : Float(3)
      %1 : Float(2, 3)
      %2 : Float(2)) {
  %3 : Float(3!, 2!) = aten::t(%1), scope: Net/Linear[linear]
  %4 : Float(2) = aten::matmul(%0, %3), scope: Net/Linear[linear]
  %5 : Float(2) = aten::add[alpha={1}](%4, %2), scope: Net/Linear[linear]
  %6 : Float(2) = aten::tanh(%5), scope: Net
  return (%6);
}
```
Protobuf
```
1: 3
2: "pytorch"
3: "0.3"
7 {
  1 {
    1: "1"
    2: "3"
    4: "aten::t"
    6: <redacted source location>
  }
  1 {
    1: "0"
    1: "3"
    2: "4"
    4: "aten::matmul"
    6: <redacted source location>
  }
  1 {
    1: "4"
    1: "2"
    2: "5"
    4 {
      12: 0x6464613a3a6e6574
    }
    5 {
      1: "alpha"
      5 {
        2: 11
        9: "\000\000\000\000\000\000\360?"
      }
      20: 4
    }
    6: <redacted source location>
  }
  1 {
    1: "5"
    2: "6"
    4: "aten::tanh"
    6: <redacted source location>
  }
  2: "torch-jit-export"
  5 {
    1: 2
    1: 3
    2: 1
    8: "1"
    9: "\220\\V\276tw\305>\246#\\\276\026y\203>\020-&\275\244s\340>"
  }
  5 {
    1: 2
    2: 1
    8: "2"
    9: "8~\362\275\034\306\225\276"
  }
  11 {
    1: "0"
    2 {
      1 {
        1: 1
        2 {
          1 {
            1: 3
          }
        }
      }
    }
  }
  11 {
    1: "1"
    2 {
      1 {
        1: 1
        2 {
          1 {
            1: 2
          }
          1 {
            1: 3
          }
        }
      }
    }
  }
  11 {
    1: "2"
    2 {
      1 {
        1: 1
        2 {
          1 {
            1: 2
          }
        }
      }
    }
  }
  12 {
    1: "6"
    2 {
      1 {
        1: 1
        2 {
          1 {
            1: 2
          }
        }
      }
    }
  }
}
8 {
  2: 6
}
```

**Comment by lantiga** [comment]
As for @ezyang's suggestion on doing some work in the ONNX pass to avoid conditionals, I for it. I haven't implemented it yet, I'd like to see how the rest goes first.t

File: tools/cpp_build/build_nanopb.sh (hunk 28 above)
[the remark this answers is not in the document]
Comment (apaszke) [reply tools/cpp_build/build_nanopb.sh]: Yeah, that would work.

File: torch/csrc/jit/ir_import.cpp (hunk 8 above)
Comment (apaszke) [reply torch/csrc/jit/ir_import.cpp]: Makes sense. Can you please leave a comment saying that?

File: torch/csrc/jit/ir_import.cpp (hunk 9 above)
Comment (apaszke) [reply torch/csrc/jit/ir_import.cpp]: Thanks! Can you please leave a comment?

File: torch/csrc/jit/ir_import.cpp (hunk 21 above)
Comment (apaszke) [reply torch/csrc/jit/ir_import.cpp]: They should. My point is that if they weren't then you'd silently ignore them. The code might work now, but this makes it really easy to add some bugs in the future and don't even notice them (hey, it works!).

File: torch/csrc/jit/ir_import.cpp (hunk 23 above)
Comment (apaszke) [reply torch/csrc/jit/ir_import.cpp]: Do we use them for anything though? Are they ever non-empty?

File: torch/csrc/jit/python_ir.cpp (hunk 24 above)
Comment (apaszke) [reply torch/csrc/jit/python_ir.cpp]: Yep, it will mutate it in C++, but it won't propagate to Python.

File: torch/csrc/jit/import.cpp [hunk 29]
```diff
@@ -131,11 +125,9 @@ template<>
 struct Reader<int64_t> : ReaderBase {
   Reader(pb_callback_t& cb) : ReaderBase(cb) {}
   virtual void decode(pb_istream_t *stream) override {
-    uint64_t val;
-    if (!pb_decode_varint(stream, &val)) {
+    if (!pb_decode_varint(stream, reinterpret_cast<uint64_t*>(&value))) {
```
Comment (apaszke) [inline torch/csrc/jit/import.cpp]: Oh I didn't notice this one isn't the same type! This is really worrying because this means that it's effectively impossible to get a negative `int64_t` from protobuf. Are you sure there's really no other function that would give us a signed number?

File: torch/csrc/jit/import.cpp [hunk 30]
```diff
@@ -498,37 +482,11 @@ void buildBlock(const Graph_& graph_, Block* block,
...
-
-  return graph;
-}
-
-std::vector<std::shared_ptr<Graph>> buildGraphs(const std::vector<Graph_>& graphs_) {
-  std::vector<std::shared_ptr<Graph>> graphs;
-  for (auto g_ : graphs_) {
-    graphs.push_back(buildGraph(g_));
+  for (auto & output : graph_.outputs) {
+    assert(value_map.find(output.name) != value_map.end());
```
Comment (apaszke) [inline torch/csrc/jit/import.cpp]: This assert is not necessary. We usually compile with `-DNDEBUG` so it won't even be there, but `.at` already does the error checking for you.

**Review by apaszke — COMMENTED** [review]
Two minor things, but I'd like to understand what can `initializers` be in our case.

File: torch/csrc/jit/import.cpp (hunk 29 above)
Comment (lantiga) [reply torch/csrc/jit/import.cpp]: Yeah, it looks fishy, but apparently this is the way it's intended to be used
(https://github.com/nanopb/nanopb/blob/master/pb_decode.c#L1289 and https://github.com/nanopb/nanopb/blob/master/tests/decode_unittests/decode_unittests.c).
Encoding is similar, see @ezyang's comment (https://github.com/pytorch/pytorch/blob/master/torch/csrc/onnx/onnx.cpp#L12).

I'm obviously not an expert, but from what I read protobuf encodes all integers (signed and unsigned) as a `varint` internally (https://developers.google.com/protocol-buffers/docs/encoding?csw=1#varints). A `varint` is decoded by nanopb into 64 bits, meant to be interpreted as a signed or unsigned integer depending what was originally encoded in the `varint`. Thus negative `int64_t` will be returned as such after the `reinterpret_cast`.

File: torch/csrc/jit/ir_import.cpp (hunk 23 above)
Comment (lantiga) [reply torch/csrc/jit/ir_import.cpp]: See comment below

File: tools/cpp_build/build_nanopb.sh (hunk 28 above)
[the remark this answers is not in the document]
Comment (lantiga) [reply tools/cpp_build/build_nanopb.sh]: Do you think we should also build `aten` with `ExternalProject` and get rid of the build scripts? Maybe move to `ExternalProject` for both `aten` and `nanopb` in a separate PR?

**Review by apaszke — APPROVED** [review]
@ezyang I don't see a lot of value form emitting 100% ONNX compliant output, since pretty much no other library will be able to consume this output anyway. It will be very PyTorch and will easily break if we change some internals (like our Python API!). If @lantiga wants to go and fix it then sure, otherwise we should probably just get this in.

**Comment by lantiga** [comment]
@ezyang ahah, sorry about the dump.

I actually didn't know we could make the output ONNX compliant by using the domain field. It's just a matter of munging the op strings, so why not? I can give it a shot.
The value I see is that at least other libraries will be able to recognize that the ONNX file was created for a domain that they can't handle, and manage the situation gracefully.

However, the `op_version` bit, however, is going to be hard to maintain at the current stage, given that PyTorch tends to evolve rapidly. Maybe we could leave versioning for the future?

I propose that we add the `domain` part and merge, while `import_opset` and `op_version` remain as TODO.

**Comment by lantiga** [comment]
Sorry @ezyang, I'm trying to use `protoc --decode` to produce a pretty printout, but I'm failing miserably. How do you do that?

**Comment by ezyang** [comment]
@lantiga Don't worry about it, it would have been nice if you had it easily available, but if it's difficult no worries. Not sure why protoc is not printing fields; probably the onnx library can also do this for you.

> I actually didn't know we could make the output ONNX compliant by using the domain field. It's just a matter of munging the op strings, so why not? I can give it a shot.
> The value I see is that at least other libraries will be able to recognize that the ONNX file was created for a domain that they can't handle, and manage the situation gracefully.

Yeah, otherwise they will be like, "This ONNX file fails validation, it uses ONNX operator aten::foo which I don't know about."

> The op_version bit, however, is going to be hard to maintain at the current stage, given that PyTorch tends to evolve rapidly. Maybe we could leave versioning for the future?

Yeah, just set it to some number and leave it there for now.

**Comment by lantiga** [comment]
@ezyang not sure what the version will be in clients if not specified (zero I guess, since it's an integer).
I'd rather leave it that way for now, otherwise I'll need to update `onnx.pb.h`. `NodeProto` does not include `version` at the moment (it did include `domain` so that was quick).

**Comment by ezyang** [comment]
SGTM!

**Comment by lantiga** [comment]
Great! Should I go ahead and merge?

**Comment by ezyang** [comment]
Yes please do!

**Comment by apaszke** [comment]
Thank you, Luca!
