### ISSUE TITLE
Module 'Sequential' has no attribute '_modules' :

### ISSUE THREAD

**Issue by SerBad** [pytorch/pytorch#98064]
### 🐛 Describe the bug
```pythons
import torch
import torch.nn as nn
class MyModule(nn.Module):
    def __init__(self):

        super(MyModule, self).__init__()

        self.seq = nn.Sequential(
            nn.Linear(10, 20),
            nn.ReLU(),
            nn.Linear(20, 5)
        )

def forward(self, x):
    return self.seq(x)

my_module = MyModule()
scripted_module = torch.jit.script(my_module)
```

```
RuntimeError: 
Module 'Sequential' has no attribute '_modules' :
  File "/home/zhou/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 251
    @property
    def modules(self):
        return self._modules
               ~~~~~~~~~~~~~ <--- HERE

```

### Versions

__version__ = '2.0.0+cu117'
debug = False
cuda = '11.7'
git_version = 'c263bd43e8e8502d4726643bc6fd046f0130ac0e'
hip = None

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by SerBad** [comment]
RuntimeError: 
Module 'Sequential' has no attribute '_modules' :
  File "/home/zhou/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 251
    @property
    def modules(self):
        return self._modules
               ~~~~~~~~~~~~~ <--- HERE

**Comment by pat749** [comment]
When I am running this code , I am not seeing any error. Here is the collab [link](https://colab.research.google.com/drive/1PmUD7c9Up9TU8ox2KdoQhocvnAHWO0ZP?usp=sharing) .

I think there is error in your system locally, Here is also alternative way to fix this error is to properly indent the forward method within the **MyModule** class.
```
import torch
import torch.nn as nn

class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.seq = nn.Sequential(
            nn.Linear(10, 20),
            nn.ReLU(),
            nn.Linear(20, 5)
        )

    def forward(self, x):
        return self.seq(x)

my_module = MyModule()
scripted_module = torch.jit.script(my_module)
```

Here is the implementation of this code also in [google colab](https://colab.research.google.com/drive/1MaV1JbE5pOyx0mkZ2AuS0tcIpPvVlqLH?usp=sharing).

**Comment by pat749** [comment]
Yes I used torch 2.0.0 version . It works on torch 2.0.0.
Thank you

**Comment by SerBad** [comment]
It works when I remove @property on 'def modules(self):', 
and I don't know why my version have  @property.
maybe because I compile pytorch on local system? I don't know the reason.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
