### ISSUE TITLE
DISABLED test_origami_fallback_when_disabled (__main__.TestOrigami)

### ISSUE THREAD

**Issue by jithunnair-amd** [pytorch/pytorch#184660]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent example](https://github.com/pytorch/pytorch/actions/runs/26198938822/job/77087708002)).

```
2026-05-21T04:36:31.1066962Z =================================== FAILURES ===================================
2026-05-21T04:36:31.1067453Z ________ TestOrigami.test_origami_fallback_when_disabled (op_name='mm') ________
2026-05-21T04:36:31.1067846Z Traceback (most recent call last):
2026-05-21T04:36:31.1074751Z   File "/var/lib/jenkins/pytorch/test/inductor/test_origami.py", line 450, in test_origami_fallback_when_disabled
2026-05-21T04:36:31.1075203Z     mock.patch(
2026-05-21T04:36:31.1075499Z   File "/opt/conda/envs/py_3.12/lib/python3.12/unittest/mock.py", line 1451, in __enter__
2026-05-21T04:36:31.1075903Z     self.target = self.getter()
2026-05-21T04:36:31.1076171Z                   ^^^^^^^^^^^^^
2026-05-21T04:36:31.1076504Z   File "/opt/conda/envs/py_3.12/lib/python3.12/pkgutil.py", line 528, in resolve_name
2026-05-21T04:36:31.1076808Z     result = getattr(result, p)
2026-05-21T04:36:31.1077046Z              ^^^^^^^^^^^^^^^^^^
2026-05-21T04:36:31.1077319Z AttributeError: module 'torch._inductor' has no attribute 'template_heuristics'
```

This test is most likely failing due to the refactor in https://github.com/pytorch/pytorch/commit/5236c717d49986daaa72249528f8f1aa5062bedb:
```
* `heuristics/template/`: move of the former top-level
  `template_heuristics/` package into the new hierarchy.  All internal imports,
  test imports, and `select_algorithm.py` are updated to the new paths.
```

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @jataylo @hongxiayang @naromero77amd @pragupta @jerrymannil @xinyazhang @mruberry @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @kadeng @muchulee8 @amjames @aakhundov @coconutruben

**Comment by jithunnair-amd** [comment]
@umechand-amd This is probably something for you to fix in [test_origami.py](https://github.com/pytorch/pytorch/blob/bf6b7fb48c55069847a0887eb84b0781e0c9a838/test/inductor/test_origami.py#L451)

**Comment by izaitsevfb** [comment]
https://github.com/pytorch/pytorch/pull/183275 is reverted
