### PR TITLE
Make inductor kernel metadata comments more descriptive

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #126698
* #126573

Summary:

A couple of improvements to the generated comments in inductor kernels:

1. Makes the nodes in the comment topologically sorted, I think having them
   alphabetically sorted is a gotcha. I was always confused on why the
   sorting in the comments did not match the code.
2. Adds a printout of the aten graph fragment corresponding to the
   current inductor kernel, to make it easier to map from aten
   code to inductor code

Example float8-overhead-related inductor kernel comment after this PR:

```
# kernel path: /tmp/torchinductor_vasiliy/27/c27ts3rdw56ns7od5j6ovdnhxphished2lcu3adclzzixoo7khg5.py                                                                                      
# Source Nodes: [weight_fp8], Original ATen: [aten.mul, aten.clamp, aten._to_copy]                                                                                                        
# Source node to ATen node mapping:                                                                                                                                                       
#   weight_fp8 => clamp_max_1, clamp_min_3, convert_element_type_10, convert_element_type_11, convert_element_type_9, mul_3                                                               
# Graph fragment:                                                                                                                                                                         
#   %mul_3 : [num_users=1] = call_function[target=torch.ops.aten.mul.Tensor](args = (%primals_2, %convert_element_type_8), kwargs = {})                                                   
#   %convert_element_type_9 : [num_users=1] = call_function[target=torch.ops.prims.convert_element_type.default](args = (%mul_3, torch.float32), kwargs = {})                             
#   %clamp_min_3 : [num_users=1] = call_function[target=torch.ops.aten.clamp_min.default](args = (%convert_element_type_9, -448.0), kwargs = {})                                          
#   %clamp_max_1 : [num_users=1] = call_function[target=torch.ops.aten.clamp_max.default](args = (%clamp_min_3, 448.0), kwargs = {})                                                      
#   %convert_element_type_10 : [num_users=1] = call_function[target=torch.ops.prims.convert_element_type.default](args = (%clamp_max_1, torch.bfloat16), kwargs = {})                     
#   %convert_element_type_11 : [num_users=1] = call_function[target=torch.ops.prims.convert_element_type.default](args = (%convert_element_type_10, torch.float8_e4m3fn), kwargs = {})    
triton_poi_fused__to_copy_clamp_mul_5 = async_compile.triton('triton_', '''                                                                                                                                                                                                                                                                                                 
```

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by vkuzo** [comment]
adding folks who recently touched this code as reviewers

File: torch/_inductor/utils.py [hunk 1]
```diff
@@ -256,11 +257,15 @@ def convert_shape_to_symint(
     from .virtualized import V
 
     return [
-        i
-        if isinstance(i, int)
-        else int(i)
-        if isinstance(i, sympy.Integer)
-        else V.graph.sizevars.shape_env.create_symintnode(i, hint=None)
+        (
```
Comment (vkuzo) [inline torch/_inductor/utils.py:260]: this is from linter, no logic change, can revert if needed

File: torch/_inductor/utils.py [hunk 2]
```diff
@@ -388,11 +393,9 @@ def sort_func(elem):
 
 class CachedMethod(Generic[P, RV], Protocol):
     @staticmethod
-    def clear_cache(self) -> None:
-        ...
+    def clear_cache(self) -> None: ...
```
Comment (vkuzo) [inline torch/_inductor/utils.py:396]: from linter

File: torch/_inductor/utils.py [hunk 3]
```diff
@@ -388,11 +393,9 @@ def sort_func(elem):
...
 
-    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> RV:
-        ...
+    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> RV: ...
```
Comment (vkuzo) [inline torch/_inductor/utils.py:398]: from linter

**Comment by ezyang** [comment]
IDs in the code looks sus, 139645798654288, because it means the generated files are no longer deterministic

**Comment by vkuzo** [comment]
> IDs in the code looks sus, 139645798654288, because it means the generated files are no longer deterministic

hmm, ok, let me see what we can do about that

**Comment by Chillee** [comment]
We definitely want some tests for this btw.

File: torch/_inductor/utils.py [hunk 4]
```diff
@@ -479,15 +489,56 @@ def get_kernel_metadata(node_schedule, wrapper):
...
+            f"{wrapper.comment}   {original_node} => {', '.join(sorted(nodes))}"
+        )
+
+    # print the aot_autograd graph fragment
+    detailed_metadata.append(f"{wrapper.comment} Graph fragment:")
+    for node in inductor_nodes:
+        node_s = node.format_node()
+        # Make the node string representation easier to read
+        # before: %abs_3 : [num_users=1] = call_function[target=torch.ops.aten.abs.default](args = (%tangents_1,), kwargs = {})
+        # after: %abs_3 = torch.ops.aten.abs.default(args = (%tangents_1,), kwargs = {})
```
Comment (ezyang) [inline torch/_inductor/utils.py:509]: It'd be nice to use the Python code formatter but I'm not sure if you can conveniently only do a few nodes without having to shove them in an fx.Graph or something

Comment (vkuzo) [reply torch/_inductor/utils.py:509]: yeah, I hacked it after looking at how much work it would be to implement it properly and with the context that this PR should not be in the critical path, but can take another look if you prefer, lmk

Comment (vkuzo) [reply torch/_inductor/utils.py]: made it a bit less hacky

**Comment by vkuzo** [comment]
> IDs in the code looks sus, 139645798654288, because it means the generated files are no longer deterministic

hid behind a config, off by default

File: torch/_inductor/utils.py (hunk 1 above)
Comment (ezyang) [reply torch/_inductor/utils.py:260]: This file is UFMT enabled, why is the linter wobbling these lines 🤔

File: torch/_inductor/utils.py [hunk 5]
```diff
@@ -471,6 +474,14 @@ def get_kernel_metadata(node_schedule, wrapper):
 
     from_node_dict = collections.defaultdict(list)
     original_aten_dict = collections.defaultdict(list)
+
+    # sort `inductor_nodes` topologically
+    graph = None
+    if len(inductor_nodes):
+        graph = inductor_nodes[0].graph
+        if all(n for n in inductor_nodes if n in graph.nodes):
+            inductor_nodes = [n for n in graph.nodes if n in inductor_nodes]
```
Comment (ezyang) [inline torch/_inductor/utils.py:483]: This is O(n) on the FX graph nodes, and so this is ultimately quadratic in the number of kernels in the Inductor graph

File: torch/_inductor/utils.py [hunk 6]
```diff
@@ -479,15 +490,61 @@ def get_kernel_metadata(node_schedule, wrapper):
...
         )
+
+    # print the aot_autograd graph fragment
+    if graph is not None:
+        detailed_metadata.append(f"{wrapper.comment} Graph fragment:")
+        node_names = {node.name for node in inductor_nodes}
+        # A bit hacky: get the parent graph generated code and only keep the
+        # lines corresponding to the variables we care about. This allows us
+        # to reuse the Python codegen code.
+        for line in graph.python_code("").src.split("\n"):
```
Comment (ezyang) [inline torch/_inductor/utils.py:511]: Uhhh, this is a Graph, not a GraphModule, right? So the Python code is not cached, you're rendering it over and over again every time you print the aot autograd graph fragment. The Python code rendering is pretty expensive, definitely not recommended.

**Comment by ezyang** [comment]
In the spirit of constructiveness, here is my suggestion for how to do the implementations without being heinously inefficient:

1. Just write a little node formatter by hand, it's not too hard. If you want to, you can factor out the python code formatter so that you can get at a helper for node by node
2. Generate a numbering for every node in the graph (node_1 => 0, node_2 => 1), cache it (I'm not sure where, you could potentially just stick it on the Graph if you're lazy), and then sort on these ints

**Comment by vkuzo** [comment]
Ok, ready for review again, I found myself repeatedly coming back to this PR over the past weeks to help with inductor debugging and finally took the time to clean it up:
1. removed the nn.Module stack stuff for now as I haven't used that in months.  May come back to it in a future PR if the need arises.  Btw, the object IDs from this part of the logs were coming from activation checkpointing.
2. moved the graph fragment generation to use `n.format_node()`, it's a bit longer but removes the need to refactor FX code.  I think it would be actually really nice to generate code fragments, just don't want that to block this PR
3. made topological sort more efficient based on @ezyang 's suggestion

File: torch/_inductor/utils.py [hunk 7]
```diff
@@ -523,23 +523,53 @@ def get_kernel_metadata(node_schedule, wrapper):
...
-            f"{wrapper.comment} {original_node} => {', '.join(sorted(nodes))}"
+            f"{wrapper.comment}   {original_node} => {', '.join(sorted(nodes))}"
         )
+
+    # print the aot_autograd graph fragment
+    if single_graph is not None:
+        detailed_metadata.append(f"{wrapper.comment} Graph fragment:")
+        for n in inductor_nodes:
+            # TODO(future): maybe refactor torch/fx/graph.py to make it easy to
+            # generate python code for graph fragments
```
Comment (ezyang) [inline torch/_inductor/utils.py:570]: yes please

**Review by ezyang — APPROVED** [review]
Thanks!

**Comment by jataylo** [comment]
@vkuzo @ezyang this commit broke rocm b2b_gemm tests cc: @jithunnair-amd @jeffdaily @pruthvistony @huydhn @malfet 
e.g. python test/inductor/test_b2b_gemm.py -k "test_b2b_gemm_right_assoc_good_shape"

We will need to revert this

this commit:
```
git log
commit 700a11fdd46f21a0c64c4ccbd24ac951e7b58307 (HEAD)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/fx/node.py", line 70, in _find_module_of_method
    module = orig_method.__module__
AttributeError: 'functools.partial' object has no attribute '__module__'
```

this commit-1:
```
git log
commit 260e7cb143be4dc12e27931babcbcfaced3cfccc (HEAD, refs/bisect/good-260e7cb143be4dc12e27931babcbcfaced3cfccc)
.
----------------------------------------------------------------------
Ran 1 test in 21.012s

OK
```

I see this get_kernel_metadata being called:
`detailed_metadata.append(f"{wrapper.comment}   {n.format_node()}")`

Logs: [rocm-failure-b2b-gemm.txt](https://github.com/user-attachments/files/16678133/rocm-failure-b2b-gemm.txt)

**Comment by malfet** [comment]
@jataylo can we simply skip this test on ROCM? Or are you saying that it simply doesn't work on Python-3.8? If that's the case, let's migrate to 3.9, as 3.8 will reach EOL in October this year

**Comment by jataylo** [comment]
It's more than skipping a single test, there are multiple failures in the file regarding this. I hadn't associated this to being a 3.8 issue though, let me check if it works for us on 3.9/3.10 and see what our plan is there. cc: @jeffdaily @jithunnair-amd @pruthvistony

**Comment by vkuzo** [comment]
I think a forward fix would be better than a revert, we can skip outputting this metadata in the cases where `n.format_node()` is not supported.  Is there a way to reproduce the breakage in CI?

**Comment by jataylo** [comment]
> I think a forward fix would be better than a revert, we can skip outputting this metadata in the cases where `n.format_node()` is not supported. Is there a way to reproduce the breakage in CI?

Yep this one will fail with ciflow/rocm e.g.
```
https://hud.pytorch.org/failure?name=rocm%20%2F%20linux-focal-rocm6.1-py3.8%20%2F%20test%20(default%2C%205%2C%206%2C%20linux.rocm.gpu.2)&jobName=undefined&failureCaptures=%5B%22inductor%2Ftest_b2b_gemm.py%3A%3AB2BGEMMTest%3A%3Atest_b2b_gemm_trivial_right_assoc_good_shape%22%5D
```

A forward fix would be nice to have, we're also setting up a PR to  upgrade rocm CI to 3.10 which I'm hoping will resolve it too https://github.com/pytorch/pytorch/pull/134108
