### PR TITLE
Fix compatibility problem with LSTMs and torch.save

### LINKED ISSUE #53359: Backward compatibility problem of LSTMs in v1.8.0
## 🐛 Bug

A LSTM model saved entirely by v1.7.1 cannot work in v1.8.0 (caused by a new attribute proj_size)

## To Reproduce

```
torch.save(a_module_with_lstm_inside, path)  # with pytorch v1.7.1
torch.load(path).to(device)  # with pytorch v1.8.0
```

> Traceback (most recent call last):
>   File "main.py", line 206, in <module>
>     net = torch.load(TASK_RUN_DIR + '/net.pkl').to(device)
>   File "/home/zhyue/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
>     return self._apply(convert)
>   File "/home/zhyue/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
>     module._apply(fn)
>   File "/home/zhyue/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
>     module._apply(fn)
>   File "/home/zhyue/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
>     module._apply(fn)
>   File "/home/zhyue/anaconda3/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 186, in _apply
>     self.flatten_parameters()
>   File "/home/zhyue/anaconda3/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 170, in flatten_parameters
>     if self.proj_size > 0:
>   File "/home/zhyue/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
>     raise AttributeError("'{}' object has no attribute '{}'".format(
> AttributeError: 'LSTM' object has no attribute 'proj_size'

## Expected behavior

No error.

## Environment

Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 3090
GPU 2: GeForce RTX 3090
GPU 3: GeForce RTX 3090
GPU 4: GeForce RTX 3090
GPU 5: GeForce RTX 3090
GPU 6: GeForce RTX 3090
GPU 7: GeForce RTX 3090

Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.8.0
[pip3] torchaudio==0.8.0a0+a751e1d
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.2                      256    defaults
[conda] mkl-service               2.3.0            py38he904b0f_0    defaults
[conda] mkl_fft                   1.3.0            py38h54f3939_0    defaults
[conda] mkl_random                1.1.1            py38h0573a6f_0    defaults
[conda] numpy                     1.19.2           py38h54aff64_0    defaults
[conda] numpy-base                1.19.2           py38hfa32c7d_0    defaults
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1    defaults
[conda] pytorch                   1.8.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchaudio                0.8.0                      py38    pytorch
[conda] torchvision               0.9.0                py38_cu111    pytorch

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#57558 Fix compatibility problem with LSTMs and torch.save**

Fixes #53359

If someone directly saves an nn.LSTM in PyTorch 1.7 and then loads it in PyTorch
1.8, it errors out with the following:
```
(In PyTorch 1.7)
import torch
model = torch.nn.LSTM(2, 3)
torch.save(model, 'lstm17.pt')

(In PyTorch 1.8)
model = torch.load('lstm17.pt')
AttributeError: 'LSTM' object has no attribute 'proj_size'
```

Although we do not officially support this (directly saving modules via
torch.save), it used to work and the fix is very simple. This PR adds an
extra line to `__setstate__`: if the state we are passed does not have
a `proj_size` attribute, we assume it was saved from PyTorch 1.7 and
older and set `proj_size` equal to 0.

Test Plan:

I wrote a test that tests `__setstate__`. But also,

Run the following:
```
(In PyTorch 1.7)
import torch
x = torch.ones(32, 5, 2)
model = torch.nn.LSTM(2, 3)
torch.save(model, 'lstm17.pt')
y17 = model(x)

(Using this PR)
model = torch.load('lstm17.pt')
x = torch.ones(32, 5, 2)
y18 = model(x)
```
and finally compare y17 and y18.

Differential Revision: [D28198477](https://our.internmc.facebook.com/intern/diff/D28198477)

### CODE REVIEW

File: torch/nn/modules/rnn.py [hunk 1]
```diff
@@ -299,6 +299,11 @@ def __setstate__(self, d):
         super(RNNBase, self).__setstate__(d)
         if 'all_weights' in d:
             self._all_weights = d['all_weights']
+        # In PyTorch 1.8 we added a proj_size member variable to LSTM.
+        # LSTMs that were serialized via torch.save(module) before PyTorch 1.8
```
Comment (albanD) [inline torch/nn/modules/rnn.py:303]: nit: we don't usually comment with the timeline in these.

**Review by albanD — APPROVED** [review]
LGTM Thanks!

File: torch/nn/modules/rnn.py (hunk 1 above)
Comment (zou3519) [reply torch/nn/modules/rnn.py:303]: Is the suggestion to remove the reference to PyTorch 1.8?

Comment (jbschlosser) [reply torch/nn/modules/rnn.py:303]: It could reasonably go either way imo.

Examples without version references [here](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L1105), [here](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/conv.py#L164-L167), and [here](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/transformer.py#L384-L387).

One example with the version in it [here](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/activation.py#L933).

**Review by jbschlosser — APPROVED** [review]
LGTM! Thanks for knocking out the fix :)
