### ISSUE TITLE
Backward compatibility problem of LSTMs in v1.8.0

### ISSUE THREAD

**Issue by yuezhihan** [pytorch/pytorch#53359]
## 🐛 Bug

A LSTM model saved entirely by v1.7.1 cannot work in v1.8.0 (caused by a new attribute proj_size)

## To Reproduce

```
torch.save(a_module_with_lstm_inside, path)  # with pytorch v1.7.1
torch.load(path).to(device)  # with pytorch v1.8.0
```

> Traceback (most recent call last):
>   File "main.py", line 206, in <module>
>     net = torch.load(TASK_RUN_DIR + '/net.pkl').to(device)
>   File "/home/zhyue/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
>     return self._apply(convert)
>   File "/home/zhyue/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
>     module._apply(fn)
>   File "/home/zhyue/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
>     module._apply(fn)
>   File "/home/zhyue/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
>     module._apply(fn)
>   File "/home/zhyue/anaconda3/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 186, in _apply
>     self.flatten_parameters()
>   File "/home/zhyue/anaconda3/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 170, in flatten_parameters
>     if self.proj_size > 0:
>   File "/home/zhyue/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
>     raise AttributeError("'{}' object has no attribute '{}'".format(
> AttributeError: 'LSTM' object has no attribute 'proj_size'

## Expected behavior

No error.

## Environment

Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 3090
GPU 2: GeForce RTX 3090
GPU 3: GeForce RTX 3090
GPU 4: GeForce RTX 3090
GPU 5: GeForce RTX 3090
GPU 6: GeForce RTX 3090
GPU 7: GeForce RTX 3090

Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.8.0
[pip3] torchaudio==0.8.0a0+a751e1d
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.2                      256    defaults
[conda] mkl-service               2.3.0            py38he904b0f_0    defaults
[conda] mkl_fft                   1.3.0            py38h54f3939_0    defaults
[conda] mkl_random                1.1.1            py38h0573a6f_0    defaults
[conda] numpy                     1.19.2           py38h54aff64_0    defaults
[conda] numpy-base                1.19.2           py38hfa32c7d_0    defaults
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1    defaults
[conda] pytorch                   1.8.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchaudio                0.8.0                      py38    pytorch
[conda] torchvision               0.9.0                py38_cu111    pytorch

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by anjali411** [comment]
@yuezhihan we don't guarantee this will work. It's recommended to store state_dicts instead of saving the module.
This is clearly documented in our serialization notes:
https://pytorch.org/docs/stable/notes/serialization.html
"Instead of saving a module directly, for compatibility reasons it is recommended to instead save only its state dict. Python modules even have a function, load_state_dict(), to restore their states from a state dict:"

**Comment by jbschlosser** [comment]
@yuezhihan Also, for more information on `state_dict`s & serialization, check out: https://pytorch.org/docs/stable/notes/modules.html#module-state

**Comment by ezyang** [comment]
Just a reminder that we can and should prevent errors like this by defining `__setstate__` on modules when we add new attributes. Unfortunately it is very easy to forget.

**Comment by zou3519** [comment]
It sounds like modifying `__setstate__` to do something when the module doesn't have `proj_size` would fix this problem: https://github.com/pytorch/pytorch/blob/1b35b1a0c4efa0cb14441a53d5f9d50c15484b26/torch/nn/modules/rnn.py#L295-L326

Is this a fix we should consider, especially for 1.8.1? Since the fix is easy we could just update `__setstate__` to avoid minor headaches like this

**Comment by gchanan** [comment]
I do think it's a fix we should consider, LSTMs are common.  Adding to the 1.8.1 milestone.

**Comment by z-a-f** [comment]
I saw this problem while browsing the [FlairNLP](https://github.com/flairNLP/flair/issues/2137). One comment that I have, though: I don't think it is fair to allow `torch.save` on models without warnings/errors, and once a concern is raised, to simply say "we don't guarantee this will work". I believe we should either raise a warning when the whole model is being saved or we should not allow it at all.

FYI, I am on the latest commit as of 03/17, and the error is still there.

**Comment by MichaelJanzFrogs42** [comment]
Hi, is there any progress in this topic?

**Comment by zou3519** [comment]
Raising priority based on activity

**Comment by albanD** [comment]
As mentioned in the doc, users should be only saving state_dicts to avoid such issues.
For backward compatibility reasons, it is hard to plain forbid nn.Module save though.

**Comment by zou3519** [comment]
@albanD @jbschlosser although our official stance is that users should not be saving modules directly, would you be opposed if I sent a fix for this and we can discuss how to prevent users from saving modules directly separately?

**Comment by jbschlosser** [comment]
@zou3519 I'm not opposed to a fix for this particular issue. Happy to review the PR if you open it!
