### ISSUE TITLE
Compilation error with gcc11 and libstdc++11 (thread_id != operator removed)

### ISSUE THREAD

**Issue by ankurverma85** [pytorch/pytorch#62933]
## 🐛 Bug
Error originates from mkl-dnn which uses != operator on thread_id 
the != operator on thread_id has been removed in c++20 (was deprecated earlier)

A simpler fix is to do !( thread_id() == key.thread_id())

## To Reproduce

1. Build on fedora 34 with gcc11.2 and libstdc++11
1. python setup.py bdist_wheel

```
../third_party/ideep/mkl-dnn/src/common/primitive_cache.cpp:155:60: error: no match for ‘operator!=’ (operand types are ‘const std::thread::id’ and ‘const std::thread::id’)
  155 |     if (it == cache_mapper_.end() || it->first.thread_id() != key.thread_id())
      |                                      ~~~~~~~~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~~~~
      |                                                         |                  |
      |                                                         |                  const std::thread::id
      |                                                         const std::thread::id
In file included from /usr/include/c++/11/utility:70,
                 from /usr/include/c++/11/tuple:38,
                 from /usr/include/c++/11/mutex:38,
                 from /usr/include/c++/11/future:38,
                 from ../third_party/ideep/mkl-dnn/src/common/primitive_cache.hpp:20,
                 from ../third_party/ideep/mkl-dnn/src/common/primitive_cache.cpp:17:
/usr/include/c++/11/bits/stl_pair.h:496:5: note: candidate: ‘template<class _T1, class _T2> constexpr bool std::operator!=(const std::pair<_T1, _T2>&, const std::pair<_T1, _T2>&)’
  496 |     operator!=(const pair<_T1, _T2>& __x, const pair<_T1, _T2>& __y)
      |     ^~~~~~~~
      
```
## Expected behavior

Builds successfully

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by d4l3k** [comment]
I'm also running into this issue when trying to build on Arch Linux w/ the standard gcc11 install.

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 11.1.0
Clang version: Could not collect
CMake version: version 3.19.6
Libc version: glibc-2.33

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.14.16-arch1-1-x86_64-with-glibc2.33
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.3.0
/usr/lib/libcudnn_adv_infer.so.8.3.0
/usr/lib/libcudnn_adv_train.so.8.3.0
/usr/lib/libcudnn_cnn_infer.so.8.3.0
/usr/lib/libcudnn_cnn_train.so.8.3.0
/usr/lib/libcudnn_ops_infer.so.8.3.0
/usr/lib/libcudnn_ops_train.so.8.3.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] botorch==0.5.1
[pip3] gpytorch==1.5.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.0
[pip3] numpydoc==1.1.0
[pip3] pytorch-lightning==1.5.2
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch-model-archiver==0.4.2
[pip3] torchaudio==0.10.0
[pip3] torchmetrics==0.5.1
[pip3] torchserve==0.4.2
[pip3] torchtext==0.11.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl  
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-include               2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] mypy_extensions           0.4.3            py39h06a4308_0  
[conda] numpy                     1.20.3           py39hf144106_0  
[conda] numpy-base                1.20.3           py39h74d4b33_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
```

**Comment by d4l3k** [comment]
Installing gcc10 https://archlinux.org/packages/community/x86_64/gcc10/ and overriding CC and CXX to point to the gcc-10 and g++-10 fixed it for me.

**Comment by surak** [comment]
@d4l3k While this is a solution for you, it's not a fix for the fact that compilation will fail for gcc11 

This is a fix for this specific issue (there are many other ones, though)

```patch
/p/PyTorch/PyTorch-1.10.0_fix-gcc11-ideep.patch 
--- pytorch/third_party/ideep/mkl-dnn/src/common/primitive_cache.hpp.orig	2021-12-01 18:23:31.810057406 +0100
+++ pytorch/third_party/ideep/mkl-dnn/src/common/primitive_cache.hpp	2021-12-01 18:22:31.311550966 +0100
@@ -17,6 +17,7 @@
 #ifndef COMMON_PRIMITIVE_CACHE_HPP
 #define COMMON_PRIMITIVE_CACHE_HPP
 
+#include <thread>
 #include <future>
 #include <list>
 #include <memory>
```

**Comment by XiaobingSuper** [comment]
@vpirogov

**Comment by vpirogov** [comment]
This is the result of changes introduced in GCC11. oneDNN introduced the fix in v2.2.4. See  https://github.com/oneapi-src/oneDNN/issues/1091 for details.

**Comment by XiaobingSuper** [comment]
I verified v2.3.3, it can work.
