### ISSUE TITLE
[JIT] Unable to script a model with spectral_norm layers

### ISSUE THREAD

**Issue by tcapelle** [pytorch/pytorch#59302]
## 🐛 Bug

If I try to export a model with spectral_norm in it, it fails.

## To Reproduce

```python
import torch
import torch.nn as nn
from torch.nn.utils import weight_norm, spectral_norm
conv_spectral = spectral_norm(nn.Conv2d(3, 16, 3))
torch.jit.script(conv_spectral)
```

![image](https://user-images.githubusercontent.com/18441985/120500875-742ad280-c3c1-11eb-8595-f6232cb0039b.png)

## Environment
```text
=== Software === 
python        : 3.8.10
fastai        : 2.3.1
torch         : 1.8.1
nvidia driver : 460.32
torch cuda    : 10.2 / is available
torch cudnn   : 7605 / is enabled

=== Hardware === 
nvidia gpus   : 2
torch devices : 2
  - gpu0      : Quadro RTX 8000
  - gpu1      : GeForce RTX 2070 SUPER

=== Environment === 
platform      : Linux-5.8.0-36-generic-x86_64-with-glibc2.10
distro        : #40~20.04.1-Ubuntu SMP Wed Jan 6 10:15:55 UTC 2021
conda env     : pytorch_18
python        : /home/tcapelle/miniconda3/envs/pytorch_18/bin/python
sys.path      : /home/tcapelle/SteadySun/suneye_dl_models/training_nbs
/home/tcapelle/miniconda3/envs/pytorch_18/lib/python38.zip
/home/tcapelle/miniconda3/envs/pytorch_18/lib/python3.8
/home/tcapelle/miniconda3/envs/pytorch_18/lib/python3.8/lib-dynload

/home/tcapelle/miniconda3/envs/pytorch_18/lib/python3.8/site-packages
/home/tcapelle/Apps/fastai
/home/tcapelle/miniconda3/envs/pytorch_18/lib/python3.8/site-packages/IPython/extensions
/home/tcapelle/.ipython
```

**Comment by tugsbayasgalan** [comment]
It seems like python instance objects don't have __name__ attribute (https://stackoverflow.com/questions/14514838/why-do-python-instances-have-no-name-attribute) . So it should be written as `pre_hook.__class__.__name__` to access it from the class. @Lilyjjo do you think this can be changed as my suggestion? Or does it have to be `pre_hook.__name__`?

**Comment by Lilyjjo** [comment]
@tugsbayasgalan The support for module level hooks in TorchScript is limited in functionality :( I took a peek at the spectral norm code, and making the name change you suggested wouldn't be sufficient to make spectral_norm script friendly. JIT module level hooks only support stand-alone, fully typed functions as hooks and prehooks. The SpectralNorm object is a class and the propsed name change wouldn't be sufficient to make SpectralNorm compatable with the hooks API. I'm not aware of plans to add this functionality

**Comment by tcapelle** [comment]
It worked on 1.7.1

**Comment by Lilyjjo** [comment]
Can you confirm @tcapelle that the spectral_norms layers were running in 1.7.1? JIT was previously just ignoring hooks altogether, and it looks like spectral_norm is implemented with hooks

**Comment by tcapelle** [comment]
Lol, it was then probably ignoring it.

**Comment by Canvis-Me** [comment]
Sorry, but I still encountered the problem when using torch 2.0.1 with the test example given above. The error is:
```
AttributeError: 'SpectralNorm' object has no attribute '__name__'
```

When change `spectral_norm` to `torch.nn.utils.parametrizations.spectral_norm`, it shows:
```
NotSupportedError: Comprehension ifs are not supported yet:
```
