### ISSUE TITLE
Pytorch 1.4.0 weight drop - 'LSTM' object has no attribute 'weight_hh_l0'

### ISSUE THREAD

**Issue by realiti4** [pytorch/pytorch#32346]
Hi,

awd-lstm implementation doesn't work after upgrading to 1.4.0. Here is how weight drop class looks like:

```python
class WeightDrop(torch.nn.Module):
    def __init__(self, module, weights, dropout=0, variational=False):
        super(WeightDrop, self).__init__()
        self.module = module
        self.weights = weights
        self.dropout = dropout
        self.variational = variational
        self._setup()

    def widget_demagnetizer_y2k_edition(*args, **kwargs):        
        return

    def _setup(self):
        # Terrible temporary solution to an issue regarding compacting weights re: CUDNN RNN
        if issubclass(type(self.module), torch.nn.RNNBase):
            self.module.flatten_parameters = self.widget_demagnetizer_y2k_edition

        for name_w in self.weights:
            print('Applying weight drop of {} to {}'.format(self.dropout, name_w))
            w = getattr(self.module, name_w)
            del self.module._parameters[name_w]
            self.module.register_parameter(name_w + '_raw', Parameter(w.data))

    def _setweights(self):
        for name_w in self.weights:
            raw_w = getattr(self.module, name_w + '_raw')
            w = None
            if self.variational:               
                mask = torch.ones(raw_w.size(0), 1)

                if raw_w.is_cuda: mask = mask.cuda()
                mask = torch.nn.functional.dropout(mask, p=self.dropout, training=True)
                w = mask.expand_as(raw_w) * raw_w
            else:
                w = torch.nn.functional.dropout(raw_w, p=self.dropout, training=self.training)
            setattr(self.module, name_w, w)

    def forward(self, *args):
        self._setweights()        
        return self.module.forward(*args)
```

what model's init looks like:

```python
class RNNModel(nn.Module):
    def __init__(self, ninp, nhid, history_size, label_size, nlayers=1, dropout=0.5, dropouth=0.5, dropouti=0.2, dropoute=0.1, wdrop=0.7, tie_weights=False):
        super(RNNModel, self).__init__()
        self.ninp = ninp
        self.nhid = nhid
        self.nlayers = nlayers        

        self.rnns = [torch.nn.LSTM(ninp if l == 0 else nhid, nhid if l != nlayers - 1 else (ninp if tie_weights else nhid), 1, dropout=0) for l in range(nlayers)]
        if wdrop:
            self.rnns = [WeightDrop(rnn, ['weight_hh_l0'], dropout=wdrop) for rnn in self.rnns]

        self.rnns = torch.nn.ModuleList(self.rnns)
        self.decoder = nn.Linear(nhid, label_size)
```

What should I do to update my code? I can't figure it out myself, thanks.

**edit:**
To reproduce, the code below is enough and I discovered it only happens when using .to(device), .cpu() or .cuda()

    encoder = RNNModel(5, 128, 120, 2, 1).cuda()

**Environment**
- PyTorch Version (e.g., 1.0): 1.4.0
- OS (e.g., Linux): Windows 10
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source):
- Python version: 3.7
- CUDA/cuDNN version: 10.1
- GPU models and configuration:
- Any other relevant information:

cc @ezyang @gchanan @zou3519

**Comment by mrshenli** [comment]
Hey @realiti4 what was the previous PyTorch version you were using before you switch to 1.4.0?

@zou3519, has anything changed recently? The LSTM doc does mention there is a `weight_hh_l[k]` attribute.

```
        weight_hh_l[k]: the learnable hidden-hidden weights of the k-th layer,
            of shape `(hidden_size, hidden_size)`
```

**Comment by realiti4** [comment]
Hi @mrshenli I was using 1.3.1

**Comment by ngimel** [comment]
What's the minimum script to reproduce the error? Forwarding through the model defined above? `RNNModel` does not have a forward method defined, would forwarding through `WeightDrop` be enough?

**Comment by realiti4** [comment]
@ngimel yes the above two classes and the code below is enough to reproduce the issue on my end. Another thing I discovered right now is it only happens with '.to(device)', '.cuda' or '.cpu()'

    encoder = RNNModel(5, 128, 120, 2, 1).cuda()
or

    encoder = RNNModel(5, 128, 120, 2, 1).cpu()

**Comment by ngimel** [comment]
The root cause of this bug is that `_apply` function for rnn module (https://github.com/pytorch/pytorch/blame/58234c0254f135d1e3714b17f44f4922d56d41b4/torch/nn/modules/rnn.py#L131-L139) does not work correctly after the parameters of rnn have been renamed, like in WeightDrop module here, or after applying weight_norm, so a minimum script to trigger an error cause by buggy `_apply` is this:
```
import torch
ninp = 128
rnn = torch.nn.LSTM(ninp, ninp)
#rnn = rnn.cuda() #uncomment this line for the script to work
name = 'weight_hh_l0'
m = torch.nn.utils.weight_norm(rnn, name=name)
m = m.cuda() # comment this line for the script to work
print([(name, p.device) for name, p in m.named_parameters()])
```

**Comment by mrshenli** [comment]
closed by #32563

**Comment by realiti4** [comment]
Hi @ngimel I'm not sure if should open a new issue, but the problem still exists on master with fix #32563.

Code to reproduce:

```
class WeightDrop(torch.nn.Module):
    def __init__(self, module, weights, dropout=0):
        super(WeightDrop, self).__init__()
        self.module = module
        self.weights = weights
        self.dropout = dropout
        self._setup()

    def widget_demagnetizer_y2k_edition(*args, **kwargs):        
        return

    def _setup(self):
        # Terrible temporary solution to an issue regarding compacting weights re: CUDNN RNN
        if issubclass(type(self.module), torch.nn.RNNBase):
            self.module.flatten_parameters = self.widget_demagnetizer_y2k_edition

        for name_w in self.weights:
            print('Applying weight drop of {} to {}'.format(self.dropout, name_w))
            w = getattr(self.module, name_w)
            del self.module._parameters[name_w]
            self.module.register_parameter(name_w + '_raw', Parameter(w.data))

    def _setweights(self):
        for name_w in self.weights:
            raw_w = getattr(self.module, name_w + '_raw')
            w = torch.nn.functional.dropout(raw_w, p=self.dropout, training=self.training)
            setattr(self.module, name_w, w)

    def forward(self, *args):
        self._setweights()        
        return self.module.forward(*args)

class RNNModel(torch.nn.Module):
    def __init__(self):
        super(RNNModel, self).__init__()

        rnn = torch.nn.LSTM(6, 128)
        self.rnn = WeightDrop(rnn, ['weight_hh_l0'], dropout=0.5)


    def forward(self, input_data, return_h=False):
        output, _ = self.rnn(input_data)

        return output


model = RNNModel().cuda()
ones = torch.ones([128, 64, 6]).cuda()
x = model(ones)
```
This works fine with:
```
model = RNNModel()
ones = torch.ones([128, 64, 6])
x = model(ones)
```

Adding `.cuda()` gives this:
```
RuntimeError: MatrixRef: ArrayRef size 3 not divisible by stride 4
```

And adding `.cpu()` gives this:
```
RuntimeError: got an incorrect number of RNN parameters
```

**Comment by ezyang** [comment]
@realiti4 go ahead and open a new issue

**Comment by ezyang** [comment]
@realiti4 go ahead and open a new issue

**Comment by mourga** [comment]
Hi @realiti4 @ngimel I still have the same error ` 'LSTM' object has no attribute 'weight_hh_l0'`. How do I fix it for pytorch 1.4.0? Thanks!

**Comment by ngimel** [comment]
Unfortunately you can't fix it for pytorch 1.4.0, you need to get nightly package to get a fix.

**Comment by AndreaLK3** [comment]
I am using PyTorch 1.4.0+cu100 right now, and I came across this very issue.

I have written code that works around this, while requiring no special/nightly build:
- **get** the `model._parameters` Ordered Dictionary
- apply dropout on specified parameter(s)
- **set** named parameter in `_parameters`
- replace the module's `forward` with our `forward`

`def weight_drop(module, weights_names_ls, dropout_p):

    original_module_forward = module.forward

    def forward(*args, **kwargs):
        for name_param in weights_names_ls:
            param = module._parameters.get(name_param)
            param_with_droput = Parameter(torch.nn.functional.dropout(param, p=dropout_p), requires_grad=param.requires_grad)
            module._parameters.__setitem__(name_param, param_with_droput)

            return original_module_forward(*args, **kwargs)

    setattr(module, 'forward', forward)`

**Comment by AndreaLK3** [comment]
I also write here a Version 2 of the code that does the same thing, but allows for the Pytorch model to be pickled and saved, because the inner function is defined as a top-level class in the module:

`def weight_drop(module, weights_names_ls, dropout_p):

    original_module_forward = module.forward
    forward_with_drop = ForwardWithDrop(weights_names_ls, module, dropout_p, original_module_forward)
    setattr(module, 'forward', forward_with_drop)
    return module

# Functions are only pickle-able if they are defined at the top-level of a module,
# so we create a class that is first initialized and then called as the forward()
class ForwardWithDrop(object):
    def __init__(self,weights_names_ls, module, dropout_p, original_module_forward):
        self.weights_names_ls = weights_names_ls
        self.module = module
        self.dropout_p = dropout_p
        self.original_module_forward = original_module_forward

    def __call__(self, *args, **kwargs): # the function formerly known as "forward_new"
        for name_param in self.weights_names_ls:
            param = self.module._parameters.get(name_param)
            param_with_droput = Parameter(torch.nn.functional.dropout(param, p=self.dropout_p, training=self.module.training),
                                          requires_grad=param.requires_grad)
            self.module._parameters.__setitem__(name_param, param_with_droput)

        return self.original_module_forward(*args, **kwargs)
`

**Comment by congchan** [comment]
> I also write here a Version 2 of the code that does the same thing, but allows for the Pytorch model to be pickled and saved.
> 
> ```
> def weight_drop(module, weights_names_ls, dropout_p):
> 
>     original_module_forward = module.forward
>     forward_with_drop = ForwardWithDrop(weights_names_ls, module, dropout_p, original_module_forward)
>     setattr(module, 'forward', forward_with_drop)
>     return module
> ```
> 
> Functions are only pickle-able if they are defined at the top-level of a module, so we create a class that is first initialized and then called as the forward()
> 
> ```
> class ForwardWithDrop(object):
>     def __init__(self,weights_names_ls, module, dropout_p, original_module_forward):
>         self.weights_names_ls = weights_names_ls
>         self.module = module
>         self.dropout_p = dropout_p
>         self.original_module_forward = original_module_forward
> 
>     def __call__(self, *args, **kwargs): # the function formerly known as "forward_new"
>         for name_param in self.weights_names_ls:
>             param = self.module._parameters.get(name_param)
>             param_with_droput = Parameter(torch.nn.functional.dropout(param, p=self.dropout_p, training=self.module.training),
>                                           requires_grad=param.requires_grad)
>             self.module._parameters.__setitem__(name_param, param_with_droput)
> 
>         return self.original_module_forward(*args, **kwargs)
> ```

First thanks for your codes, I try to use it, but found that it failed to reproduce the same evaluation mode results after loading a checkpoint
