### ISSUE TITLE
Pytorch 2.12 compile regression: abs() on scalar float in compiled section causing exception after compilation.

### ISSUE THREAD

**Issue by cooldome** [pytorch/pytorch#183880]
### 🐛 Describe the bug

The following code crashes with the stacktrace: 

```
File "C:\issue,py", line 15, in details:
    @torch.compile(fullgraph=True, dynamic=True, options={'triton.cudagraphs': False, 'max_autotune': False})
AttributeError: 'NoneType' object has no attribute 'item'
```
Stacktrace is not useful and it doesn't really tell where the problem it is. It is in generated code.

It used to work on all versions of pytorch starting from 2.7.

Code snippet:
```
import torch
from dataclasses import dataclass
from enum import IntEnum
from typing import Dict, Any

@dataclass(frozen=True, slots=True)
class Example:
    volume: float


class ExampleDetails(IntEnum):
    BuySellInd = 0
    Quantity = 1


@torch.compile(fullgraph=True, dynamic=True, options={'triton.cudagraphs': False, 'max_autotune': False})
def details(x: Example) -> Dict[ExampleDetails, Any]:
    result = {
        ExampleDetails.BuySellInd: x.volume >= 0.0,
        ExampleDetails.Quantity: abs(x.volume)
    }
    return result


t = Example(volume=-50.10)
print(details(t))
```

The following code works in eager mode and torch 2.8, 2.9.1, 2.10, 2.11. 
The problem is caused by this expression: `abs(x.volume)`

There are simple workarounds to make it work, for example: `abs(torch.as_tensor(x.volume))`
But using tensor is overkill here.

### Versions

Collecting environment information...

PyTorch version: 2.12.0+cu130
Is debug build: False
CUDA used to build PyTorch: 13.0
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Enterprise (10.0.22631 64-bit)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 4.1.0
Libc version: N/A

 

Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: 13.0.48

 

CUDA_MODULE_LOADING set to:
GPU models and configuration: GPU 0: NVIDIA RTX A6000
Nvidia driver version: 582.16
cuDNN version: Could not collect
Is XPU available: False
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
Caching allocator config: N/A

 

CPU:

----------------------

Name: Intel(R) Xeon(R) Gold 5122 CPU @ 3.60GHz
Manufacturer: GenuineIntel
Family: 179
Architecture: 9
ProcessorType: 3
DeviceID: CPU0
CurrentClockSpeed: 3592
MaxClockSpeed: 3592
L2CacheSize: 4096
L2CacheSpeed: None
Revision: 21764

----------------------

Name: Intel(R) Xeon(R) Gold 5122 CPU @ 3.60GHz

Manufacturer: GenuineIntel
Family: 179
Architecture: 9
ProcessorType: 3
DeviceID: CPU1
CurrentClockSpeed: 3592
MaxClockSpeed: 3592
L2CacheSize: 4096
L2CacheSpeed: None
Revision: 21764

 

Versions of relevant libraries:
[pip3] numpy==2.2.6
[pip3] onnx==1.16.2
[pip3] onnxruntime==1.20.1
[pip3] tbb==2022.3.0
[pip3] tbb-devel==2022.3.0
[pip3] tcmlib==1.4.1
[pip3] torch==2.12.0+cu130
[pip3] torch-cpp-extension==0.0.0
[pip3] torchaudio==2.11.0+cu130
[pip3] torchdata==0.12.0.dev20250220
[pip3] torchinterp1d==1.1
[pip3] torchvision==0.27.0+cu130
[pip3] triton-windows==3.7.0.post26
[conda] Could not collect

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex @nkhasbag-nv @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @kadeng @amjames @jataylo @azahed98

**Comment by nkhasbag-nv** [comment]
Thank you @cooldome for reporting this bug. We will look into it

**Comment by anijain2305** [comment]
Cannot repro this on `main` branch.

**Comment by jansel** [comment]
My agent was unable to reproduce this on 8dd44388526b4c638900a96f16ecfd1c0b2b0f8d. Reopen if you see this on the latest PyTorch nightly
