### PR TITLE
ATen/native (5/6): Use per-operator headers

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #75576
* __->__ #75575
* #75574
* #75573

Differential Revision: [D40126696](https://our.internmc.facebook.com/intern/diff/D40126696)

### CODE REVIEW

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40126696).

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40126696).

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40126696).

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
This break trunk (I guess land race):
```
var/lib/jenkins/workspace/aten/src/ATen/native/TensorShape.cpp:92:10: fatal error: ATen/ops/diag_backward_native.h: No such file or directory
 #include <ATen/ops/diag_backward_native.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
