### ISSUE TITLE
Update how to build PyTorch with CUDA Windows instructions

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#47483]
PyTorch currently could not be build using recommended `14.11.25503` minimal toolchain, see:
https://github.com/pytorch/pytorch/blame/b4b0fa637178baf9147416b550c7db70de6a5fa3/README.md#L258

But if one tries to following this instructions using PyTorch-1.7 or newer it will fail with as shown in:
https://github.com/pytorch/pytorch/issues/46208#issuecomment-707352250

cc @malfet @seemethere @walterddr @jlin27 @mruberry @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by mszhanyi** [comment]
From the issue, the user built with cuda 10.0, but cuda 10.0 looks not compatible with vs 2019.
So we need tell users that they have to clone python 1.6 or lower if they want to use cuda 10.0 or lower, am I right?

**Comment by peterjc123** [comment]
@mszhanyi I think we should just say that we support cuda >= 10.1 and vs >= 2019.

**Comment by peterjc123** [comment]
> So we need tell users that they have to clone python 1.6 or lower if they want to use cuda 10.0 or lower, am I right?

Maybe we could create a new table for this. Something like

| CUDA VERSION | CUDA ARCH | LATEST PYTORCH VERSION SUPPORTED |
|--------------|-----------|----------------------------------|
| 10.0         | 3.5+      | 1.6.0                            |
| 9.2          | 3.5+      | 1.x.0                            |

**Comment by skyline75489** [comment]
https://github.com/pytorch/pytorch/issues/42722#issuecomment-674314586 is another compilation error caused by VS2017 that confuses users.. I guess it's time to drop the support of VS2017.
