### ISSUE TITLE
cifar10_tutorial not working on CUDA 11.3 and ROCm 5.1.1 nightly pytorch

### ISSUE THREAD

**Issue by xiaoyu-work** [pytorch/pytorch#80181]
### 🐛 Describe the bug

Hi,

I was trying to run cifar10_tutorial (https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html) with ROCm 5.1.1 nightly torch:
`torch-1.13.0.dev20220619+rocm5.1.1` + `torchvision-0.14.0.dev20220619+rocm5.1.1`. But got error:
```
(ptca) root@5e432b79e8b9:~# python cifar10_tutorial.py
Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "cifar10_tutorial.py", line 113, in <module>
    images, labels = dataiter.next()
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'next'
```

You can repro this by just running tutorial code with ROCm nightly torch and ROCm nightly torchvision:
```
import torch
import torchvision
import torchvision.transforms as transforms

transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

batch_size = 4

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,
                                          shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

import matplotlib.pyplot as plt
import numpy as np

# functions to show an image


def imshow(img):
    img = img / 2 + 0.5     # unnormalize
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    plt.show()


# get some random training images
dataiter = iter(trainloader)
images, labels = dataiter.next()

# show images
imshow(torchvision.utils.make_grid(images))
# print labels
print(' '.join(f'{classes[labels[j]]:5s}' for j in range(batch_size)))
```

### Versions
```
Collecting environment information...
PyTorch version: 1.13.0.dev20220623+rocm5.1.1
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.1.20531-cacfa990

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-109-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.1.20531
MIOpen runtime version: 2.16.0
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] pytorch-lightning==1.6.3
[pip3] torch==1.13.0.dev20220623+rocm5.1.1
[pip3] torch-ort==1.12.0.dev20220523
[pip3] torchaudio==0.13.0.dev20220623+rocm5.1.1
[pip3] torchmetrics==0.7.1
[pip3] torchvision==0.14.0.dev20220623+rocm5.1.1
[conda] mkl                       2021.4.0                 pypi_0    pypi
[conda] mkl-include               2021.4.0                 pypi_0    pypi
[conda] numpy                     1.22.2                   pypi_0    pypi
[conda] pytorch-lightning         1.6.3                    pypi_0    pypi
[conda] torch                     1.13.0.dev20220623+rocm5.1.1          pypi_0    pypi
[conda] torch-ort                 1.12.0.dev20220523          pypi_0    pypi
[conda] torchaudio                0.13.0.dev20220623+rocm5.1.1          pypi_0    pypi
[conda] torchmetrics              0.7.1                    pypi_0    pypi
[conda] torchvision               0.14.0.dev20220623+rocm5.1.1          pypi_0    pypi
```

Updated on July 7th

The problem is found on CUDA also installing below nightly whls
` torch-1.13.0.dev20220707+cu113-cp38-cp38-linux_x86_64.whl` and `torchvision-0.14.0.dev20220707+cu113-cp38-cp38-linux_x86_64.whl`

It is a generic issue.

cc @ngimel @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by xiaoyu-work** [comment]
@mruberry Hi Mike, any update on this?

**Comment by pruthvistony** [comment]
The issue is due to break in the upstream pyTorch code and it is not working on CUDA also (on latest nightly)
```
root@ecacccd70a2:/tutorial# pip list | grep torch
torch               1.13.0.dev20220707+cu113
torchvision         0.14.0.dev20220707+cu113
root@ecacccd70a2:/tutorial# python3 cifar_model.py
Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "cifar_model.py", line 39, in <module>
    images, labels = dataiter.next()
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'next'
root@ecacccd70a2:/tutorial#
```

**Comment by ranggihwang** [comment]
So is it fixed fo now?

**Comment by jithunnair-amd** [comment]
@cpuhrsch Can someone from PyTorch team triage this, since it seemed to be an issue with the tutorial?

**Comment by hongxiayang** [comment]
I reproduced the problem. To fix the tutorial, do below to get the FIRST sample from the train dataloader (basically, use enumerate instead of using iter and then next):
```
for step, (images, labels) in enumerate(trainloader):
  # show images
  imshow(torchvision.utils.make_grid(images))
  # print labels
  print(' '.join(f'{classes[labels[j]]:5s}' for j in range(batch_size)))
  break
```

**Comment by hongxiayang** [comment]
Let me get a PR for this soon.

**Comment by hongxiayang** [comment]
This issue can be closed as the tutorial has been updated already, and I verified just now that it works fine without problem.
