### ISSUE TITLE
ImportError: cannot import name 'get_cuda_stream' from 'triton.runtime.jit'

### ISSUE THREAD

**Issue by netw0rkf10w** [pytorch/pytorch#120199]
### 🐛 Describe the bug

`torch.compile` does not work in PyTorch 2.2.0: `ImportError: cannot import name 'get_cuda_stream' from 'triton.runtime.jit' (/home/user/.local/lib/python3.10/site-packages/triton/runtime/jit.py`)

The following script (taken from here: https://pytorch.org/tutorials/recipes/compiling_optimizer.html) allows reproducing:

```python
import torch
import torch.utils.benchmark as benchmark

# exit cleanly if we are on a device that doesn't support torch.compile
if torch.cuda.get_device_capability() < (7, 0):
    print("Exiting because torch.compile is not supported on this device.")
    import sys
    sys.exit(0)


# Let's define a helpful benchmarking function:
def benchmark_torch_function_in_microseconds(f, *args, **kwargs):
    t0 = benchmark.Timer(
        stmt="f(*args, **kwargs)", globals={"args": args, "kwargs": kwargs, "f": f}
    )
    return t0.blocked_autorange().mean * 1e6

    
def main():
    model = torch.nn.Sequential(
        *[torch.nn.Linear(1024, 1024, False, device="cuda") for _ in range(10)]
    )
    input = torch.rand(1024, device="cuda")
    output = model(input)
    output.sum().backward()

    opt = torch.optim.Adam(model.parameters(), lr=0.01)

    @torch.compile(fullgraph=False)
    def fn():
        opt.step()

    # Warmup runs to compile the function
    for _ in range(5):
        fn()

    eager_runtime = benchmark_torch_function_in_microseconds(opt.step)
    compiled_runtime = benchmark_torch_function_in_microseconds(fn)

    assert eager_runtime > compiled_runtime

    print(f"eager runtime: {eager_runtime}us")
    print(f"compiled runtime: {compiled_runtime}us")

if __name__ == '__main__':
    main()

```

Traceback:

```bash
(python-3.10.4) bash-4.4$ python benchmark_optimizers.py 
Traceback (most recent call last):
  File "/home/user/code/visionBERT2/tests/benchmark_optimizers.py", line 46, in <module>
    main()
  File "/home/user/code/visionBERT2/tests/benchmark_optimizers.py", line 30, in main
    def fn():
  File "/home/user/.local/lib/python3.10/site-packages/torch/__init__.py", line 1802, in fn
    return compile(model,
  File "/home/user/.local/lib/python3.10/site-packages/torch/__init__.py", line 1820, in compile
    return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic, disable=disable)(model)
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 782, in optimize
    compiler_config=backend.get_compiler_config()
  File "/home/user/.local/lib/python3.10/site-packages/torch/__init__.py", line 1665, in get_compiler_config
    from torch._inductor.compile_fx import get_patched_config_dict
  File "/home/user/.local/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 49, in <module>
    from .fx_passes.joint_graph import joint_graph_passes
  File "/home/user/.local/lib/python3.10/site-packages/torch/_inductor/fx_passes/joint_graph.py", line 12, in <module>
    from ..pattern_matcher import (
  File "/home/user/.local/lib/python3.10/site-packages/torch/_inductor/pattern_matcher.py", line 44, in <module>
    from .lowering import fallback_node_due_to_unsupported_type
  File "/home/user/.local/lib/python3.10/site-packages/torch/_inductor/lowering.py", line 5394, in <module>
    from . import kernel
  File "/home/user/.local/lib/python3.10/site-packages/torch/_inductor/kernel/__init__.py", line 1, in <module>
    from . import mm, mm_common, mm_plus_mm, unpack_mixed_mm
  File "/home/user/.local/lib/python3.10/site-packages/torch/_inductor/kernel/mm.py", line 7, in <module>
    from ..codegen.cuda.gemm_template import CUTLASSGemmTemplate
  File "/home/user/.local/lib/python3.10/site-packages/torch/_inductor/codegen/cuda/gemm_template.py", line 11, in <module>
    from .cuda_kernel import CUDATemplateKernel
  File "/home/user/.local/lib/python3.10/site-packages/torch/_inductor/codegen/cuda/cuda_kernel.py", line 7, in <module>
    from ...select_algorithm import ChoiceCaller
  File "/home/user/.local/lib/python3.10/site-packages/torch/_inductor/select_algorithm.py", line 24, in <module>
    from .codegen.triton import texpr, TritonKernel, TritonPrinter, TritonScheduling
  File "/home/user/.local/lib/python3.10/site-packages/torch/_inductor/codegen/triton.py", line 31, in <module>
    from ..triton_heuristics import AutotuneHint
  File "/home/user/.local/lib/python3.10/site-packages/torch/_inductor/triton_heuristics.py", line 54, in <module>
    from triton.runtime.jit import get_cuda_stream
ImportError: cannot import name 'get_cuda_stream' from 'triton.runtime.jit' (/home/user/.local/lib/python3.10/site-packages/triton/runtime/jit.py)
```

This issue already happened before: https://github.com/pytorch/pytorch/issues/91827.

### Versions

(python-3.10.4) bash-4.4$ python collect_env.py 
Collecting environment information...
PyTorch version: 2.2.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux release 8.6 (Ootpa) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10)
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.28

Python version: 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:38:57) [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-4.18.0-372.75.1.el8_6.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-80GB
Nvidia driver version: 535.129.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              128
On-line CPU(s) list: 0-127
Thread(s) per core:  2
Core(s) per socket:  32
Socket(s):           2
NUMA node(s):        8
Vendor ID:           AuthenticAMD
CPU family:          25
Model:               1
Model name:          AMD EPYC 7543 32-Core Processor
Stepping:            1
CPU MHz:             3084.788
BogoMIPS:            5589.33
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            32768K
NUMA node0 CPU(s):   0-7,64-71
NUMA node1 CPU(s):   8-15,72-79
NUMA node2 CPU(s):   16-23,80-87
NUMA node3 CPU(s):   24-31,88-95
NUMA node4 CPU(s):   32-39,96-103
NUMA node5 CPU(s):   40-47,104-111
NUMA node6 CPU(s):   48-55,112-119
NUMA node7 CPU(s):   56-63,120-127
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] flake8==4.0.1
[pip3] mypy==0.991
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.0rc2
[pip3] numpydoc==1.2.1
[pip3] pytorch-pfn-extras==0.6.2
[pip3] pytorch-triton==3.0.0+901819d2b6
[pip3] rotary-embedding-torch==0.2.1
[pip3] torch==2.2.0+cu118
[pip3] torchaudio==2.2.0+cu118
[pip3] torching==0.0.1
[pip3] torchmetrics==0.10.2
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.17.0+cu118
[pip3] triton==2.2.0
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] numpydoc                  1.2.1              pyhd8ed1ab_0    conda-forge

cc @ezyang @gchanan @zou3519 @kadeng @seemethere @malfet @osalpekar @atalman @msaroufim @bdhirsh @anijain2305

**Comment by malfet** [comment]
Hi-pri to get a reproducer, though it feels really strange as this code is tested in CI

**Comment by netw0rkf10w** [comment]
Arrg sorry I messed up with the installation! Thank you very much!
