### ISSUE TITLE
Build issue with protobuf 3.15+

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/pytorch#72167]
### 🐛 Describe the bug

One of our users reported a build issue with protobuf 3.15+: https://github.com/spack/spack/issues/28679 

The build error looks like:
```
third_party/onnx/onnx/proto_utils.h:34:66: error: no matching function for call to 'google::protobuf::io::CodedInputStream::SetTotalBytesLimit(long long int, long long int)'
```

It looks like TensorFlow hit this same issue and recently fixed it, see https://github.com/spack/spack/issues/28612 for a detailed explanation.

@a-akram 

### Versions

Don't have access to the system to run this, but the issue reported to us contains some of this information.

P.S. If anyone from the PyTorch team would like to be listed as maintainers of Spack's PyTorch build recipe you can be immediately notified when someone reports these kind of issues. You don't need to know anything about Spack, I can handle the Spack-specific questions.

**Comment by garymm** [comment]
Can you please describe the build environment in more detail?
The onnx submodule works with protobuf 3.16. See their CI:
https://github.com/onnx/onnx/blob/main/.azure-pipelines/Linux-CI.yml#L50

This has been the case since https://github.com/onnx/onnx/pull/3571, which was merged into PyTorch in https://github.com/pytorch/pytorch/pull/64576

**Comment by adamjstewart** [comment]
Thanks @garymm. It looks like the issue reported in https://github.com/spack/spack/issues/28679 is for PyTorch 1.8.2. From what I can tell, the updated version of ONNX you linked to first appeared in PyTorch 1.10.0. So if that's true, based on https://github.com/onnx/onnx/pull/3684, PyTorch 1.9 and older requires protobuf 3.14 and older, and PyTorch 1.10+ requires protobuf 3.12.2+. Thanks for the help!
