### ISSUE TITLE
[Caffe2] CUDA 9.2 and gcc 7.3.1

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#7881]
## Issue description

CUDA 9.2 is now listing gcc-7.3.1 in its supported compiler.
Use it for several CUDA projects, including Caffe1, and works well.

A PR is created to adjust the cmake restriction: #7880 

However in Caffe2 we're getting some errors in operator headers like
```
GetSingleArgument is not a member of OperatorBase
```
Seems nvcc has some compile errors inside template function.
The same commit works with gcc-6.3.1.
Any idea?

## System Info

- PyTorch or Caffe2: Caffe2
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): cmake
- OS: CentOS-7
- PyTorch version: master
- CUDA version: 9.2
- GPU models and configuration: 1080Ti
- GCC version (if compiling from source): 7.3.1 from devtoolset-7
- CMake version: 3.11.2

**Comment by Snowball0823** [comment]
Hello,I want ask a question,I use cuda9.2,but when I run:
sudo python /opt/caffe2/pytorch/caffe2/python/operator_test/relu_op_test.py
I get warning:
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libcurand.so.9.1: cannot open shared object file: No such file or directory
I don't know why,have you met these problems?If you have,how did you mix it?

**Comment by achalshah20** [comment]
Facing the same issue. Any update?

**Comment by xkszltl** [comment]
https://github.com/pytorch/pytorch/blob/6bdbad93b96ecd943fe5091725ccd70fad9a6057/caffe2/operators/given_tensor_byte_string_to_uint8_fill_op.h#L52

Still getting
```
pytorch/caffe2/operators/given_tensor_byte_string_to_uint8_fill_op.h:52:51: error: 'GetRepeatedArgument<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >' is not a member of 'caffe2::GivenTensorByteStringToUInt8FillOp<Context>'
```

Looks like gcc7 doesn't like this syntax at all.
Even `OperatorBase::template GetRepeatedArgument<string>()` doesn't work.

**Comment by xkszltl** [comment]
PR submitted.
`this->template GetRepeatedArgument<string>("")` should work
