### ISSUE TITLE
SLEEF does not allow in-source builds

### ISSUE THREAD

**Issue by HerculesJack** [pytorch/pytorch#17139]
Hi, I encountered some bugs when trying to compile `pytorch` and `libtorch`, and I'd like to report them together with my solution here. The latest version on GitHub failed on my side for some other errors, and this post is for the source up to commit `ec8b1c9`.

Btw, the reason I need to compile them from source is that, the current binary `libtorch` does not work with my `glibc 2.14`.

## Environment
```
Collecting environment information...
PyTorch version: 1.1.0a0+ec8b1c9
Is debug build: No
CUDA used to build PyTorch: None

OS: SUSE Linux Enterprise Server 12 SP3
GCC version: (SUSE Linux) 4.8.5
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl  []
[conda] magma-cuda100             2.5.0                         1    pytorch
[conda] mkl                       2018.0.3                      1  []
[conda] mkl-include               2019.1                      144  
[conda] mkl-service               1.1.2            py36h17a0993_4  []
[conda] mkl_fft                   1.0.1            py36h3010b51_0  []
[conda] mkl_random                1.0.1            py36h629b387_0  []
[conda] torch                     1.1.0a0+ec8b1c9           <pip>
```
## CMAKE_PREFIX_PATH
I started from
```
export CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"
export NO_CUDA=1
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch && git reset --hard ec8b1c9
python setup.py install
```
But then it stopped at
```
[ 79%] Linking CXX executable ../bin/mobile_test
/global/u2/h/hejia/pytorch/build/lib/libcaffe2.so: undefined reference to `cblas_gemm_s8u8s32'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/mobile_test.dir/build.make:95: recipe for target 'bin/mobile_test' failed
make[2]: *** [bin/mobile_test] Error 1
CMakeFiles/Makefile2:2673: recipe for target 'caffe2/CMakeFiles/mobile_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/mobile_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
I think this may be related to `CMAKE_PREFIX_PATH`, since if I do `export CMAKE_PREFIX_PATH="" && rm -rf build` and compile again, the problem is gone.
## In-source builds
Then I tried to build `libtorch` with
```
cd <pytorch_root>
python -m tools.build_libtorch
```
But it ends up with
```
-- Performing Test C_HAS_THREAD
-- Performing Test C_HAS_THREAD - Success
-- GCC 7.2.0: Adding gcc and gcc_s libs to link line
disabling CUDA because USE_CUDA is set false
CMake Error at third_party/sleef/CMakeLists.txt:27 (message):
  SLEEF does not allow in-source builds.

  You can refer to doc/build-with-cmake.md for instructions on how provide a
  separate build directory.  Note: Please remove autogenerated file
  `CMakeCache.txt` and directory `CMakeFiles` in the current directory.


-- Configuring incomplete, errors occurred!
See also "/global/homes/h/hejia/pytorch/CMakeFiles/CMakeOutput.log".
See also "/global/homes/h/hejia/pytorch/CMakeFiles/CMakeError.log".
```
To solved this problem, first I found the file `third_party/sleef/CMakeLists.txt` and commented out the sanitary check near line 27. But this led to another error:
```
[ 91%] Linking CXX shared library ../lib/libcaffe2.so
CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.AVX2.cpp.o:(.data.rel.local+0x0): multiple definition of `at::native::DispatchStub<void (*)(at::Tensor&, at::Tensor const&), at::native::truncImpl>::AVX2'
CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.o:(.data.rel.local+0x0): first defined here
CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.AVX2.cpp.o:(.data.rel.local+0x8): multiple definition of `at::native::DispatchStub<void (*)(at::Tensor&, at::Tensor const&), at::native::tanhImpl>::AVX2'
CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.o:(.data.rel.local+0x8): first defined here
CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.AVX2.cpp.o:(.data.rel.local+0x10): multiple definition of `at::native::DispatchStub<void (*)(at::Tensor&, at::Tensor const&), at::native::tanImpl>::AVX2'
CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.o:(.data.rel.local+0x10): first defined here
CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.AVX2.cpp.o:(.data.rel.local+0x18): multiple definition of `at::native::DispatchStub<void (*)(at::Tensor&, at::Tensor const&), at::native::sqrtImpl>::AVX2'
CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.o:(.data.rel.local+0x18): first defined here
CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.AVX2.cpp.o:(.data.rel.local+0x20): multiple definition of `at::native::DispatchStub<void (*)(at::Tensor&, at::Tensor const&), at::native::sinImpl>::AVX2'
CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.o:(.data.rel.local+0x20): first defined here
......
```
Finally I figured out that, as hinted, we'd better build in another directory. So I tried
```
rm CMakeCache.txt && rm -rf CMakeFiles
mkdir build_libtorch && cd build_libtorch
BUILD_TORCH=ON ONNX_NAMESPACE=onnx_torch bash ../tools/build_pytorch_libs.sh --use-nnpack caffe2
```
And it works well. Though I'm not sure how to fix it with the recommended `python -m tools.build_libtorch` approach.

**Comment by ezyang** [comment]
Reopening this as it is a legit bug.

**Comment by ezyang** [comment]
cc @nwsterling @AshStuff @tastyminerals

**Comment by ezyang** [comment]
Oh, I see you closed this in favor of #17181
