### ISSUE TITLE
How can I access the model's attribution created during forward pass when using dataparallel?

### ISSUE THREAD

**Issue by sonack** [pytorch/pytorch#5958]
For example, I have such a forward function():

```python

def forward(self, x):
    mgdata = self.encoder(x)
    self.imp_mask_sigmoid = self.impmap_sigmoid(mgdata)
    self.imp_mask = self.impmap_expand(self.imp_mask_sigmoid)
    enc_data = mgdata * self.imp_mask
    dec_data = self.decoder(enc_data)
    return dec_data
```

When I using dataparallel, I always using `model.module` to access the wrapped original model.However, I found I can't access `model.module.imp_mask_sigmoid`, it will complain about `AttributeError: 'ContentWeightedCNN' object has no attribute 'imp_mask_sigmoid'`.
How to deal with it?

Thanks very much.

**Comment by Erotemic** [comment]
My guess is that DataParallel uses multiprocessing under the hood, so the model is copied into worker processes. When you set an attribute in the forward pass it sets it in the local model for that process. Therefore your model in the main thread will never see it (nor could it because the attribute set by the forward passes in multiple processes would clobber each other). 

There might be a way to setup data as shared memory and pass it between processes, but you'll have to be careful of race conditions. 

As an immediate workaround you could use multiprocessing to get the process id and write the data you are interested in to disk tagged with the process id. Perhaps someone who knows how to use `torch.Tensor`'s shared memory abilities will have a better solution.

**Comment by sonack** [comment]
@Erotemic  So, If I want to get an intermediate output of a network's some layer, I have to pay such a lot effort when using multiple GPU. I have just came to a idea that maybe I can use dataparallel wrap the before and after sub networks separately individually, i.e. treating the interested intermediate output as a fake output where are the workers' production will be merged. But I haven't tried it because it may requires my modifying the network's definition, which isn't as clean as I expected. But maybe it is a workaround. What do you think of it?

**Comment by Erotemic** [comment]
Returning what you want from the top-level forward function should defiantly work. You could do this pretty easily with an additional wrapper. As such:

```python

class NormalModel(nn.Module):
    pass

class ExtraOutputWrapper(nn.Module):
   def __init__(self, *args, **kw):
       self.wrapped = NormalModel(*args, **kw)

    def forward(self, input):
        normal_output = self.wrapped(input)
        extra_output = self.wrapped.layer_of_interest.property
        return normal_output, extra_output
```

Then wrap `ExtraOutputWrapper` with `DataParallel` and it will return the property of interest.  This seems fairly clean to me. Is there an issue with this?

**Comment by sonack** [comment]
@Erotemic  I think it is enough to use for my case, thank you for your help!
