### PR TITLE
Update Cutlass to v3.1

### PR DESCRIPTION
**Pull request by Skylion007**
Now that we are on CUDA 11+ exclusively, we can update Nvidia's Cutlass to the next version.

### CODE REVIEW

File: cmake/Dependencies.cmake [hunk 1]
```diff
@@ -1653,7 +1653,6 @@ if(NOT INTERN_BUILD_MOBILE)
   message(STATUS "Found CUDA with FP16 support, compiling with torch.cuda.HalfTensor")
   string(APPEND CMAKE_CUDA_FLAGS " -DCUDA_HAS_FP16=1"
                                  " -D__CUDA_NO_HALF_OPERATORS__"
-                                 " -D__CUDA_NO_HALF_CONVERSIONS__"
```
[the remark this answers is not in the document]
Comment (Skylion007) [reply cmake/Dependencies.cmake:1656]: @ezyang from this PR: https://github.com/pytorch/pytorch/pull/94424/files#r1100558422

[the remark this answers is not in the document]
Comment (jansel) [reply cmake/Dependencies.cmake:1656]: CUTLASS fails to build with this option.

[the remark this answers is not in the document]
Comment (ngimel) [reply cmake/Dependencies.cmake:1656]: Can we still retain this option for pytorch files, and only remove it for cutlass?

[the remark this answers is not in the document]
Comment (ezyang) [reply cmake/Dependencies.cmake:1656]: Since cutlass is I assume primarily a header library, we would have to do this on a per cpp file basis for files that import cutlass. Might be hard

[the remark this answers is not in the document]
Comment (jansel) [reply cmake/Dependencies.cmake:1656]: IMO different options for each cpp file depending on what headers it imports is not a great solution.

If someone adds a new `#include` they will start getting confusing error messages in cutlass headers (not involving any PyTorch code) that are not straightforward to debug.  Both @Skylion007 and myself tried and failed to debug those errors, then @ngimel told me about this define and allowed me to fix the issue.

[the remark this answers is not in the document]
Comment (ngimel) [reply cmake/Dependencies.cmake:1656]: Ok let's try landing like this (@jansel's 3.0 version) and hope that nothing breaks :-)

[the remark this answers is not in the document]
Comment (ezyang) [reply cmake/Dependencies.cmake:1656]: Yeah, hopefully c10::Half will prevent people from doing naughty conversions

[the remark this answers is not in the document]
Comment (ngimel) [reply cmake/Dependencies.cmake:1656]: yes

**Review by ezyang — APPROVED** [review]
Assuming you can get it to build

**Review by jansel — APPROVED** [review]

**Comment by xwang233** [comment]
Hi, this change is probably breaking our build with cuda 12. Sample error messages are
```
#26 497.8 [6100/6999] Building CUDA object caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/AveragePool3d.cu.o
#26 497.8 FAILED: caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/AveragePool3d.cu.o 
...
#26 497.8 /opt/pytorch/pytorch/aten/src/ATen/native/cuda/KernelUtils.cuh(52): error: more than one user-defined conversion from "c10::Half" to "__half" applies:
#26 497.8             function "__half::__half(float)"
#26 497.8 /usr/local/cuda/include/cuda_fp16.hpp(214): here
#26 497.8             function "__half::__half(__half &&) noexcept" (declared implicitly)
#26 497.8           detected during:
#26 497.8             instantiation of "void at::native::fastSpecializedAtomicAdd(scalar_t *, index_t, index_t, scalar_t) [with scalar_t=c10::Half, index_t=int, <unnamed>=(void *)nullptr]" 
#26 497.8 (131): here
#26 497.8             instantiation of "void at::native::fastAtomicAdd(scalar_t *, index_t, index_t, scalar_t, __nv_bool) [with scalar_t=c10::Half, index_t=int]" 
#26 497.8 /opt/pytorch/pytorch/aten/src/ATen/native/cuda/AveragePool3d.cu(267): here
#26 497.8             instantiation of "void at::native::<unnamed>::avg_pool3d_cuda_update_grad_input_atomic<scalar_t,accscalar_t>(at::PackedTensorAccessor64<scalar_t, 4UL, at::DefaultPtrTraits>, at::PackedTensorAccessor64<scalar_t, 4UL, at::DefaultPtrTraits>, int, int, int, int, int, int, int, int, int, __nv_bool, int, int, int) [with scalar_t=c10::Half, accscalar_t=float]" 
#26 497.8 /opt/pytorch/pytorch/aten/src/ATen/native/cuda/AveragePool3d.cu(560): here
#26 497.8 
#26 497.8 /opt/pytorch/pytorch/aten/src/ATen/native/cuda/KernelUtils.cuh(59): error: more than one user-defined conversion from "c10::Half" to "__half" applies:
#26 497.8             function "__half::__half(float)"
#26 497.8 /usr/local/cuda/include/cuda_fp16.hpp(214): here
#26 497.8             function "__half::__half(__half &&) noexcept" (declared implicitly)
#26 497.8           detected during:
#26 497.8             instantiation of "void at::native::fastSpecializedAtomicAdd(scalar_t *, index_t, index_t, scalar_t) [with scalar_t=c10::Half, index_t=int, <unnamed>=(void *)nullptr]" 
#26 497.8 (131): here
#26 497.8             instantiation of "void at::native::fastAtomicAdd(scalar_t *, index_t, index_t, scalar_t, __nv_bool) [with scalar_t=c10::Half, index_t=int]" 
#26 497.8 /opt/pytorch/pytorch/aten/src/ATen/native/cuda/AveragePool3d.cu(267): here
#26 497.8             instantiation of "void at::native::<unnamed>::avg_pool3d_cuda_update_grad_input_atomic<scalar_t,accscalar_t>(at::PackedTensorAccessor64<scalar_t, 4UL, at::DefaultPtrTraits>, at::PackedTensorAccessor64<scalar_t, 4UL, at::DefaultPtrTraits>, int, int, int, int, int, int, int, int, int, __nv_bool, int, int, int) [with scalar_t=c10::Half, accscalar_t=float]" 
#26 497.8 /opt/pytorch/pytorch/aten/src/ATen/native/cuda/AveragePool3d.cu(560): here
#26 497.8 
#26 497.8 /opt/pytorch/pytorch/aten/src/ATen/native/cuda/KernelUtils.cuh(64): error: more than one user-defined conversion from "c10::Half" to "__half" applies:
#26 497.8             function "__half::__half(float)"
#26 497.8 /usr/local/cuda/include/cuda_fp16.hpp(214): here
#26 497.8             function "__half::__half(__half &&) noexcept" (declared implicitly)
#26 497.8           detected during:
#26 497.8             instantiation of "void at::native::fastSpecializedAtomicAdd(scalar_t *, index_t, index_t, scalar_t) [with scalar_t=c10::Half, index_t=int, <unnamed>=(void *)nullptr]" 
#26 497.8 (131): here
#26 497.8             instantiation of "void at::native::fastAtomicAdd(scalar_t *, index_t, index_t, scalar_t, __nv_bool) [with scalar_t=c10::Half, index_t=int]" 
#26 497.8 /opt/pytorch/pytorch/aten/src/ATen/native/cuda/AveragePool3d.cu(267): here
#26 497.8             instantiation of "void at::native::<unnamed>::avg_pool3d_cuda_update_grad_input_atomic<scalar_t,accscalar_t>(at::PackedTensorAccessor64<scalar_t, 4UL, at::DefaultPtrTraits>, at::PackedTensorAccessor64<scalar_t, 4UL, at::DefaultPtrTraits>, int, int, int, int, int, int, int, int, int, __nv_bool, int, int, int) [with scalar_t=c10::Half, accscalar_t=float]" 
#26 497.8 /opt/pytorch/pytorch/aten/src/ATen/native/cuda/AveragePool3d.cu(560): here
#26 497.8 
#26 497.8 3 errors detected in the compilation of "/opt/pytorch/pytorch/aten/src/ATen/native/cuda/AveragePool3d.cu".
```

cc @ngimel @ezyang @ptrblck

**Comment by ezyang** [comment]
cc @malfet @atalman for whether or not we should just bounce this PR till after branch cut

**Comment by seemethere** [comment]
I'm open to bouncing this prior to branch cut. I want to de-risk the branch cut as much as possible and this doesn't seem to be adding functionality right now so I'm a +1 to reverting this for now and re-visiting it after the branch cut.

**Comment by mnicely** [comment]
https://github.com/pytorch/pytorch/pull/94188#issuecomment-1428468832
@hwu36 for vis

**Comment by hwu36** [comment]
@jackkosaian for `-D__CUDA_NO_HALF_CONVERSIONS__`

**Comment by jackkosaian** [comment]
Hi, all. The CUTLASS team recently learned of the use of `__CUDA_NO_HALF_CONVERSIONS__` in PyTorch.

Could you see if the following branch fixes the issues you were seeing that led to the need to remove `__CUDA_NO_HALF_CONVERSIONS__`? https://github.com/jackkosaian/cutlass/tree/fix/float8-half-conversions-2.11

If these changes help, we may be able to apply them upstream in CUTLASS. Would PyTorch potentially be able to use CUTLASS 3.0? It would be easiest for us to add such changes there.

**Comment by ezyang** [comment]
I think we are ok with 3, because jansel was attempting to jump us straight there

**Comment by jackkosaian** [comment]
Thanks. Let me know if the patch in the branch listed in my comment above resolves the issues. If so, we can port this to 3.0.

**Comment by ezyang** [comment]
@Skylion007 do you mind updating this PR to the branch?

**Comment by Skylion007** [comment]
@jackkosaian Unfortunately, I am still seeing the float8 errors.

**Comment by jackkosaian** [comment]
Hi, @Skylion007. Which float8 errors are you seeing? I don't see them in the logs, but, if you paste them here, I can work on fixing them.

I do see the following (non-float8) errors in `linux-binary-manywheel / manywheel-py3_8-cuda11_7-with-pypi-cudnn-build`:

```
2023-02-18T21:11:52.1049039Z ../aten/src/ATen/../../../third_party/cutlass/include/cutlass/functional.h(404): error: no suitable conversion function from "__half" to "int" exists
```

I'll work on fixing these.

**Comment by Skylion007** [comment]
@jackkosaian whoops, mistyped that last comment. 

Yeah the implicit half to int conversions are the main blockers at the moment.

**Comment by jackkosaian** [comment]
@Skylion007, I just pushed an update to that branch. Could you try it out, please?

**Comment by Skylion007** [comment]
@jackkosaian A bit early too tell since the run has completed, but it got past the part where it was stuck so it looks like that fixed it.

**Comment by Skylion007** [comment]
@jackkosaian Failures are all unrelated

**Comment by jackkosaian** [comment]
Thanks, @Skylion007. We will be including the fixes in question when we tag CUTLASS 3.0 (which should be taking place soon).

**Comment by Skylion007** [comment]
@jackkosaian Interestingly, I am getting errors on master from functional.h. Any idea what the issue is?

**Comment by Skylion007** [comment]
```
../aten/src/ATen/../../../third_party/cutlass/include/cutlass/functional.h(98): error: identifier "__hadd2" is undefined

../aten/src/ATen/../../../third_party/cutlass/include/cutlass/functional.h(106): error: identifier "__hsub2" is undefined

../aten/src/ATen/../../../third_party/cutlass/include/cutlass/functional.h(114): error: identifier "__hmul2" is undefined

../aten/src/ATen/../../../third_party/cutlass/include/cutlass/functional.h(123): error: no suitable conversion function from "__half" to "int" exists

../aten/src/ATen/../../../third_party/cutlass/include/cutlass/functional.h(123): error: no suitable conversion function from "const __half" to "int" exists

../aten/src/ATen/../../../third_party/cutlass/include/cutlass/functional.h(131): error: identifier "__hsub" is undefined

../aten/src/ATen/../../../third_party/cutlass/include/cutlass/functional.h(139): error: identifier "__hmul" is undefined

7 errors detected in the compilation of "../aten/src/ATen/native/nested/cuda/NestedTensorMatmul.cu".
../aten/src/ATen/../../../third_party/cutlass/include/cutlass/functional.h(98): error: identifier "__hadd2" is undefined

../aten/src/ATen/../../../third_party/cutlass/include/cutlass/functional.h(106): error: identifier "__hsub2" is undefined

../aten/src/ATen/../../../third_party/cutlass/include/cutlass/functional.h(114): error: identifier "__hmul2" is undefined

../aten/src/ATen/../../../third_party/cutlass/include/cutlass/functional.h(123): error: no suitable conversion function from "__half" to "int" exists

../aten/src/ATen/../../../third_party/cutlass/include/cutlass/functional.h(123): error: no suitable conversion function from "const __half" to "int" exists

../aten/src/ATen/../../../third_party/cutlass/include/cutlass/functional.h(131): error: identifier "__hsub" is undefined

../aten/src/ATen/../../../third_party/cutlass/include/cutlass/functional.h(139): error: identifier "__hmul" is undefined

7 errors detected in the compilation of "../aten/src/ATen/native/nested/cuda/NestedTensorMatmul.cu".
```
Seems to errors caused by code introduced by new operations in master.

**Comment by jackkosaian** [comment]
Thanks for trying it out, @Skylion007.

It's interesting that these operators caused an issue. I had previously found the absence of these to cause an error when compiling CUTLASS with `__CUDA_NO_HALF2_OPERATORS__` set. This flag is set when building PyTorch, right?

**Comment by Skylion007** [comment]
> Thanks for trying it out, @Skylion007.
> 
> It's interesting that these operators caused an issue. I had previously found the absence of these to cause an error when compiling CUTLASS with `__CUDA_NO_HALF_OPERATORS__` and `__CUDA_NO_HALF2_OPERATORS__` set. These flags are set when building PyTorch, right?

I believe so yes: https://github.com/pytorch/pytorch/blob/24c49dbf143aa25926723c16e3e013add2199cd9/cmake/Dependencies.cmake#L1638

**Comment by Skylion007** [comment]
@ngimel What are your thoughts about enabling HALF and HALF2 operators?

**Comment by ngimel** [comment]
Enabling half operators tanks performance on consumer pascal cards that are still in use, also, implicit half operators shouldn't be used in pytorch, for native bandwidth bound ops we convert to float everywhere.

**Comment by Skylion007** [comment]
@ngimel Yeah, CUTLASS v3 does drop support for Pascal cards, hence why I initially wanted to update CUTLASS to 2.11. I know @jansel wanted to jump straight to 3 though.

**Comment by ngimel** [comment]
I'm not against dropping support for pascal cards for operations we implement via cutlass (hence updating to cutlass 3.0 is not a problem by itself, we already guard compilation of those ops on compute capability), but I'm reluctant to change the compile flags for all of pytorch.

**Comment by ngimel** [comment]
Per https://github.com/pytorch/pytorch/pull/94188#issuecomment-1428468832, enabling HALF ops broke cuda 12 builds?

**Comment by Skylion007** [comment]
@jackkosaian Would it be possible to allow it to be compiled without the OPERATOR flags?

**Review by malfet — APPROVED** [review]

**Comment by jackkosaian** [comment]
@Skylion007 , yes, CUTLASS doesn't need those flags. We can likely remove the code that is causing an issue -- I had added it because it seemed like there were some issues without this code with one of these flags (I can't remember which one): https://github.com/pytorch/pytorch/blob/24c49dbf143aa25926723c16e3e013add2199cd9/cmake/Dependencies.cmake#L1638-L1642.

I'll make sure that things are fine from the CUTLASS end without this and report back. If it doesn't seem needed, we'll remove the lines currently causing the issue.

**Comment by jackkosaian** [comment]
@Skylion007, would you be able to provide a small reproducer for this? I haven't been able to reproduce the issue itself. I actually find that the lines that your compilation errors out on are needed to avoid other errors in CUTLASS unit tests when compiling with `-D__CUDA_NO_HALF_OPERATORS__` and friends.

**Comment by Skylion007** [comment]
> @Skylion007, would you be able to provide a small reproducer for this? I haven't been able to reproduce the issue itself. I actually find that the lines that your compilation errors out on are needed to avoid other errors in CUTLASS unit tests when compiling with `-D__CUDA_NO_HALF_OPERATORS__` and friends.

@jackkosaian Any ideas for a small reproducer?

**Comment by ptrblck** [comment]
I've tried to reproduce the build failure using `skylion007/update-cutlass-to-v2.11` which points to [`cutlass @ c4f6b8c6`](https://github.com/NVIDIA/cutlass/commit/c4f6b8c6) in CUDA 12.1, but the build did not break. Since the reported issues are seen in 11.x builds, I'll retry the build using these CUDA versions.

**Comment by ngimel** [comment]
@ptrblck yeah I think we'd like to update cutlass pin to https://github.com/NVIDIA/cutlass/commit/c4f6b8c6 - it should be possible to use it with cuda 11.x, or does it require cuda 12? If so, that would explain build failures.

**Comment by jackkosaian** [comment]
@ngimel, CUTLASS 3.0 supports CUDA 11.4 and beyond. Full Hopper support requires 12.0, but it doesn't seem that the errors linked above have anything to do with Hopper kernels, so I'd be surprised if that's a factor.

**Comment by thakkarV** [comment]
CUTLASS 3.0 release is compatible with CUDA 11.4 or newer but we recommend 11.8 at least for < SM90. Hopper (SM90a) tensor core support requires 12.0.

**Comment by ptrblck** [comment]
I've ran a few more builds with CUDA 11.8 and different compute capabilities (7.0, 8.0, 8.6), which all worked. The build log indicated that GCC 7.5.0 was used so I downgraded from 9.4.0, which also did not reproduce the failure.

However, I missed in the build logs that `TORCH_CUDA_ARCH_LIST: 5.2` is used as I guess this build is done for an M60 runner.
Building for this compute capability fails (thanks @ngimel for pointing me into the direction of investigating different compute capabilities).

A fix would be to add an additional guard to cutlass [here](https://github.com/NVIDIA/cutlass/blob/c4f6b8c6bc94ff69048492fb34df0dfaf1983933/include/cutlass/functional.h#L92):
```
#if defined(__CUDA_ARCH__) && __CUDA_ARCH__ >=530
/// Partial specializations needed when __CUDA_NO_HALF2_OPERATORS__ is set
template<>
struct plus<__half2> {
  CUTLASS_HOST_DEVICE
  __half2 operator()(__half2 lhs, __half2 const &rhs) const {
    return __hadd2(lhs, rhs);
  }
};
```
Note that I naively stole `__CUDA_ARCH__ >=530` from e.g. [aten/src/ATen/native/transformers/cuda/flash_attn/utils.h#L262](https://github.com/pytorch/pytorch/blob/eb32bb2ca6811ea21002699f4be884d3012dc362/aten/src/ATen/native/transformers/cuda/flash_attn/utils.h#L262), but since cutlass drops Pascal support this check could use a newer architecture.

Also, I removed [this dispatch](https://github.com/pytorch/pytorch/blob/912748e3b7e4cd02d8fb7b428ab083e444dde8df/aten/src/ATen/native/transformers/cuda/mem_eff_attention/gemm_kernel_utils.h#L45-L47):
```
    } else if (CC >= 50) {                                                \
      using ArchTag = cutlass::arch::Sm50;                                \
      func();                                                             \
```
since I have guessed it could cause other issues (I did not verify that the deletion is needed).

A build for sm_52 and sm_80 was successful:
```python
python -c "import torch; print(torch.cuda.get_arch_list())"
['sm_52', 'sm_80']
```
and I ran `python test/test_transformers.py` additionally on an A100 which also seems to work:
```
...
test_transformerencoderlayer_src_mask_device_cuda_nhead_1 (__main__.TestTransformers) ... ok
test_transformerencoderlayer_src_mask_device_cuda_nhead_4 (__main__.TestTransformers) ... ok
test_transformerencoderlayer_src_mask_device_cuda_nhead_8 (__main__.TestTransformers) ... ok

----------------------------------------------------------------------
Ran 20290 tests in 92.044s

OK (skipped=8)
```

@jackkosaian @thakkarV would it be possible to add the `__CUDA_ARCH__` check into cutlass, which might also solve [this issue](https://github.com/NVIDIA/cutlass/issues/4)?

**Comment by ngimel** [comment]
Thank you @ptrbck for the investigation! cc @cpuhrsch as the build errors come from the NestedTensor. Should we instead ifdef compilation of NestedTensor ops that won't be supported on earlier architectures? I suspect nothing good comes out if someone attempts to run GroupedGemm on an older card.

**Comment by cpuhrsch** [comment]
@ngimel - Yes, I think it's ok to not support older architectures. How old are we thinking? There are people running stuff in Google colab GPUs and such.

**Comment by ngimel** [comment]
NestedTensorMatmul.cu that errors with these includes dispatched to `cutlass::GroupGemm` for sm80 only anyway, everything older went to loop fallback. Similarly for mha, so it's no user visible changes, just need to make build pass.

**Comment by Skylion007** [comment]
Still a few errors on certain compilers even after @ptrblck's fix. Thoughts @jackkosaian? @ptrblck?

**Comment by ptrblck** [comment]
The issue is caused by the usage of VLAs in `CUTLASS==3.0` and fails in Clang12 build, which I was able to reproduce.
CUTLASS has fixed this issue already in an internal branch and I was also able to verify a successful build using this PR branch, `CUTLASS==3.1`RC and Clang12.
`CUTLASS==3.1` should be released soon, but I let @jackkosaian and @thakkarV comment on the release date.

**Comment by thakkarV** [comment]
CUTLASS 3.1 release is set for next week, which fixes this issue. Would it be possible to wait until 3.1 release for integration?

**Comment by Qiyu8** [comment]
I'm building pytorch1.13.1 with cutlass，but when `python3 setup.py install` is finished, no cutlass is available under `build/lib/libtorch_cuda_cpp.so`, how to enable cutlass when build pytorch1.13.1?

**Comment by Skylion007** [comment]
@thakkarV @jackkosaian @ptrblck looks like still a few compilation issues with the latest version of CUTLASS

**Comment by thakkarV** [comment]
CUTLASS 3.1 was just released. It has not been tagged just yet as we wait for any potential bugs to be reported, but it should be able to address some of the issues that were brought up in this thread regarding compiler support.

**Comment by ptrblck** [comment]
The build failure in [linux-bionic-cuda11.8-py3.10-gcc7-bazel-test](https://github.com/pytorch/pytorch/actions/runs/4714641889/jobs/8361133218?pr=94188#logs):
```
ERROR: /var/lib/jenkins/workspace/BUILD.bazel:427:11: Compiling aten/src/ATen/native/nested/cuda/NestedTensorTransformerFunctions.cu failed: (Exit 1): nvcc failed: error executing command external/local_cuda/cuda/bin/nvcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++11' -MD -MF ... (remaining 314 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
nvcc-real warning : incompatible redefinition for option 'std', the last value of this option was used
In file included from external/cutlass/include/cutlass/gemm/gemm.h:38:0,
                 from external/cutlass/include/cutlass/arch/mma.h:41,
                 from external/cutlass/include/cutlass/gemm/device/default_gemm_configuration.h:40,
                 from aten/src/ATen/native/nested/cuda/NestedTensorTransformerFunctions.cu:22:
external/cutlass/include/cutlass/layout/matrix.h:42:10: fatal error: cute/layout.hpp: No such file or directory
 #include "cute/layout.hpp"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
```
is real and caused by `third_party/cutlass.BUILD` which does not include the `cute/*hpp` files.
This can be seen via `bazel query "@cutlass//:*"` and the fix would be changing `third_party/cutlass.BUILD` to:
```
 cc_library(
     name = "cutlass",
-    hdrs = glob(["include/**/*.h"]),
+    hdrs = glob(["include/**/*.h", "include/**/*.hpp"]),
     includes = ["include/"],
     visibility = ["//visibility:public"],
 )
```
I've verified the bazel build issue locally first and a successful build afterwards using my proposed change. 

The other failing tests show:
```
2023-04-16T19:08:17.3698152Z cuda eval  detectron2_maskrcnn_r_101_c4        WARNING:common:fp64 golden ref were not generated for detectron2_maskrcnn_r_101_c4. Setting accuracy check to cosine
2023-04-16T19:08:28.0912919Z ERROR:common:
2023-04-16T19:08:28.0913395Z Traceback (most recent call last):
2023-04-16T19:08:28.0914684Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 729, in LOAD_GLOBAL
2023-04-16T19:08:28.0920653Z     value = self.f_globals[name]
2023-04-16T19:08:28.0921713Z KeyError: '_ignore_torch_cuda_oom'
```
```
ERROR:common:

from user code:
   File "/var/lib/jenkins/.local/lib/python3.10/site-packages/torchvision/ops/boxes.py", line 165, in clip_boxes_to_image
    return clipped_boxes.reshape(boxes.shape)
...
RecursionError: maximum recursion depth exceeded in __instancecheck__
```
```
FAILED [3.5133s] distributed/fsdp/test_fsdp_sharded_grad_scaler.py::TestShardedGradScalerParityWithDDP::test_fsdp_ddp_parity_with_grad_scaler_offload_false_none_mixed_precision_use_orig_params
...
Expected 624.0 but got -10640.5.
Absolute difference: 11264.5 (up to 1e-05 allowed)
Relative difference: 18.052083333333332 (up to 0.001 allowed)
```
and might be unrelated to this PR.

**Comment by malfet** [comment]
@Skylion007 can you please rebase (this should at least fix `KeyError: '_ignore_torch_cuda_oom'`

I've never seen recursion depth error before, but probably something that rebase could fix

**Comment by ptrblck** [comment]
Failing test is:
```
2023-04-22T15:59:26.2472754Z Error 1 models failed
2023-04-22T15:59:26.2473094Z     pyhpc_turbulent_kinetic_energy
```
Unsure, if it's real or unrelated to this PR.

**Comment by ngimel** [comment]
Test failure is unrelated.
