### ISSUE TITLE
Adding a link to libtorch in the ompl project will cause the definition of Boost to not be found during the link process of the original code of the project

### ISSUE THREAD

**Issue by JYMiracle305** [pytorch/pytorch#136517]
## Issue description

```
[ 68%] Linking CXX executable test_adjacency_list
/usr/bin/ld: CMakeFiles/test_adjacency_list.dir/datastructures/adjacency_list.cpp.o: in function boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long) [clone .isra.0]':
adjacency_list.cpp:(.text.startup+0x41): undefined reference to boost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring<char const>)'
/usr/bin/ld: ../src/ompl/libompl.so.1.6.0: undefined reference to boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::save(std::string const&)
'

collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/test_adjacency_list.dir/build.make:107: tests/test_adjacency_list] Error 1
make[1]: *** [CMakeFiles/Makefile2:508: tests/CMakeFiles/test_adjacency_list.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```
![image](https://github.com/user-attachments/assets/44824222-749d-40ac-ba77-0e35547ef16c)

Provide a short description.

Adding a link to libtorch in the ompl project will cause the definition of Boost to not be found during the link process of the original code of the project

ompl：https://github.com/ompl/ompl

Add in the ompl root directory
```
list(APPEND CMAKE_PREFIX_PATH "/home/l/libtorch")
find_package(Torch REQUIRED)
```

Add in ompl/src
![image](https://github.com/user-attachments/assets/27eb7189-03d4-4bed-93c4-2572c8d08a2c)

Why are there no problems when they are compiled separately, but when they are combined together, it will affect the definition of linking to the Boost library

cc @seemethere @malfet @osalpekar @atalman @jbschlosser

**Comment by malfet** [comment]
This looks like something that should be discussed in https://discuss.pytorch.org as it's not a torch problem per se. 
But I guess this is due to CXX11 incompatibilities. Please try installing CXX11 ABI compatible libtorch
