### PR TITLE
Test that TORCH_FEATURE_VERSION guards are used where needed

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
Splits each torch library registration in the 2.10 folder into its own file -- I had a script that parsed kernel.cpp to do this but I felt like forcing this responsibility on the user might be less error prone

Compiles each file targetting 2.9 and asserts that compilation fails. (There are 2 2.9 kernels we use as negative tests where compilation is expected to succeed)

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #168062
* #168034
* __->__ #167962
* #167804
* #167803
* #167802
* #168025

### CODE REVIEW

File: test/cpp_extensions/libtorch_agnostic_2_10_extension/libtorch_agnostic_2_10/csrc/mv_tensor_accessor_cpu.cpp [hunk 1]
```diff
@@ -0,0 +1,40 @@
+// This is duplicated from the libtorch_agnostic_2_9_extension
```
Comment (janeyx99) [inline test/cpp_extensions/libtorch_agnostic_2_10_extension/libtorch_agnostic_2_10/csrc/mv_tensor_accessor_cpu.cpp:1]: mv_tensor_accessor_cpu was added in 2_10, no?

File: test/cpp_extensions/libtorch_agnostic_2_10_extension/libtorch_agnostic_2_10/csrc/mv_tensor_accessor_cuda.cu [hunk 2]
```diff
@@ -0,0 +1,47 @@
+// This is duplicated from the libtorch_agnostic_2_9_extension
```
Comment (janeyx99) [inline test/cpp_extensions/libtorch_agnostic_2_10_extension/libtorch_agnostic_2_10/csrc/mv_tensor_accessor_cuda.cu:1]: same

File: test/cpp_extensions/libtorch_agnostic_2_10_extension/libtorch_agnostic_2_10/csrc/make_tensor_clones_and_call_foreach.cpp [hunk 3]
```diff
@@ -0,0 +1,41 @@
+#include <torch/csrc/stable/library.h>
+#include <torch/csrc/stable/ops.h>
+#include <torch/csrc/stable/tensor.h>
+
+#include <vector>
+
+using torch::stable::Tensor;
+
+// Declare my__foreach_mul (defined in my__foreach_mul.cpp)
+extern std::vector<Tensor> my__foreach_mul(
```
Comment (janeyx99) [inline test/cpp_extensions/libtorch_agnostic_2_10_extension/libtorch_agnostic_2_10/csrc/make_tensor_clones_and_call_foreach.cpp:10]: Is this code resilient to linking order? e.g., if this code is linked before my__foreach_mul.cpp, will it break?

File: test/cpp_extensions/libtorch_agnostic_2_10_extension/libtorch_agnostic_2_10/csrc/mv_tensor_accessor_cpu.cpp (hunk 1 above)
Comment (janeyx99) [reply test/cpp_extensions/libtorch_agnostic_2_10_extension/libtorch_agnostic_2_10/csrc/mv_tensor_accessor_cpu.cpp:1]: yea hmmm should this code be in 2_10 from the start? Or no, because it's header only?

This is a bit of a confusing counterexample because it is headeronly so it retroactively works, but a more clear example might be something that was definitely landed in 2_9?

Comment (mikaylagawarecki) [reply test/cpp_extensions/libtorch_agnostic_2_10_extension/libtorch_agnostic_2_10/csrc/mv_tensor_accessor_cpu.cpp:1]: It works in 2.9 because it only uses things in headeronly

There's nothing being passed across the shim boundary and stable::Tensor.sizes() and stable::Tensor.strides() also works in 2.9 is my understanding 

My workflow in the below PR ensures that this test is able to run on 2.9

File: test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py [hunk 4]
```diff
@@ -0,0 +1,300 @@
...
+            if not self.cuda_available:
+                self.skipTest(f"CUDA not available, skipping {source_file.name}")
+            success, error_msg = self._compile_cu_file(source_file, obj_file)
+        else:
+            success, error_msg = self._compile_cpp_file(source_file, obj_file)
+
+        obj_file.unlink(missing_ok=True)
+
+        # Print error details for debugging
+        if not success and os.environ.get("VERSION_COMPAT_DEBUG", "0") == "1":
```
Comment (janeyx99) [inline test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py]: how come we don't always print by default?

File: test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py [hunk 5]
```diff
@@ -0,0 +1,300 @@
...
+        success, error_msg = self._compile_cpp_file(cpp_file, obj_file)
+
+        # Clean up
+        obj_file.unlink(missing_ok=True)
+
+        if not success:
+            relevant_errors = self._extract_relevant_errors(error_msg)
+            if relevant_errors:
+                print("\n  Unexpected compilation errors for mv_tensor_accessor_cpu:")
+                for err in relevant_errors[:10]:
```
Comment (janeyx99) [inline test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py]: is the 10 arbitrary haha

File: test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py [hunk 6]
```diff
@@ -0,0 +1,300 @@
...
+                    print(f"{err}")
+
+        self.assertTrue(
+            success,
+            f"mv_tensor_accessor_cpu.cpp failed to compile with TORCH_TARGET_VERSION=2.9.0. "
+            f"This file is expected to work with 2.9.0 since it doesn't use 2.10+ features. "
+            f"Error: {error_msg[:500]}",
```
Comment (janeyx99) [inline test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py]: and 500 here too--what's the normal max length you'd expect?

File: test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py [hunk 7]
```diff
@@ -0,0 +1,300 @@
...
+                or "undefined" in line_lower
+                or "undeclared" in line_lower
+                or "no member named" in line_lower
+            ):
+                relevant_errors.append(line.strip())
+
+        return relevant_errors
+
+
+# Dynamically create test methods for each .cpp and .cu file
```
Comment (janeyx99) [inline test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py]: Can we still run an individual test with -k for dynamically created test methods? (I'm guessing yes)

File: test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py [hunk 8]
```diff
@@ -0,0 +1,300 @@
...
+    test_method_impl.__name__ = f"test_{func_name}_requires_2_10"
+    test_method_impl.__doc__ = f"Test that {func_name}{file_ext} requires PyTorch 2.10+"
+
+    return test_method_impl
+
+
+# Test discovery: generate a test for each .cpp and .cu file
+_csrc_dir = Path(__file__).parent / "libtorch_agnostic_2_10" / "csrc"
+if _csrc_dir.exists():
+    # Collect both .cpp and .cu files, excluding those used for negative tests
```
Comment (janeyx99) [inline test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py]:
```suggestion
    # Collect both .cpp and .cu files, excluding those used for negative tests already defined above
```

**Review by janeyx99 — APPROVED** [review]

File: test/cpp_extensions/libtorch_agnostic_2_10_extension/libtorch_agnostic_2_10/csrc/mv_tensor_accessor_cpu.cpp (hunk 1 above)
Comment (mikaylagawarecki) [reply test/cpp_extensions/libtorch_agnostic_2_10_extension/libtorch_agnostic_2_10/csrc/mv_tensor_accessor_cpu.cpp:1]: @janeyx99

> This is a bit of a confusing counterexample because it is headeronly so it retroactively works, but a more clear example might be something that was definitely landed in 2_9?

I agree that it is confusing, but I disagree that it's not a good sanity check test, this function demonstrates the exact case that we want this test class to catch

- Current version is 2.x, user adds test and adds it to `libtorch_agnostic_2_x_extension` thinking this is a 2.x feature
- We want this test to catch this (due to compilation succeeding) and prompt the user to either add version guards or move this test to `libtorch_agnostic_2_(x-1)_extension`
- If the `libtorch_agnostic_targetting` workflow succeeds, we've confirmed the test belongs in `libtorch_agnostic_2_(x-1)_extension`, otherwise we have signal for the user that they missed version guards

wdyt, does that motivate the rationale for choosing this kernel better? Also happy to add others in a followup if you disagree

File: test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py (hunk 7 above)
Comment (mikaylagawarecki) [reply test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py]: Yep, I was able to run 

```
python test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py  -k test_my_view_requires_2_10
```

File: test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py (hunk 4 above)
Comment (mikaylagawarecki) [reply test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py]: fixed

File: test/cpp_extensions/libtorch_agnostic_2_10_extension/libtorch_agnostic_2_10/csrc/make_tensor_clones_and_call_foreach.cpp (hunk 3 above)
Comment (mikaylagawarecki) [reply test/cpp_extensions/libtorch_agnostic_2_10_extension/libtorch_agnostic_2_10/csrc/make_tensor_clones_and_call_foreach.cpp:10]: Hm good question, I didn't run into any issues with this so far, according to claude it should not matter :)

*   `**setup.py**` compiles all `.cpp` files in the `csrc` directory as separate object files
*   The files are linked together into a single shared library (`_C.so`)
*   The linker resolves the symbol `**my__foreach_mul**`regardless of which object file comes first in the link order

File: test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py (hunk 5 above)
Comment (mikaylagawarecki) [reply test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py]: yea removed all these

File: test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py (hunk 6 above)
Comment (mikaylagawarecki) [reply test/cpp_extensions/libtorch_agnostic_2_10_extension/test_version_compatibility.py]: removed

**Comment by jeffdaily** [comment]
This broke ROCm, but forward fix incoming.
