### ISSUE TITLE
Unable to build PyTorch without Numpy installed (again)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#55849]
```
In file included from /data/users/ezyang/pytorch-tmp/caffe2/python/pybind_state.cc:1:
/data/users/ezyang/pytorch-tmp/caffe2/python/pybind_state.h:27:10: fatal error: numpy/arrayobject.h: No such file or directory
 #include <numpy/arrayobject.h>                                  
          ^~~~~~~~~~~~~~~~~~~~~
```

cc @malfet @seemethere @walterddr @mruberry @rgommers @heitorschueroff

**Comment by ngimel** [comment]
That's a caffe2 bug :-) Workaround is `BUILD_CAFFE2=0 BUILD_CAFFE2_OPS=0`. One day, it will become default :-)

**Comment by rgommers** [comment]
Seems like we should have a CI job where numpy is not installed ...

**Comment by gchanan** [comment]
CC @malfet @seemethere

**Comment by malfet** [comment]
We should fix the build, but I've also filed https://github.com/pytorch/pytorch/issues/56038 to track which optional features are currently tested. I don't think it's feasible to test builds for every feature turned on and off, but perhaps a periodic build that tries to build with certain features enabled/disabled would be good

**Comment by malfet** [comment]
It was caused by https://github.com/pytorch/pytorch/pull/51143
