### PR TITLE
[BE][Ez][Bugfix] Update minimum typing_extenions to '>4.10.0'

### LINKED ISSUE #133883: TypeIs Not Found in typing_extensions for python version > 3.9
### 🐛 Describe the bug

Encountered an issue with a recent merge in the PyTorch repository ([https://github.com/pytorch/pytorch/commit/cf60fe53a83bafec0857d5b49c2054de6ba4cddc](https://github.com/pytorch/pytorch/commit/cf60fe53a83bafec0857d5b49c2054de6ba4cddc))
The issue arises because `TypeIs` was changed from `TypeGuard`.  It is proposed for a future version of  python (3.13) but does not currently work on 3.10. 
Link: https://peps.python.org/pep-0742/

Reverting the change to use `TypeGuard` resolves the issue.
To reproduce this bug, run a torchrun command in an environment with python version 3.10: 
 
 `torchrun -node_rank=${ARRAY_INDEX} --master_addr=${MASTER_ADDR} --master_port=49228  --nproc_per_node=8 --nnodes=1 test.py`

`test.py` is a simple `Hello World` print program. 
 
 The error that I get is: 
`ImportError: cannot import name 'TypeIs' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)`

The files where 'TypeGuard' was changed to 'TypeIs':
- torch/__init__.py
- torch/_dynamo/utils.py
- torch/_inductor/pattern_matcher.py
- torch/_subclasses/fake_tensor.py
- torch/masked/maskedtensor/core.py
- torch/nn/parameter.pyi
- torch/serialization.py
- torch/utils/_python_dispatch.py
- torch/utils/_sympy/value_ranges.py

Reverting the change to use `TypeGuard` resolves the issue.

### Versions

```
torchrun -node_rank=${ARRAY_INDEX} --master_addr=${MASTER_ADDR} --master_port=49228  --nproc_per_node=8 --nnodes=1  /workspace/test.py
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.2.0a0+81ea7a4', 'console_scripts', 'torchrun')())
  File "/usr/local/bin/torchrun", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "-<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 37, in <module>
    from typing_extensions import ParamSpec as _ParamSpec, TypeIs as _TypeIs
ImportError: cannot import name 'TypeIs' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)
```

### PR DESCRIPTION
**Pull request by Skylion007**
Fixes #133883 since we require newer typing_extension features now as a result of https://github.com/pytorch/pytorch/commit/cf60fe53a83bafec0857d5b49c2054de6ba4cddc

### CODE REVIEW

**Comment by Skylion007** [comment]
Superceded by reland of #133814
