### PR TITLE
do not use constexpr with CUDA >= 9.2 compiler on Windows.

### PR DESCRIPTION
**Pull request by shkit**
Define `AT_CPP14_CONSTEXPR` from `constexpr` to empty on Windows with CUDA >= 9.2 as workaround.

Discussed in #18425.

When using CUDA 10.1 on Windows, I faced following errors:
~~~
D:/data/source/pytorch\c10/util/ArrayRef.h(144): error: variable in constexpr function does not have automatic storage duration
          detected during instantiation of "const T &c10::ArrayRef<T>::front() const [with T=at::Tensor]"
D:/data/source/pytorch/aten/src\ATen/DeviceGuard.h(30): here
~~~

From documentation of CUDA Toolkit v10.1.105, compiler supports `constexpr` and relaxing requirements (in C++14), but compilation failed.

I suppose this could be compiler bug and require this workaround.

### CODE REVIEW

**Comment by peterjc123** [comment]
It suppose this is MSVC only. Could you please add this check `if defined(_MSC_VER)`?

**Comment by shkit** [comment]
I tried to compile in `nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04` container and compilation succeeds.
Ok, this workaround seems to be required only in MSVC environment.
I'll update patch.

**Comment by peterjc123** [comment]
https://github.com/pytorch/pytorch/issues/11203 looks like it is also a problem for cuda 9.2. Could you change the minimum version a little bit?

**Comment by shkit** [comment]
Hmm...
I'll update checking `>=9.2`

**Review by peterjc123 — APPROVED** [review]

**Comment by ezyang** [comment]
cc @smessmer

**Comment by xsacha** [comment]
Thanks! I noticed this issue and just removed the constexpr for MSVC in my fork. Wasn't sure which versions of CUDA were affected.
This will help a lot.

**Review by xsacha — APPROVED** [review]

**Comment by peterjc123** [comment]
@ezyang Please remember to merge this.

**Comment by ezyang** [comment]
Ya, there was an internal outage which meant I couldn't land. It's landing now.
