### ISSUE TITLE
Sparse tensors don't work with DataParallel

### ISSUE THREAD

**Issue by bobchennan** [pytorch/pytorch#1456]
When should us use sparse embedding? I tried to use it in my module and get the following error:

```
  File "", line 58, in <module>
    loss.backward()
  File "", line 146, in backward
    self._execution_engine.run_backward((self,), (gradient,), retain_variables)
  File "", line 24, in backward
    return comm.reduce_add_coalesced(grad_outputs, self.input_device)
  File "", line 123, in reduce_add_coalesced
    for chunks in zip(*itrs):
  File "", line 242, in _take_tensors
    param_size = tensor.numel() * tensor.element_size()
AttributeError: 'torch.cuda.sparse.FloatTensor' object has no attribute 'numel'
```

**Comment by soumith** [comment]
@bobchennan how can i reproduce this? Do you have a code snippet?

**Comment by apaszke** [comment]
From the stack trace it seems that sparse CUDA Embedding isn't compatible with DataParallel

**Comment by bobchennan** [comment]
Yes, I used the data parallel. Let me test with non-parallel case.

**Comment by bobchennan** [comment]
Meet another error:
```

  File "", line 60, in <module>
    optimizer.step()
  File "", line 66, in step
    exp_avg_sq.mul_(beta2).addcmul_(1 - beta2, grad, grad)
AttributeError: 'torch.cuda.sparse.FloatTensor' object has no attribute 'addcmul_'
```
It seems to be mentioned by another issue.

**Comment by SsnL** [comment]
Fixed via #3211 .

**Comment by ortasa** [comment]
Hi,
Is there a work around for working with sparse tensor when batch_size>1? The version I work with is 0.3.1.
The error I get is:
AttributeError: 'torch.sparse.FloatTensor' object has no attribute 'unsqueeze'
Thank you,
Ortal
