### ISSUE TITLE
Not working in the Python 3.12.0

### ISSUE THREAD

**Issue by thisisankit27** [pytorch/pytorch#112478]
### 🐛 Describe the bug

```
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
```

### Versions

Well i rolled back Python 3.12.0 to 3.10.5,
here is the output in 3.10.5

ollecting environment information...
Traceback (most recent call last):
  File "C:\Users\thisi\OneDrive\Desktop\Others\collect_env.py", line 612, in <module>
    main()
  File "C:\Users\thisi\OneDrive\Desktop\Others\collect_env.py", line 595, in main
    output = get_pretty_env_info()
  File "C:\Users\thisi\OneDrive\Desktop\Others\collect_env.py", line 590, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "C:\Users\thisi\OneDrive\Desktop\Others\collect_env.py", line 428, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
  File "C:\Users\thisi\OneDrive\Desktop\Others\collect_env.py", line 400, in get_pip_packages
    out = run_with_pip([sys.executable, '-mpip'])
  File "C:\Users\thisi\OneDrive\Desktop\Others\collect_env.py", line 384, in run_with_pip
    for line in out.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'

cc @seemethere @malfet @osalpekar @atalman

**Comment by malfet** [comment]
Yes, there are no binary builds for Python-3.12 yet

**Comment by thisisankit27** [comment]
Oh, well thank you.

**Comment by albanD** [comment]
Closing in favor of https://github.com/pytorch/pytorch/issues/110436 which is about the same thing
