### PR TITLE
[BE] [cuDNN] Always build assuming cuDNN >= 8.1

### PR DESCRIPTION
**Pull request by eqy**
### <samp>🤖 Generated by Copilot at 27084ed</samp>

This pull request simplifies and cleans up the code that uses the cuDNN library for convolution, batch normalization, CTC loss, and quantized operations. It removes the unnecessary checks and conditions for older cuDNN versions and the experimental cuDNN v8 API, and ~~replaces them with the stable `cudnn_frontend` API that requires cuDNN v8 or higher. It also adds the dependency and configuration for the `cudnn_frontend` library in the cmake and bazel files.~~ Correction: The v7 API will still be available with this PR, and can still be used, without any changes to the defaults. This change simply always _builds_ the v8 API, and removes the case where _only_ the v7 API is built.

This is a re-land of https://github.com/pytorch/pytorch/pull/91527

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Added `cudnn_frontend` dependency to few internal targets, if everything is green, will land today.

**Review by malfet — CHANGES_REQUESTED** [review]
Please fix Bazel build. Also, why aren't you deleting `src/ATen/native/cudnn/Macros.h`

**Comment by eqy** [comment]
Thanks, removed `Macros.h` and remaining use of `HAS_CUDNN_V8` which hopefully fixes the bazel build problem as well?

**Review by malfet — APPROVED** [review]

**Comment by eqy** [comment]
(moving discussion back here) @malfet this PR does add cudnn frontend to the bazel build but do you think something is missing for cudnn frontend? The reason I mentioned the other PR was that CI was green on this PR (with cudnn-frontend) during the last round, and the current failing test was added by #101475

**Comment by eqy** [comment]
Confirming that I can reproduec the bazel failure locally. Hopefully it's debuggable without too much additional effort but the lack of a stack trace by default (even with `TORCH_SHOW_CPP_STACKTRACES=1` is disappointing

**Comment by eqy** [comment]
It does look to be related to the quantized path as gdb reveals this stack trace
```
Warning: Loading nvfuser library failed with: Error in dlopen: libnvfuser_codegen.so: cannot open shared object file: No such file or directory (function LoadingNvfuserLibrary)                                                    [12/1851]
terminate called after throwing an instance of 'c10::Error'
  what():  Type c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > could not be converted to any of the known types.
Exception raised from operator() at aten/src/ATen/core/jit_type.h:1809 (most recent call first):
(no backtrace available)

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=139678745432064) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb)
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139678745432064) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139678745432064) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139678745432064, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f097e054476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f097e03a7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007f093cd02bbe in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f093cd0e24c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f093cd0e2b7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f093cd0e518 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f095652b484 in c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#10 0x00007f094954195d in c10::detail::getTypePtr_<c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > >::call()::{lambda()#1}::operator()() const ()
   from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#11 0x00007f09495419bb in c10::detail::getTypePtr_<c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > >::call() ()
   from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#12 0x00007f09495419dd in c10::detail::getMaybeFakeTypePtr_<c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > >, false>::call() ()
   from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#13 0x00007f09495419ff in decltype(auto) c10::getTypePtr<c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > >() ()
   from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#14 0x00007f0949541a22 in c10::Type::SingletonOrSharedTypePtr<c10::Type> c10::getTypePtrCopy<c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > >() ()
   from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#15 0x00007f0949a6c2d3 in c10::detail::infer_schema::(anonymous namespace)::createArgumentVector(c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>) () from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#16 0x00007f0949a6c47d in c10::detail::infer_schema::make_function_schema(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>) () from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#17 0x00007f0949a6c667 in c10::detail::infer_schema::make_function_schema(c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>) ()
   from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#18 0x00007f09495415fd in c10::FunctionSchema c10::detail::infer_schema::createFunctionSchemaFromTraitsFlattenedReturns<c10::guts::function_traits<at::Tensor (at::Tensor, c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > const&, double, long)> >() () from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#19 0x00007f0949540f27 in c10::FunctionSchema c10::inferFunctionSchemaFlattenedReturns<at::Tensor (at::Tensor, c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > const&, double, long)>() () from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#20 0x00007f094954091f in std::unique_ptr<c10::FunctionSchema, std::default_delete<c10::FunctionSchema> > c10::detail::inferFunctionSchemaFromFunctor<at::Tensor (*)(at::Tensor, c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > const&, double, long)>() () from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#21 0x00007f0949540554 in torch::CppFunction::CppFunction<at::Tensor (at::Tensor, c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > const&, double, long)>(at::Tensor (*)(at::Tensor, c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > const&, double, long), std::enable_if<c10::guts::is_function_type<at::Tensor (at::Tensor, c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > const&, double, long)>::value, decltype(nullptr)>::type) ()
   from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#22 0x00007f094953bbdc in torch::Library& torch::Library::impl<char const*, at::Tensor (&)(at::Tensor, c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > const&, double, long)>(char const*, at::Tensor (&)(at::Tensor, c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > const&, double, long), torch::_RegisterOrVerify) & ()
   from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#23 0x00007f094953add9 in torch::Library& torch::Library::impl<at::Tensor (&)(at::Tensor, c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > const&, double, long)>(torch::detail::SelectiveStr<true>, at::Tensor (&)(at::Tensor, c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > const&, double, long)) & ()
   from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#24 0x00007f0949537621 in at::native::(anonymous namespace)::TORCH_LIBRARY_IMPL_init_quantized_QuantizedCUDA_2(torch::Library&) () from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#25 0x00007f094253452c in torch::detail::TorchLibraryInit::TorchLibraryInit(torch::Library::Kind, void (*)(torch::Library&), char const*, c10::optional<c10::DispatchKey>, char const*, unsigned int) ()
   from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#26 0x00007f094953ab3c in __static_initialization_and_destruction_0(int, int) () from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#27 0x00007f094953ab81 in _GLOBAL__sub_I_Conv.cpp () from /workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so
#28 0x00007f097f71647e in call_init (l=<optimized out>, argc=argc@entry=2, argv=argv@entry=0x7ffc6bb76b18, env=env@entry=0x7ffc6bb76b30) at ./elf/dl-init.c:70
#29 0x00007f097f716568 in call_init (env=0x7ffc6bb76b30, argv=0x7ffc6bb76b18, argc=2, l=<optimized out>) at ./elf/dl-init.c:33
#30 _dl_init (main_map=0x9f9060, argc=2, argv=0x7ffc6bb76b18, env=0x7ffc6bb76b30) at ./elf/dl-init.c:117
#31 0x00007f097e186c85 in __GI__dl_catch_exception (exception=<optimized out>, operate=<optimized out>, args=<optimized out>) at ./elf/dl-error-skeleton.c:182
#32 0x00007f097f71dff6 in dl_open_worker (a=0x7ffc6bb734d0) at ./elf/dl-open.c:808
#33 dl_open_worker (a=a@entry=0x7ffc6bb734d0) at ./elf/dl-open.c:771
#34 0x00007f097e186c28 in __GI__dl_catch_exception (exception=<optimized out>, operate=<optimized out>, args=<optimized out>) at ./elf/dl-error-skeleton.c:208
#35 0x00007f097f71e34e in _dl_open (file=<optimized out>, mode=-2147483646, caller_dlopen=0x7f097e53a057 <_PyImport_FindSharedFuncptr+103>, nsid=-2, argc=2, argv=<optimized out>, env=0x7ffc6bb76b30) at ./elf/dl-open.c:883
#36 0x00007f097e0a26bc in dlopen_doit (a=a@entry=0x7ffc6bb73740) at ./dlfcn/dlopen.c:56
#37 0x00007f097e186c28 in __GI__dl_catch_exception (exception=exception@entry=0x7ffc6bb736a0, operate=<optimized out>, args=<optimized out>) at ./elf/dl-error-skeleton.c:208
#38 0x00007f097e186cf3 in __GI__dl_catch_error (objname=0x7ffc6bb736f8, errstring=0x7ffc6bb73700, mallocedp=0x7ffc6bb736f7, operate=<optimized out>, args=<optimized out>) at ./elf/dl-error-skeleton.c:227
#39 0x00007f097e0a21ae in _dlerror_run (operate=operate@entry=0x7f097e0a2660 <dlopen_doit>, args=args@entry=0x7ffc6bb73740) at ./dlfcn/dlerror.c:138
#40 0x00007f097e0a2748 in dlopen_implementation (dl_caller=<optimized out>, mode=<optimized out>, file=<optimized out>) at ./dlfcn/dlopen.c:71
#41 ___dlopen (file=<optimized out>, mode=<optimized out>) at ./dlfcn/dlopen.c:81
#42 0x00007f097e53a057 in _PyImport_FindSharedFuncptr (prefix=<optimized out>, shortname=0x7f097db723b0 "_C", pathname=0x7f097db58de0 "/workspace/temp/pytorch/bazel-bin/test_bazel.runfiles/pytorch/torch/_C.so", fp=0x0)
    at ./Python/dynload_shlib.c:99
#43 0x00007f097e52c903 in _PyImport_LoadDynamicModuleWithSpec (spec=0x7f097db728e0, fp=0x0) at ./Python/importdl.c:134
#44 0x00007f097e52c59e in _imp_create_dynamic_impl (module=<optimized out>, spec=0x7f097db728e0, file=<optimized out>) at Python/import.c:2221
#45 0x00007f097e604424 in cfunction_vectorcall_FASTCALL (func=0x7f097df5f8b0, args=0x7f097dc46478, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/methodobject.c:426
#46 0x00007f097e4e409c in PyVectorcall_Call (callable=0x2e3d, tuple=0x7f097dc46460, kwargs=0x7f097db61040) at Objects/call.c:200
#47 0x00007f097e64d724 in PyCFunction_Call (func=<optimized out>, args=<optimized out>, kwargs=0x7f097db61040) at Objects/call.c:775
#48 do_call_core (tstate=0x8b1ce0, func=<optimized out>, callargs=<optimized out>, kwdict=0x7f097db61040) at Python/ceval.c:4983
```

**Comment by eqy** [comment]
OK, I think I have the root cause now, but the fix doesn't look like it would be trivial.
Basically #90133 fixed some static linking issues, but only for CPU quantization. cuDNN quantization with static linking is probably still broken, but there seemed to be no tests that tried it out until (this) bazel build.
I think the fix is something similar like adding `register_linear_params()` and `register_conv_params()` to `TORCH_LIBRARY_IMPL`, but the issue is `register_linear_params()` is not exposed outside of of the `ao::sparse` namespace it seems.

Will try moving it out of this namespace to see if that resolves the issue. CC @dzdang @ppwwyyxx

**Comment by malfet** [comment]
@eqy I'm afraid we might have to wait with it a bit more, as some users still reporting significantly larger memory utilization after migration to v8 API)

**Comment by eqy** [comment]
@malfet just wanted to clarify that this PR does nothing with respect to v7 vs. v8 API usage (which has been default for ~6 months now). It just always builds with v8 support (which has been the default for > 1yr now) by dropping v7 API-only builds.

**Comment by malfet** [comment]
@eqy it's default in OSS, but not yet at Meta, where one could still disable it by undefining `HAS_CUDNN_V8`, which this PR removes the ability to do.

**Comment by eqy** [comment]
@malfet cuDNN V8 API can still be disabled at runtime via `TORCH_CUDNN_V8_API_DISABLED=1`, but you are correct that this PR disables the ability to remove it from the _build_

**Comment by davidberard98** [comment]
@eqy is cuDNN >= 8.0 the only requirement or does this actually require a newer version?

I'm building with 8.0.5 (which I realize is pretty old, but technically should satisfy cuDNN >= 8.0) and I run into errors like this:

```
../cmake/../third_party/cudnn_frontend/include/cudnn_frontend_Operation.h:2850:53: error: ‘CUDNN_BACKEND_OPERATION_BN_FINALIZE_STATISTICS_DESCRIPTOR’ was not declared in this scope; did you mean ‘CUDNN_BACKEND_OPERATION_GEN_STATS_DESCRIPTOR’?
 2850 |         is_bn_finalize_op = (m_operation.op_mode == CUDNN_BACKEND_OPERATION_BN_FINALIZE_STATISTICS_DESCRIPTOR);
 ```

In /usr/local/cuda-12.0/include I see cudnn_version.h with 8.0.5, and when I grep in this folder for `CUDNN_BACKEND_OPERATION` I get:
```
cudnn_backend.h
218:    CUDNN_BACKEND_OPERATION_CONVOLUTION_FORWARD_DESCRIPTOR,
219:    CUDNN_BACKEND_OPERATION_CONVOLUTION_BACKWARD_FILTER_DESCRIPTOR,
220:    CUDNN_BACKEND_OPERATION_CONVOLUTION_BACKWARD_DATA_DESCRIPTOR,
221:    CUDNN_BACKEND_OPERATION_POINTWISE_DESCRIPTOR,
222:    CUDNN_BACKEND_OPERATION_GEN_STATS_DESCRIPTOR,
223:    CUDNN_BACKEND_OPERATIONGRAPH_DESCRIPTOR,
```

**Comment by eqy** [comment]
@davidberard98 I think >= 8.0 is the only requirement from the "PyTorch side" of the code, it looks like this issue is caused by  `third_party/cudnn_frontend` being much newer than your cuDNN version. I believe this should be fixed in the cudnn-frontend rather than PyTorch, so I'll forward this issue to them.

**Comment by eqy** [comment]
@davidberard98 Looks like I was mistaken, the response from cuDNN is that the minimum required version for 0.x frontend (which the submodule is currently on) should be 8.1.

**Comment by malfet** [comment]
@eqy do you mind sending a followup PR that would error out if CuDNN version is older than minversion supported by cudnn_frontend?

**Comment by PaliC** [comment]
@pytorchbot revert -m "is breaking a bunch of internal pytorch users" -c ghfirst

The error looks like this

```
xplat/caffe2/aten/src/ATen/native/cudnn/Conv_v8.cpp:12:10: fatal error: 'cudnn_frontend.h' file not found  
#include <cudnn_frontend.h>  
         ^~~~~~~~~~~~~~~~~~  
1 error generated.  
```

**Comment by PaliC** [comment]
@pytorchbot revert -m "is breaking a bunch of internal pytorch users" -c ghfirst

The error looks like this

```
xplat/caffe2/aten/src/ATen/native/cudnn/Conv_v8.cpp:12:10: fatal error: 'cudnn_frontend.h' file not found  
#include <cudnn_frontend.h>  
         ^~~~~~~~~~~~~~~~~~  
1 error generated.  
```

**Comment by eqy** [comment]
@PaliC Is the internal build process not in-sync with CI? I didn't see such a build failure with `ciflow/periodic` `ciflow/trunk` etc.

**Comment by malfet** [comment]
@eqy yes, internal builds are called internal because they are not public. And it does not feel like there is anything that could be done on your end.

**Comment by malfet** [comment]
Ok, landed the change, let's try to reland it internally again

**Comment by eqy** [comment]
@malfet Should the internal version be bumped again or does it look good to retry a merge?

**Review by atalman — APPROVED** [review]
