### ISSUE TITLE
Build fails with gcc 9.1 + CUDA-10.2

### ISSUE THREAD

**Issue by tuxmaster5000** [pytorch/pytorch#36578]
At the aten/src/ATen/core/dispatch/Dispatcher.h part it fails with:
```
/builddir/build/BUILD/torch-1.4.1/aten/src/ATen/core/dispatch/Dispatcher.h: In instantiation of 'Return c10::Dispatcher::doCallUnboxedOnly(const c10::DispatchTable&, const c10::LeftRight<ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction> >&, Args ...) const [with Return = void; Args = {const at::Tensor&, const at::Tensor&, bool, bool}]':
/builddir/build/BUILD/torch-1.4.1/aten/src/ATen/core/dispatch/Dispatcher.h:201:114:   required from 'Return c10::Dispatcher::callUnboxedOnly(const c10::OperatorHandle&, Args ...) const [with Return = void; Args = {const at::Tensor&, const at::Tensor&, bool, bool}]'
/builddir/build/BUILD/torch-1.4.1/build/aten/src/ATen/core/TensorMethods.h:66:75:   required from here
/builddir/build/BUILD/torch-1.4.1/aten/src/ATen/core/dispatch/Dispatcher.h:211:80: error: redeclaration of 'const at::Tensor& args#0'
  211 |     return kernel.template callUnboxedOnly<Return, Args...>(std::forward<Args>(args)...);
```
I have added the whole build file.
[build.log.zip](https://github.com/pytorch/pytorch/files/4475157/build.log.zip)

cc @ezyang @gchanan @zou3519

**Comment by colesbury** [comment]
Lots of error messages relating to PyTorch 1.4.1 Dispatcher.

@ezyang @gchanan can we make sure that PyTorch 1.5 builds with GCC 9.1 before release?

```
/builddir/build/BUILD/torch-1.4.1/c10/util/LeftRight.h:67:10: error: 'typename std::result_of<F(const T&)>::type c10::LeftRight<T>::read(F&&) const [with F = c10::Dispatcher::doCallUnboxedOnly(const c10::DispatchTable&, const c10::LeftRight<ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction> >&, Args ...) const [with Return = at::Tensor; Args = {const at::Tensor&, long int, long int, at::Dimname}]::<lambda(const ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction>&)>; T = ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction>; typename std::result_of<F(const T&)>::type = at::Tensor]', declared using local type 'c10::Dispatcher::doCallUnboxedOnly(const c10::DispatchTable&, const c10::LeftRight<ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction> >&, Args ...) const [with Return = at::Tensor; Args = {const at::Tensor&, long int, long int, at::Dimname}]::<lambda(const ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction>&)>', is used but never defined [-fpermissive]
```

**Comment by tuxmaster5000** [comment]
Using GCC 7.3.1 will work.

**Comment by ezyang** [comment]
cc @smessmer

**Comment by rgommers** [comment]
gh-32770 is related, different cause but also failure to build with GCC 9.x

**Comment by gchanan** [comment]
@seemethere @malfet should we set up a GCC 9.X CI?

**Comment by malfet** [comment]
Sure, will look into that

**Comment by malfet** [comment]
https://github.com/pytorch/pytorch/pull/38747 adds gcc-9 + CUDA-10.2  build configuration

**Comment by mattip** [comment]
Since #38747 was merged and the CI seems to pass, I think this can be closed.
