### PR TITLE
third_party/breakpad: update, fixes build on linux/gcc

### LINKED ISSUE #70297: fails to build with: no matching function for call to max(int, long int)
### 🐛 Describe the bug

Fails to build with gcc on Linux

error: `no matching function for call to max(int, long int)`

somewhere in breakpad

### Versions

1.10.1

### LINKED ISSUE #73113: PyTorch fails to compile on gcc 11.2 due to breakpad
### 🐛 Describe the bug

Error message:
```
FAILED: third_party/breakpad/CMakeFiles/breakpad.dir/src/client/linux/handler/exception_handler.cc.o 
/usr/bin/c++ -DHAVE_A_OUT_H -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DUSE_EXTERNAL_MZCRC -D_FILE_OFFSET_BITS=64 -I/home/gaoxiang/pytorch-master/cmake/../third_party/benchmark/include -I/home/gaoxiang/pytorch-master/cmake/../third_party/cudnn_frontend/include -I/home/gaoxiang/pytorch-master/third_party/onnx -I/home/gaoxiang/pytorch-master/build/third_party/onnx -I/home/gaoxiang/pytorch-master/third_party/foxi -I/home/gaoxiang/pytorch-master/build/third_party/foxi -I/home/gaoxiang/pytorch-master/third_party/breakpad/src -I/home/gaoxiang/pytorch-master/third_party/breakpad/src/third_party/linux/include -isystem /home/gaoxiang/pytorch-master/build/third_party/gloo -isystem /home/gaoxiang/pytorch-master/cmake/../third_party/gloo -isystem /home/gaoxiang/pytorch-master/cmake/../third_party/googletest/googlemock/include -isystem /home/gaoxiang/pytorch-master/cmake/../third_party/googletest/googletest/include -isystem /home/gaoxiang/pytorch-master/third_party/protobuf/src -isystem /opt/intel/mkl/include -isystem /home/gaoxiang/pytorch-master/third_party/gemmlowp -isystem /home/gaoxiang/pytorch-master/third_party/neon2sse -isystem /home/gaoxiang/pytorch-master/third_party/XNNPACK/include -isystem /home/gaoxiang/pytorch-master/cmake/../third_party/eigen -isystem /opt/cuda/include -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -O2 -g -DNDEBUG -fPIC -DCAFFE2_USE_GLOO -DTH_HAVE_THREAD -std=gnu++14 -MD -MT third_party/breakpad/CMakeFiles/breakpad.dir/src/client/linux/handler/exception_handler.cc.o -MF third_party/breakpad/CMakeFiles/breakpad.dir/src/client/linux/handler/exception_handler.cc.o.d -o third_party/breakpad/CMakeFiles/breakpad.dir/src/client/linux/handler/exception_handler.cc.o -c /home/gaoxiang/pytorch-master/third_party/breakpad/src/client/linux/handler/exception_handler.cc
/home/gaoxiang/pytorch-master/third_party/breakpad/src/client/linux/handler/exception_handler.cc: In function ‘void google_breakpad::{anonymous}::InstallAlternateStackLocked()’:
/home/gaoxiang/pytorch-master/third_party/breakpad/src/client/linux/handler/exception_handler.cc:141:49: error: no matching function for call to ‘max(int, long int)’
```

### Versions

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 11.2.0
Clang version: 13.0.1
CMake version: version 3.22.2
Libc version: glibc-2.35

Python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0] (64-bit runtime)
Python platform: Linux-5.16.9-arch1-1-x86_64-with-glibc2.35
Is CUDA available: N/A
CUDA runtime version: 11.6.55
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 510.54
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.3.1
/usr/lib/libcudnn_adv_infer.so.8.3.1
/usr/lib/libcudnn_adv_train.so.8.3.1
/usr/lib/libcudnn_cnn_infer.so.8.3.1
/usr/lib/libcudnn_cnn_train.so.8.3.1
/usr/lib/libcudnn_ops_infer.so.8.3.1
/usr/lib/libcudnn_ops_train.so.8.3.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] torch-ucc==1.0.0
[pip3] torchani==2.2
[conda] Could not collect

```

### PR DESCRIPTION
**Pull request by Miezhiko**
Fixes #70297
Fixes #73113

updating breakpad to edbb99f95c75be27d038fffb1d969cdacf705db2
using fork https://github.com/driazati/breakpad

### CODE REVIEW

**Review by malfet — COMMENTED** [review]
Looks good to me, but please extend a PR description to mention which version of the library you are upgrading it to. Also, there used to be the patch on top of breakpad, this is why it was pulled from forked repo, is it still the case?

**Comment by Miezhiko** [comment]
@malfet added description to PR, it's still targeting the same fork, can't verify myself if patch was merged back to upstream because I'm not aware of that one but seems like fork is still maintained.

**Comment by acxz** [comment]
@malfet can you provide closure to this PR? The Archlinux packaging team would love for this to get merged in.

> there used to be the patch on top of breakpad

Can you specify which particular patchset? Since the same fork is being used, I would assume the patch still exists in the fork.

Edit: I just checked and the fork is two commits ahead from google/breakpad. The latest commit being a merge from google/breakpad and the second to last commit being what I can only assume to be the patch you are talking about.

https://github.com/driazati/breakpad/blob/edbb99f95c75be27d038fffb1d969cdacf705db2/src/tools/mac/upload_system_symbols/go.mod

As we can see the latest commit still has that second to last change i.e. the merge from upstream in the fork has not affected the diverging commit (the patch in question) in the fork.

Therefore this should be safe to merge as it updates the breakpad repo in our pipeline while also maintaining the original patch we used the fork in the first place for.

**Comment by acxz** [comment]
@Miezhiko thanks for the PR btw!

**Comment by acxz** [comment]
@malfet sorry for the ping but if you get the time can you provide closure to this PR?

I believe we have answered your concerns regarding this change. Feel free to ask any other questions.

Pinging @seemethere for visibility

**Comment by acxz** [comment]
@Miezhiko can you add "Fixes #73113" in OP so that that issue can get closed with the merge of this PR.

**Comment by Miezhiko** [comment]
@acxz done

**Comment by acxz** [comment]
@malfet @seemethere @suo who can we ping for a review of this PR?

Also is it usual for the CI to skip so many tests? Can someone restart the CI as well?

Thank you.

**Comment by malfet** [comment]
@acxz It looks like breakpad is not actively used by the community, so instead of updating it to a forked repos, I think it would be better to disable it altogether, though I hadn't had time to finish https://github.com/pytorch/pytorch/pull/75394 yet, let me give it one more try

**Comment by acxz** [comment]
> breakpad is not actively used by the community

I see.

> I think it would be better to disable it altogether

Got it, makes sense.

> let me give it one more try

take your time, I think most users that are currently experiencing this issue are just patching around it themselves, so its prob not a big deal. However, I do ask that if it taking a long enough time, having this commit in the pytorch codebase wouldn't hurt either.

**Comment by Miezhiko** [comment]
it is really simpler to remove breakpad than to merge this PR >__<

joking aside I don't think I needed breakpad myself, just cmake flag was ON by default and I expect that most of linux distributions packagers or source based linux users needed such patch for recent releases and it's always safer and simpler taking merged and tested patch than researching the problem and providing own solution for each.

**Comment by acxz** [comment]
[Miezhiko](https://github.com/Miezhiko) looks like that breakpad has been removed. I think you can go ahead and close this PR and the associated issues with it.
