### ISSUE TITLE
Python 3.14 test error: `AttributeError: 'MobileNetV2' object has no attribute '__annotations__'.`

### ISSUE THREAD

**Issue by sarahec** [pytorch/pytorch#172254]
### 🐛 Describe the bug

While building 2.9.1 for nixpkgs, pytest fails with ``AttributeError: 'MobileNetV2' object has no attribute '__annotations__'.`

(Note: this was building as a dependency of `fickling`, hence the line prefix)

```sh
fickling> _________________________ TestPolyglotModule.test_zip __________________________
fickling>
fickling> self = <test.test_polyglot.TestPolyglotModule testMethod=test_zip>
fickling>
fickling>     def setUp(self):
fickling>         # Not covered: PyTorch MAR & earlier TorchScript versions
fickling>
fickling>         # PyTorch v1.3
fickling>         model = models.mobilenet_v2()
fickling>         self.filename_v1_3 = "model_v1_3.pth"
fickling>         torch.save(model, self.filename_v1_3)
fickling>
fickling>         # PyTorch v1.3 Dup (for testing)
fickling>         self.filename_v1_3_dup = "model_v1_3_dup.pth"
fickling>         torch.save(model, self.filename_v1_3_dup)
fickling>
fickling>         # PyTorch v0.1.10 (Stacked pickle files)
fickling>         self.filename_legacy_pickle = "model_legacy_pickle.pth"
fickling>         torch.save(model, self.filename_legacy_pickle, _use_new_zipfile_serialization=False)
fickling>
fickling>         # TorchScript v1.4
fickling> >       m = torch.jit.script(model)
fickling>             ^^^^^^^^^^^^^^^^^^^^^^^
fickling>
fickling> test/test_polyglot.py:65:
fickling> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
fickling> /nix/store/h17yvi8qz45zakfscpb085fph0sqxw7l-python3.14-torch-2.9.1/lib/python3.14/site-packages/torch/jit/_script.py:1437: in script
fickling>     ret = _script_impl(
fickling> /nix/store/h17yvi8qz45zakfscpb085fph0sqxw7l-python3.14-torch-2.9.1/lib/python3.14/site-packages/torch/jit/_script.py:1146: in _script_impl
fickling>     return torch.jit._recursive.create_script_module(
fickling> /nix/store/h17yvi8qz45zakfscpb085fph0sqxw7l-python3.14-torch-2.9.1/lib/python3.14/site-packages/torch/jit/_recursive.py:556: in create_script_module
fickling>     AttributeTypeIsSupportedChecker().check(nn_module)
fickling> /nix/store/h17yvi8qz45zakfscpb085fph0sqxw7l-python3.14-torch-2.9.1/lib/python3.14/site-packages/torch/jit/_check.py:77: in check
fickling>     self.class_level_annotations = list(nn_module.__annotations__.keys())
fickling>                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
fickling> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
fickling>
fickling> self = MobileNetV2(
fickling>   (features): Sequential(
fickling>     (0): Conv2dNormActivation(
fickling>       (0): Conv2d(3, 32, kernel_size=(3, 3), str...equential(
fickling>     (0): Dropout(p=0.2, inplace=False)
fickling>     (1): Linear(in_features=1280, out_features=1000, bias=True)
fickling>   )
fickling> )
fickling> name = '__annotations__'
fickling>
fickling>     def __getattr__(self, name: str) -> Union[Tensor, "Module"]:
fickling>         if "_parameters" in self.__dict__:
fickling>             _parameters = self.__dict__["_parameters"]
fickling>             if name in _parameters:
fickling>                 return _parameters[name]
fickling>         if "_buffers" in self.__dict__:
fickling>             _buffers = self.__dict__["_buffers"]
fickling>             if name in _buffers:
fickling>                 return _buffers[name]
fickling>         if "_modules" in self.__dict__:
fickling>             modules = self.__dict__["_modules"]
fickling>             if name in modules:
fickling>                 return modules[name]
fickling> >       raise AttributeError(
fickling>             f"'{type(self).__name__}' object has no attribute '{name}'"
fickling>         )
fickling> E       AttributeError: 'MobileNetV2' object has no attribute '__annotations__'. Did you mean: '__annotate_func__'?
fickling>
fickling> /nix/store/h17yvi8qz45zakfscpb085fph0sqxw7l-python3.14-torch-2.9.1/lib/python3.14/site-packages/torch/nn/modules/module.py:1964: AttributeError
```

### Versions

torch 2.9.1

cc @malfet @seemethere

**Comment by malfet** [comment]
I think Python-3.14 support for 2.9 was very limited, but also I don't expect JitScript will work with Python-3.14

**Comment by Skylion007** [comment]
Ah, yeah __annotations__ attribute is broken in 3.14, we need inspect.get_annotations instead here I think.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
