### PR TITLE
[12/12] Enforce C++20 minimum in header guards (#178150)

### PR DESCRIPTION
**Pull request by r-barnes**
Summary:

Raise the compile-time enforcement from C++17 to C++20 in the
header guards of c10/util/C++17.h, ATen/ATen.h, and torch/all.h.
This is the enforcement gate — all consumers must already be
building with -std=c++20 before this lands.

#buildmore

Test Plan: Sandcastle

Reviewed By: huydhn

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @kadeng @muchulee8 @amjames @chauhang @aakhundov @coconutruben @jataylo

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by r-barnes** [comment]
@Skylion007 - your comment has the wrong link :-)

File: torch/csrc/api/include/torch/all.h [hunk 1]
```diff
@@ -1,7 +1,7 @@
 #pragma once
 
-#if !defined(_MSC_VER) && __cplusplus < 201703L
```
Comment (cyyever) [inline torch/csrc/api/include/torch/all.h:3]: MSVC defines __cplusplus with ```/Zc:__cplusplus```, so that the guard can be improved to `#if defined(__cplusplus) && __cplusplus < 201703L`?

**Review by cyyever — CHANGES_REQUESTED** [review]

**Comment by r-barnes** [comment]
Not sure why so many tests were skipped. Rebasing.

**Review by malfet — APPROVED** [review]

**Review by cyyever — APPROVED** [review]

**Comment by r-barnes** [comment]
Another step for #176662

**Comment by atalman** [comment]
Heads-up: this change (enforcing a C++20 minimum in the ATen / libtorch header guards) surfaced a build break in vLLM's **torch-nightly** CI. Not a PyTorch bug — flagging for visibility since it's the trigger, and the fix is on the vLLM side.

vLLM's vendored `vllm-flash-attn` extension was still compiling its host C++ sources (`_vllm_fa2_C`: `flash_api.cpp`, `flash_api_sparse.cpp`) at **C++17**, so once `ATen.h` began requiring C++20 the build stops at:

```
torch/include/ATen/ATen.h:5:2: error: #error C++20 or later compatible compiler is required to use ATen.
```

Bisected to this commit (`bab118ec7598`):

| torch nightly | vLLM `:docker: Build image` |
|---|---|
| `2.14.0.dev20260715` (pre-commit) | ✅ builds (ATen still C++17 guard) |
| `2.14.0.dev20260719` (first nightly with this commit) | ❌ fails on the C++20 `#error` |

Tracked and fixed downstream — the `vllm-flash-attn` targets are being bumped to `CXX_STANDARD 20` / `CXX_STANDARD_REQUIRED ON`:

- vLLM issue: vllm-project/vllm#49260
- vllm-flash-attn fix: vllm-project/flash-attention#168
- vLLM CI validation PR: vllm-project/vllm#49326

Thanks!
