### PR TITLE
Unify libtorch and libcaffe2

### PR DESCRIPTION
**Pull request by kostmo**
This PR is an intermediate step toward the ultimate goal of eliminating "caffe2" in favor of "torch".  This PR moves all of the files that had constituted "libtorch.so" into the "libcaffe2.so" library, and wraps "libcaffe2.so" with a shell library named "libtorch.so".  This means that, for now, `caffe2/CMakeLists.txt` becomes a lot bigger, and `torch/CMakeLists.txt` becomes smaller.

The torch Python bindings (`torch_python.so`) still remain in `torch/CMakeLists.txt`.

The follow-up to this PR will rename references to `caffe2` to `torch`, and flatten the shell into one library.

### CODE REVIEW

File: caffe2/CMakeLists.txt [hunk 1]
```diff
@@ -211,10 +206,579 @@ if(NOT BUILD_ATEN_ONLY)
   endif()
 endif()
 
+
+# ==========================================================
+# formerly-libtorch
+# ==========================================================
+
+set(TORCH_SRC_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../torch")
```
Comment (dzhulgakov) [inline caffe2/CMakeLists.txt]: we should probably just lift this main folder up to avoid `..` but we can do it in a separate PR

File: caffe2/CMakeLists.txt [hunk 2]
```diff
@@ -211,10 +206,579 @@ if(NOT BUILD_ATEN_ONLY)
...
+  add_custom_target(
+    generate-torch-sources
+    DEPENDS ${TORCH_GENERATED_CODE}
+    )
+
+  
+  set(TORCH_SRCS
+    ${GENERATED_CXX_TORCH}
+    ${GENERATED_H_TORCH}
+    ${TORCH_SRC_DIR}/csrc/autograd/anomaly_mode.cpp
```
Comment (dzhulgakov) [inline caffe2/CMakeLists.txt]: it'd be nice to dedup this list with build_variables.py in the future (not this PR) - I wonder whether we can just read the same file in in both build systems

File: caffe2/CMakeLists.txt [hunk 3]
```diff
@@ -211,10 +206,579 @@ if(NOT BUILD_ATEN_ONLY)
...
+  # Forces caffe2.pb.h to be generated before its dependents are compiled.
+  # Adding the generated header file to the ${TORCH_SRCS} list is not sufficient
+  # to establish the dependency, since the generation procedure is declared in a different CMake file.
+  # See https://samthursfield.wordpress.com/2015/11/21/cmake-dependencies-between-targets-and-files-and-custom-commands/#custom-commands-in-different-directories
+  add_dependencies(caffe2 Caffe2_PROTO)
+
+  target_compile_definitions(caffe2 PUBLIC _THP_CORE)
+
+
+  # until they can be unified, keep these lists synced with setup.py
```
Comment (dzhulgakov) [inline caffe2/CMakeLists.txt]: probably it's worth to look into it in the future (not sure what exact history of this duplication is) - from setup.py it seems we're building only stub.cpp, so it might be outdated comment

File: caffe2/CMakeLists.txt [hunk 4]
```diff
@@ -211,10 +206,579 @@ if(NOT BUILD_ATEN_ONLY)
...
+endif()
+
+
+
+
+
 if (NOT WIN32)
-  target_compile_options(caffe2 PRIVATE "-fvisibility=hidden")
+    # FIXME kostmo
+#  target_compile_options(caffe2 PRIVATE "-fvisibility=hidden")
```
Comment (dzhulgakov) [inline caffe2/CMakeLists.txt]: after we fixed THPPointer - can we bring it on or are there still a lot of failures?

File: caffe2/CMakeLists.txt [hunk 5]
```diff
@@ -244,9 +808,9 @@ target_include_directories(caffe2 SYSTEM PRIVATE "${Caffe2_DEPENDENCY_INCLUDE}")
 # Set standard properties on the target
 torch_set_target_props(caffe2)
 
-if (NOT MSVC)
-  target_compile_options(caffe2 INTERFACE "$<$<COMPILE_LANGUAGE:CXX>:-std=c++11>")
-endif()
+#if (NOT MSVC)
```
Comment (dzhulgakov) [inline caffe2/CMakeLists.txt]: why is this off?

**Review by dzhulgakov — COMMENTED** [review]
Great progress, CI passes! :)

One question is about libtorch.so - as far as I understand there's not such file any more. We probably should keep libtorch.so name because external things can depend on it. I'd imagine there are fewer dependencies on libcaffe2.so externally and we can make a symlink maybe.

I think it's getting to a point to get more people's input. @soumith @orionr @yf225 @bddppq - please take a look. Also, we have a release soon. Should we strive to land it before that? (pro: stress testing during binary builds, cons: potentially more churn)

File: caffe2/CMakeLists.txt (hunk 5 above)
Comment (kostmo) [reply caffe2/CMakeLists.txt]: Seems redundant with [this line](https://github.com/pytorch/pytorch/blob/320f47f66529fd85164542105a0119ef2d0f5c6d/caffe2/CMakeLists.txt#L637):

    set_property(TARGET caffe2 PROPERTY CXX_STANDARD 11)

File: caffe2/CMakeLists.txt (hunk 4 above)
Comment (kostmo) [reply caffe2/CMakeLists.txt]: There are still failures, e.g.:

    ImportError: /scratch/kostmo/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so: undefined symbol: _ZTIN5torch3jit4NodeE

**Comment by kostmo** [comment]
Ran into this Windows build failure after rebasing (to resolve a merge conflict):
```
21:55:55 dataloader.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl torch::data::samplers::Sampler<struct TestIndex>::~Sampler<struct TestIndex>(void)" (__imp_??1?$Sampler@UTestIndex@@@samplers@data@torch@@UEAA@XZ) referenced in function "int `class std::unique_ptr<class torch::data::StatelessDataLoader<struct TestIndexDataset,struct TestIndexSampler>,struct std::default_delete<class torch::data::StatelessDataLoader<struct TestIndexDataset,struct TestIndexSampler> > > __cdecl torch::data::make_data_loader<struct TestIndexDataset,struct TestIndexSampler>(struct TestIndexDataset,struct TestIndexSampler,struct data::dtor$7::DataLoaderOptions)'::`1'::dtor$7" (?dtor$7@?0???$make_data_loader@UTestIndexDataset@@UTestIndexSampler@@@data@torch@@YA?AV?$unique_ptr@V?$StatelessDataLoader@UTestIndexDataset@@UTestIndexSampler@@@data@torch@@U?$default_delete@V?$StatelessDataLoader@UTestIndexDataset@@UTestIndexSampler@@@data@torch@@@std@@@std@@UTestIndexDataset@@UTestIndexSampler@@UDataLoaderOptions@01@@Z@4HA)
21:55:55 dataloader.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) const torch::data::samplers::Sampler<struct TestIndex>::`vftable'" (__imp_??_7?$Sampler@UTestIndex@@@samplers@data@torch@@6B@) referenced in function "class std::unique_ptr<class torch::data::StatelessDataLoader<struct TestIndexDataset,struct TestIndexSampler>,struct std::default_delete<class torch::data::StatelessDataLoader<struct TestIndexDataset,struct TestIndexSampler> > > __cdecl torch::data::make_data_loader<struct TestIndexDataset,struct TestIndexSampler>(struct TestIndexDataset,struct TestIndexSampler,struct torch::data::DataLoaderOptions)" (??$make_data_loader@UTestIndexDataset@@UTestIndexSampler@@@data@torch@@YA?AV?$unique_ptr@V?$StatelessDataLoader@UTestIndexDataset@@UTestIndexSampler@@@data@torch@@U?$default_delete@V?$StatelessDataLoader@UTestIndexDataset@@UTestIndexSampler@@@data@torch@@@std@@@std@@UTestIndexDataset@@UTestIndexSampler@@UDataLoaderOptions@01@@Z)
21:55:55 bin\test_api.exe : fatal error LNK1120: 2 unresolved externals
```

**Comment by dzhulgakov** [comment]
It's getting in a good shape - all of the following with visibility=hidden enabled:
- The windows build passes (!!!) and only tests fails because of test_extension - we have hard-coded libtorch name here: https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py#L432
- ASAN build is broken because of header-only classes with visibility=hidden, I'm fixing it
- ROCm has some symbol missing - I'm looking into it too.

However, before we can land this we need to decide naming problem:
1) `libtorch.so` is a public name, so we should either name the entire thing libtorch (and break libcaffe2 backward compat which is more ok) or figure out some way to create a proxy library (or symlink?)
2) gpu pieces are now linked in the "add-on" library caffe2_gpu.so. If we decide not to make a proxy libtorch which depends on both in (1), we'd need to fold the gpu bits directly in the main library.

@soumith @gchanan - do you have insights on above?

Also asking for review from more folks: @orionr @bddppq @yf225 @pjh5

File: torch/CMakeLists.txt [hunk 6]
```diff
@@ -643,38 +180,37 @@ if (BUILD_PYTHON)
...
 
-  if (USE_ROCM)
+if (USE_ROCM)
     list(APPEND TORCH_PYTHON_SRCS
       ${TORCH_SRC_DIR}/csrc/cuda/Module.cpp
       ${TORCH_SRC_DIR}/csrc/cuda/Storage.cpp
       ${TORCH_SRC_DIR}/csrc/cuda/Stream.cpp
       ${TORCH_SRC_DIR}/csrc/cuda/Event.cpp
       ${TORCH_SRC_DIR}/csrc/cuda/utils.cpp
-      ${TORCH_SRC_DIR}/csrc/cuda/comm.cpp
```
Comment (bddppq) [inline torch/CMakeLists.txt]: Is this is the reason causing the undefined symbol in rocm build? (although I don't understand why cuda build doesn't see the same issue).

Comment (bddppq) [reply torch/CMakeLists.txt]: Ok I saw it has been moved to caffe2/CMakeLists.txt. But from the generated build.ninja file, comm.cpp is not included in the rocm build.

File: caffe2/CMakeLists.txt [hunk 7]
```diff
@@ -211,9 +206,582 @@ if(NOT BUILD_ATEN_ONLY)
...
+      add_library(thnvrtc SHARED ${TORCH_SRC_DIR}/csrc/jit/fuser/cuda/thnvrtc.cpp)
+      target_link_libraries(thnvrtc ${CUDA_NVRTC} ${CUDA_CUDA_LIB} ${CUDA_NVRTC_LIB})
+      target_include_directories(thnvrtc PRIVATE ${CUDA_INCLUDE_DIRS})
+      install(TARGETS thnvrtc DESTINATION "${TORCH_INSTALL_LIB_DIR}")
+
+    endif()
+  endif ()
+
+  if (USE_CUDA)
+    list(APPEND Caffe2_GPU_SRCS
```
Comment (bddppq) [inline caffe2/CMakeLists.txt]: These need to be added to Caffe2_HIP_SRCS if USE_ROCM

**Comment by dzhulgakov** [comment]
So apparently windows CI (on jenkins) doesn't start if the merge doesn't go smoothly. Brace for rebase I guess.

File: caffe2/CMakeLists.txt [hunk 8]
```diff
@@ -211,9 +206,596 @@ if(NOT BUILD_ATEN_ONLY)
...
+
 # Compile exposed libraries.
 add_library(caffe2 ${Caffe2_CPU_SRCS})
+
+
+# Wrapper library for transition to merged libcaffe and libtorch.
+# Only necessary on Windows?
+# Contains "caffe2" and "caffe2_gpu".
+file(WRITE ${CMAKE_BINARY_DIR}/empty.cpp "")
+add_library(torch STATIC ${CMAKE_BINARY_DIR}/empty.cpp)
```
Comment (pjh5) [inline caffe2/CMakeLists.txt]: What does this solve on windows? It looks like torch is just a wrapper around caffe2 and caffe2_gpu; what do we need this target for?

**Comment by peterjc123** [comment]
As for the build timeout issue for caffe2 win builds, I think that you can try the following things:
1. Remove the argument `/maxcpucount` in `tools\build_pytorch_libs.py`, to confirm whether it was or was not caused by a deadlock in msbuild
2. Try different generators (in/ not in msbuild)
3. Updating VS (in / not in the MSVC toolchain)

File: caffe2/CMakeLists.txt [hunk 9]
```diff
@@ -516,20 +516,25 @@ endif()
...
 
 
-
 # This is required for older versions of CMake, which don't allow
 # specifying add_library() without a list of source files
 set(DUMMY_EMPTY_FILE ${CMAKE_BINARY_DIR}/empty.cpp)
-file(WRITE ${DUMMY_EMPTY_FILE} "")
+
+if (MSVC)
+  set(DUMMY_FILE_CONTENT "__declspec(dllexport) int ignore_this_library_placeholder(){return 0;}")
```
[the remark this answers is not in the document]
Comment (kostmo) [reply caffe2/CMakeLists.txt]: > I don't know why the empty stub is needed here. Maybe it was used to keep the backward compatibility?

Relaying an answer from Dima:
> primarily to keep the shared library file name to be torch, not caffe2 to make sure that people builds and extensions don’t break
Alternatively we could just generate only libtorch instead of libcaffe2 but it’d make the PR bigger and also would still have the same issue for C2 users ( but the latter part might be fine)

**Review by orionr — APPROVED** [review]
Woohoo!

**Review by soumith — APPROVED** [review]
