### PR TITLE
[IG CTR] Fix constexpr Compilation Error in ttir

### PR DESCRIPTION
**Pull request by oniononion36**
Summary: Some constexpr seems to have no `_flatten_ir_types` attribute, which causes identifying mutated tensors to fail during ttir generation, and as a result all inputs are considered to be mutated. Note that the breaking change was introduced in D89669796, and this is a partial revert of the diff.

Test Plan: buck run fbcode//mode/opt-amd-gpu -c 'fbcode.enable_gpu_sections=true' -c 'fbcode.split-dwarf=true' -c 'fbcode.use_link_groups=true' -c fbcode.rocm_arch=mi300  fbcode//inference_enablement/model_processing/infra/components/lowering/client/re/test/ae:test_local_lowering_replay_v0 -- -r test_aot_inductor_ig_ctr_v0

Differential Revision: D90155022

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @kadeng @muchulee8 @amjames @chauhang @aakhundov @coconutruben @jataylo

### CODE REVIEW

File: torch/_higher_order_ops/triton_kernel_wrap.py [hunk 1]
```diff
@@ -441,13 +441,13 @@ def _native_specialize_impl(
...
     specialization = _get_specialization(ordered_args.values())
 
-    # Triton explicitly interprets ASTSource.constants entries as constexpr
-    # (triton-lang/triton#8248). Thus, only arguments marked `is_constexpr`
-    # should be treated as such, not just non-tensor-like arguments.
+    def is_tensor_like_arg(arg: Any) -> bool:
+        if isinstance(arg, Tensor) or is_stable_tensor_descriptor_arg(arg):
+            return True
+        return False
+
```
Comment (zou3519) [inline torch/_higher_order_ops/triton_kernel_wrap.py]: Can you add a test?

Comment (Skylion007) [reply torch/_higher_order_ops/triton_kernel_wrap.py]: TypeGuard return would be great here, but importing the type for is is_stable_tensor_descriptor_arg requires to be put in a TYPE_CHECKING import block, probably.

Comment (oniononion36) [reply torch/_higher_order_ops/triton_kernel_wrap.py]: I dug a bit deeper into the root cause and realized that it was because None value variables were excluded from constants and therefore causing an issue when generating ttir. Thus, the only thing I am changing now is adding back None valued args to constants. Also added a test.

**Review by oulgen — APPROVED** [review]

File: torch/_higher_order_ops/triton_kernel_wrap.py [hunk 2]
```diff
@@ -441,11 +441,11 @@ def _native_specialize_impl(
 
     # Triton explicitly interprets ASTSource.constants entries as constexpr
     # (triton-lang/triton#8248). Thus, only arguments marked `is_constexpr`
-    # should be treated as such, not just non-tensor-like arguments.
+    # or None values should be treated as such, not just non-tensor-like arguments.
     constants = {
-        (i,): arg
-        for i, ((_, arg), param) in enumerate(zip(ordered_args.items(), kernel.params))
-        if param.is_constexpr
+        name: arg
```
Comment (jjvraw) [inline torch/_higher_order_ops/triton_kernel_wrap.py:446]: For what its worth now, given these changes have been since reverted...

The `ASTSource` constructor accepts both string/tuple key formats, with tuple avoiding lookup. 

```python
        if constexprs is not None:
            for k, v in constexprs.items():
                k = (fn.arg_names.index(k), ) if isinstance(k, str) else k
                assert isinstance(k, tuple)
                self.constants[k] = v
```

https://github.com/triton-lang/triton/blob/cebd1fd48d402ae94185e81f014bee621b2680f5/python/triton/compiler/compiler.py#L61-L65
