### ISSUE TITLE
C++ linking to Pytorch on Linux (CPU) fails with libtorch 1.10.1 - cannot find MKL

### ISSUE THREAD

**Issue by vdemichev** [pytorch/pytorch#72653]
### 🐛 Describe the bug

**test.cpp:**
```
#include "torch/script.h"

int main() {
    return 0;
}
```

**Building:** (libtorch 1.10.1 Linux, CPU, C++, cxx11 ABI)
```
g++-8 -o test-binary test.cpp -Ilibtorch/include -D_GLIBCXX_USE_CXX11_ABI=1 -Llibtorch/lib -lfbgemm -lasmjit -lnnapi_backend -lcaffe2_observers -lcaffe2_detectron_ops -lbackend_with_compiler -ltorch -ltorch_global_deps -ltorch_cpu -ltorch_python -ltorchbind_test -lXNNPACK -lmkldnn -ljitbackend_test -lcaffe2_module_test_dynamic -lshm -lc10
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_zd_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_d_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_dsbrdbn'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_zlaeh2'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_d_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_s_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_zd_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_trans_mkl_zimatcopy_square_t_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_sc_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_claeh2'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_slaeh2'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_d_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_dlaed2'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_c_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_zhbrdbn'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_dz_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_c_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_s_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_s_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_cs_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_trans_mkl_comatcopy2_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_dlaeh2'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_z_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_sc_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_cs_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_z_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_dlaed3'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_z_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_slaed3'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_trans_mkl_cimatcopy_square_t_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_z_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_c_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_ssbrdbn'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_trans_mkl_zomatcopy2_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_dz_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_s_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_d_out_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_c_par'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_chbrdbn'
libtorch/lib/libtorch_cpu.so: undefined reference to `mkl_lapack_slaed2'
```

No problem with libtorch 1.8.2. But does not work with 1.10.1.

### Versions

g++-8 --version
```
g++-8 (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

cc @ezyang @gchanan @zou3519 @seemethere @malfet @jbschlosser

**Comment by atalman** [comment]
One possible solution is to link this library statically when compiling: https://oneapi-src.github.io/oneDNN/v1.0/dev_guide_build_options.html

by setting following flag:
MKLDNN_LIBRARY_TYPE = static

**Comment by malfet** [comment]
Regression happened between [Aug 3rd](https://pytorch.s3.amazonaws.com/libtorch/nightly/cpu/libtorch-cxx11-abi-shared-with-deps-1.10.0.dev20210803%2Bcpu.zip) and [Aug 4th](https://pytorch.s3.amazonaws.com/libtorch/nightly/cpu/libtorch-cxx11-abi-shared-with-deps-1.10.0.dev20210804%2Bcpu.zip
) nightlies:

**Comment by atalman** [comment]
The reverting the following PR seems to resolve this particular issue: https://github.com/pytorch/pytorch/pull/49647/files
However followup work is required

**Comment by iammeizu** [comment]
met the same problem, need to be fixed

**Comment by atalman** [comment]
This issue should be resolved by followin git pull https://github.com/pytorch/pytorch/pull/72959

**Comment by atalman** [comment]
Closing this issue we do have followup: https://github.com/pytorch/pytorch/issues/73008
