### ISSUE TITLE
PyTorch master failed to build with glog 0.5.0.

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#58054]
## Bug

Log:

```
root@164a9000a4ab:/tmp/scratch/pytorch/build# cmake --build . -- -j1
[1/153] : && /usr/bin/g++-8 -fdebug-prefix-map='/tmp/scratch'='/usr/local/src' -g -march=haswell -mtune=generic -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow -O3 -DNDEBUG -DNDEBUG -rdynamic c10/cuda/test/CMakeFiles/c10_cuda_CUDATest.dir/impl/CUDATest.cpp.o -o bin/c10_cuda_CUDATest  -Wl,-rpath,/tmp/scratch/pytorch/build/lib:/usr/local/lib:/usr/local/cuda/lib64:  lib/libc10_cuda.so  lib/libgtest_main.a  lib/libc10.so  /usr/local/lib/libglog.so.0.5.0  /usr/local/lib/libgflags.so.2.2.2  -lpthread  /usr/local/cuda/lib64/libcudart.so  lib/libgtest.a  -pthread && :
FAILED: bin/c10_cuda_CUDATest 
: && /usr/bin/g++-8 -fdebug-prefix-map='/tmp/scratch'='/usr/local/src' -g -march=haswell -mtune=generic -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow -O3 -DNDEBUG -DNDEBUG -rdynamic c10/cuda/test/CMakeFiles/c10_cuda_CUDATest.dir/impl/CUDATest.cpp.o -o bin/c10_cuda_CUDATest  -Wl,-rpath,/tmp/scratch/pytorch/build/lib:/usr/local/lib:/usr/local/cuda/lib64:  lib/libc10_cuda.so  lib/libgtest_main.a  lib/libc10.so  /usr/local/lib/libglog.so.0.5.0  /usr/local/lib/libgflags.so.2.2.2  -lpthread  /usr/local/cuda/lib64/libcudart.so  lib/libgtest.a  -pthread && :
lib/libc10.so: undefined reference to `google::glog_internal_namespace_::IsGoogleLoggingInitialized()'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

glog 0.5 is released a few days ago.
IIRC pytorch redefined that func to expose it.
Wondering that's related.

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Ubuntu 18.04 / CentOS 7
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake+ninja+gcc
 - Python version: 3.6
 - CUDA/cuDNN version: 11.3

**Comment by xkszltl** [comment]
This commit set default visibility to hidden and could be related:
https://github.com/google/glog/commit/c30896d3d545ad15910ad4279b63e23f7d66d3e9#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a

**Comment by mruberry** [comment]
What about PyTorch 1.8, @xkszltl?

**Comment by xkszltl** [comment]
Haven't tried but I don't think it is related to change in pytorch.
If it's hidden now, you won't be able to take it out like this:
https://github.com/pytorch/pytorch/blob/1e77ba36dbe6578ec87c4cd94127e9f4138389c0/c10/util/Logging.cpp#L194-L202

**Comment by xkszltl** [comment]
I've added an API so that you don't have to use the previous hack:
https://github.com/google/glog/pull/651
But you'll need some mechanism to detect its existence.

**Comment by malfet** [comment]
Thank you for reporting. We would accept the patch that fixes it

**Comment by xkszltl** [comment]
Given they're different functions (named the same but old one is in `google::glog_internal_namespace_` and the new one is in `google` directly), I don't know how to automatically route to the correct one.
Any ideas?

**Comment by essandess** [comment]
This appears to be the fix: https://github.com/google/glog/issues/125#issuecomment-749601226

Related:
* https://github.com/google/glog/issues/660
* https://trac.macports.org/ticket/62921

**Comment by xkszltl** [comment]
@essandess 
No, that's exactly what doesn't work in glog 0.5.0
See the linked PR: https://github.com/google/glog/pull/651
- I added a public API in master, not 0.5.
- They don't want to keep internal API for compatibility.
- Need a fancy way to distinguish between 0.4/0.5/master and generate different code.

**Comment by essandess** [comment]
This remains an issue in torch version 1.9.1:

```
:info:build : && /opt/local/var/macports/build/_opt_local_ports_python_py-pytorch/py39-pytorch/work/compwrap/cxx/usr/bin/clang++ -arch x86_64 -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const -O3 -DNDEBUG -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -mmacosx-version-min=11.0 -dynamiclib -Wl,-headerpad_max_install_names -arch x86_64 -rdynamic -o lib/libc10.dylib -install_name @rpath/libc10.dylib c10/CMakeFiles/c10.dir/core/Allocator.cpp.o c10/CMakeFiles/c10.dir/core/CPUAllocator.cpp.o c10/CMakeFiles/c10.dir/core/CopyBytes.cpp.o c10/CMakeFiles/c10.dir/core/DefaultDtype.cpp.o c10/CMakeFiles/c10.dir/core/Device.cpp.o c10/CMakeFiles/c10.dir/core/DeviceType.cpp.o c10/CMakeFiles/c10.dir/core/DispatchKey.cpp.o c10/CMakeFiles/c10.dir/core/DispatchKeySet.cpp.o c10/CMakeFiles/c10.dir/core/GeneratorImpl.cpp.o c10/CMakeFiles/c10.dir/core/GradMode.cpp.o c10/CMakeFiles/c10.dir/core/InferenceMode.cpp.o c10/CMakeFiles/c10.dir/core/Scalar.cpp.o c10/CMakeFiles/c10.dir/core/Storage.cpp.o c10/CMakeFiles/c10.dir/core/StorageImpl.cpp.o c10/CMakeFiles/c10.dir/core/Stream.cpp.o c10/CMakeFiles/c10.dir/core/TensorImpl.cpp.o c10/CMakeFiles/c10.dir/core/TensorOptions.cpp.o c10/CMakeFiles/c10.dir/core/UndefinedTensorImpl.cpp.o c10/CMakeFiles/c10.dir/core/impl/DeviceGuardImplInterface.cpp.o c10/CMakeFiles/c10.dir/core/impl/LocalDispatchKeySet.cpp.o c10/CMakeFiles/c10.dir/core/impl/SizesAndStrides.cpp.o c10/CMakeFiles/c10.dir/core/thread_pool.cpp.o c10/CMakeFiles/c10.dir/mobile/CPUCachingAllocator.cpp.o c10/CMakeFiles/c10.dir/mobile/CPUProfilingAllocator.cpp.o c10/CMakeFiles/c10.dir/util/Array.cpp.o c10/CMakeFiles/c10.dir/util/Backtrace.cpp.o c10/CMakeFiles/c10.dir/util/C++17.cpp.o c10/CMakeFiles/c10.dir/util/DeadlockDetection.cpp.o c10/CMakeFiles/c10.dir/util/Exception.cpp.o c10/CMakeFiles/c10.dir/util/Half.cpp.o c10/CMakeFiles/c10.dir/util/LeftRight.cpp.o c10/CMakeFiles/c10.dir/util/Logging.cpp.o c10/CMakeFiles/c10.dir/util/MathConstants.cpp.o c10/CMakeFiles/c10.dir/util/Metaprogramming.cpp.o c10/CMakeFiles/c10.dir/util/Optional.cpp.o c10/CMakeFiles/c10.dir/util/SmallVector.cpp.o c10/CMakeFiles/c10.dir/util/StringUtil.cpp.o c10/CMakeFiles/c10.dir/util/ThreadLocalDebugInfo.cpp.o c10/CMakeFiles/c10.dir/util/Type.cpp.o c10/CMakeFiles/c10.dir/util/TypeList.cpp.o c10/CMakeFiles/c10.dir/util/TypeTraits.cpp.o c10/CMakeFiles/c10.dir/util/Unicode.cpp.o c10/CMakeFiles/c10.dir/util/UniqueVoidPtr.cpp.o c10/CMakeFiles/c10.dir/util/complex_math.cpp.o c10/CMakeFiles/c10.dir/util/flags_use_gflags.cpp.o c10/CMakeFiles/c10.dir/util/flags_use_no_gflags.cpp.o c10/CMakeFiles/c10.dir/util/intrusive_ptr.cpp.o c10/CMakeFiles/c10.dir/util/numa.cpp.o c10/CMakeFiles/c10.dir/util/signal_handler.cpp.o c10/CMakeFiles/c10.dir/util/thread_name.cpp.o c10/CMakeFiles/c10.dir/util/typeid.cpp.o  /opt/local/lib/libglog.0.5.0.dylib  /opt/local/lib/libgflags.2.2.2.dylib && :
:info:build ld: warning: dylib (/opt/local/lib/libglog.0.5.0.dylib) was built for newer macOS version (11.3) than being linked (11.0)
:info:build Undefined symbols for architecture x86_64:
:info:build   "google::glog_internal_namespace_::IsGoogleLoggingInitialized()", referenced from:
:info:build       c10::InitCaffeLogging(int*, char**) in Logging.cpp.o
```

**Comment by essandess** [comment]
This remains an issue in torch version 1.10.1:

```
:info:build Undefined symbols for architecture x86_64:
:info:build   "google::glog_internal_namespace_::IsGoogleLoggingInitialized()", referenced from:
:info:build       c10::InitCaffeLogging(int*, char**) in Logging.cpp.o
:info:build ld: symbol(s) not found for architecture x86_64
```

**Comment by essandess** [comment]
PT team: what’s this status on fixing this longstanding issue? It’s breaking a bunch of downstream dependencies and preventing updates to the latest versions?

**Comment by mascguy** [comment]
> @essandess No, that's exactly what doesn't work in glog 0.5.0 See the linked PR: [google/glog#651](https://github.com/google/glog/pull/651) in your issue.
> 
>     * I added a public API in master, not 0.5.
> 
>     * They don't want to keep internal API for compatibility.
> 
>     * Need a fancy way to distinguish between 0.4/0.5/master and generate different code.

One thought Could we simply expose the call via both namespaces, to provide backward compatibility? (And mark the one in the internal namespace as deprecated.)

That way the code can rely on the internal namespace for now, and eventually move to the public API?

**Comment by xkszltl** [comment]
@mascguy 

> Thoughts?

That would be wonderful.
Please send this feedback directly to glog.
I wasn't able to convince them for compatibility so maybe more user input can help.

Alternatively see if there's SFINAE magic to help detecting the existence of function.

**Comment by mascguy** [comment]
For awareness, this is how we handled the situation via MacPorts:

* Our `google-glog` 0.5.0 distribution has been patched with your fix, to make the init function public.
* We patched PyTorch to use that.

However, until the API fix has been included in a glog release, dependent projects are stuck. Definitely a crappy situation!

**Comment by jiapei100** [comment]
@mascguy Now, it's already google-glog 0.6.0 
Any patch for that?

**Comment by meerfrau** [comment]
Still present:
```
 && /usr/bin/g++-12 -march=native -mtune=native -O2 -pipe -fno-plt -fexceptions -Wformat -Wp,-D_GLIBCXX_ASSERTIONS -fpermissive -Wzero-as-null-pointer-constant -I third_party/ideep/mkl-dnn/third_party/oneDNN/include/ -D_GLIBCXX_USE_CXX11_ABI=1 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN -DUSE_VULKAN_API -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=range-loop-construct -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow -O3 -DNDEBUG -DNDEBUG -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -rdynamic     -Wl,--no-as-needed c10/test/CMakeFiles/c10_StreamGuard_test.dir/core/StreamGuard_test.cpp.o -o bin/c10_StreamGuard_test  -Wl,-rpath,./src/pytorch/build/lib:  lib/libc10.so  lib/libgmock.a  lib/libgtest.a  lib/libgtest_main.a  /usr/lib/libglog.so.0.6.0  /usr/lib/libgflags.so.2.2.2  -lpthread  lib/libgtest.a && /usr/bin/cmake -E __run_co_compile --lwyu="ldd;-u;-r" --source=bin/c10_StreamGuard_test && :
/usr/bin/ld: lib/libc10.so: undefined reference to `google::glog_internal_namespace_::IsGoogleLoggingInitialized()'
```

**Comment by BwL1289** [comment]
FWIW here's the fix in `Logging.cpp`

```c++
namespace google { // Remove glog_internal_namespace_
bool IsGoogleLoggingInitialized(); 
} // namespace google

namespace c10 {
namespace {

void initGoogleLogging(char const* name) {
#if !defined(_MSC_VER)
  // This trick can only be used on UNIX platforms
  if (!::google::IsGoogleLoggingInitialized())  // Remove glog_internal_namespace_
#endif
  {
    ::google::InitGoogleLogging(name);
#if !defined(_MSC_VER)
    // This is never defined on Windows
    ::google::InstallFailureSignalHandler();
#endif
  }
}
```
