### ISSUE TITLE
Cannot compile SGlang with Torch 2.7 or Torch 2.8 and CUDA 12.8 (sm_120).

### ISSUE THREAD

**Issue by shahizat** [pytorch/pytorch#149796]
### 🐛 Describe the bug

Greetings to all,

I want to build SGlang from source on a machine with Nvidia RTX 5090. Using torch  2.6, the build succeeds, but torch 2.6 does not work with Triton version 3.3 and CUDA 12.8 with sm_120 support. Errors appear with versions 2.7 and the latest 2.8.

Error logs related to torch:

```
/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(180): error: identifier "PyFrame_FastToLocalsWithError" is undefined
      if (PyFrame_FastToLocalsWithError(frame) < 0) {
          ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(186): error: pointer or reference to incomplete type "_frame" is not allowed
      return _Py_NewRef(((PyObject*)(frame->f_locals)));
                                     ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(195): error: pointer or reference to incomplete type "_frame" is not allowed
      return _Py_NewRef(((PyObject*)(frame->f_globals)));
                                     ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(204): error: pointer or reference to incomplete type "_frame" is not allowed
      return _Py_NewRef(((PyObject*)(frame->f_builtins)));
                                     ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(217): error: pointer or reference to incomplete type "_frame" is not allowed
      if (frame->f_lasti < 0) {
          ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(220): error: pointer or reference to incomplete type "_frame" is not allowed
      return frame->f_lasti * 2;
             ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(346): error: pointer or reference to incomplete type "_ts" is not allowed
      tstate->tracing++;
      ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(348): error: pointer or reference to incomplete type "_ts" is not allowed
      tstate->cframe->use_tracing = 0;
      ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(359): error: pointer or reference to incomplete type "_ts" is not allowed
      int use_tracing = (tstate->c_tracefunc != nullptr
                         ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(360): error: pointer or reference to incomplete type "_ts" is not allowed
                         || tstate->c_profilefunc != nullptr);
                            ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(361): error: pointer or reference to incomplete type "_ts" is not allowed
      tstate->tracing--;
      ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(363): error: pointer or reference to incomplete type "_ts" is not allowed
      tstate->cframe->use_tracing = use_tracing;
      ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(475): error: identifier "_PyFloat_Pack2" is undefined
  { return _PyFloat_Pack2(x, (unsigned char*)p, le); }
           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(478): error: identifier "_PyFloat_Unpack2" is undefined
  { return _PyFloat_Unpack2((const unsigned char *)p, le); }
           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(489): error: identifier "_PyFloat_Pack4" is undefined
  { return _PyFloat_Pack4(x, (unsigned char*)p, le); }
           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(492): error: identifier "_PyFloat_Pack8" is undefined
  { return _PyFloat_Pack8(x, (unsigned char*)p, le); }
           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(495): error: identifier "_PyFloat_Unpack4" is undefined
  { return _PyFloat_Unpack4((const unsigned char *)p, le); }
           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(498): error: identifier "_PyFloat_Unpack8" is undefined
  { return _PyFloat_Unpack8((const unsigned char *)p, le); }
           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(506): error: pointer or reference to incomplete type "PyCodeObject" is not allowed
      return _Py_NewRef(((PyObject*)(code->co_code)));
                                     ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(515): error: pointer or reference to incomplete type "PyCodeObject" is not allowed
      return _Py_NewRef(((PyObject*)(code->co_varnames)));
                                     ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(523): error: pointer or reference to incomplete type "PyCodeObject" is not allowed
      return _Py_NewRef(((PyObject*)(code->co_freevars)));
                                     ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(531): error: pointer or reference to incomplete type "PyCodeObject" is not allowed
      return _Py_NewRef(((PyObject*)(code->co_cellvars)));
                                     ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(678): error: identifier "_PyObject_LookupAttr" is undefined
      return _PyObject_LookupAttr(obj, attr_name, result);
             ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(863): error: identifier "_Py_IsFinalizing" is undefined
      return _Py_IsFinalizing();
             ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(902): error: identifier "_PyLong_AsInt" is undefined
      return _PyLong_AsInt(obj);
             ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(913): error: identifier "_PyObject_GetDictPtr" is undefined
      PyObject **dict = _PyObject_GetDictPtr(obj);
                        ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(924): error: identifier "_PyObject_GetDictPtr" is undefined
      PyObject **dict = _PyObject_GetDictPtr(obj);
                        ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(938): error: identifier "_PyThreadState_UncheckedGet" is undefined
      return _PyThreadState_UncheckedGet();
             ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(958): error: identifier "PyUnicode_IS_ASCII" is undefined
      if (PyUnicode_IS_ASCII(unicode)) {
          ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(959): error: identifier "PyUnicode_DATA" is undefined
          utf8 = PyUnicode_DATA(unicode);
                 ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(960): error: identifier "PyUnicode_GET_LENGTH" is undefined
          len = PyUnicode_GET_LENGTH(unicode);
                ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(963): error: identifier "PyUnicode_AsUTF8AndSize" is undefined
          utf8 = PyUnicode_AsUTF8AndSize(unicode, &len);
                 ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1054): error: identifier "_PyDict_Pop" is undefined
      value = _PyDict_Pop(dict, key,
              ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1104): error: identifier "_Py_HashPointer" is undefined
      return _Py_HashPointer(ptr);
             ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1115): error: identifier "_PyTime_t" is undefined
  typedef _PyTime_t PyTime_t;
          ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1120): error: identifier "_PyTime_AsSecondsDouble" is undefined
  { return _PyTime_AsSecondsDouble(t); }
           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1123): error: identifier "_PyTime_GetMonotonicClockWithInfo" is undefined
  { return _PyTime_GetMonotonicClockWithInfo(result,
           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1126): error: identifier "_PyTime_GetSystemClockWithInfo" is undefined
  { return _PyTime_GetSystemClockWithInfo(result,
           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1131): error: identifier "_PyTime_GetPerfCounterWithInfo" is undefined
      return _PyTime_GetPerfCounterWithInfo(result,
             ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1353): error: identifier "_PyUnicodeWriter" is undefined
      _PyUnicodeWriter_Dealloc((_PyUnicodeWriter*)writer);
                                ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1353): error: expected an expression
      _PyUnicodeWriter_Dealloc((_PyUnicodeWriter*)writer);
                                                 ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1353): error: expected a ")"
      _PyUnicodeWriter_Dealloc((_PyUnicodeWriter*)writer);
                                                  ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1353): error: identifier "_PyUnicodeWriter_Dealloc" is undefined
      _PyUnicodeWriter_Dealloc((_PyUnicodeWriter*)writer);
      ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1365): error: identifier "_PyUnicodeWriter" is undefined
      const size_t size = sizeof(_PyUnicodeWriter);
                                 ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1371): error: identifier "writer" is undefined
      _PyUnicodeWriter *writer = (_PyUnicodeWriter *)pub_writer;
                        ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1371): error: expected an expression
      _PyUnicodeWriter *writer = (_PyUnicodeWriter *)pub_writer;
                                                    ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1371): error: expected a ";"
      _PyUnicodeWriter *writer = (_PyUnicodeWriter *)pub_writer;
                                                     ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1373): error: identifier "_PyUnicodeWriter_Init" is undefined
      _PyUnicodeWriter_Init(writer);
      ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1374): error: identifier "_PyUnicodeWriter_Prepare" is undefined
      if (_PyUnicodeWriter_Prepare(writer, length, 127) < 0) {
          ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1384): error: identifier "_PyUnicodeWriter" is undefined
      PyObject *str = _PyUnicodeWriter_Finish((_PyUnicodeWriter*)writer);
                                               ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1384): error: expected an expression
      PyObject *str = _PyUnicodeWriter_Finish((_PyUnicodeWriter*)writer);
                                                                ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1384): error: expected a ")"
      PyObject *str = _PyUnicodeWriter_Finish((_PyUnicodeWriter*)writer);
                                                                 ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1384): error: identifier "_PyUnicodeWriter_Finish" is undefined
      PyObject *str = _PyUnicodeWriter_Finish((_PyUnicodeWriter*)writer);
                      ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1399): error: identifier "_PyUnicodeWriter" is undefined
      return _PyUnicodeWriter_WriteChar((_PyUnicodeWriter*)writer, ch);
                                         ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1399): error: expected an expression
      return _PyUnicodeWriter_WriteChar((_PyUnicodeWriter*)writer, ch);
                                                          ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1399): error: expected a ")"
      return _PyUnicodeWriter_WriteChar((_PyUnicodeWriter*)writer, ch);
                                                           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1399): error: identifier "_PyUnicodeWriter_WriteChar" is undefined
      return _PyUnicodeWriter_WriteChar((_PyUnicodeWriter*)writer, ch);
             ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1410): error: identifier "_PyUnicodeWriter" is undefined
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                                           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1410): error: expected an expression
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                                                            ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1410): error: expected a ")"
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                                                             ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1410): error: identifier "_PyUnicodeWriter_WriteStr" is undefined
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1410): error: "str" has already been declared in the current scope
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                                                                     ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1410): error: expected a ";"
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                                                                        ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1411): warning #549-D: variable "str" is used before its value is set
      _Py_DECREF(((PyObject*)(str)));
                              ^

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1423): error: identifier "_PyUnicodeWriter" is undefined
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                                           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1423): error: expected an expression
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                                                            ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1423): error: expected a ")"
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                                                             ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1423): error: identifier "_PyUnicodeWriter_WriteStr" is undefined
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1423): error: "str" has already been declared in the current scope
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                                                                     ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1423): error: expected a ";"
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                                                                        ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1424): warning #549-D: variable "str" is used before its value is set
      _Py_DECREF(((PyObject*)(str)));
                              ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1441): error: identifier "_PyUnicodeWriter" is undefined
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str_obj);
                                           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1441): error: expected an expression
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str_obj);
                                                            ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1441): error: expected a ")"
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str_obj);
                                                             ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1441): error: identifier "_PyUnicodeWriter_WriteStr" is undefined
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str_obj);
                ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1441): error: "str_obj" has already been declared in the current scope
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str_obj);
                                                                     ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1441): error: expected a ";"
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str_obj);
                                                                            ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1442): warning #549-D: variable "str_obj" is used before its value is set
      _Py_DECREF(((PyObject*)(str_obj)));
                              ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1459): error: identifier "_PyUnicodeWriter" is undefined
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str_obj);
                                           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1459): error: expected an expression
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str_obj);
                                                            ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1459): error: expected a ")"
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str_obj);
                                                             ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1459): error: identifier "_PyUnicodeWriter_WriteStr" is undefined
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str_obj);
                ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1459): error: "str_obj" has already been declared in the current scope
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str_obj);
                                                                     ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1459): error: expected a ";"
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str_obj);
                                                                            ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1460): warning #549-D: variable "str_obj" is used before its value is set
      _Py_DECREF(((PyObject*)(str_obj)));
                              ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1476): error: identifier "PyUnicode_GET_LENGTH" is undefined
      if (end > PyUnicode_GET_LENGTH(str)) {
                ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1481): error: identifier "_PyUnicodeWriter" is undefined
      return _PyUnicodeWriter_WriteSubstring((_PyUnicodeWriter*)writer, str,
                                              ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1481): error: expected an expression
      return _PyUnicodeWriter_WriteSubstring((_PyUnicodeWriter*)writer, str,
                                                               ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1481): error: expected a ")"
      return _PyUnicodeWriter_WriteSubstring((_PyUnicodeWriter*)writer, str,
                                                                ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1481): error: identifier "_PyUnicodeWriter_WriteSubstring" is undefined
      return _PyUnicodeWriter_WriteSubstring((_PyUnicodeWriter*)writer, str,
             ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1496): error: identifier "_PyUnicodeWriter" is undefined
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                                           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1496): error: expected an expression
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                                                            ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1496): error: expected a ")"
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                                                             ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1496): error: identifier "_PyUnicodeWriter_WriteStr" is undefined
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1496): error: "str" has already been declared in the current scope
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                                                                     ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1496): error: expected a ";"
      int res = _PyUnicodeWriter_WriteStr((_PyUnicodeWriter*)writer, str);
                                                                        ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1497): warning #549-D: variable "str" is used before its value is set
      _Py_DECREF(((PyObject*)(str)));
                              ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1507): error: pointer or reference to incomplete type "_typeobject" is not allowed
          PyErr_Format(PyExc_TypeError, "expect int, got %s", (((PyObject*)(obj))->ob_type)->tp_name);
                                                              ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/torch/csrc/utils/pythoncapi_compat.h(1511): error: identifier "_PyLong_Sign" is undefined
      *sign = _PyLong_Sign(obj);
              ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/pybind11/buffer_info.h(107): error: identifier "Py_buffer" is undefined
      explicit buffer_info(Py_buffer *view, bool ownview = true)
                           ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/pybind11/buffer_info.h(153): error: identifier "Py_buffer" is undefined
      Py_buffer *view() const { return m_view; }
      ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/pybind11/buffer_info.h(154): error: identifier "Py_buffer" is undefined
      Py_buffer *&view() { return m_view; }
      ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/pybind11/buffer_info.h(181): error: identifier "Py_buffer" is undefined
      Py_buffer *m_view = nullptr;
      ^

/home/admin2/.virtualenvs/sglang/lib/python3.10/site-packages/torch/include/pybind11/buffer_info.h(118): error: more than one user-defined conversion from "<error-type>" to "std::vector<int64_t, std::allocator<int64_t>>" (aka "std::vector<signed long, std::allocator<signed long>>") applies:
                    ? std::vector<ssize_t>(view->strides, view->strides + view->ndim)
                      ^


```

### Versions

PyTorch version: 2.7.0a0+gitcdd7a2c
Is debug build: False
CUDA used to build PyTorch: 12.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Clang version: Could not collect
CMake version: version 3.31.6
Libc version: glibc-2.35

Python version: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.8.0-52-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.8.93
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 5090
Nvidia driver version: 570.124.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        43 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               64
On-line CPU(s) list:                  0-63
Vendor ID:                            AuthenticAMD
Model name:                           AMD Ryzen Threadripper 3970X 32-Core Processor
CPU family:                           23
Model:                                49
Thread(s) per core:                   2
Core(s) per socket:                   32
Socket(s):                            1
Stepping:                             0
Frequency boost:                      enabled
CPU max MHz:                          4549,1211
CPU min MHz:                          2200,0000
BogoMIPS:                             7400.09
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
Virtualization:                       AMD-V
L1d cache:                            1 MiB (32 instances)
L1i cache:                            1 MiB (32 instances)
L2 cache:                             16 MiB (32 instances)
L3 cache:                             128 MiB (8 instances)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-63
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec rstack overflow:   Mitigation; Safe RET
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; IBPB conditional; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] optree==0.14.1
[pip3] torch==2.7.0a0+gitcdd7a2c
[pip3] torchao==0.9.0
[pip3] triton==3.3.0+gite1964461
[conda] Could not collect
