### ISSUE TITLE
XPU build failure with DLE 2025.1.0

### ISSUE THREAD

**Issue by pbchekin** [pytorch/pytorch#150047]
Deep Learning Essentials 2025.1.0 has been [released](https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?packages=dl-essentials&dl-essentials-os=linux&dl-lin=offline). Building PyTorch XPU with this release fails with the following errors:

```
pytorch/third_party/kineto/libkineto/src/plugin/xpupti/XpuptiActivityApi.cpp: In member function ‘void libkineto::XpuptiActivityApi::enableXpuptiActivities(const std::set<libkineto::ActivityType>&)’:
pytorch/third_party/kineto/libkineto/src/plugin/xpupti/XpuptiActivityApi.cpp:195:33: error: ‘PTI_VIEW_SYCL_RUNTIME_CALLS’ was not declared in this scope; did you mean ‘PTI_VIEW_RUNTIME_API’?
  195 |       XPUPTI_CALL(ptiViewEnable(PTI_VIEW_SYCL_RUNTIME_CALLS));
```

```
pytorch/third_party/kineto/libkineto/src/plugin/xpupti/XpuptiActivityProfiler.cpp:1:
pytorch/third_party/kineto/libkineto/src/plugin/xpupti/XpuptiActivityProfiler.h:55:13: error: ‘pti_view_record_sycl_runtime’ does not name a type
   55 |       const pti_view_record_sycl_runtime* activity,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```
pytorch/third_party/kineto/libkineto/src/plugin/xpupti/XpuptiActivityProfiler.h:55:13: error: ‘pti_view_record_sycl_runtime’ does not name a type
   55 |       const pti_view_record_sycl_runtime* activity,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
pytorch/third_party/kineto/libkineto/src/plugin/xpupti/XpuptiActivityHandlers.cpp:101:11: error: ‘pti_view_record_sycl_runtime’ does not name a type
  101 |     const pti_view_record_sycl_runtime* activity,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

And other errors, see https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/14091932056/job/39470474844.

PyTorch commit id: 87bfd66c3c7061db6d36d8daa62f08f507f90e39

cc @malfet @seemethere @robieta @chaekit @guotuofeng @guyang3532 @dzhulgakov @davidberard98 @briancoutinho @sraikund16 @sanrise @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by idkSeth** [comment]
I am also experiencing issues building PyTorch with oneAPI/Deep Learning Essentials 2025.1.0

**Comment by malfet** [comment]
> xpupti

:)

**Comment by chuanqi129** [comment]
Hi @pbchekin the latest pytorch main is not ready to work with oneAPI DLE 2025.1. We plan to do the oneAPI DLE 2025.1 upgrade when the conditions ready before release 2.8 branch cut.

**Comment by riverliuintel** [comment]
@pbchekin  this is not a valid issue report. Please follow the Intel GPU PyTorch instructions to set up your environment https://github.com/pytorch/pytorch/?tab=readme-ov-file#intel-gpu-support

**Comment by EikanWang** [comment]
It is as expected, @pbchekin. Pls. follow the document to build PyTorch. I think it is the same experience for other hardware backends. For example, it took a longer time for torch to support the latest CUDA SDK version.

**Comment by pbchekin** [comment]
@riverliuintel, @EikanWang, no problem. What is the ETA for supporting DLE 2025.1.0 in main branch?

**Comment by riverliuintel** [comment]
Deep Learning Essentials 2025.1.0 is planned to be upgraded for PyTorch 2.8 release.

**Comment by alexbaden** [comment]
I was able to build and run a few tests under DLE 2025.1 with this patch https://github.com/intel/torch-xpu-ops/pull/1515 and `USE_KINETO=0`.Looks like the main issue is updating Kineto to use the new PTI interface.

**Comment by pbchekin** [comment]
> I was able to build and run a few tests under DLE 2025.1 with this patch [intel/torch-xpu-ops#1515](https://github.com/intel/torch-xpu-ops/pull/1515) and `USE_KINETO=0`.Looks like the main issue is updating Kineto to use the new PTI interface.

I also had compilation errors related to ccl, so I also had to set `USE_XCCL=0`. There are inductor tests [failures](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/14113566684/job/39538199356), potentially some of them are related to disabled Kineto.

**Comment by malfet** [comment]
@chuanqi129 why did you add a 2.8.0 milestone? Is there anyone working on this issue? De-milestoning for now

**Comment by chuanqi129** [comment]
Hi @malfet, we have updated the XPU support package oneAPI DLE to 2025.1 for 2.8 release, please refer the issue #151097 to get more detail information, and I'll close this issue due to we have completed it.
